@startuml SuaNguyenLieu
mainframe sd Seq_SuaNguyenLieu
autonumber "<b>##."
skinparam sequenceMessageAlign center
skinparam style strictuml

    skinparam noteBackgroundColor transpar1ent
    skinparam noteBorderColor transparent

actor "Thủ kho" as TK #White
boundary "Form_SuaNguyenLieu" as FRM #White
boundary "GUI_KhoVaNguyenLieu" as UI #White
control "Controller_QuanLyNguyenLieu" as SYS #White
entity ": NGUYENLIEU" as DB_NL #White

TK -> UI: Chọn sửa một nguyên liệu
activate UI
deactivate UI


UI -> SYS: Yêu cầu lấy thông tin
activate SYS
deactivate SYS

SYS -> DB_NL: Lấy dữ liệu nguyên liệu theo ID
activate DB_NL
deactivate DB_NL

SYS -->> FRM: Hiển thị biểu mẫu với \n thông tin nguyên liệu hiện tại

group opt Hủy thao tác
    autonumber stop
    TK -[hidden]-> DB_NL
    autonumber resume "<b>##."
    TK -> FRM: Nhấn nút "Hủy"
    activate FRM
    deactivate FRM
    
FRM -> SYS: Yêu cầu đóng form
    activate SYS
    deactivate SYS
    
    SYS -->> UI: Đóng biểu mẫu, không lưu dữ liệu
end

TK -> FRM: Chỉnh sửa thông tin nguyên liệu và nhấn "Lưu"
activate FRM
deactivate FRM

FRM -> SYS: Gửi dữ liệu cập nhật
activate SYS
deactivate SYS

SYS -> SYS: Kiểm tra tính hợp lệ của dữ liệu
activate SYS
deactivate SYS

group alt Kiểm tra dữ liệu
    note over of TK: [Thông tin không hợp lệ]
    autonumber stop
    TK -[hidden]-> DB_NL
    autonumber resume "<b>##."
    SYS -->> UI: Thông báo lỗi và giữ nguyên biểu mẫu
else 
    note over of TK: [Thông tin hợp lệ]
    autonumber stop
    TK -[hidden]-> DB_NL
    autonumber resume "<b>##."
    SYS -> DB_NL: Cập nhật thông tin nguyên liệu
    activate DB_NL
    deactivate DB_NL

    SYS -> SYS: Kiểm tra kết quả cập nhật
    activate SYS
    deactivate SYS
    
    group alt Kết quả cập nhật
        note over of TK: [Lưu thất bại]
        autonumber stop
        TK -[hidden]-> DB_NL
        autonumber resume "<b>##."
        SYS -->> UI: Thông báo lỗi lưu dữ liệu
    else 
        note over of TK: [Lưu thành công]
        autonumber stop
        TK -[hidden]-> DB_NL
        autonumber resume "<b>##."
        SYS -->> UI: Thông báo thành công và làm mới danh sách
    end
end



@enduml
