@startuml CapNhatTrangThaiNhaCungCap
mainframe sd Seq_CapNhatTrangThaiNhaCungCap
autonumber "<b>##."
skinparam sequenceMessageAlign center
skinparam style strictuml

    skinparam noteBackgroundColor transparent
    skinparam noteBorderColor transparent

actor "Thủ kho" as TK #White
boundary "GUI_NhaCungCap" as UI #White
control "Controller_NhaCungCap" as SYS #White
entity ": NHACUNGCAP" as DB_NCC #White

TK -> UI: Chọn một nhà cung cấp cần ngừng giao dịch
activate UI
deactivate UI

TK -> UI: Nhấn "Xóa"
activate UI
deactivate UI

UI -> SYS: Gửi yêu cầu xóa nhà cung cấp
activate SYS
deactivate SYS

SYS -->> UI: Hiển thị yêu cầu xác nhận và\ncảnh báo lịch sử phiếu nhập vẫn được giữ nguyên

group alt Xác nhận thao tác
    note over of TK: [Từ chối xác nhận]
    autonumber stop
    TK -[hidden]-> DB_NCC
    autonumber resume "<b>##."
    TK -> UI: Hủy bỏ
    activate UI
    deactivate UI
    
    UI -> SYS: Hủy yêu cầu
    activate SYS
    deactivate SYS
    
    SYS -->> UI: Hủy thao tác, trạng thái giữ nguyên
else 
    note over of TK: [Đồng ý xác nhận]
    autonumber stop
    TK -[hidden]-> DB_NCC
    autonumber resume "<b>##."
    TK -> UI: Xác nhận
    activate UI
    deactivate UI
    
    UI -> SYS: Gửi yêu cầu xác nhận xóa
    activate SYS
    deactivate SYS
    
    SYS -> DB_NCC: Ghi nhận trạng thái xóa
    activate DB_NCC
    deactivate DB_NCC

    SYS -> SYS: Kiểm tra kết quả cập nhật
    activate SYS
    deactivate SYS
    
    group alt Kết quả cập nhật
        note over of TK: [Lưu thất bại]
        autonumber stop
        TK -[hidden]-> DB_NCC
        autonumber resume "<b>##."
        SYS -->> UI: Thông báo lỗi, trạng thái không thay đổi
    else 
        note over of TK: [Lưu thành công]
        autonumber stop
        TK -[hidden]-> DB_NCC
        autonumber resume "<b>##."
        SYS -->> UI: Thông báo thành công và làm mới danh sách
    end
end

@enduml
