@startuml SuaLoaiThuChi
mainframe sd Seq_SuaLoaiThuChi
autonumber "<b>##."
skinparam sequenceMessageAlign center
skinparam style strictuml

    skinparam noteBackgroundColor transparent
    skinparam noteBorderColor transparent

actor "Quản lý" as QL #White
boundary "Form_SuaLoaiThuChi" as FRM #White
boundary "GUI_QuanLyThuChi" as UI #White
control "Controller_QuanLyThuChi" as SYS #White
entity ": LOAITHUCHI" as DB_LTC #White

QL -> UI: Chọn sửa một loại thu chi
activate UI
deactivate UI

UI -->> FRM: Hiển thị biểu mẫu sửa


FRM -> SYS: Yêu cầu lấy thông tin
activate SYS
deactivate SYS

SYS -> DB_LTC: Lấy dữ liệu loại thu chi theo ID
activate DB_LTC
deactivate DB_LTC

SYS -->> FRM: Hiển thị biểu mẫu với thông tin hiện tại

group opt Hủy thao tác
    autonumber stop
    QL -[hidden]-> DB_LTC
    autonumber resume "<b>##."
    QL -> FRM: Nhấn nút "Hủy"
    activate FRM
    deactivate FRM
    
FRM -> SYS: Yêu cầu đóng form
    activate SYS
    deactivate SYS
    
    SYS -->> UI: Đóng biểu mẫu, không lưu dữ liệu
end


QL -> FRM: Chỉnh sửa thông tin và nhấn "Lưu"
activate FRM
deactivate FRM

FRM -> SYS: Gửi dữ liệu cập nhật
activate SYS
deactivate SYS

SYS -> SYS: Kiểm tra tính hợp lệ
activate SYS
deactivate SYS

group alt Kiểm tra dữ liệu
    note over of QL: [Tên trống]
    autonumber stop
    QL -[hidden]-> DB_LTC
    autonumber resume "<b>##."
    SYS -->> UI: Thông báo lỗi và giữ nguyên biểu mẫu
else 
    note over of QL: [Thông tin hợp lệ]
    autonumber stop
    QL -[hidden]-> DB_LTC
    autonumber resume "<b>##."
    SYS -> DB_LTC: Cập nhật thông tin loại thu chi
    activate DB_LTC
    deactivate DB_LTC

    SYS -> SYS: Kiểm tra kết quả cập nhật
    activate SYS
    deactivate SYS
    
    group alt Kết quả cập nhật
        note over of QL: [Lưu thất bại]
        autonumber stop
        QL -[hidden]-> DB_LTC
        autonumber resume "<b>##."
        SYS -->> UI: Thông báo lỗi lưu dữ liệu
    else 
        note over of QL: [Lưu thành công (kể cả không có thay đổi)]
        autonumber stop
        QL -[hidden]-> DB_LTC
        autonumber resume "<b>##."
        SYS -->> UI: Thông báo thành công và làm mới danh sách
    end
end

@enduml
