-- Trigger cấm xóa phiếu thu chi
CREATE OR REPLACE TRIGGER TRG_CAMXOAKETOAN_PHIEUTHUCHI
BEFORE DELETE ON PHIEUTHUCHI
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_TC_CAM_XOA_PHIEUTHUCHI, 'Vi pham ke toan: Cam tuyet doi xoa vat ly chung tu phieu thu chi.');
END;
/