-- Trigger cấm xóa phiếu thu chi
CREATE OR REPLACE TRIGGER TRG_CAMXOAKETOAN_PHIEUTHUCHI
BEFORE DELETE ON PHIEUTHUCHI
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_TC_CAM_XOA_PHIEUTHUCHI, 'Vi phạm kế toán: Cấm tuyệt đối xóa vật lý chứng từ phiếu thu chi.');
END;
/