@startuml
left to right direction


  usecase "Xem báo cáo thống kê" as UC_Main
  usecase "Xem báo cáo lợi nhuận" as UC_Profit
  usecase "Xem báo cáo doanh thu" as UC_Rev

UC_Profit .up.> UC_Main : <<extend>>
UC_Rev .up.> UC_Main : <<extend>>

@enduml
