@startuml uc_ban_hang
left to right direction


  usecase "Quản lý bán hàng" as UC_Main
  usecase "Lập hóa đơn bán lẻ" as UC_Retail
  usecase "Hủy hóa đơn bán lẻ" as UC_CancelRetail
  usecase "Lập đơn đặt bánh tùy chỉnh" as UC_Custom
  usecase "Cập nhật trạng thái đơn" as UC_StatusOrder
  usecase "Tra cứu danh sách đơn" as UC_SearchOrder
  usecase "Hủy đơn và hoàn cọc" as UC_CancelOrder



UC_Retail .up.> UC_Main : <<extend>>
UC_CancelRetail .up.> UC_Main : <<extend>>
UC_Custom .up.> UC_Main : <<extend>>
UC_StatusOrder .up.> UC_Main : <<extend>>
UC_SearchOrder .up.> UC_Main : <<extend>>
UC_CancelOrder .up.> UC_Main : <<extend>>

UC_CancelRetail ..> UC_SearchOrder : <<include>>
UC_StatusOrder ..> UC_SearchOrder : <<include>>
UC_CancelOrder ..> UC_SearchOrder : <<include>>

@enduml
