@startuml
left to right direction


  usecase "Quản lý sản phẩm" as UC_Main
  usecase "Thêm danh mục sản phẩm" as UC_AddCat
  usecase "Sửa danh mục sản phẩm" as UC_EditCat
  usecase "Cập nhật trạng thái danh mục" as UC_StatusCat
  usecase "Thêm sản phẩm" as UC_AddProd
  usecase "Sửa sản phẩm" as UC_EditProd
  usecase "Cập nhật trạng thái sản phẩm" as UC_StatusProd
  usecase "Tra cứu sản phẩm" as UC_SearchProd




UC_AddCat .up.> UC_Main : <<extend>>
UC_EditCat .up.> UC_Main : <<extend>>
UC_StatusCat .up.> UC_Main : <<extend>>
UC_AddProd .up.> UC_Main : <<extend>>
UC_EditProd .up.> UC_Main : <<extend>>
UC_StatusProd .up.> UC_Main : <<extend>>
UC_SearchProd .up.> UC_Main : <<extend>>

UC_EditProd ..> UC_SearchProd : <<include>>
UC_StatusProd ..> UC_SearchProd : <<include>>

@enduml
