@startuml uc_tong_quat
left to right direction
skinparam packageStyle rectangle

actor "Nhân viên" as NV
actor "Thu ngân" as TN
actor "Thợ bếp" as TB
actor "Thủ kho" as TK
actor "Quản lý" as QL

NV <|-- QL
NV <|-- TN
NV <|-- TB
NV <|-- TK

rectangle "Hệ thống Quản lý tiệm bánh" {
  usecase "Cài đặt tài khoản" as UC1
  usecase "Quản lý ca làm việc" as UC5
  
  usecase "Quản lý khách hàng" as UC3
  usecase "Quản lý bán hàng" as UC4
  usecase "Quản lý sản phẩm" as UC6
  usecase "Quản lý thu chi" as UC10
  
  usecase "Quản lý nhân sự" as UC2
  usecase "Quản lý công thức và sản xuất" as UC7
  usecase "Xem báo cáo thống kê" as UC11
  
  usecase "Quản lý kho và nguyên liệu" as UC8
  usecase "Quản lý nhà cung cấp" as UC9
}

' ==========================================
' CÁC ACTOR BÊN TRÁI (Dùng mũi tên xuôi -->)
' ==========================================
NV --> UC1

TN --> UC5
TN --> UC3
TN --> UC4
TN --> UC6
TN --> UC10
TN --> UC11

TB --> UC8
TB --> UC7
TK --> UC8
TK --> UC9

' ==========================================
' ACTOR QUẢN LÝ BÊN PHẢI (Dùng mũi tên ngược <--)
' ==========================================
UC3 <-- QL
UC4 <-- QL
UC6 <-- QL
UC10 <-- QL

UC2 <-- QL
UC7 <-- QL
UC11 <-- QL

@enduml