-- Procedure mẫu CUD cho Nhân sự (NHANVIEN)
CREATE OR REPLACE PROCEDURE PROC_STAFF_CUD_TEMPLATE (
    P_ACTION            IN VARCHAR2,      -- CREATE | UPDATE | DELETE
    P_MANV              IN NUMBER,
    P_HOTEN             IN NVARCHAR2,
    P_TENDANGNHAP       IN VARCHAR2,
    P_SODIENTHOAI       IN VARCHAR2,
    P_MATKHAU_BAM       IN VARCHAR2,
    P_MAVAITRO          IN NUMBER,
    P_MANV_OUT          OUT NUMBER
)
IS
    V_MANV              NUMBER;
    V_ACTION            VARCHAR2(20) := UPPER(TRIM(P_ACTION));
BEGIN
    -- 1. Tạo nhân viên mới
    IF V_ACTION = 'CREATE' THEN
        INSERT INTO NHANVIEN (HOTEN, TENDANGNHAP, SODIENTHOAI, MATKHAU, THOIDIEMXOA)
        VALUES (P_HOTEN, P_TENDANGNHAP, P_SODIENTHOAI, P_MATKHAU_BAM, NULL)
        RETURNING MANV INTO V_MANV;

        -- 2. Gán vai trò mặc định
        INSERT INTO VAITRO_NHANVIEN (MAVAITRO, MANV)
        VALUES (P_MAVAITRO, V_MANV);

        P_MANV_OUT := V_MANV;
    ELSIF V_ACTION = 'UPDATE' THEN
        -- 3. Cập nhật hồ sơ
        UPDATE NHANVIEN
        SET HOTEN = P_HOTEN,
            SODIENTHOAI = P_SODIENTHOAI
        WHERE MANV = P_MANV;

        P_MANV_OUT := P_MANV;
    ELSIF V_ACTION = 'DELETE' THEN
        -- 4. Xóa mềm nhân viên
        UPDATE NHANVIEN
        SET THOIDIEMXOA = SYSDATE
        WHERE MANV = P_MANV;

        P_MANV_OUT := P_MANV;
    ELSE
        RAISE_APPLICATION_ERROR(-20110, 'Hành động CUD không hợp lệ cho nhân sự.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20111, 'Lỗi xử lý CUD nhân sự: ' || SQLERRM);
END;
/
