-- Trigger tự động cập nhật giá vốn sản phẩm khi giá vốn trung bình nguyên liệu thay đổi
-- Kích hoạt: SAU khi TRG_GIAVONTRUNGBINH_SOLUONGTONTONG cập nhật NGUYENLIEU.GIAVONTRUNGBINH
-- Tác dụng: Đảm bảo SANPHAM.GIAVON luôn phản ánh đúng giá vốn thực tế theo WAC
CREATE OR REPLACE TRIGGER TRG_CAPNHATGIASP_KHIGIAVONNL
AFTER UPDATE OF GIAVONTRUNGBINH ON NGUYENLIEU
FOR EACH ROW
WHEN (NEW.GIAVONTRUNGBINH <> OLD.GIAVONTRUNGBINH)
BEGIN

    UPDATE SANPHAM SP
    SET SP.GIAVON    = FUNC_TONGGIAVON(SP.MASP),
        SP.GIABAN    = ROUND(FUNC_TONGGIAVON(SP.MASP) * 2, -3),
        SP.PHIENBAN  = SP.PHIENBAN + 1
    WHERE SP.MASP IN (
        SELECT CT.MASP FROM CONGTHUC CT WHERE CT.MANL = :NEW.MANL
    )
    AND SP.THOIDIEMXOA IS NULL;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_CAPNHATGIASP_KHIGIAVONNL,
            'Lỗi TRG_CAPNHATGIASP_KHIGIAVONNL: ' || SQLERRM);
END;
/