-- Trigger trừ số lượng tồn tổng của một nguyên liệu khi thực hiện việc xuất nguyên liệu để làm bánh
CREATE OR REPLACE TRIGGER TRG_XUATSLNGUYENLIEU
AFTER INSERT OR UPDATE OR DELETE ON CTPHIEUXUAT_NL
FOR EACH ROW
DECLARE
    V_MALO CTPHIEUNHAP.MALO%type;
    V_MANL NGUYENLIEU.MANL%type;
    V_CHENHLECH CTPHIEUXUAT_NL.SOLUONG%type := 0;
BEGIN
    IF INSERTING THEN
        V_CHENHLECH := :NEW.SOLUONG;
        V_MALO := :NEW.MALO;
    ELSIF UPDATING THEN
        V_CHENHLECH := :NEW.SOLUONG - :OLD.SOLUONG;
        V_MALO := :NEW.MALO;
    ELSIF DELETING THEN
        V_CHENHLECH := -(:OLD.SOLUONG);
        V_MALO := :OLD.MALO;
    END IF;

    SELECT MANL INTO V_MANL
    FROM CTPHIEUNHAP
    WHERE MALO = V_MALO;

    UPDATE CTPHIEUNHAP
    SET SOLUONGCONLAI = SOLUONGCONLAI - V_CHENHLECH
    WHERE MALO = V_MALO;

    UPDATE NGUYENLIEU
    SET SOLUONGTONTONG = SOLUONGTONTONG - V_CHENHLECH
    WHERE MANL = V_MANL;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NL_KHONG_CO_LO_HANG, 'Lỗi: Không tìm thấy lô hàng trong kho.');
END;
/