-- Trigger tự động cập nhật giá vốn sản phẩm khi giá vốn trung bình nguyên liệu thay đổi
-- Kích hoạt: SAU khi TRG_GIAVONTRUNGBINH_SOLUONGTONTONG cập nhật NGUYENLIEU.GIAVONTRUNGBINH
-- Tác dụng: Đảm bảo SANPHAM.GIAVON luôn phản ánh đúng giá vốn thực tế theo WAC
CREATE OR REPLACE TRIGGER TRG_CAPNHATGIASP_KHIGIAVONNL
AFTER UPDATE OF GIAVONTRUNGBINH ON NGUYENLIEU
FOR EACH ROW
WHEN (NEW.GIAVONTRUNGBINH <> OLD.GIAVONTRUNGBINH)
BEGIN
    -- Sử dụng subquery SQL trực tiếp để tránh lỗi mutating table (ORA-04091) khi gọi function
    UPDATE SANPHAM SP
    SET (SP.GIAVON, SP.GIABAN) = (
        SELECT 
            NVL(SUM(CT.SOLUONGTIEUHAO * NL.GIAVONTRUNGBINH), 0),
            CASE 
                WHEN NVL(SUM(CT.SOLUONGTIEUHAO * NL.GIAVONTRUNGBINH), 0) * 2 >= 1000 
                THEN ROUND(NVL(SUM(CT.SOLUONGTIEUHAO * NL.GIAVONTRUNGBINH), 0) * 2, -3)
                ELSE NVL(SUM(CT.SOLUONGTIEUHAO * NL.GIAVONTRUNGBINH), 0) * 2
            END
        FROM CONGTHUC CT
        JOIN NGUYENLIEU NL ON CT.MANL = NL.MANL
        WHERE CT.MASP = SP.MASP
    ),
    SP.PHIENBAN  = SP.PHIENBAN + 1
    WHERE SP.MASP IN (
        SELECT CT.MASP FROM CONGTHUC CT WHERE CT.MANL = :NEW.MANL
    )
    AND SP.THOIDIEMXOA IS NULL;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_CAPNHATGIASP_KHIGIAVONNL,
            'Lỗi TRG_CAPNHATGIASP_KHIGIAVONNL: ' || SQLERRM);
END;
/