-- Trigger cập nhật giá vốn trung bình và số lượng tồn tổng
CREATE OR REPLACE TRIGGER TRG_GIAVONTRUNGBINH_SOLUONGTONTONG
AFTER INSERT ON CTPHIEUNHAP
FOR EACH ROW
DECLARE
    V_TONCU NGUYENLIEU.SOLUONGTONTONG%type := 0;
    V_GIACU NGUYENLIEU.GIAVONTRUNGBINH%type := 0;
    V_TONGSOLUONGMOI NGUYENLIEU.SOLUONGTONTONG%type := 0;
    V_GIAVONMOI NGUYENLIEU.GIAVONTRUNGBINH%type := 0;
BEGIN
    SELECT NVL(SOLUONGTONTONG, 0), NVL(GIAVONTRUNGBINH, 0)
    INTO V_TONCU, V_GIACU
    FROM NGUYENLIEU
    WHERE MANL = :NEW.MANL;

    V_TONGSOLUONGMOI := V_TONCU + :NEW.SOLUONG;

    IF V_TONGSOLUONGMOI > 0 THEN
        V_GIAVONMOI := ((V_TONCU * V_GIACU) + (:NEW.SOLUONG * :NEW.DONGIA)) / V_TONGSOLUONGMOI;
    ELSE
        V_GIAVONMOI := V_GIACU;
    END IF;

    UPDATE NGUYENLIEU
    SET GIAVONTRUNGBINH = V_GIAVONMOI,
        SOLUONGTONTONG = V_TONGSOLUONGMOI
    WHERE MANL = :NEW.MANL;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KHONG_CO_NGUYEN_LIEU, 'Lỗi: Không tìm thấy dữ liệu nguyên liệu.');
END;
/

