-- Trigger tính tổng tiền phiếu nhập kho
CREATE OR REPLACE TRIGGER TRG_TONGTIENNHAP
AFTER INSERT OR UPDATE OR DELETE ON CTPHIEUNHAP
FOR EACH ROW
DECLARE
    V_MAPN NUMBER;
    V_CHENHLECH NUMBER(15,2);
BEGIN
    IF INSERTING THEN
        V_CHENHLECH := :NEW.DONGIA * :NEW.SOLUONG;
        V_MAPN := :NEW.MAPN;
    ELSIF UPDATING THEN
        V_CHENHLECH := :NEW.DONGIA * :NEW.SOLUONG - :OLD.DONGIA * :OLD.SOLUONG;
        V_MAPN := :NEW.MAPN;
    ELSIF DELETING THEN
        V_CHENHLECH := -(:OLD.DONGIA * :OLD.SOLUONG);
        V_MAPN := :OLD.MAPN;
    END IF;

    UPDATE PHIEUNHAPKHO
    SET TONGTIENNHAP = NVL(TONGTIENNHAP, 0) + V_CHENHLECH
    WHERE MAPN = V_MAPN;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NL_KHONG_CO_PHIEUNHAP, 'Loi: Khong tim thay du lieu phieu nhap.');
END;
/