
CREATE OR REPLACE TRIGGER TRG_TINHLAI_GIASP
AFTER INSERT OR UPDATE OR DELETE ON CONGTHUC
BEGIN
    -- Tính lại giá vốn và giá bán cho toàn bộ sản phẩm có trong CONGTHUC
    -- ROUND(-3) = làm tròn đến nghìn gần nhất
    UPDATE SANPHAM SP
    SET SP.GIAVON = FUNC_TONGGIAVON(SP.MASP),
        SP.GIABAN = ROUND(FUNC_TONGGIAVON(SP.MASP) * 2, -3),
        SP.PHIENBAN = SP.PHIENBAN + 1
    WHERE SP.MASP IN (SELECT DISTINCT MASP FROM CONGTHUC)
      AND SP.THOIDIEMXOA IS NULL;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20100,
            'Loi TRG_TINHLAI_GIASP: ' || SQLERRM);
END;
/
