-- Trigger kiểm tra vệ sinh an toàn thực phẩm
    CREATE OR REPLACE TRIGGER TRG_KIEMTRAVSATTP
    BEFORE INSERT OR UPDATE ON NGUYENLIEU
    FOR EACH ROW
    BEGIN
        IF :NEW.DATCHUANVSATTP = 0 THEN
            RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NL_KHONG_DAT_VSATTP, 'NGUYEN_LIEU_KHONG_DAT_CHUAN: Nguyên liệu không đạt chuẩn, cấm nhập kho');
        END IF;
    END;
    /