
CREATE OR REPLACE TRIGGER TRG_TINHLAI_GIASP
AFTER INSERT OR UPDATE OR DELETE ON CONGTHUC
BEGIN
    -- Tính lại giá vốn và giá bán cho toàn bộ sản phẩm có trong CONGTHUC
    -- Sử dụng subquery SQL trực tiếp để tránh lỗi mutating table (ORA-04091) khi gọi function
    UPDATE SANPHAM SP
    SET (SP.GIAVON, SP.GIABAN) = (
        SELECT 
            NVL(SUM(CT.SOLUONGTIEUHAO * NL.GIAVONTRUNGBINH), 0),
            CASE 
                WHEN NVL(SUM(CT.SOLUONGTIEUHAO * NL.GIAVONTRUNGBINH), 0) * 2 >= 1000 
                THEN ROUND(NVL(SUM(CT.SOLUONGTIEUHAO * NL.GIAVONTRUNGBINH), 0) * 2, -3)
                ELSE NVL(SUM(CT.SOLUONGTIEUHAO * NL.GIAVONTRUNGBINH), 0) * 2
            END
        FROM CONGTHUC CT
        JOIN NGUYENLIEU NL ON CT.MANL = NL.MANL
        WHERE CT.MASP = SP.MASP
    ),
    SP.PHIENBAN = SP.PHIENBAN + 1
    WHERE SP.MASP IN (SELECT DISTINCT MASP FROM CONGTHUC)
      AND SP.THOIDIEMXOA IS NULL;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20100,
            'Loi TRG_TINHLAI_GIASP: ' || SQLERRM);
END;
/
