-- === 2.1 HOADON ===
CREATE OR REPLACE PROCEDURE PROC_HOADON_INSERT (
    p_MADON IN NUMBER DEFAULT NULL,
    p_MACA IN NUMBER,
    p_THUEVAT IN NUMBER DEFAULT 0,
    p_TONGTIENTHANHTOAN IN NUMBER,
    p_MAPTTT IN NUMBER,
    p_LOAIHD IN NVARCHAR2 DEFAULT NULL,
    p_MAHD OUT NUMBER
) AS
BEGIN
    INSERT INTO HOADON (
        MADON, MACA, NGAYXUATHD, THUEVAT, TONGTIENTHANHTOAN, MAPTTT, LOAIHD
    ) VALUES (
        p_MADON, p_MACA, CURRENT_TIMESTAMP, p_THUEVAT, p_TONGTIENTHANHTOAN, p_MAPTTT, p_LOAIHD
    ) RETURNING MAHD INTO p_MAHD;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HD_INSERT, 'Lỗi INSERT HOADON: ' || SQLERRM);
END PROC_HOADON_INSERT;
/

CREATE OR REPLACE PROCEDURE PROC_HOADON_UPDATE (
    p_MAHD IN NUMBER,
    p_THUEVAT IN NUMBER DEFAULT NULL,
    p_TONGTIENTHANHTOAN IN NUMBER DEFAULT NULL,
    p_MAPTTT IN NUMBER DEFAULT NULL,
    p_LOAIHD IN NVARCHAR2 DEFAULT NULL
) AS
BEGIN
    UPDATE HOADON SET
        THUEVAT = NVL(p_THUEVAT, THUEVAT),
        TONGTIENTHANHTOAN = NVL(p_TONGTIENTHANHTOAN, TONGTIENTHANHTOAN),
        MAPTTT = NVL(p_MAPTTT, MAPTTT),
        LOAIHD = NVL(p_LOAIHD, LOAIHD)
    WHERE MAHD = p_MAHD;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HD_UPDATE, 'Lỗi UPDATE HOADON: ' || SQLERRM);
END PROC_HOADON_UPDATE;
/

CREATE OR REPLACE PROCEDURE PROC_HOADON_DELETE (
    p_MAHD IN NUMBER
) AS
BEGIN
    -- Trigger INSTEAD OF DELETE sẽ chặn, nhưng vẫn để proc này để tính toàn
    RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HD_DELETE, 'Không thể xóa hóa đơn (Chứng từ tài chính)!');
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HD_DELETE, 'Lỗi DELETE HOADON: ' || SQLERRM);
END PROC_HOADON_DELETE;
/