-- === 4.1 NGUYENLIEU ===
CREATE OR REPLACE PROCEDURE PROC_NGUYENLIEU_INSERT (
    p_TENNL IN NVARCHAR2,
    p_XUATXU IN NVARCHAR2 DEFAULT NULL,
    p_MADVT IN NUMBER,
    p_MUCTONANTOAN IN NUMBER DEFAULT 0,
    p_MANX IN NUMBER,
    p_MANL OUT NUMBER
) AS
BEGIN
    INSERT INTO NGUYENLIEU (
        TENNL, XUATXU, MADVT, GIAVONTRUNGBINH, MUCTONANTOAN,
        SOLUONGTONTONG, DATCHUANVSATTP, PHIENBAN, MANX
    ) VALUES (
        p_TENNL, p_XUATXU, p_MADVT, 0, p_MUCTONANTOAN,
        0, 1, 1, p_MANX
    ) RETURNING MANL INTO p_MANL;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NL_INSERT, 'Lỗi INSERT NGUYENLIEU: ' || SQLERRM);
END PROC_NGUYENLIEU_INSERT;
/

CREATE OR REPLACE PROCEDURE PROC_NGUYENLIEU_UPDATE (
    p_MANL IN NUMBER,
    p_TENNL IN NVARCHAR2 DEFAULT NULL,
    p_XUATXU IN NVARCHAR2 DEFAULT NULL,
    p_MADVT IN NUMBER DEFAULT NULL,
    p_MUCTONANTOAN IN NUMBER DEFAULT NULL,
    p_DATCHUANVSATTP IN NUMBER DEFAULT NULL,
    p_PHIENBAN IN NUMBER
) AS
    v_affected_rows NUMBER;
BEGIN
    UPDATE NGUYENLIEU SET
        TENNL = NVL(p_TENNL, TENNL),
        XUATXU = NVL(p_XUATXU, XUATXU),
        MADVT = NVL(p_MADVT, MADVT),
        MUCTONANTOAN = NVL(p_MUCTONANTOAN, MUCTONANTOAN),
        DATCHUANVSATTP = NVL(p_DATCHUANVSATTP, DATCHUANVSATTP),
        PHIENBAN = PHIENBAN + 1
    WHERE MANL = p_MANL
    AND PHIENBAN = p_PHIENBAN;

    v_affected_rows := SQL%ROWCOUNT;

    IF v_affected_rows = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NL_UPDATE_CONFLICT, 'Xung đột dữ liệu NGUYENLIEU (Optimistic Lock)!');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NL_UPDATE, 'Lỗi UPDATE NGUYENLIEU: ' || SQLERRM);
END PROC_NGUYENLIEU_UPDATE;
/

CREATE OR REPLACE PROCEDURE PROC_NGUYENLIEU_DELETE (
    p_MANL IN NUMBER,
    p_MANX IN NUMBER
) AS
BEGIN
    -- Xóa mềm (Soft Delete)
    UPDATE NGUYENLIEU SET
        THOIDIEMXOA = CURRENT_TIMESTAMP,
        MANX = p_MANX
    WHERE MANL = p_MANL;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NL_DELETE, 'Lỗi DELETE NGUYENLIEU: ' || SQLERRM);
END PROC_NGUYENLIEU_DELETE;
/