
CREATE OR REPLACE PROCEDURE PROC_LAPBAOCAOPHIEUNHAP (
    P_SO_PHIEU_OUT  OUT NUMBER,
    P_CURSOR_OUT    OUT SYS_REFCURSOR
) IS
    V_SO_PHIEU NUMBER := 0;
BEGIN
    -- EXECUTE IMMEDIATE 'SET TRANSACTION ISOLATION LEVEL SERIALIZABLE';

    SELECT COUNT(*)
    INTO V_SO_PHIEU
    FROM PHIEUNHAPKHO;
    P_SO_PHIEU_OUT := V_SO_PHIEU;
    DBMS_SESSION.SLEEP(8);

    OPEN P_CURSOR_OUT FOR
        SELECT
            PN.MAPN,
            TO_CHAR(PN.NGAYNHAP, 'DD/MM/YYYY HH24:MI') AS NGAYNHAP_STR,
            NVL(NCC.TENNCC, '---')                      AS TENNCC,
            NVL(NV.HOTEN, '---')                        AS TENNV,
            NVL(PN.TONGTIENNHAP, 0)                     AS TONGTIENNHAP
        FROM PHIEUNHAPKHO PN
        LEFT JOIN NHACUNGCAP NCC ON PN.MANCC = NCC.MANCC
        LEFT JOIN NHANVIEN   NV  ON PN.MANV  = NV.MANV
        ORDER BY PN.MAPN DESC;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(
            PKG_ERROR_CODES.ERR_PHANTOM_READ_NHAPKHO,
            'Loi lap bao cao kiem ke phieu nhap: ' || SQLERRM
        );
END;
/
