-- === 1.2 CTDONHANG ===
CREATE OR REPLACE PROCEDURE PROC_CTDONHANG_INSERT (
    p_MADON IN NUMBER,
    p_MASP IN NUMBER,
    p_SOLUONG IN NUMBER,
    p_DONGIA IN NUMBER,
    p_PHANTRAMGIAM IN NUMBER DEFAULT 0,
    p_MACTHD OUT NUMBER
) AS
BEGIN
    INSERT INTO CTDONHANG (MADON, MASP, SOLUONG, DONGIA, PHANTRAMGIAM)
    VALUES (p_MADON, p_MASP, p_SOLUONG, p_DONGIA, p_PHANTRAMGIAM)
    RETURNING MACTHD INTO p_MACTHD;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_CTDON_INSERT, 'Lỗi INSERT CTDONHANG: ' || SQLERRM);
END PROC_CTDONHANG_INSERT;
/

CREATE OR REPLACE PROCEDURE PROC_CTDONHANG_UPDATE (
    p_MACTHD IN NUMBER,
    p_SOLUONG IN NUMBER DEFAULT NULL,
    p_DONGIA IN NUMBER DEFAULT NULL,
    p_PHANTRAMGIAM IN NUMBER DEFAULT NULL
) AS
BEGIN
    UPDATE CTDONHANG SET
        SOLUONG = NVL(p_SOLUONG, SOLUONG),
        DONGIA = NVL(p_DONGIA, DONGIA),
        PHANTRAMGIAM = NVL(p_PHANTRAMGIAM, PHANTRAMGIAM)
    WHERE MACTHD = p_MACTHD;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_CTDON_UPDATE, 'Lỗi UPDATE CTDONHANG: ' || SQLERRM);
END PROC_CTDONHANG_UPDATE;
/

CREATE OR REPLACE PROCEDURE PROC_CTDONHANG_DELETE (
    p_MACTHD IN NUMBER
) AS
BEGIN
    DELETE FROM CTDONHANG WHERE MACTHD = p_MACTHD;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_CTDON_DELETE, 'Lỗi DELETE CTDONHANG: ' || SQLERRM);
END PROC_CTDONHANG_DELETE;
/