-- Procedure Xử lý rủi ro Hủy/Bom hàng và hoàn kho
CREATE OR REPLACE PROCEDURE PROC_HUYDONVAHOANKHO(
    P_MADON IN NUMBER,
    P_LYDOHUY IN NVARCHAR2,
    P_MANV_CAPNHAT IN NUMBER
)
IS
    V_MATRANGTHAI_CU NUMBER;
    V_MATT_HUY NUMBER;
BEGIN
    -- 1. Lấy trạng thái hiện tại của đơn hàng trước khi chết
    SELECT MATRANGTHAI INTO V_MATRANGTHAI_CU
    FROM DONDATHANG
    WHERE MADON = P_MADON;

    -- Lấy ID động của trạng thái "Hủy"
    SELECT MATRANGTHAI INTO V_MATT_HUY
    FROM TRANGTHAIDON
    WHERE UPPER(TENTRANGTHAI) = 'HỦY';

    -- 2. Chốt án tử: Đổi trạng thái đơn hàng sang "Hủy"
    UPDATE DONDATHANG
    SET MATRANGTHAI = V_MATT_HUY
    WHERE MADON = P_MADON;

    -- 3. Quét & Hoàn kho
    FOR ROW_CT IN (
        SELECT MASP, SOLUONG
        FROM CTDONHANG
        WHERE MADON = P_MADON
    )
    LOOP
        UPDATE SANPHAM
        SET SOLUONGTON = SOLUONGTON + ROW_CT.SOLUONG
        WHERE MASP = ROW_CT.MASP;
    END LOOP;

    -- 4. Audit Log (Lưu vết hành động của Nhân viên kèm Lý Do Hủy chi tiết)
    INSERT INTO LICHSUDONHANG(MADON, MATRANGTHAI_CU, MATRANGTHAI_MOI, THOIGIANTHAYDOI, MANV_CAPNHAT, GHICHU)
    VALUES (P_MADON, V_MATRANGTHAI_CU, V_MATT_HUY, SYSDATE, P_MANV_CAPNHAT, P_LYDOHUY);

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HUY_DON_GIAO_DICH, 'Lỗi hệ thống giao dịch khi thực thi hủy đơn: ' || SQLERRM);
END;
/