-- Procedure khôi phục dữ liệu
CREATE OR REPLACE PROCEDURE PROC_KHOIPHUCDULIEU (
    P_TENBANG IN VARCHAR2,
    P_TENCOTXOA IN VARCHAR2,
    P_ID IN VARCHAR2
)
AS
    V_DYNAMICSQL VARCHAR2(1000);
BEGIN
    V_DYNAMICSQL := 'UPDATE ' || P_TENBANG ||
                    ' SET ThoiDiemXoa = NULL, MaNX = NULL ' ||
                    ' WHERE ' || P_TENCOTXOA || ' = :ID';

    EXECUTE IMMEDIATE V_DYNAMICSQL USING P_ID;
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HE_THONG_KHOIPHUC, 'Loi he thong khi khoi phuc du lieu: ' || SQLERRM);
END;
/