-- Procedure cập nhật trạng thái đơn hàng và lưu lịch sử thay đổi trong cùng một transaction
CREATE OR REPLACE PROCEDURE PROC_CHUYENTRANGTHAIDON(
    P_MADON IN DONDATHANG.MADON%type,
    P_MATRANGTHAI_MOI IN TRANGTHAIDON.MATRANGTHAI%type,
    P_MANV_CAPNHAT IN NHANVIEN.MANV%type,
    P_HINHTHUCNHAN IN DONDATHANG.HINHTHUCNHAN%type DEFAULT NULL
)
IS
    V_MATRANGTHAI_CU NUMBER;
    V_MATRANGTHAI_CHOT NUMBER;
    V_MATT_HOANTHANH NUMBER;
    V_MATT_CHOGIAO NUMBER;
    V_MATT_CHOKHACHLAY NUMBER;
BEGIN
    -- 1. Đọc trạng thái hiện tại của đơn và khóa dòng để tránh cập nhật đè
    SELECT MATRANGTHAI
    INTO V_MATRANGTHAI_CU
    FROM DONDATHANG
    WHERE MADON = P_MADON
    FOR UPDATE;

    -- 2. Nạp các trạng thái chuẩn theo tên (không hardcode ID)
    SELECT MATRANGTHAI INTO V_MATT_HOANTHANH
    FROM TRANGTHAIDON
    WHERE TENTRANGTHAI = N'Hoàn thành'
    FETCH FIRST 1 ROW ONLY;

    SELECT MATRANGTHAI INTO V_MATT_CHOGIAO
    FROM TRANGTHAIDON
    WHERE TENTRANGTHAI = N'Chờ giao'
    FETCH FIRST 1 ROW ONLY;

    SELECT MATRANGTHAI INTO V_MATT_CHOKHACHLAY
    FROM TRANGTHAIDON
    WHERE TENTRANGTHAI = N'Chờ khách lấy'
    FETCH FIRST 1 ROW ONLY;

    -- 3. Chặn sửa trạng thái nếu đơn đã hoàn thành
    IF V_MATRANGTHAI_CU = V_MATT_HOANTHANH THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DON_CHUYEN_TRANGTHAI, 'Don da hoan thanh, khong the cap nhat trang thai.');
    END IF;

    -- 4. Trường hợp bếp đánh dấu hoàn tất: map sang Chờ giao / Chờ khách lấy theo hình thức nhận
    V_MATRANGTHAI_CHOT := P_MATRANGTHAI_MOI;
    IF P_HINHTHUCNHAN IS NOT NULL AND P_MATRANGTHAI_MOI = V_MATT_HOANTHANH THEN
        IF P_HINHTHUCNHAN = 2 THEN
            V_MATRANGTHAI_CHOT := V_MATT_CHOGIAO;
        ELSIF P_HINHTHUCNHAN = 1 THEN
            V_MATRANGTHAI_CHOT := V_MATT_CHOKHACHLAY;
        END IF;
    END IF;

    -- 5. Chặn cập nhật trùng trạng thái
    IF V_MATRANGTHAI_CU = V_MATRANGTHAI_CHOT THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DON_CHUYEN_TRANGTHAI, 'Trang thai moi khong duoc trung trang thai hien tai.');
    END IF;

    -- 6. Cập nhật đơn hàng
    UPDATE DONDATHANG
    SET MATRANGTHAI = V_MATRANGTHAI_CHOT
    WHERE MADON = P_MADON;

    -- 7. Lưu lịch sử trạng thái
    INSERT INTO LICHSUDONHANG(MADON, MATRANGTHAI_CU, MATRANGTHAI_MOI, THOIGIANTHAYDOI, MANV_CAPNHAT)
    VALUES (P_MADON, V_MATRANGTHAI_CU, V_MATRANGTHAI_CHOT, CURRENT_TIMESTAMP, P_MANV_CAPNHAT);

    -- 8. Ghi log hoạt động nhân viên
    INSERT INTO HOATDONGNHANVIEN (MANV, NHOM, HANHDONG, ENTITY_ID)
    VALUES (P_MANV_CAPNHAT, 'DON_HANG',
            'Chuyen TT don #' || P_MADON || ' -> TT #' || V_MATRANGTHAI_CHOT,
            P_MADON);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DON_CHUYEN_TRANGTHAI, 'Loi he thong khi chuyen trang thai don hang: ' || SQLERRM);
END;
/