-- Procedure Đóng ca đối soát
CREATE OR REPLACE PROCEDURE PROC_DONGCADOISOAT(
    P_MACA            IN CALAMVIEC.MACA%type,
    P_TIENTHUCTEDEM   IN DOISOAT.TIENTHUCTEDEM%type,
    P_LYDOCHENHLECH   IN DOISOAT.LYDOCHENHLECH%type DEFAULT NULL
)
IS
    V_TONGTIENHETHONG NUMBER;
    V_CHENHLECH       NUMBER;
BEGIN
    -- 1. LẤY CON SỐ HỆ THỐNG MỚI NHẤT (DOUBLE-CHECK)
    V_TONGTIENHETHONG := FUNC_TINHTIENMATLYTUONG(P_MACA);
    V_CHENHLECH       := P_TIENTHUCTEDEM - V_TONGTIENHETHONG;

    -- 2. LƯU KẾT QUẢ ĐỐI SOÁT (Chỉ được lập 1 lần lúc đóng ca)
    INSERT INTO DOISOAT (MACA, TONGTIENHETHONG, TIENTHUCTEDEM, CHENHLECH, LYDOCHENHLECH)
    VALUES (P_MACA, V_TONGTIENHETHONG, P_TIENTHUCTEDEM, V_CHENHLECH, P_LYDOCHENHLECH);

    -- 3. CẬP NHẬT TRẠNG THÁI CA
    UPDATE CALAMVIEC
    SET THOIGIANDONGCA = SYSDATE,
        TRANGTHAI = 'Đã đóng'
    WHERE MACA = P_MACA AND TRANGTHAI = 'Đang mở';

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_CA_KHONG_TON_TAI, 'Lỗi: Ca làm việc không tồn tại hoặc đã được đóng trước đó.');
    END IF;

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_CA_KHONG_TON_TAI THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_CA_DONG_HE_THONG, 'Lỗi hệ thống khi Đóng ca và đối soát: ' || SQLERRM);
END;
/
