
-- === 1.3 CTDONTUYCHINH ===
CREATE OR REPLACE PROCEDURE PROC_CTDONTUYCHINH_INSERT (
    p_MADON IN NUMBER,
    p_MASP IN NUMBER,
    p_SOLUONG IN NUMBER,
    p_MAKC IN NUMBER DEFAULT NULL,
    p_MACOT IN NUMBER DEFAULT NULL,
    p_MANHAN IN NUMBER DEFAULT NULL,
    p_MATRANGTRI IN NUMBER DEFAULT NULL,
    p_LOICHUCTRENBAHN IN NVARCHAR2 DEFAULT NULL,
    p_GHICHUTHOBANH IN NVARCHAR2 DEFAULT NULL,
    p_HINHANHTHAMKHAO IN VARCHAR2 DEFAULT NULL,
    p_DONGIA IN NUMBER,
    p_THOIGIANCHUANBI IN NUMBER DEFAULT NULL,
    p_MACTTC OUT NUMBER
) AS
BEGIN
    INSERT INTO CTDONTUYCHINH (
        MADON, MASP, SOLUONG, MAKC, MACOT, MANHAN, MATRANGTRI,
        LOICHUCTRENBANH, GHICHUTHOBANH, HINHANHTHAMKHAO, DONGIA, THOIGIANCHUANBI
    ) VALUES (
        p_MADON, p_MASP, p_SOLUONG, p_MAKC, p_MACOT, p_MANHAN, p_MATRANGTRI,
        p_LOICHUCTRENBAHN, p_GHICHUTHOBANH, p_HINHANHTHAMKHAO, p_DONGIA, p_THOIGIANCHUANBI
    ) RETURNING MACTTC INTO p_MACTTC;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_CTDONTC_INSERT, 'Lỗi INSERT CTDONTUYCHINH: ' || SQLERRM);
END PROC_CTDONTUYCHINH_INSERT;
/

CREATE OR REPLACE PROCEDURE PROC_CTDONTUYCHINH_UPDATE (
    p_MACTTC IN NUMBER,
    p_SOLUONG IN NUMBER DEFAULT NULL,
    p_MAKC IN NUMBER DEFAULT NULL,
    p_MACOT IN NUMBER DEFAULT NULL,
    p_MANHAN IN NUMBER DEFAULT NULL,
    p_MATRANGTRI IN NUMBER DEFAULT NULL,
    p_LOICHUCTRENBAHN IN NVARCHAR2 DEFAULT NULL,
    p_GHICHUTHOBANH IN NVARCHAR2 DEFAULT NULL,
    p_HINHANHTHAMKHAO IN VARCHAR2 DEFAULT NULL,
    p_DONGIA IN NUMBER DEFAULT NULL,
    p_THOIGIANCHUANBI IN NUMBER DEFAULT NULL
) AS
BEGIN
    UPDATE CTDONTUYCHINH SET
        SOLUONG = NVL(p_SOLUONG, SOLUONG),
        MAKC = NVL(p_MAKC, MAKC),
        MACOT = NVL(p_MACOT, MACOT),
        MANHAN = NVL(p_MANHAN, MANHAN),
        MATRANGTRI = NVL(p_MATRANGTRI, MATRANGTRI),
        LOICHUCTRENBANH = NVL(p_LOICHUCTRENBAHN, LOICHUCTRENBANH),
        GHICHUTHOBANH = NVL(p_GHICHUTHOBANH, GHICHUTHOBANH),
        HINHANHTHAMKHAO = NVL(p_HINHANHTHAMKHAO, HINHANHTHAMKHAO),
        DONGIA = NVL(p_DONGIA, DONGIA),
        THOIGIANCHUANBI = NVL(p_THOIGIANCHUANBI, THOIGIANCHUANBI)
    WHERE MACTTC = p_MACTTC;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_CTDONTC_UPDATE, 'Lỗi UPDATE CTDONTUYCHINH: ' || SQLERRM);
END PROC_CTDONTUYCHINH_UPDATE;
/

CREATE OR REPLACE PROCEDURE PROC_CTDONTUYCHINH_DELETE (
    p_MACTTC IN NUMBER
) AS
BEGIN
    DELETE FROM CTDONTUYCHINH WHERE MACTTC = p_MACTTC;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_CTDONTC_DELETE, 'Lỗi DELETE CTDONTUYCHINH: ' || SQLERRM);
END PROC_CTDONTUYCHINH_DELETE;
/