

-- === 4.2 PHIEUNHAPKHO ===
CREATE OR REPLACE PROCEDURE PROC_PHIEUNHAPKHO_INSERT (
    p_MANV IN NUMBER,
    p_MANCC IN NUMBER,
    p_MAPN OUT NUMBER
) AS
BEGIN
    INSERT INTO PHIEUNHAPKHO (
        NGAYNHAP, MANV, MANCC, TONGTIENNHAP
    ) VALUES (
        CURRENT_TIMESTAMP, p_MANV, p_MANCC, 0
    ) RETURNING MAPN INTO p_MAPN;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_PNK_INSERT, 'Lỗi INSERT PHIEUNHAPKHO: ' || SQLERRM);
END PROC_PHIEUNHAPKHO_INSERT;
/

CREATE OR REPLACE PROCEDURE PROC_PHIEUNHAPKHO_UPDATE (
    p_MAPN IN NUMBER,
    p_MANV IN NUMBER DEFAULT NULL,
    p_MANCC IN NUMBER DEFAULT NULL
) AS
BEGIN
    UPDATE PHIEUNHAPKHO SET
        MANV = NVL(p_MANV, MANV),
        MANCC = NVL(p_MANCC, MANCC)
    WHERE MAPN = p_MAPN;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_PNK_UPDATE, 'Lỗi UPDATE PHIEUNHAPKHO: ' || SQLERRM);
END PROC_PHIEUNHAPKHO_UPDATE;
/

CREATE OR REPLACE PROCEDURE PROC_PHIEUNHAPKHO_DELETE (
    p_MAPN IN NUMBER
) AS
    v_count NUMBER;
BEGIN
    -- Kiểm tra xem có chi tiết nào đã được xuất kho hay không
    SELECT COUNT(*) INTO v_count
    FROM CTPHIEUNHAP
    WHERE MAPN = p_MAPN AND SOLUONGCONLAI < SOLUONG;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_PNK_DELETE_VALIDATION, 'Không thể hủy phiếu nhập này vì nguyên liệu đã được đem đi làm bánh!');
    END IF;

    DELETE FROM PHIEUNHAPKHO WHERE MAPN = p_MAPN;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_PNK_DELETE, 'Lỗi DELETE PHIEUNHAPKHO: ' || SQLERRM);
END PROC_PHIEUNHAPKHO_DELETE;
/
