

-- === 3.1 SANPHAM ===
CREATE OR REPLACE PROCEDURE PROC_SANPHAM_INSERT (
    p_MADM IN NUMBER,
    p_TENSP IN NVARCHAR2,
    p_GIACOBAN IN NUMBER,
    p_HINHANH IN VARCHAR2 DEFAULT NULL,
    p_CHOPHEPTUYCHINH IN NUMBER DEFAULT 0,
    p_THOIGIANBAOQUAN IN NUMBER DEFAULT NULL,
    p_THOIGIANCHUANBI IN NUMBER DEFAULT 0,
    p_MANX IN NUMBER,
    p_MASP OUT NUMBER
) AS
BEGIN
    IF p_GIACOBAN <= 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SP_GIACOBAN_VALIDATION, 'Giá cơ bản phải > 0!');
    END IF;

    INSERT INTO SANPHAM (
        MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH,
        THOIGIANBAOQUAN, SOLUONGTON, PHIENBAN, THOIGIANCHUANBI, MANX
    ) VALUES (
        p_MADM, p_TENSP, p_GIACOBAN, p_HINHANH, p_CHOPHEPTUYCHINH,
        p_THOIGIANBAOQUAN, 0, 1, p_THOIGIANCHUANBI, p_MANX
    ) RETURNING MASP INTO p_MASP;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SP_INSERT, 'Lỗi INSERT SANPHAM: ' || SQLERRM);
END PROC_SANPHAM_INSERT;
/

CREATE OR REPLACE PROCEDURE PROC_SANPHAM_UPDATE (
    p_MASP IN NUMBER,
    p_MADM IN NUMBER DEFAULT NULL,
    p_TENSP IN NVARCHAR2 DEFAULT NULL,
    p_GIACOBAN IN NUMBER DEFAULT NULL,
    p_HINHANH IN VARCHAR2 DEFAULT NULL,
    p_CHOPHEPTUYCHINH IN NUMBER DEFAULT NULL,
    p_THOIGIANBAOQUAN IN NUMBER DEFAULT NULL,
    p_THOIGIANCHUANBI IN NUMBER DEFAULT NULL,
    p_PHIENBAN IN NUMBER
) AS
    v_affected_rows NUMBER;
BEGIN
    UPDATE SANPHAM SET
        MADM = NVL(p_MADM, MADM),
        TENSP = NVL(p_TENSP, TENSP),
        GIACOBAN = NVL(p_GIACOBAN, GIACOBAN),
        HINHANH = NVL(p_HINHANH, HINHANH),
        CHOPHEPTUYCHINH = NVL(p_CHOPHEPTUYCHINH, CHOPHEPTUYCHINH),
        THOIGIANBAOQUAN = NVL(p_THOIGIANBAOQUAN, THOIGIANBAOQUAN),
        THOIGIANCHUANBI = NVL(p_THOIGIANCHUANBI, THOIGIANCHUANBI),
        PHIENBAN = PHIENBAN + 1
    WHERE MASP = p_MASP
    AND PHIENBAN = p_PHIENBAN;

    v_affected_rows := SQL%ROWCOUNT;

    IF v_affected_rows = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SP_UPDATE_CONFLICT, 'Xung đột dữ liệu SANPHAM (Optimistic Lock)!');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SP_UPDATE, 'Lỗi UPDATE SANPHAM: ' || SQLERRM);
END PROC_SANPHAM_UPDATE;
/

CREATE OR REPLACE PROCEDURE PROC_SANPHAM_DELETE (
    p_MASP IN NUMBER,
    p_MANX IN NUMBER
) AS
BEGIN
    -- Xóa mềm (Soft Delete)
    UPDATE SANPHAM SET
        THOIDIEMXOA = CURRENT_TIMESTAMP,
        MANX = p_MANX
    WHERE MASP = p_MASP;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SP_DELETE, 'Lỗi DELETE SANPHAM: ' || SQLERRM);
END PROC_SANPHAM_DELETE;
/