
-- === 1.1 DONDATHANG ===
CREATE OR REPLACE PROCEDURE PROC_DONDATHANG_INSERT (
    p_NGAYGIONHANBANH IN TIMESTAMP,
    p_MAKH IN NUMBER DEFAULT NULL,
    p_MANV_LAP IN NUMBER,
    p_MATRANGTHAI IN NUMBER,
    p_HINHTHUCNHAN IN NUMBER,
    p_DIACHIGIAO IN NVARCHAR2 DEFAULT NULL,
    p_TIENDACOC IN NUMBER DEFAULT 0,
    p_MADON OUT NUMBER
) AS
BEGIN
    INSERT INTO DONDATHANG (
        NGAYLAP, NGAYGIONHANBANH, MAKH, MANV_LAP, MATRANGTHAI,
        HINHTHUCNHAN, DIACHIGIAO, TIENDACOC, TONGTIENHDBAN, PHIENBAN
    ) VALUES (
        CURRENT_TIMESTAMP, p_NGAYGIONHANBANH, p_MAKH, p_MANV_LAP, p_MATRANGTHAI,
        p_HINHTHUCNHAN, p_DIACHIGIAO, p_TIENDACOC, 0, 1
    ) RETURNING MADON INTO p_MADON;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DON_INSERT, 'Lỗi INSERT DONDATHANG: ' || SQLERRM);
END PROC_DONDATHANG_INSERT;
/

CREATE OR REPLACE PROCEDURE PROC_DONDATHANG_UPDATE (
    p_MADON IN NUMBER,
    p_NGAYGIONHANBANH IN TIMESTAMP DEFAULT NULL,
    p_MATRANGTHAI IN NUMBER DEFAULT NULL,
    p_HINHTHUCNHAN IN NUMBER DEFAULT NULL,
    p_DIACHIGIAO IN NVARCHAR2 DEFAULT NULL,
    p_TIENDACOC IN NUMBER DEFAULT NULL,
    p_TONGTIENHDBAN IN NUMBER DEFAULT NULL
) AS
    v_affected_rows NUMBER;
BEGIN
    UPDATE DONDATHANG SET
        NGAYGIONHANBANH = NVL(p_NGAYGIONHANBANH, NGAYGIONHANBANH),
        MATRANGTHAI = NVL(p_MATRANGTHAI, MATRANGTHAI),
        HINHTHUCNHAN = NVL(p_HINHTHUCNHAN, HINHTHUCNHAN),
        DIACHIGIAO = NVL(p_DIACHIGIAO, DIACHIGIAO),
        TIENDACOC = NVL(p_TIENDACOC, TIENDACOC),
        TONGTIENHDBAN = NVL(p_TONGTIENHDBAN, TONGTIENHDBAN),
        PHIENBAN = PHIENBAN + 1
    WHERE MADON = p_MADON
    AND PHIENBAN = (SELECT PHIENBAN FROM DONDATHANG WHERE MADON = p_MADON);

    v_affected_rows := SQL%ROWCOUNT;

    IF v_affected_rows = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DON_UPDATE_CONFLICT, 'Xung đột dữ liệu (Optimistic Lock). Vui lòng tải lại trang!');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DON_UPDATE, 'Lỗi UPDATE DONDATHANG: ' || SQLERRM);
END PROC_DONDATHANG_UPDATE;
/

CREATE OR REPLACE PROCEDURE PROC_DONDATHANG_DELETE (
    p_MADON IN NUMBER
) AS
BEGIN
    DELETE FROM DONDATHANG WHERE MADON = p_MADON;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DON_DELETE, 'Lỗi DELETE DONDATHANG: ' || SQLERRM);
END PROC_DONDATHANG_DELETE;
/