-- Procedure Mở ca làm việc 
CREATE OR REPLACE PROCEDURE PROC_MOCA(
    P_MANV IN NHANVIEN.MANV%type,
    P_MAMAYPOS IN CALAMVIEC.MAMAYPOS%type,
    P_MACA_OUT OUT CALAMVIEC.MACA%type
)
IS
BEGIN
    INSERT INTO CALAMVIEC (MANV, MAMAYPOS, THOIGIANMOCA, TRANGTHAI)
    VALUES (P_MANV, P_MAMAYPOS, SYSDATE, 'Đang mở')
    RETURNING MACA INTO P_MACA_OUT;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_CA_MO_HE_THONG, 'Lỗi hệ thống khi Mở ca làm việc: ' || SQLERRM);
END;
/
