-- Procedure chốt ca làm việc và lưu bằng chứng đối soát
CREATE OR REPLACE PROCEDURE PROC_DONGCADOISOAT (
    P_MACA            IN NUMBER,
    P_TIENTHUCTEDEM   IN NUMBER,
    P_LYDOCHENHLECH   IN VARCHAR2 DEFAULT NULL
)
IS
    V_TONGTIENHETHONG NUMBER;
    V_CHENHLECH       NUMBER;
BEGIN
    -- 1. LẤY CON SỐ HỆ THỐNG MỚI NHẤT (DOUBLE-CHECK)
    V_TONGTIENHETHONG := FUNC_TINHTIENMATLYTUONG(P_MACA);
    V_CHENHLECH       := P_TIENTHUCTEDEM - V_TONGTIENHETHONG;

    -- 2. LƯU KẾT QUẢ ĐỐI SOÁT
    INSERT INTO DOISOAT (MACA, TONGTIENHETHONG, TIENTHUCTEDEM, CHENHLECH, LYDOCHENHLECH)
    VALUES (P_MACA, V_TONGTIENHETHONG, P_TIENTHUCTEDEM, V_CHENHLECH, P_LYDOCHENHLECH);

    -- 3. CẬP NHẬT TRẠNG THÁI CA
    UPDATE CALAMVIEC
    SET THOIGIANDONGCA = SYSDATE,
        TRANGTHAI = 'Đã đóng'
    WHERE MACA = P_MACA AND TRANGTHAI = 'Đang mở';

    -- 4. NẾU KHÔNG TÌM THẤY CA ĐỂ UPDATE, BÁO LỖI VỀ JAVA
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_CA_KHONG_TON_TAI, 'Loi: Ca lam viec khong ton tai hoac da duoc dong truoc do.');
    END IF;

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/