
-- === 2.2 PHIEUTHUCHI ===
CREATE OR REPLACE PROCEDURE PROC_PHIEUTHUCHI_INSERT (
    p_MALOAITHUCHI IN NUMBER,
    p_SOTIEN IN NUMBER,
    p_MANV IN NUMBER,
    p_MACA IN NUMBER,
    p_MAHD IN NUMBER DEFAULT NULL,
    p_MAPN IN NUMBER DEFAULT NULL,
    p_GHICHU IN NVARCHAR2 DEFAULT NULL,
    p_MAPHIEUTC OUT NUMBER
) AS
BEGIN
    -- Validate: chỉ 1 trong 2 (MAHD hoặc MAPN) được set
    IF (p_MAHD IS NOT NULL AND p_MAPN IS NOT NULL) OR (p_MAHD IS NULL AND p_MAPN IS NULL) THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_TC_PHIEUTHUCHI_VALIDATION, 'Phiếu thu chi phải liên kết với HÓA ĐƠN hoặc PHIẾU NHẬP, không được cả hai hoặc không có!');
    END IF;

    INSERT INTO PHIEUTHUCHI (
        NGAYTAO, MALOAITHUCHI, SOTIEN, MANV, MAHD, MAPN, MACA, GHICHU
    ) VALUES (
        CURRENT_TIMESTAMP, p_MALOAITHUCHI, p_SOTIEN, p_MANV, p_MAHD, p_MAPN, p_MACA, p_GHICHU
    ) RETURNING MAPHIEUTC INTO p_MAPHIEUTC;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_TC_PHIEUTHUCHI_INSERT, 'Lỗi INSERT PHIEUTHUCHI: ' || SQLERRM);
END PROC_PHIEUTHUCHI_INSERT;
/

CREATE OR REPLACE PROCEDURE PROC_PHIEUTHUCHI_UPDATE (
    p_MAPHIEUTC IN NUMBER,
    p_SOTIEN IN NUMBER DEFAULT NULL,
    p_GHICHU IN NVARCHAR2 DEFAULT NULL
) AS
BEGIN
    UPDATE PHIEUTHUCHI SET
        SOTIEN = NVL(p_SOTIEN, SOTIEN),
        GHICHU = NVL(p_GHICHU, GHICHU)
    WHERE MAPHIEUTC = p_MAPHIEUTC;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_TC_PHIEUTHUCHI_UPDATE, 'Lỗi UPDATE PHIEUTHUCHI: ' || SQLERRM);
END PROC_PHIEUTHUCHI_UPDATE;
/

CREATE OR REPLACE PROCEDURE PROC_PHIEUTHUCHI_DELETE (
    p_MAPHIEUTC IN NUMBER
) AS
BEGIN
    -- Trigger INSTEAD OF DELETE sẽ chặn, nhưng vẫn để proc này
    RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_TC_PHIEUTHUCHI_DELETE, 'Không thể xóa phiếu thu chi (Chứng từ tài chính)!');
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_TC_PHIEUTHUCHI_DELETE, 'Lỗi DELETE PHIEUTHUCHI: ' || SQLERRM);
END PROC_PHIEUTHUCHI_DELETE;
/
