@startuml
skinparam conditionStyle diamond
skinparam ranksep 80
skinparam swimlaneWidth 140
skinparam shadowing false
skinparam ActivityShape rounded
skinparam linetype ortho

|Người dùng|
|Hệ thống|
|CSDL|

|Người dùng|
start
:Chọn thao tác thêm mới, chỉnh sửa\nhoặc vô hiệu hóa\ntại màn hình quản lý;
|Hệ thống|
:Hiển thị biểu mẫu\nhoặc hộp thoại cảnh báo;
|Người dùng|
if (Nhấn nút hủy bỏ/Từ chối?) then (Có)
  |Hệ thống|
  :Đóng giao diện thao tác\nvà không ghi nhận dữ liệu;
  stop
else (Điền thông tin/Đồng ý)
  |Người dùng|
  :Điền thông tin và\nnhấn nút lưu/cập nhật/đồng ý;
  |Hệ thống|
  :Kiểm tra tính hợp lệ\ncủa các dữ liệu đầu vào;
  
  if (Bỏ trống các trường bắt buộc?) then (Có)
    :Hiển thị cảnh báo\nyêu cầu bổ sung;
    stop
  else (Không)
    if (Tên đăng nhập tạo mới đã tồn tại?) then (Có)
      :Báo lỗi trùng lặp\nvà yêu cầu chọn tên khác;
      stop
    else (Dữ liệu hợp lệ)
      |CSDL|
      :Thực thi lệnh lưu trữ\nhoặc đổi trạng thái;
      |Hệ thống|
      :Thông báo thành công\nvà tải lại danh sách nhân sự;
      stop
    endif
  endif
endif
@enduml