flowchart TD
    subgraph Nguoi_dung [Người dùng]
        ND1("Truy cập phân hệ Tài chính")
        ND2("Chọn Theo dõi dòng tiền")
    end

    subgraph He_thong [Hệ thống]
        start(( )) --> ND1
        ND1 --> ND2
        ND2 --> HT1("Tổng hợp các khoản thu và chi")
        HT1 --> HT2("Phân loại dòng tiền theo thẻ mặc định")
        HT2 --> HT3("Hiển thị tổng quan thu/chi")
        HT3 --> end_node((( )))
    end

    subgraph CSDL [CSDL]
        DB1("SELECT PHIEUTHUCHI, HOADON")
        Table1["PHIEUTHUCHI"]
    end

    HT1 --> DB1
    DB1 --> Table1
    Table1 --> HT2
