@startuml
skinparam conditionStyle diamond
skinparam ranksep 80
skinparam swimlaneWidth 140
skinparam shadowing false
skinparam ActivityShape rounded
skinparam linetype ortho

|Người dùng|
|Hệ thống|
|CSDL|

|Người dùng|
start
:Nhập từ khóa tìm kiếm\nvào thanh công cụ;
if (Xóa từ khóa tìm kiếm?) then (Có)
  |Hệ thống|
  :Hiển thị lại toàn bộ\ndanh sách khách hàng ban đầu;
  stop
else (Tìm kiêm khóa)
  |Hệ thống|
  :Tiếp nhận từ khóa;
  |CSDL|
  :Truy xuất dữ liệu từ danh sách\nhồ sơ khách hàng;
  |Hệ thống|
  if (Có dữ liệu nào khớp?) then (Không)
    :Hiển thị thông báo\nkhông tìm thấy kết quả\nvà xuất hiện nút gợi ý tạo mới;
    stop
  else (Có)
    :Trả về danh sách các khách hàng\nkhớp với điều kiện;
    |Người dùng|
    :Nhấn chọn một khách hàng cụ thể\nđể xem chi tiết hoặc áp dụng vào hóa đơn;
    stop
  endif
endif
@enduml