@startuml
skinparam conditionStyle diamond
skinparam ranksep 80
skinparam swimlaneWidth 140
skinparam shadowing false
skinparam ActivityShape rounded
skinparam linetype ortho

|Người dùng|
|Hệ thống|
|CSDL|

|Người dùng|
start
:Chọn các loại bánh hoặc đồ uống\nđể đưa vào giỏ hàng;
|Hệ thống|
:Tự động tính toán tổng tiền tạm tính;
|Người dùng|
if (Khách hàng là vãng lai không tài khoản?) then (Có)
  :Bỏ qua bước nhập số điện thoại;
else (Có tài khoản)
  :Nhập số điện thoại để kiểm tra\nthông tin thành viên;
  |Hệ thống|
  |CSDL|
  :Truy vấn hồ sơ;
  |Hệ thống|
  :Tự động áp dụng mức phần trăm giảm giá\nvà hiển thị tổng tiền cuối cùng;
endif
|Người dùng|
if (Khách muốn bỏ bớt một món đồ?) then (Có)
  :Chọn món và nhấn nút xóa;
  |Hệ thống|
  :Tính toán lại tổng tiền;
else (Không cập nhật)
endif
|Người dùng|
:Tiếp tục nhận tiền từ khách,\nnhập con số thực nhận;
|Hệ thống|
if (Số tiền khách đưa < Tổng hoá đơn?) then (Có)
  :Bôi đỏ ô nhập liệu\nvà vô hiệu hóa nút thanh toán;
  stop
else (Hợp lệ)
  |Người dùng|
  :Nhấn nút thanh toán;
  |CSDL|
  :Lưu trữ hóa đơn\nvà ghi nhận doanh thu;
  :Cộng dồn điểm tích lũy;
  |Hệ thống|
  :Điều khiển máy in xuất hóa đơn\nvà tự động tải lại màn hình bán hàng mới;
  stop
endif
@enduml