flowchart TD
    subgraph Nguoi_dung [Người dùng]
        ND1("Chọn Phân tích xu hướng")
        ND2("Chọn tiêu chí và mốc thời gian")
        ND3("Xem kết quả phân tích")
    end

    subgraph He_thong [Hệ thống]
        start(( )) --> ND1
        ND1 --> ND2
        ND2 --> HT1("Tổng hợp dữ liệu")
        HT1 --> HT2("Vẽ biểu đồ")
        HT2 --> DK1{"Đủ dữ liệu?"}
        DK1 -->|Không| HT3("Thông báo Chưa đủ dữ liệu để thống kê")
        HT3 --> end_node((( )))
        DK1 -->|Có| HT4("Hiển thị biểu đồ xu hướng")
        HT4 --> ND3
        ND3 --> end_node
    end

    subgraph CSDL [CSDL]
        DB1("SELECT HOADON, PHIEUTHUCHI")
        Table1["HOADON"]
    end

    HT1 --> DB1
    DB1 --> Table1
    Table1 --> DK1
