flowchart TD
    subgraph Nguoi_dung [Người dùng]
        ND1("Chọn chức năng Báo cáo hao hụt")
        ND2("Chọn thời gian cần xem")
    end

    subgraph He_thong [Hệ thống]
        start(( )) --> ND1
        ND1 --> ND2
        ND2 --> HT1("Quét phiếu hủy hàng, hàng lỗi")
        HT1 --> DK1{"Có phiếu hủy?"}
        DK1 -->|Không| HT2("Báo cáo mức hao hụt bằng 0")
        DK1 -->|Có| HT3("Quy đổi số lượng hỏng thành tiền")
        HT3 --> HT4("Hiển thị tổng giá trị hao hụt")
        HT4 --> end_node((( )))
        HT2 --> end_node
    end

    subgraph CSDL [CSDL]
        DB1("SELECT phiếu hủy, CTPHIEUXUAT")
        Table1["PHIEUXUATKHO"]
    end

    HT1 --> DB1
    DB1 --> Table1
    Table1 --> DK1
