flowchart TD
    subgraph Nguoi_dung [Người dùng]
        ND1("Chọn màn hình Quản lý đơn hàng")
        ND2("Nhấn vào từng đơn để xem chi tiết")
    end

    subgraph He_thong [Hệ thống]
        start(( )) --> ND1
        ND1 --> HT1("Tải danh sách các đơn hàng hiện tại")
        HT1 --> DK1{"Danh sách trống?"}
        DK1 -->|Có| HT2("Hiển thị giao diện không có đơn hàng")
        DK1 -->|Không| HT3("Phân loại đơn theo trạng thái")
        HT3 --> HT4("Hiển thị danh sách")
        HT4 --> ND2
        ND2 --> end_node((( )))
        HT2 --> end_node
    end

    subgraph CSDL [CSDL]
        DB1("SELECT DONDATHANG")
        Table1["DONDATHANG"]
    end

    HT1 --> DB1
    DB1 --> Table1
    Table1 --> DK1
