flowchart TD
    subgraph Nguoi_dung [Người dùng]
        ND1("Chọn ô tìm kiếm khách hàng")
        ND2("Nhập SĐT hoặc tên")
        ND3("Nhấn chọn khách để xem chi tiết")
    end

    subgraph He_thong [Hệ thống]
        start(( )) --> ND1
        ND1 --> ND2
        ND2 --> HT1("Kiểm tra định dạng SĐT")
        HT1 --> DK1{"Định dạng hợp lệ?"}
        DK1 -->|Không| HT2("Ngăn truy vấn, báo lỗi cú pháp")
        HT2 --> end_node((( )))
        DK1 -->|Có| HT3("Quét dữ liệu, trả kết quả")
        HT3 --> DK2{"Tìm thấy?"}
        DK2 -->|Không| HT4("Hiển thị gợi ý Tạo khách hàng mới")
        DK2 -->|Có| HT5("Hiển thị Hạng thẻ, Điểm tích lũy")
        HT5 --> ND3
        ND3 --> end_node
        HT4 --> end_node
    end

    subgraph CSDL [CSDL]
        DB1("SELECT KHACHHANG")
        Table1["KHACHHANG"]
    end

    HT3 --> DB1
    DB1 --> Table1
    Table1 --> DK2
