@startuml
skinparam ranksep 80
skinparam swimlaneWidth 140
skinparam shadowing false
skinparam ActivityShape rounded
skinparam linetype ortho

|Người dùng|
|Hệ thống|
|CSDL|

|Người dùng|
start
:Chọn chức năng báo cáo tồn kho\ntại màn hình tổng quan của kho;
:Thiết lập tháng và năm cần kiểm tra dữ liệu;
|Hệ thống|
|CSDL|
if (Hệ thống mất kết nối với bảng lịch sử thẻ kho?) then (Có)
  |Hệ thống|
  :Báo lỗi gián đoạn truy xuất\nvà yêu cầu thao tác tải lại trang;
  stop
else (Kết nối bình thường)
  |Hệ thống|
  :Xác định số lượng tồn cuối kỳ của tháng trước\nđể làm số lượng tồn đầu kỳ của tháng hiện tại;
  |CSDL|
  :Tập hợp tổng số lượng đã nhập,\nxuất hoặc xuất hủy trong tháng đó;
  |Hệ thống|
  :Cộng tổng nhập trừ tổng xuất;\nĐưa ra con số tồn cuối kỳ từng loại nguyên liệu;
  :Hiển thị bảng cân đối hoàn chỉnh;
  |Người dùng|
  if (Kết xuất danh sách?) then (Có)
    |Hệ thống|
    :Tạo lập tập tin định dạng bảng tính;
    stop
  else (Không)
    stop
  endif
endif
@enduml
