@startuml
skinparam style strictuml
skinparam shadowing false
skinparam defaultTextAlignment center

title Lập phiếu nhập kho

|Nhân viên|
|Hệ thống|
|CSDL|

|Hệ thống|
start
|CSDL|
:PHIEUNHAPKHO;
|Hệ thống|
:Hiển thị trang nhập kho;
|Nhân viên|
:Chọn thao tác tạo phiếu\nnhập;
|CSDL|
fork
  :NHACUNGCAP;
fork again
  :NGUYENLIEU;
end fork
|Hệ thống|
:Hiển thị biểu mẫu nhập\nthông tin phiếu nhập;
repeat
  |Nhân viên|
  :Điền thông tin nhà cung\ncấp và chi tiết lô hàng;
  |Hệ thống|
  :Kiểm tra thông tin nhập;
  if () then (Không\nhợp lệ)
    :Thông báo lỗi\nđịnh dạng;
  else (Hợp lệ)
    |CSDL|
    :Lưu thông tin\nphiếu nhập;
    :CTPHIEUNHAP;
    |Hệ thống|
    :Thông báo lập phiếu\nnhập thành công;
    stop
  endif
repeat while ()
@enduml
