-- Procedure them phuong thuc thanh toan
CREATE OR REPLACE PROCEDURE PROC_THEM_PHUONGTHUCTT (
    P_TENPTTT IN NVARCHAR2,
    P_MAPTTT_OUT OUT NUMBER
)
IS
BEGIN
    INSERT INTO PHUONGTHUCTT (TENPTTT, THOIDIEMXOA, MANX)
    VALUES (P_TENPTTT, NULL, NULL)
    RETURNING MAPTTT INTO P_MAPTTT_OUT;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_PTTT_THEM_HE_THONG, 'Loi he thong khi them Phuong thuc thanh toan: ' || SQLERRM);
END;
/

-- Procedure sua phuong thuc thanh toan
CREATE OR REPLACE PROCEDURE PROC_SUA_PHUONGTHUCTT (
    P_MAPTTT IN NUMBER,
    P_TENPTTT IN NVARCHAR2
)
IS
BEGIN
    UPDATE PHUONGTHUCTT
    SET TENPTTT = NVL(P_TENPTTT, TENPTTT)
    WHERE MAPTTT = P_MAPTTT;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_PTTT_KHONG_TON_TAI, 'Loi: Khong tim thay Phuong thuc thanh toan de cap nhat.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_PTTT_KHONG_TON_TAI THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_PTTT_THEM_HE_THONG, 'Loi he thong khi cap nhat Phuong thuc thanh toan: ' || SQLERRM);
END;
/

-- Procedure xoa phuong thuc thanh toan
CREATE OR REPLACE PROCEDURE PROC_XOA_PHUONGTHUCTT (
    P_MAPTTT IN NUMBER,
    P_MANX IN NUMBER
)
IS
BEGIN
    UPDATE PHUONGTHUCTT
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANX
    WHERE MAPTTT = P_MAPTTT;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_PTTT_KHONG_TON_TAI, 'Loi: Khong tim thay Phuong thuc thanh toan de xoa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_PTTT_KHONG_TON_TAI THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_PTTT_THEM_HE_THONG, 'Loi he thong khi xoa Phuong thuc thanh toan: ' || SQLERRM);
END;
/

-- Procedure them loai thu chi
CREATE OR REPLACE PROCEDURE PROC_THEM_LOAITHUCHI (
    P_TENLOAITHUCHI IN NVARCHAR2,
    P_PHANLOAI IN NVARCHAR2,
    P_MALOAITHUCHI_OUT OUT NUMBER
)
IS
BEGIN
    INSERT INTO LOAITHUCHI (TENLOAITHUCHI, PHANLOAI, THOIDIEMXOA, MANX)
    VALUES (P_TENLOAITHUCHI, P_PHANLOAI, NULL, NULL)
    RETURNING MALOAITHUCHI INTO P_MALOAITHUCHI_OUT;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_THANH_TOAN_GIAO_DICH, 'Loi he thong khi them Loai thu chi: ' || SQLERRM);
END;
/

-- Procedure sua loai thu chi
CREATE OR REPLACE PROCEDURE PROC_SUA_LOAITHUCHI (
    P_MALOAITHUCHI IN NUMBER,
    P_TENLOAITHUCHI IN NVARCHAR2,
    P_PHANLOAI IN NVARCHAR2
)
IS
BEGIN
    UPDATE LOAITHUCHI
    SET TENLOAITHUCHI = NVL(P_TENLOAITHUCHI, TENLOAITHUCHI),
        PHANLOAI = NVL(P_PHANLOAI, PHANLOAI)
    WHERE MALOAITHUCHI = P_MALOAITHUCHI;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_LOAITHUCHI_KHONG_TON_TAI, 'Loi: Khong tim thay Loai thu chi de cap nhat.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_LOAITHUCHI_KHONG_TON_TAI THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_THANH_TOAN_GIAO_DICH, 'Loi he thong khi cap nhat Loai thu chi: ' || SQLERRM);
END;
/

-- Procedure xoa loai thu chi
CREATE OR REPLACE PROCEDURE PROC_XOA_LOAITHUCHI(
    P_MALOAITHUCHI IN NUMBER,
    P_MANX IN NUMBER
)
IS
BEGIN
    UPDATE LOAITHUCHI
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANX
    WHERE MALOAITHUCHI = P_MALOAITHUCHI;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_LOAITHUCHI_KHONG_TON_TAI, 'Loi: Khong tim thay Loai thu chi de xoa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_LOAITHUCHI_KHONG_TON_TAI THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_THANH_TOAN_GIAO_DICH, 'Loi he thong khi xoa Loai thu chi: ' || SQLERRM);
END;
/

-- Procedure tao phieu thu chi
CREATE OR REPLACE PROCEDURE PROC_TAOPHIEUTHUCHI (
    P_MALOAITHUCHI IN NUMBER,
    P_SOTIEN IN NUMBER,
    P_MANV IN NUMBER,
    P_MAHD IN NUMBER DEFAULT NULL,
    P_MAPN IN NUMBER DEFAULT NULL,
    P_MACA IN NUMBER,
    P_GHICHU IN NVARCHAR2 DEFAULT NULL,
    P_MAPHIEUTC_OUT OUT NUMBER
)
IS
BEGIN
    INSERT INTO PHIEUTHUCHI (MALOAITHUCHI, SOTIEN, MANV, MAHD, MAPN, MACA, GHICHU)
    VALUES (P_MALOAITHUCHI, P_SOTIEN, P_MANV, P_MAHD, P_MAPN, P_MACA, P_GHICHU)
    RETURNING MAPHIEUTC INTO P_MAPHIEUTC_OUT;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_PHIEUTHUCHI_THEM_HE_THONG, 'Loi he thong khi tao Phieu Thu Chi: ' || SQLERRM);
END;
/

-- Procedure tao hoa don
CREATE OR REPLACE PROCEDURE PROC_TAOHOADON (
    P_MADON IN NUMBER,
    P_MACA IN NUMBER,
    P_THUEVAT IN NUMBER,
    P_TONGTIENTHANHTOAN IN NUMBER,
    P_MAPTTT IN NUMBER,
    P_LOAIHD IN NVARCHAR2,
    P_MAHD_OUT OUT NUMBER
)
IS
BEGIN
    INSERT INTO HOADON (MADON, MACA, THUEVAT, TONGTIENTHANHTOAN, MAPTTT, LOAIHD)
    VALUES (P_MADON, P_MACA, NVL(P_THUEVAT, 0), NVL(P_TONGTIENTHANHTOAN, 0), P_MAPTTT, P_LOAIHD)
    RETURNING MAHD INTO P_MAHD_OUT;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_THANH_TOAN_GIAO_DICH, 'Loi he thong khi tao Hoa don: ' || SQLERRM);
END;
/
