-- Procedure Thêm danh mục sản phẩm
CREATE OR REPLACE PROCEDURE PROC_THEM_DANHMUCSP (
    P_TENDM IN DANHMUCSP.TENDM%type,
    P_MADM_OUT OUT DANHMUCSP.MADM%type
)
IS
BEGIN
    INSERT INTO DANHMUCSP (TENDM)
    VALUES (P_TENDM)
    RETURNING MADM INTO P_MADM_OUT;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DM_THEM_HE_THONG, 'Loi he thong khi them Danh muc san pham: ' || SQLERRM);
END;
/

-- Procedure Sửa danh mục sản phẩm
CREATE OR REPLACE PROCEDURE PROC_SUA_DANHMUCSP (
    P_MADM IN DANHMUCSP.MADM%type,
    P_TENDM IN DANHMUCSP.TENDM%type
)
IS
BEGIN
    UPDATE DANHMUCSP
    SET TENDM = NVL(P_TENDM, TENDM)
    WHERE MADM = P_MADM;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DM_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Danh muc san pham de cap nhat.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_DM_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DM_CAPNHAT_HE_THONG, 'Loi he thong khi cap nhat Danh muc san pham: ' || SQLERRM);
END;
/

-- Procedure Xóa danh mục sản phẩm
CREATE OR REPLACE PROCEDURE PROC_XOA_DANHMUCSP (
    P_MADM IN DANHMUCSP.MADM%type,
    P_MANX IN NHANVIEN.MANV%type
)
IS
BEGIN
    UPDATE DANHMUCSP
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANX
    WHERE MADM = P_MADM;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DM_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay Danh muc san pham de xoa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_DM_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DM_XOA_HE_THONG, 'Loi he thong khi xoa Danh muc san pham: ' || SQLERRM);
END;
/

-- Procedure Thêm sản phẩm (tự động tính giá vốn/giá bán nếu không truyền vào)
CREATE OR REPLACE PROCEDURE PROC_THEM_SANPHAM (
    P_MADM              IN NUMBER,
    P_TENSP             IN NVARCHAR2,
    P_HINHANH           IN VARCHAR2,
    P_CHOPHEPTUYCHINH   IN NUMBER,
    P_THOIGIANBAOQUAN   IN NUMBER,
    P_THOIGIANCHUANBI   IN NUMBER,
    P_GIAVON            IN NUMBER,
    P_GIABAN            IN NUMBER,
    P_MASP_OUT          OUT NUMBER,
    P_MANV_LAP          IN NUMBER DEFAULT NULL
)
IS
    V_GIAVON NUMBER := NVL(P_GIAVON, 0);
    V_GIABAN NUMBER;
BEGIN
    -- 1. Tạo bản ghi sản phẩm; GIAVON/GIABAN = 0 hợp lệ khi chưa có BOM
    INSERT INTO SANPHAM (MADM, TENSP, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, THOIGIANCHUANBI, GIAVON, GIABAN)
    VALUES (P_MADM, P_TENSP, P_HINHANH, P_CHOPHEPTUYCHINH, P_THOIGIANBAOQUAN, P_THOIGIANCHUANBI, V_GIAVON, 0)
    RETURNING MASP INTO P_MASP_OUT;

    -- 2. Tính giá bán: ưu tiên P_GIABAN, fallback tính từ giá vốn; bỏ qua nếu chưa có
    IF NVL(P_GIABAN, 0) > 0 THEN
        V_GIABAN := ROUND(P_GIABAN, -3);
    ELSIF V_GIAVON > 0 THEN
        V_GIABAN := ROUND(V_GIAVON * 2, -3);
    END IF;

    -- 3. Cập nhật giá bán chỉ khi đã tính được
    IF V_GIABAN IS NOT NULL THEN
        UPDATE SANPHAM SET GIABAN = V_GIABAN WHERE MASP = P_MASP_OUT;
    END IF;

    -- 4. Ghi log hoạt động
    IF P_MANV_LAP IS NOT NULL THEN
        INSERT INTO HOATDONGNHANVIEN (MANV, NHOM, HANHDONG, ENTITY_ID)
        VALUES (P_MANV_LAP, 'SAN_PHAM', 'Them SP: ' || P_TENSP || ' (#' || P_MASP_OUT || ')', P_MASP_OUT);
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SANPHAM_THEM_HE_THONG, 'Lỗi hệ thống khi thêm sản phẩm: ' || SQLERRM);
END;
/

-- Procedure Sửa sản phẩm (tự động tính lại giá vốn/giá bán từ công thức nếu không truyền)
CREATE OR REPLACE PROCEDURE PROC_SUA_SANPHAM (
    P_MASP              IN SANPHAM.MASP%type,
    P_MADM              IN DANHMUCSP.MADM%type,
    P_TENSP             IN SANPHAM.TENSP%type,
    P_HINHANH           IN SANPHAM.HINHANH%type,
    P_CHOPHEPTUYCHINH   IN SANPHAM.CHOPHEPTUYCHINH%type,
    P_THOIGIANBAOQUAN   IN SANPHAM.THOIGIANBAOQUAN%type,
    P_THOIGIANCHUANBI   IN SANPHAM.THOIGIANCHUANBI%type,
    P_GIAVON            IN SANPHAM.GIAVON%type,
    P_GIABAN            IN SANPHAM.GIABAN%type
)
IS
    V_GIAVON NUMBER;
    V_GIABAN NUMBER;
BEGIN
    -- 1. Xác định giá vốn: nếu truyền vào thì dùng, ngược lại tính từ công thức
    IF NVL(P_GIAVON, 0) > 0 THEN
        V_GIAVON := P_GIAVON;
    ELSE
        V_GIAVON := FUNC_TONGGIAVON(P_MASP);
    END IF;

    -- 2. Xác định giá bán: nếu truyền vào thì làm tròn, ngược lại tính theo công thức
    IF NVL(P_GIABAN, 0) > 0 THEN
        V_GIABAN := ROUND(P_GIABAN, -3);
    ELSE
        V_GIABAN := ROUND(V_GIAVON * 2, -3);
    END IF;

    -- 3. Cập nhật toàn bộ thông tin sản phẩm
    UPDATE SANPHAM
    SET MADM              = NVL(P_MADM, MADM),
        TENSP             = NVL(P_TENSP, TENSP),
        HINHANH           = NVL(P_HINHANH, HINHANH),
        CHOPHEPTUYCHINH   = NVL(P_CHOPHEPTUYCHINH, CHOPHEPTUYCHINH),
        THOIGIANBAOQUAN   = NVL(P_THOIGIANBAOQUAN, THOIGIANBAOQUAN),
        THOIGIANCHUANBI   = NVL(P_THOIGIANCHUANBI, THOIGIANCHUANBI),
        GIAVON            = V_GIAVON,
        GIABAN            = V_GIABAN,
        PHIENBAN          = PHIENBAN + 1
    WHERE MASP = P_MASP;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SANPHAM_KHONG_TON_TAI_CN, 'Lỗi: Không tìm thấy sản phẩm để cập nhật.');
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_SANPHAM_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SANPHAM_CAPNHAT_HE_THONG, 'Lỗi hệ thống khi cập nhật sản phẩm: ' || SQLERRM);
END;
/

-- Procedure Xóa sản phẩm
CREATE OR REPLACE PROCEDURE PROC_XOA_SANPHAM (
    P_MASP IN SANPHAM.MASP%type,
    P_MANX IN NHANVIEN.MANV%type
)
IS
    V_ORDER_COUNT NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO V_ORDER_COUNT FROM CTDONHANG WHERE MASP = P_MASP;

    IF V_ORDER_COUNT > 0 THEN
        UPDATE SANPHAM
        SET THOIDIEMXOA = SYSDATE,
            MANX = P_MANX,
            PHIENBAN = PHIENBAN + 1
        WHERE MASP = P_MASP;
    ELSE
        DELETE FROM CONGTHUC WHERE MASP = P_MASP;
        DELETE FROM SANPHAM WHERE MASP = P_MASP;
    END IF;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SANPHAM_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay San pham de xoa.');
    END IF;

    INSERT INTO HOATDONGNHANVIEN (MANV, NHOM, HANHDONG, ENTITY_ID)
    VALUES (P_MANX, 'SAN_PHAM', 'Xoa SP #' || P_MASP, P_MASP);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_SANPHAM_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SANPHAM_XOA_HE_THONG, 'Loi he thong khi xoa San pham: ' || SQLERRM);
END;
/

-- ==============================================================
-- PROCEDURE CUD - MODULE THUOC TINH SAN PHAM
-- Gom: KICH CO BANH, COT BANH, NHAN BANH, KIEU TRANG TRI
-- ==============================================================

-- --------------------------------------------------------------
-- 1. KICH CO BANH
-- --------------------------------------------------------------
CREATE OR REPLACE PROCEDURE PROC_THEM_KICHCOBANH (
    P_TENKC IN KICHCOBANH.TENKC%type,
    P_PHUPHI IN KICHCOBANH.PHUPHI%type,
    P_MAKC_OUT OUT KICHCOBANH.MAKC%type
)
IS
BEGIN
    INSERT INTO KICHCOBANH (TENKC, PHUPHI)
    VALUES (P_TENKC, NVL(P_PHUPHI, 0))
    RETURNING MAKC INTO P_MAKC_OUT;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KICHCO_THEM_HE_THONG, 'Loi he thong khi them Kich co banh: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_CAPNHAT_KICHCOBANH (
    P_MAKC IN KICHCOBANH.MAKC%type,
    P_TENKC IN KICHCOBANH.TENKC%type,
    P_PHUPHI IN KICHCOBANH.PHUPHI%type
)
IS
BEGIN
    UPDATE KICHCOBANH
    SET TENKC = NVL(P_TENKC, TENKC),
        PHUPHI = NVL(P_PHUPHI, PHUPHI)
    WHERE MAKC = P_MAKC;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KICHCO_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Kich co banh de cap nhat.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_KICHCO_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KICHCO_CAPNHAT_HE_THONG, 'Loi he thong khi cap nhat Kich co banh: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_XOA_KICHCOBANH (
    P_MAKC IN KICHCOBANH.MAKC%type,
    P_MANX IN NHANVIEN.MANV%type
)
IS
BEGIN
    UPDATE KICHCOBANH
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANX
    WHERE MAKC = P_MAKC;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KICHCO_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay Kich co banh de xoa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_KICHCO_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KICHCO_XOA_HE_THONG, 'Loi he thong khi xoa Kich co banh: ' || SQLERRM);
END;
/

-- --------------------------------------------------------------
-- 2. COT BANH
-- --------------------------------------------------------------
CREATE OR REPLACE PROCEDURE PROC_THEM_COTBANH (
    P_TENCOT IN COTBANH.TENCOT%type,
    P_PHUPHI IN COTBANH.PHUPHI%type,
    P_MACOT_OUT OUT COTBANH.MACOT%type
)
IS
BEGIN
    INSERT INTO COTBANH (TENCOT, PHUPHI)
    VALUES (P_TENCOT, NVL(P_PHUPHI, 0))
    RETURNING MACOT INTO P_MACOT_OUT;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_COTBANH_THEM_HE_THONG, 'Loi he thong khi them Cot banh: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_CAPNHAT_COTBANH (
    P_MACOT IN COTBANH.MACOT%type,
    P_TENCOT IN COTBANH.TENCOT%type,
    P_PHUPHI IN COTBANH.PHUPHI%type
)
IS
BEGIN
    UPDATE COTBANH
    SET TENCOT = NVL(P_TENCOT, TENCOT),
        PHUPHI = NVL(P_PHUPHI, PHUPHI)
    WHERE MACOT = P_MACOT;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_COTBANH_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Cot banh de cap nhat.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_COTBANH_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_COTBANH_CAPNHAT_HE_THONG, 'Loi he thong khi cap nhat Cot banh: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_XOA_COTBANH (
    P_MACOT IN NUMBER,
    P_MANX IN NUMBER
)
IS
BEGIN
    UPDATE COTBANH
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANX
    WHERE MACOT = P_MACOT;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_COTBANH_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay Cot banh de xoa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_COTBANH_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_COTBANH_XOA_HE_THONG, 'Loi he thong khi xoa Cot banh: ' || SQLERRM);
END;
/

-- --------------------------------------------------------------
-- 3. NHAN BANH
-- --------------------------------------------------------------
CREATE OR REPLACE PROCEDURE PROC_THEM_NHANBANH (
    P_TENNHAN IN NHANBANH.TENNHAN%type,
    P_PHUPHI IN NHANBANH.PHUPHI%type,
    P_MANHAN_OUT OUT NHANBANH.MANHAN%type
)
IS
BEGIN
    INSERT INTO NHANBANH (TENNHAN, PHUPHI)
    VALUES (P_TENNHAN, NVL(P_PHUPHI, 0))
    RETURNING MANHAN INTO P_MANHAN_OUT;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NHANBANH_THEM_HE_THONG, 'Loi he thong khi them Nhan banh: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_CAPNHAT_NHANBANH(
    P_MANHAN IN NHANBANH.MANHAN%type,
    P_TENNHAN IN NHANBANH.TENNHAN%type,
    P_PHUPHI IN NHANBANH.PHUPHI%type
)
IS
BEGIN
    UPDATE NHANBANH
    SET TENNHAN = NVL(P_TENNHAN, TENNHAN),
        PHUPHI = NVL(P_PHUPHI, PHUPHI)
    WHERE MANHAN = P_MANHAN;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NHANBANH_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Nhan banh de cap nhat.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_NHANBANH_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NHANBANH_CAPNHAT_HE_THONG, 'Loi he thong khi cap nhat Nhan banh: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_XOA_NHANBANH (
    P_MANHAN IN NHANBANH.MANHAN%type,
    P_MANX IN NHANVIEN.MANV%type
)
IS
BEGIN
    UPDATE NHANBANH
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANX
    WHERE MANHAN = P_MANHAN;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NHANBANH_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay Nhan banh de xoa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_NHANBANH_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NHANBANH_XOA_HE_THONG, 'Loi he thong khi xoa Nhan banh: ' || SQLERRM);
END;
/

-- --------------------------------------------------------------
-- 4. KIEU TRANG TRI
-- --------------------------------------------------------------
CREATE OR REPLACE PROCEDURE PROC_THEM_KIEUTRANGTRI (
    P_TENTRANGTRI IN KIEUTRANGTRI.TENTRANGTRI%type,
    P_PHUPHI IN KIEUTRANGTRI.PHUPHI%type,
    P_MATRANGTRI_OUT OUT KIEUTRANGTRI.MATRANGTRI%type
)
IS
BEGIN
    INSERT INTO KIEUTRANGTRI (TENTRANGTRI, PHUPHI)
    VALUES (P_TENTRANGTRI, NVL(P_PHUPHI, 0))
    RETURNING MATRANGTRI INTO P_MATRANGTRI_OUT;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_TRANGTRI_THEM_HE_THONG, 'Loi he thong khi them Kieu trang tri: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_CAPNHAT_KIEUTRANGTRI (
    P_MATRANGTRI IN KIEUTRANGTRI.MATRANGTRI%type,
    P_TENTRANGTRI IN KIEUTRANGTRI.TENTRANGTRI%type,
    P_PHUPHI IN KIEUTRANGTRI.PHUPHI%type
)
IS
BEGIN
    UPDATE KIEUTRANGTRI
    SET TENTRANGTRI = NVL(P_TENTRANGTRI, TENTRANGTRI),
        PHUPHI = NVL(P_PHUPHI, PHUPHI)
    WHERE MATRANGTRI = P_MATRANGTRI;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_TRANGTRI_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Kieu trang tri de cap nhat.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_TRANGTRI_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_TRANGTRI_CAPNHAT_HE_THONG, 'Loi he thong khi cap nhat Kieu trang tri: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_XOA_KIEUTRANGTRI (
    P_MATRANGTRI IN KIEUTRANGTRI.MATRANGTRI%type,
    P_MANX IN NHANVIEN.MANV%type
)
IS
BEGIN
    UPDATE KIEUTRANGTRI
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANX
    WHERE MATRANGTRI = P_MATRANGTRI;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_TRANGTRI_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay Kieu trang tri de xoa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_TRANGTRI_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_TRANGTRI_XOA_HE_THONG, 'Loi he thong khi xoa Kieu trang tri: ' || SQLERRM);
END;
/

-- ==============================================================
-- MODULE CONG THUC NGUYEN LIEU (Bill of Materials)
-- ==============================================================

-- Procedure Thêm/Sửa một dòng công thức (UPSERT theo PK composite)
CREATE OR REPLACE PROCEDURE PROC_UPSERT_CONGTHUC (
    P_MASP           IN CONGTHUC.MASP%type,
    P_MANL           IN CONGTHUC.MANL%type,
    P_SOLUONGTIEUHAO IN CONGTHUC.SOLUONGTIEUHAO%type
)
IS
BEGIN
    -- MERGE xử lý cả INSERT lẫn UPDATE
    MERGE INTO CONGTHUC CT
    USING (SELECT P_MASP AS MASP, P_MANL AS MANL FROM DUAL) SRC
    ON (CT.MASP = SRC.MASP AND CT.MANL = SRC.MANL)
    WHEN MATCHED THEN
        UPDATE SET CT.SOLUONGTIEUHAO = P_SOLUONGTIEUHAO
    WHEN NOT MATCHED THEN
        INSERT (MASP, MANL, SOLUONGTIEUHAO)
        VALUES (P_MASP, P_MANL, P_SOLUONGTIEUHAO);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20801, 'Lỗi hệ thống khi lưu công thức: ' || SQLERRM);
END;
/

-- Procedure Xóa một dòng nguyên liệu khỏi công thức sản phẩm
CREATE OR REPLACE PROCEDURE PROC_XOA_CONGTHUC (
    P_MASP IN CONGTHUC.MASP%type,
    P_MANL IN CONGTHUC.MANL%type
)
IS
BEGIN
    DELETE FROM CONGTHUC
    WHERE MASP = P_MASP AND MANL = P_MANL;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20802, 'Lỗi: Không tìm thấy dòng công thức cần xóa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = -20802 THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(-20803, 'Lỗi hệ thống khi xóa công thức: ' || SQLERRM);
END;
/
