-- Procedure cho nhan vien thoi viec (Soft terminate — khong xoa du lieu)
CREATE OR REPLACE PROCEDURE PROC_THOIVIEC_NHANVIEN (
    P_MANV IN NHANVIEN.MANV%type
)
IS
BEGIN
    UPDATE NHANVIEN SET TRANGTHAILAMVIEC = 0 WHERE MANV = P_MANV;
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NV_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Nhan vien de cap nhat.');
    END IF;
   
    UPDATE TAIKHOAN SET TRANGTHAITK = 0 WHERE MANV = P_MANV;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_NV_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NV_XOA_HE_THONG, 'Loi he thong khi cho thoi viec: ' || SQLERRM);
END;
/

-- Procedure them vai tro
CREATE OR REPLACE PROCEDURE PROC_THEM_VAITRO (
    P_TENVAITRO IN VAITRO.TENVAITRO%type,
    P_MOTA IN VAITRO.MOTA%type DEFAULT NULL,
    P_MAVAITRO_OUT OUT VAITRO.MAVAITRO%type
)
IS
BEGIN
    INSERT INTO VAITRO (TENVAITRO, MOTA, THOIDIEMXOA, MANX)
    VALUES (P_TENVAITRO, P_MOTA, NULL, NULL)
    RETURNING MAVAITRO INTO P_MAVAITRO_OUT;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_VAITRO_THEM_HE_THONG, 'Loi he thong khi them Vai tro: ' || SQLERRM);
END;
/

-- Procedure sua vai tro
CREATE OR REPLACE PROCEDURE PROC_SUA_VAITRO (
    P_MAVAITRO IN VAITRO.MAVAITRO%type,
    P_TENVAITRO IN VAITRO.TENVAITRO%type,
    P_MOTA IN VAITRO.MOTA%type
)
IS
BEGIN
    UPDATE VAITRO
    SET TENVAITRO = NVL(P_TENVAITRO, TENVAITRO),
        MOTA = NVL(P_MOTA, MOTA)
    WHERE MAVAITRO = P_MAVAITRO;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_VAITRO_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Vai tro de cap nhat.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_VAITRO_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_VAITRO_CAPNHAT_HE_THONG, 'Loi he thong khi cap nhat Vai tro: ' || SQLERRM);
END;
/

-- Procedure xoa vai tro
CREATE OR REPLACE PROCEDURE PROC_XOA_VAITRO (
    P_MAVAITRO IN VAITRO.MAVAITRO%type,
    P_MANV_XOA IN NHANVIEN.MANV%type
)
IS
BEGIN
    UPDATE VAITRO
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANV_XOA
    WHERE MAVAITRO = P_MAVAITRO;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_VAITRO_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay Vai tro de xoa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_VAITRO_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_VAITRO_XOA_HE_THONG, 'Loi he thong khi xoa Vai tro: ' || SQLERRM);
END;
/

-- Procedure them nhan vien (Tach NHANVIEN va TAIKHOAN)
CREATE OR REPLACE PROCEDURE PROC_THEM_NHANVIEN (
    P_HOTEN IN NHANVIEN.HOTEN%type,
    P_NGAYSINH IN NHANVIEN.NGAYSINH%type,
    P_SDT IN NHANVIEN.SDT%type,
    P_DIACHI IN NHANVIEN.DIACHI%type,
    P_TENDANGNHAP IN TAIKHOAN.TENDANGNHAP%type,
    P_MATKHAU IN TAIKHOAN.MATKHAU%type,
    P_TRANGTHAILAMVIEC IN NHANVIEN.TRANGTHAILAMVIEC%type,
    P_MANV_OUT OUT NHANVIEN.MANV%type
)
IS
    V_COUNT NUMBER;
BEGIN
    -- 1. Kiem tra trung SDT
    SELECT COUNT(*) INTO V_COUNT FROM NHANVIEN WHERE SDT = P_SDT;
    IF V_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NV_SDT_TON_TAI, 'Loi: So dien thoai nay da duoc su dung boi nhan vien khac.');
    END IF;

    -- 2. Kiem tra trung ten dang nhap
    SELECT COUNT(*) INTO V_COUNT FROM TAIKHOAN WHERE UPPER(TENDANGNHAP) = UPPER(P_TENDANGNHAP);
    IF V_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NV_TENDANGNHAP_TON_TAI, 'Loi: Ten dang nhap nay da ton tai trong he thong.');
    END IF;

    -- 3. Them ho so nhan su
    INSERT INTO NHANVIEN (HOTEN, NGAYSINH, SDT, DIACHI, TRANGTHAILAMVIEC)
    VALUES (P_HOTEN, P_NGAYSINH, P_SDT, P_DIACHI, NVL(P_TRANGTHAILAMVIEC, 1))
    RETURNING MANV INTO P_MANV_OUT;

    -- 4. Tao tai khoan dang nhap
    INSERT INTO TAIKHOAN (MANV, TENDANGNHAP, MATKHAU, TRANGTHAITK)
    VALUES (P_MANV_OUT, P_TENDANGNHAP, P_MATKHAU, 1);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- Procedure gan vai tro cho nhan vien
CREATE OR REPLACE PROCEDURE PROC_GAN_VAITRO_NHANVIEN (
    P_MANV IN NUMBER,
    P_MAVAITRO IN NUMBER
)
IS
BEGIN
    INSERT INTO NHANVIEN_VAITRO (MANV, MAVAITRO)
    SELECT P_MANV, P_MAVAITRO FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM NHANVIEN_VAITRO WHERE MANV = P_MANV AND MAVAITRO = P_MAVAITRO);
    COMMIT;
END;
/

-- Procedure cap nhat ma tran quyen chi tiet cho vai tro
CREATE OR REPLACE PROCEDURE PROC_CAPNHAT_QUYEN_CHI_TIET (
    P_MAVAITRO IN NUMBER,
    P_MACHUCNANG IN NUMBER,
    P_VIEW IN NUMBER,
    P_ADD IN NUMBER,
    P_EDIT IN NUMBER,
    P_DELETE IN NUMBER,
    P_DOWNLOAD IN NUMBER
)
IS
BEGIN
    MERGE INTO VAITRO_CHUCNANG vc
    USING (SELECT P_MAVAITRO as VT, P_MACHUCNANG as CN FROM DUAL) src
    ON (vc.MAVAITRO = src.VT AND vc.MACHUCNANG = src.CN)
    WHEN MATCHED THEN
        UPDATE SET CAN_VIEW = P_VIEW, CAN_ADD = P_ADD, CAN_EDIT = P_EDIT, 
                   CAN_DELETE = P_DELETE, CAN_DOWNLOAD = P_DOWNLOAD
    WHEN NOT MATCHED THEN
        INSERT (MAVAITRO, MACHUCNANG, CAN_VIEW, CAN_ADD, CAN_EDIT, CAN_DELETE, CAN_DOWNLOAD)
        VALUES (P_MAVAITRO, P_MACHUCNANG, P_VIEW, P_ADD, P_EDIT, P_DELETE, P_DOWNLOAD);
    COMMIT;
END;
/

-- Procedure sua nhan vien (Tach NHANVIEN va TAIKHOAN)
CREATE OR REPLACE PROCEDURE PROC_SUA_NHANVIEN (
    P_MANV IN NHANVIEN.MANV%type,
    P_HOTEN IN NHANVIEN.HOTEN%type,
    P_NGAYSINH IN NHANVIEN.NGAYSINH%type,
    P_SDT IN NHANVIEN.SDT%type,
    P_DIACHI IN NHANVIEN.DIACHI%type,
    P_TENDANGNHAP IN TAIKHOAN.TENDANGNHAP%type,
    P_MATKHAU IN TAIKHOAN.MATKHAU%type,
    P_TRANGTHAILAMVIEC IN NHANVIEN.TRANGTHAILAMVIEC%type
)
IS
BEGIN
    -- 1. Cap nhat ho so nhan su
    UPDATE NHANVIEN
    SET HOTEN = NVL(P_HOTEN, HOTEN),
        NGAYSINH = NVL(P_NGAYSINH, NGAYSINH),
        SDT = NVL(P_SDT, SDT),
        DIACHI = NVL(P_DIACHI, DIACHI),
        TRANGTHAILAMVIEC = NVL(P_TRANGTHAILAMVIEC, TRANGTHAILAMVIEC)
    WHERE MANV = P_MANV;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NV_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Nhan vien de cap nhat.');
    END IF;

    -- 2. Cap nhat tai khoan dang nhap
    UPDATE TAIKHOAN
    SET TENDANGNHAP = NVL(P_TENDANGNHAP, TENDANGNHAP),
        MATKHAU = NVL(P_MATKHAU, MATKHAU)
    WHERE MANV = P_MANV;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_NV_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NV_SUA_HE_THONG, 'Loi he thong khi cap nhat Nhan vien: ' || SQLERRM);
END;
/

-- Procedure doi mat khau tai khoan
CREATE OR REPLACE PROCEDURE PROC_DOI_MATKHAU_TAIKHOAN (
    P_MANV IN NHANVIEN.MANV%type,
    P_MATKHAU_MOI IN TAIKHOAN.MATKHAU%type
)
IS
BEGIN
    UPDATE TAIKHOAN
    SET MATKHAU = P_MATKHAU_MOI
    WHERE MANV = P_MANV;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NV_KHONG_CO_TAIKHOAN, 'Loi: Khong tim thay tai khoan de doi mat khau.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_NV_KHONG_CO_TAIKHOAN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NV_DOI_MATKHAU_HE_THONG, 'Loi he thong khi doi mat khau: ' || SQLERRM);
END;
/

-- Procedure xoa nhan vien
CREATE OR REPLACE PROCEDURE PROC_XOA_NHANVIEN (
    P_MANV IN NUMBER
)
IS
BEGIN
    UPDATE NHANVIEN
    SET TRANGTHAILAMVIEC = 0
    WHERE MANV = P_MANV;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NV_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay Nhan vien de xoa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_NV_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NV_XOA_HE_THONG, 'Loi he thong khi xoa Nhan vien: ' || SQLERRM);
END;
/
