-- Procedure Thêm nhà cung cấp
CREATE OR REPLACE PROCEDURE PROC_THEM_NHACUNGCAP(
    P_TENNCC IN NHACUNGCAP.TENNCC%TYPE,
    P_SDT IN NHACUNGCAP.SDT%TYPE,
    P_DIACHI IN NHACUNGCAP.DIACHI%TYPE,
    P_MANCC_OUT OUT NHACUNGCAP.MANCC%TYPE
)
IS
BEGIN
    INSERT INTO NHACUNGCAP (TENNCC, SDT, DIACHI)
    VALUES (P_TENNCC, P_SDT, P_DIACHI)
    RETURNING MANCC INTO P_MANCC_OUT;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NCC_THEM_HE_THONG, 'Loi he thong khi them Nha cung cap: ' || SQLERRM);
END;
/

-- Procedure Sửa nhà cung cấp
CREATE OR REPLACE PROCEDURE PROC_SUA_NHACUNGCAP(
    P_MANCC IN NHACUNGCAP.MANCC%TYPE,
    P_TENNCC IN NHACUNGCAP.TENNCC%TYPE,
    P_SDT IN NHACUNGCAP.SDT%TYPE,
    P_DIACHI IN NHACUNGCAP.DIACHI%TYPE
)
IS
BEGIN
    UPDATE NHACUNGCAP
    SET TENNCC = NVL(P_TENNCC, TENNCC),
        SDT = NVL(P_SDT, SDT),
        DIACHI = NVL(P_DIACHI, DIACHI)
    WHERE MANCC = P_MANCC;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NCC_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Nha cung cap de cap nhat.');
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_NCC_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NCC_CAPNHAT_HE_THONG, 'Loi he thong khi cap nhat Nha cung cap: ' || SQLERRM);
END;
/

-- Procedure Xóa Nhà Cung Cấp
CREATE OR REPLACE PROCEDURE PROC_XOA_NHACUNGCAP(
    P_MANCC IN NHACUNGCAP.MANCC%TYPE,
    P_MANX IN NHANVIEN.MANV%TYPE
) IS
    V_COUNT NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM PHIEUNHAPKHO WHERE MANCC = P_MANCC;

    IF V_COUNT > 0 THEN
        UPDATE NHACUNGCAP
        SET THOIDIEMXOA = SYSDATE,
            MANX = P_MANX
        WHERE MANCC = P_MANCC;
    ELSE
        DELETE FROM NHACUNGCAP WHERE MANCC = P_MANCC;
    END IF;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NCC_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay Nha cung cap de xoa.');
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_NCC_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NCC_XOA_HE_THONG, 'Loi he thong khi xoa Nha cung cap: ' || SQLERRM);
END;
/