-- ============================================================
-- Procedure thêm nguyên liệu (có hệ số quy đổi)
-- ============================================================
CREATE OR REPLACE PROCEDURE PROC_THEM_NGUYENLIEU (
    P_TENNL IN NGUYENLIEU.TENNL%type,
    P_XUATXU IN NGUYENLIEU.XUATXU%type,
    P_MUCTONANTOAN IN NGUYENLIEU.MUCTONANTOAN%type,
    P_MADVT IN DONVITINH.MADVT%type,
    P_MANL_OUT OUT NGUYENLIEU.MANL%type,
    P_HESOQUYDOI IN NGUYENLIEU.HESOQUYDOI%type DEFAULT 1
)
IS
BEGIN
    INSERT INTO NGUYENLIEU (TENNL, XUATXU, MUCTONANTOAN, MADVT, HESOQUYDOI, THOIDIEMXOA, MANX)
    VALUES (P_TENNL, P_XUATXU, P_MUCTONANTOAN, P_MADVT, NVL(P_HESOQUYDOI, 1), NULL, NULL)
    RETURNING MANL INTO P_MANL_OUT;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NL_THEM_MOI, 'Loi he thong khi tao moi Nguyen Lieu: ' || SQLERRM);
END;
/

-- ============================================================
-- Procedure sửa nguyên liệu (có hệ số quy đổi)
-- ============================================================
CREATE OR REPLACE PROCEDURE PROC_SUA_NGUYENLIEU (
    P_MANL IN NGUYENLIEU.MANL%type,
    P_TENNL IN NGUYENLIEU.TENNL%type,
    P_XUATXU IN NGUYENLIEU.XUATXU%type,
    P_MADVT IN NGUYENLIEU.MADVT%type,
    P_MUCTONANTOAN IN NGUYENLIEU.MUCTONANTOAN%type,
    P_HESOQUYDOI IN NGUYENLIEU.HESOQUYDOI%type DEFAULT NULL
)
IS
BEGIN
    UPDATE NGUYENLIEU
    SET TENNL         = NVL(P_TENNL, TENNL),
        XUATXU        = NVL(P_XUATXU, XUATXU),
        MADVT         = NVL(P_MADVT, MADVT),
        MUCTONANTOAN  = NVL(P_MUCTONANTOAN, MUCTONANTOAN),
        HESOQUYDOI    = NVL(P_HESOQUYDOI, HESOQUYDOI),
        PHIENBAN      = PHIENBAN + 1
    WHERE MANL = P_MANL;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NL_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Nguyen lieu de cap nhat.');
    END IF;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_NL_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NL_CAPNHAT_HE_THONG, 'Loi he thong khi cap nhat Nguyen Lieu: ' || SQLERRM);
END;
/

-- ============================================================
-- Procedure Thêm nguyên liệu kèm nhập kho lần đầu (atomic, có quy đổi)
-- P_SOLUONG  = số lượng theo đơn vị nhập (VD: 2 Thùng)
-- P_HESOQUYDOI = hệ số quy đổi (VD: 4320 → 2 Thùng = 8640 ml)
-- CTPHIEUNHAP.SOLUONG lưu số lượng đơn vị cơ bản (sau quy đổi)
-- ============================================================
CREATE OR REPLACE PROCEDURE PROC_THEM_NGUYENLIEU_VA_NHAP_KHO (
    P_TENNL        IN NGUYENLIEU.TENNL%TYPE,
    P_XUATXU      IN NGUYENLIEU.XUATXU%TYPE,
    P_MUCTONANTOAN IN NGUYENLIEU.MUCTONANTOAN%TYPE,
    P_MADVT        IN NGUYENLIEU.MADVT%TYPE,
    P_MANCC        IN PHIEUNHAPKHO.MANCC%TYPE,
    P_MANV         IN PHIEUNHAPKHO.MANV%TYPE,
    P_SOLUONG      IN CTPHIEUNHAP.SOLUONG%TYPE,
    P_DONGIA       IN CTPHIEUNHAP.DONGIA%TYPE,
    P_NGAYSANXUAT  IN CTPHIEUNHAP.NGAYSANXUAT%TYPE,
    P_HANSUDUNG    IN CTPHIEUNHAP.HANSUDUNG%TYPE,
    P_MANL_OUT     OUT NGUYENLIEU.MANL%TYPE,
    P_MAPN_OUT     OUT PHIEUNHAPKHO.MAPN%TYPE,
    P_HESOQUYDOI   IN NGUYENLIEU.HESOQUYDOI%TYPE DEFAULT 1
)
IS
    V_MANL            NGUYENLIEU.MANL%TYPE;
    V_MAPN            PHIEUNHAPKHO.MAPN%TYPE;
    V_SOLUONG_COSO    NUMBER(10,2);
BEGIN
    -- Quy đổi: số lượng cơ bản = số lượng nhập × hệ số
    V_SOLUONG_COSO := P_SOLUONG * NVL(P_HESOQUYDOI, 1);

    -- 1. Tạo bản ghi nguyên liệu (lưu HESOQUYDOI)
    INSERT INTO NGUYENLIEU (TENNL, XUATXU, MUCTONANTOAN, MADVT, HESOQUYDOI, THOIDIEMXOA, MANX)
    VALUES (P_TENNL, P_XUATXU, P_MUCTONANTOAN, P_MADVT, NVL(P_HESOQUYDOI, 1), NULL, NULL)
    RETURNING MANL INTO V_MANL;

    -- 2. Tạo phiếu nhập kho (gắn NCC)
    INSERT INTO PHIEUNHAPKHO (MANV, MANCC, NGAYNHAP)
    VALUES (P_MANV, P_MANCC, SYSDATE)
    RETURNING MAPN INTO V_MAPN;

    -- 3. Tạo chi tiết lô — lưu số lượng đơn vị CƠ BẢN (sau quy đổi)
    --    trigger TRG_GIAVONTRUNGBINH_SOLUONGTONTONG sẽ tự tính lại GIAVONTRUNGBINH và SOLUONGTONTONG
    INSERT INTO CTPHIEUNHAP (MAPN, MANL, SOLUONG, DONGIA, SOLUONGCONLAI, NGAYSANXUAT, HANSUDUNG)
    VALUES (V_MAPN, V_MANL, V_SOLUONG_COSO, P_DONGIA, V_SOLUONG_COSO, P_NGAYSANXUAT, P_HANSUDUNG);

    -- 4. Ghi log
    INSERT INTO HOATDONGNHANVIEN (MANV, NHOM, HANHDONG, ENTITY_ID)
    VALUES (P_MANV, 'KHO', 'Them moi NL va nhap kho lan dau (MANL: ' || V_MANL || ')', V_MANL);

    P_MANL_OUT := V_MANL;
    P_MAPN_OUT := V_MAPN;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NL_THEM_MOI,
            'Loi khi them moi nguyen lieu va nhap kho lan dau: ' || SQLERRM);
END;
/

-- ============================================================
-- Procedure Xóa nguyên liệu (giữ nguyên, không thay đổi)
-- ============================================================
CREATE OR REPLACE PROCEDURE PROC_XOA_NGUYENLIEU(
    P_MANL IN NGUYENLIEU.MANL%type,
    P_MANX IN NHANVIEN.MANV%type
)
IS
    V_LST_COUNT NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO V_LST_COUNT FROM CTPHIEUNHAP WHERE MANL = P_MANL;

    IF V_LST_COUNT > 0 THEN
        UPDATE NGUYENLIEU
        SET THOIDIEMXOA = SYSDATE,
            MANX = P_MANX,
            PHIENBAN = PHIENBAN + 1
        WHERE MANL = P_MANL;
    ELSE
        DELETE FROM NGUYENLIEU WHERE MANL = P_MANL;
    END IF;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NL_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay Nguyen lieu de xoa.');
    END IF;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_NL_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NL_XOA_HE_THONG, 'Loi he thong khi xoa Nguyen Lieu: ' || SQLERRM);
END;
/
