-- ==============================================================
-- PROCEDURE CUD (Create, Update, Delete) - MODULE SẢN PHẨM
-- Gồm: DANH MỤC SẢN PHẨM (DANHMUCSP), SẢN PHẨM (SANPHAM)
-- Tác giả: Antigravity
-- ==============================================================

-- --------------------------------------------------------------
-- 1. CUD DANH MỤC SẢN PHẨM
-- --------------------------------------------------------------

CREATE OR REPLACE PROCEDURE PROC_THEM_DANHMUCSP(
    P_TENDM IN NVARCHAR2,
    P_MADM_OUT OUT NUMBER
)
IS
BEGIN
    INSERT INTO DANHMUCSP (TENDM)
    VALUES (P_TENDM)
    RETURNING MADM INTO P_MADM_OUT;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20641, 'Lỗi hệ thống khi thêm Danh Mục Sản Phẩm: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_CAPNHAT_DANHMUCSP(
    P_MADM IN NUMBER,
    P_TENDM IN NVARCHAR2
)
IS
BEGIN
    UPDATE DANHMUCSP
    SET TENDM = NVL(P_TENDM, TENDM)
    WHERE MADM = P_MADM;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20642, 'Lỗi: Không tìm thấy Danh Mục Sản Phẩm để cập nhật.');
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = -20642 THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(-20643, 'Lỗi hệ thống khi cập nhật Danh Mục Sản Phẩm: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_XOA_DANHMUCSP(
    P_MADM IN NUMBER,
    P_MANX IN NUMBER
)
IS
BEGIN
    UPDATE DANHMUCSP
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANX
    WHERE MADM = P_MADM;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20644, 'Lỗi: Không tìm thấy Danh Mục Sản Phẩm để xóa.');
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = -20644 THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(-20645, 'Lỗi hệ thống khi xóa Danh Mục Sản Phẩm: ' || SQLERRM);
END;
/

-- --------------------------------------------------------------
-- 2. CUD SẢN PHẨM
-- --------------------------------------------------------------

CREATE OR REPLACE PROCEDURE PROC_THEM_SANPHAM(
    P_MADM IN NUMBER,
    P_TENSP IN NVARCHAR2,
    P_GIACOBAN IN NUMBER,
    P_HINHANH IN VARCHAR2,
    P_CHOPHEPTUYCHINH IN NUMBER,
    P_THOIGIANBAOQUAN IN NUMBER,
    P_THOIGIANCHUANBI IN NUMBER,
    P_MASP_OUT OUT NUMBER
)
IS
BEGIN
    INSERT INTO SANPHAM (MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, THOIGIANCHUANBI)
    VALUES (P_MADM, P_TENSP, P_GIACOBAN, P_HINHANH, P_CHOPHEPTUYCHINH, P_THOIGIANBAOQUAN, P_THOIGIANCHUANBI)
    RETURNING MASP INTO P_MASP_OUT;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20646, 'Lỗi hệ thống khi thêm Sản Phẩm: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_CAPNHAT_SANPHAM(
    P_MASP IN NUMBER,
    P_MADM IN NUMBER,
    P_TENSP IN NVARCHAR2,
    P_GIACOBAN IN NUMBER,
    P_HINHANH IN VARCHAR2,
    P_CHOPHEPTUYCHINH IN NUMBER,
    P_THOIGIANBAOQUAN IN NUMBER,
    P_THOIGIANCHUANBI IN NUMBER
)
IS
BEGIN
    UPDATE SANPHAM
    SET MADM = NVL(P_MADM, MADM),
        TENSP = NVL(P_TENSP, TENSP),
        GIACOBAN = NVL(P_GIACOBAN, GIACOBAN),
        HINHANH = NVL(P_HINHANH, HINHANH),
        CHOPHEPTUYCHINH = NVL(P_CHOPHEPTUYCHINH, CHOPHEPTUYCHINH),
        THOIGIANBAOQUAN = NVL(P_THOIGIANBAOQUAN, THOIGIANBAOQUAN),
        THOIGIANCHUANBI = NVL(P_THOIGIANCHUANBI, THOIGIANCHUANBI),
        PHIENBAN = PHIENBAN + 1
    WHERE MASP = P_MASP;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20647, 'Lỗi: Không tìm thấy Sản Phẩm để cập nhật.');
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = -20647 THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(-20648, 'Lỗi hệ thống khi cập nhật Sản Phẩm: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_XOA_SANPHAM(
    P_MASP IN NUMBER,
    P_MANX IN NUMBER
)
IS
    V_ORDER_COUNT NUMBER := 0;
BEGIN
    -- Kiểm tra nếu Bánh đã từng được đặt thì mới XÓA MỀM
    SELECT COUNT(*) INTO V_ORDER_COUNT FROM CTDONHANG WHERE MASP = P_MASP;

    IF V_ORDER_COUNT > 0 THEN
        UPDATE SANPHAM 
        SET THOIDIEMXOA = SYSDATE, 
            MANX = P_MANX,
            PHIENBAN = PHIENBAN + 1
        WHERE MASP = P_MASP;
    ELSE
        -- Nếu chưa từng phát sinh doanh số, cho phép XỎA CỨNG
        DELETE FROM SANPHAM WHERE MASP = P_MASP;
    END IF;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20649, 'Lỗi: Không tìm thấy Sản Phẩm để xóa.');
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = -20649 THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(-20650, 'Lỗi hệ thống khi xóa Sản Phẩm: ' || SQLERRM);
END;
/
