-- Procedure them hang thanh vien
CREATE OR REPLACE PROCEDURE PROC_THEM_HANGTHANHVIEN (
    P_TENHANG IN NVARCHAR2,
    P_DIEMTOITHIEU IN NUMBER,
    P_PHANTRAMGIAMGIA IN NUMBER,
    P_MAHANG_OUT OUT NUMBER
)
IS
BEGIN
    INSERT INTO HANGTHANHVIEN (TENHANG, DIEMTOITHIEU, PHANTRAMGIAMGIA, THOIDIEMXOA, MANX)
    VALUES (P_TENHANG, NVL(P_DIEMTOITHIEU, 0), NVL(P_PHANTRAMGIAMGIA, 0), NULL, NULL)
    RETURNING MAHANG INTO P_MAHANG_OUT;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HANGTV_THEM_HE_THONG, 'Loi he thong khi them Hang Thanh Vien: ' || SQLERRM);
END;
/

-- Procedure sua hang thanh vien
CREATE OR REPLACE PROCEDURE PROC_SUA_HANGTHANHVIEN (
    P_MAHANG IN NUMBER,
    P_TENHANG IN NVARCHAR2,
    P_DIEMTOITHIEU IN NUMBER,
    P_PHANTRAMGIAMGIA IN NUMBER
)
IS
BEGIN
    UPDATE HANGTHANHVIEN
    SET TENHANG = NVL(P_TENHANG, TENHANG),
        DIEMTOITHIEU = NVL(P_DIEMTOITHIEU, DIEMTOITHIEU),
        PHANTRAMGIAMGIA = NVL(P_PHANTRAMGIAMGIA, PHANTRAMGIAMGIA)
    WHERE MAHANG = P_MAHANG;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HANGTV_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Hang Thanh Vien de cap nhat.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_HANGTV_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HANGTV_CAPNHAT_HE_THONG, 'Loi he thong khi cap nhat Hang Thanh Vien: ' || SQLERRM);
END;
/

-- Procedure xoa hang thanh vien
CREATE OR REPLACE PROCEDURE PROC_XOA_HANGTHANHVIEN (
    P_MAHANG IN NUMBER,
    P_MANV_XOA IN NUMBER
)
IS
BEGIN
    UPDATE HANGTHANHVIEN
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANV_XOA
    WHERE MAHANG = P_MAHANG;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HANGTV_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay Hang Thanh Vien de xoa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_HANGTV_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HANGTV_XOA_HE_THONG, 'Loi he thong khi xoa Hang Thanh Vien: ' || SQLERRM);
END;
/

-- Procedure them khach hang
CREATE OR REPLACE PROCEDURE PROC_THEM_KHACHHANG (
    P_HOTEN IN NVARCHAR2,
    P_SDT IN VARCHAR2,
    P_DIACHI IN NVARCHAR2,
    P_DIEMTICHLUY IN NUMBER DEFAULT 0,
    P_MAHANG IN NUMBER DEFAULT NULL,
    P_MAKH_OUT OUT NUMBER
)
IS
BEGIN
    INSERT INTO KHACHHANG (HOTEN, SDT, DIACHI, NGAYDANGKY, DIEMTICHLUY, MAHANG, THOIDIEMXOA, MANX)
    VALUES (P_HOTEN, P_SDT, P_DIACHI, SYSDATE, P_DIEMTICHLUY, P_MAHANG, NULL, NULL)
    RETURNING MAKH INTO P_MAKH_OUT;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KH_THEM_HE_THONG, 'Loi he thong khi them Khach Hang: ' || SQLERRM);
END;
/

-- Procedure sua khach hang
CREATE OR REPLACE PROCEDURE PROC_SUA_KHACHHANG (
    P_MAKH IN NUMBER,
    P_HOTEN IN NVARCHAR2,
    P_SDT IN VARCHAR2,
    P_DIACHI IN NVARCHAR2,
    P_DIEMTICHLUY IN NUMBER,
    P_MAHANG IN NUMBER
)
IS
BEGIN
    UPDATE KHACHHANG
    SET HOTEN = NVL(P_HOTEN, HOTEN),
        SDT = NVL(P_SDT, SDT),
        DIACHI = NVL(P_DIACHI, DIACHI),
        DIEMTICHLUY = NVL(P_DIEMTICHLUY, DIEMTICHLUY),
        MAHANG = NVL(P_MAHANG, MAHANG)
    WHERE MAKH = P_MAKH;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KH_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Khach Hang de cap nhat.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_KH_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KH_CAPNHAT_HE_THONG, 'Loi he thong khi cap nhat Khach Hang: ' || SQLERRM);
END;
/

-- Procedure xoa khach hang
CREATE OR REPLACE PROCEDURE PROC_XOA_KHACHHANG (
    P_MAKH IN NUMBER,
    P_MANV_XOA IN NUMBER
)
IS
BEGIN
    UPDATE KHACHHANG
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANV_XOA
    WHERE MAKH = P_MAKH;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KH_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay Khach Hang de xoa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_KH_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KH_XOA_HE_THONG, 'Loi he thong khi xoa Khach Hang: ' || SQLERRM);
END;
/
