-- Procedure Thêm danh mục sản phẩm
CREATE OR REPLACE PROCEDURE PROC_THEM_DANHMUCSP (
    P_TENDM IN NVARCHAR2,
    P_MADM_OUT OUT NUMBER
)
IS
BEGIN
    INSERT INTO DANHMUCSP (TENDM)
    VALUES (P_TENDM)
    RETURNING MADM INTO P_MADM_OUT;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DM_THEM_HE_THONG, 'Lỗi hệ thống khi thêm Danh Mục Sản Phẩm: ' || SQLERRM);
END;
/

-- Procedure Sửa danh mục sản phẩm
CREATE OR REPLACE PROCEDURE PROC_SUA_DANHMUCSP(
    P_MADM IN NUMBER,
    P_TENDM IN NVARCHAR2
)
IS
BEGIN
    UPDATE DANHMUCSP
    SET TENDM = NVL(P_TENDM, TENDM)
    WHERE MADM = P_MADM;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DM_KHONG_TON_TAI_CN, 'Lỗi: Không tìm thấy Danh Mục Sản Phẩm để cập nhật.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_DM_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DM_CAPNHAT_HE_THONG, 'Lỗi hệ thống khi cập nhật Danh Mục Sản Phẩm: ' || SQLERRM);
END;
/

-- Procedure Xóa danh mục sản phẩm
CREATE OR REPLACE PROCEDURE PROC_XOA_DANHMUCSP(
    P_MADM IN NUMBER,
    P_MANX IN NUMBER
)
IS
BEGIN
    UPDATE DANHMUCSP
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANX
    WHERE MADM = P_MADM;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DM_KHONG_TON_TAI_XOA, 'Lỗi: Không tìm thấy Danh Mục Sản Phẩm để xóa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_DM_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DM_XOA_HE_THONG, 'Lỗi hệ thống khi xóa Danh Mục Sản Phẩm: ' || SQLERRM);
END;
/

-- Procedure Thêm sản phẩm
CREATE OR REPLACE PROCEDURE PROC_THEM_SANPHAM(
    P_MADM IN NUMBER,
    P_TENSP IN NVARCHAR2,
    P_GIACOBAN IN NUMBER,
    P_HINHANH IN VARCHAR2,
    P_CHOPHEPTUYCHINH IN NUMBER,
    P_THOIGIANBAOQUAN IN NUMBER,
    P_THOIGIANCHUANBI IN NUMBER,
    P_MASP_OUT OUT NUMBER
)
IS
BEGIN
    INSERT INTO SANPHAM (MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, THOIGIANCHUANBI)
    VALUES (P_MADM, P_TENSP, P_GIACOBAN, P_HINHANH, P_CHOPHEPTUYCHINH, P_THOIGIANBAOQUAN, P_THOIGIANCHUANBI)
    RETURNING MASP INTO P_MASP_OUT;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SANPHAM_THEM_HE_THONG, 'Lỗi hệ thống khi thêm Sản Phẩm: ' || SQLERRM);
END;
/

-- Procedure Sửa sản phẩm
CREATE OR REPLACE PROCEDURE PROC_SUA_SANPHAM(
    P_MASP IN NUMBER,
    P_MADM IN NUMBER,
    P_TENSP IN NVARCHAR2,
    P_GIACOBAN IN NUMBER,
    P_HINHANH IN VARCHAR2,
    P_CHOPHEPTUYCHINH IN NUMBER,
    P_THOIGIANBAOQUAN IN NUMBER,
    P_THOIGIANCHUANBI IN NUMBER
)
IS
BEGIN
    UPDATE SANPHAM
    SET MADM = NVL(P_MADM, MADM),
        TENSP = NVL(P_TENSP, TENSP),
        GIACOBAN = NVL(P_GIACOBAN, GIACOBAN),
        HINHANH = NVL(P_HINHANH, HINHANH),
        CHOPHEPTUYCHINH = NVL(P_CHOPHEPTUYCHINH, CHOPHEPTUYCHINH),
        THOIGIANBAOQUAN = NVL(P_THOIGIANBAOQUAN, THOIGIANBAOQUAN),
        THOIGIANCHUANBI = NVL(P_THOIGIANCHUANBI, THOIGIANCHUANBI),
        PHIENBAN = PHIENBAN + 1
    WHERE MASP = P_MASP;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SANPHAM_KHONG_TON_TAI_CN, 'Lỗi: Không tìm thấy Sản Phẩm để cập nhật.');
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_SANPHAM_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SANPHAM_CAPNHAT_HE_THONG, 'Lỗi hệ thống khi cập nhật Sản Phẩm: ' || SQLERRM);
END;
/

-- Procedure Xóa sản phẩm
CREATE OR REPLACE PROCEDURE PROC_XOA_SANPHAM(
    P_MASP IN NUMBER,
    P_MANX IN NUMBER
)
IS
    V_ORDER_COUNT NUMBER := 0;
BEGIN
    -- Kiểm tra nếu Bánh đã từng được đặt thì mới XÓA MỀM
    SELECT COUNT(*) INTO V_ORDER_COUNT FROM CTDONHANG WHERE MASP = P_MASP;

    IF V_ORDER_COUNT > 0 THEN
        UPDATE SANPHAM 
        SET THOIDIEMXOA = SYSDATE, 
            MANX = P_MANX,
            PHIENBAN = PHIENBAN + 1
        WHERE MASP = P_MASP;
    ELSE
        -- Nếu chưa từng phát sinh doanh số, cho phép XỎA CỨNG
        DELETE FROM SANPHAM WHERE MASP = P_MASP;
    END IF;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SANPHAM_KHONG_TON_TAI_XOA, 'Lỗi: Không tìm thấy Sản Phẩm để xóa.');
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_SANPHAM_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SANPHAM_XOA_HE_THONG, 'Lỗi hệ thống khi xóa Sản Phẩm: ' || SQLERRM);
END;
/

-- ==============================================================
-- PROCEDURE CUD - MODULE THUOC TINH SAN PHAM
-- Gom: KICH CO BANH, COT BANH, NHAN BANH, KIEU TRANG TRI
-- ==============================================================

-- --------------------------------------------------------------
-- 1. KICH CO BANH
-- --------------------------------------------------------------
CREATE OR REPLACE PROCEDURE PROC_THEM_KICHCOBANH(
    P_TENKC IN NVARCHAR2,
    P_PHUPHI IN NUMBER,
    P_MAKC_OUT OUT NUMBER
)
IS
BEGIN
    INSERT INTO KICHCOBANH (TENKC, PHUPHI)
    VALUES (P_TENKC, NVL(P_PHUPHI, 0))
    RETURNING MAKC INTO P_MAKC_OUT;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KICHCO_THEM_HE_THONG, 'Loi he thong khi them Kich co banh: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_CAPNHAT_KICHCOBANH(
    P_MAKC IN NUMBER,
    P_TENKC IN NVARCHAR2,
    P_PHUPHI IN NUMBER
)
IS
BEGIN
    UPDATE KICHCOBANH
    SET TENKC = NVL(P_TENKC, TENKC),
        PHUPHI = NVL(P_PHUPHI, PHUPHI)
    WHERE MAKC = P_MAKC;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KICHCO_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Kich co banh de cap nhat.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_KICHCO_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KICHCO_CAPNHAT_HE_THONG, 'Loi he thong khi cap nhat Kich co banh: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_XOA_KICHCOBANH(
    P_MAKC IN NUMBER,
    P_MANX IN NUMBER
)
IS
BEGIN
    UPDATE KICHCOBANH
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANX
    WHERE MAKC = P_MAKC;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KICHCO_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay Kich co banh de xoa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_KICHCO_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KICHCO_XOA_HE_THONG, 'Loi he thong khi xoa Kich co banh: ' || SQLERRM);
END;
/

-- --------------------------------------------------------------
-- 2. COT BANH
-- --------------------------------------------------------------
CREATE OR REPLACE PROCEDURE PROC_THEM_COTBANH(
    P_TENCOT IN NVARCHAR2,
    P_PHUPHI IN NUMBER,
    P_MACOT_OUT OUT NUMBER
)
IS
BEGIN
    INSERT INTO COTBANH (TENCOT, PHUPHI)
    VALUES (P_TENCOT, NVL(P_PHUPHI, 0))
    RETURNING MACOT INTO P_MACOT_OUT;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_COTBANH_THEM_HE_THONG, 'Loi he thong khi them Cot banh: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_CAPNHAT_COTBANH(
    P_MACOT IN NUMBER,
    P_TENCOT IN NVARCHAR2,
    P_PHUPHI IN NUMBER
)
IS
BEGIN
    UPDATE COTBANH
    SET TENCOT = NVL(P_TENCOT, TENCOT),
        PHUPHI = NVL(P_PHUPHI, PHUPHI)
    WHERE MACOT = P_MACOT;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_COTBANH_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Cot banh de cap nhat.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_COTBANH_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_COTBANH_CAPNHAT_HE_THONG, 'Loi he thong khi cap nhat Cot banh: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_XOA_COTBANH(
    P_MACOT IN NUMBER,
    P_MANX IN NUMBER
)
IS
BEGIN
    UPDATE COTBANH
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANX
    WHERE MACOT = P_MACOT;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_COTBANH_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay Cot banh de xoa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_COTBANH_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_COTBANH_XOA_HE_THONG, 'Loi he thong khi xoa Cot banh: ' || SQLERRM);
END;
/

-- --------------------------------------------------------------
-- 3. NHAN BANH
-- --------------------------------------------------------------
CREATE OR REPLACE PROCEDURE PROC_THEM_NHANBANH(
    P_TENNHAN IN NVARCHAR2,
    P_PHUPHI IN NUMBER,
    P_MANHAN_OUT OUT NUMBER
)
IS
BEGIN
    INSERT INTO NHANBANH (TENNHAN, PHUPHI)
    VALUES (P_TENNHAN, NVL(P_PHUPHI, 0))
    RETURNING MANHAN INTO P_MANHAN_OUT;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NHANBANH_THEM_HE_THONG, 'Loi he thong khi them Nhan banh: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_CAPNHAT_NHANBANH(
    P_MANHAN IN NUMBER,
    P_TENNHAN IN NVARCHAR2,
    P_PHUPHI IN NUMBER
)
IS
BEGIN
    UPDATE NHANBANH
    SET TENNHAN = NVL(P_TENNHAN, TENNHAN),
        PHUPHI = NVL(P_PHUPHI, PHUPHI)
    WHERE MANHAN = P_MANHAN;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NHANBANH_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Nhan banh de cap nhat.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_NHANBANH_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NHANBANH_CAPNHAT_HE_THONG, 'Loi he thong khi cap nhat Nhan banh: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_XOA_NHANBANH(
    P_MANHAN IN NUMBER,
    P_MANX IN NUMBER
)
IS
BEGIN
    UPDATE NHANBANH
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANX
    WHERE MANHAN = P_MANHAN;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NHANBANH_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay Nhan banh de xoa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_NHANBANH_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NHANBANH_XOA_HE_THONG, 'Loi he thong khi xoa Nhan banh: ' || SQLERRM);
END;
/

-- --------------------------------------------------------------
-- 4. KIEU TRANG TRI
-- --------------------------------------------------------------
CREATE OR REPLACE PROCEDURE PROC_THEM_KIEUTRANGTRI(
    P_TENTRANGTRI IN NVARCHAR2,
    P_PHUPHI IN NUMBER,
    P_MATRANGTRI_OUT OUT NUMBER
)
IS
BEGIN
    INSERT INTO KIEUTRANGTRI (TENTRANGTRI, PHUPHI)
    VALUES (P_TENTRANGTRI, NVL(P_PHUPHI, 0))
    RETURNING MATRANGTRI INTO P_MATRANGTRI_OUT;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_TRANGTRI_THEM_HE_THONG, 'Loi he thong khi them Kieu trang tri: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_CAPNHAT_KIEUTRANGTRI(
    P_MATRANGTRI IN NUMBER,
    P_TENTRANGTRI IN NVARCHAR2,
    P_PHUPHI IN NUMBER
)
IS
BEGIN
    UPDATE KIEUTRANGTRI
    SET TENTRANGTRI = NVL(P_TENTRANGTRI, TENTRANGTRI),
        PHUPHI = NVL(P_PHUPHI, PHUPHI)
    WHERE MATRANGTRI = P_MATRANGTRI;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_TRANGTRI_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Kieu trang tri de cap nhat.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_TRANGTRI_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_TRANGTRI_CAPNHAT_HE_THONG, 'Loi he thong khi cap nhat Kieu trang tri: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE PROC_XOA_KIEUTRANGTRI(
    P_MATRANGTRI IN NUMBER,
    P_MANX IN NUMBER
)
IS
BEGIN
    UPDATE KIEUTRANGTRI
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANX
    WHERE MATRANGTRI = P_MATRANGTRI;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_TRANGTRI_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay Kieu trang tri de xoa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_TRANGTRI_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_TRANGTRI_XOA_HE_THONG, 'Loi he thong khi xoa Kieu trang tri: ' || SQLERRM);
END;
/
