CREATE OR REPLACE PROCEDURE PROC_TAODONHANG(
    P_NGAYGIONHANBANH IN DONDATHANG.NGAYGIONHANBANH%TYPE,
    P_MAKH          IN DONDATHANG.MAKH%TYPE DEFAULT NULL,
    P_MANV_LAP      IN DONDATHANG.MANV_LAP%TYPE,
    P_MATRANGTHAI   IN DONDATHANG.MATRANGTHAI%TYPE,
    P_TIENDACOC     IN DONDATHANG.TIENDACOC%TYPE DEFAULT 0,
    P_HINHTHUCNHAN  IN DONDATHANG.HINHTHUCNHAN%TYPE DEFAULT 1,
    P_DIACHIGIAO    IN DONDATHANG.DIACHIGIAO%TYPE DEFAULT NULL,
    P_JSONCHITIET   IN CLOB,
    P_MADON_OUT     OUT DONDATHANG.MADON%TYPE
)
IS
    V_TONGTIEN CTDONHANG.DONGIA%type := 0;
BEGIN
    -- 1. Tính toán tổng tiền trước để tránh vi phạm Check Constraint (TONGTIEN >= TIENDACOC)
    SELECT SUM(J.SOLUONG * J.DONGIA) INTO V_TONGTIEN
    FROM JSON_TABLE(P_JSONCHITIET, '$[*]'
        COLUMNS (
            SOLUONG NUMBER PATH '$.soLuong',
            DONGIA NUMBER PATH '$.donGia'
        )
    ) J;

    -- 2. Insert Đơn Hàng Gốc (Đã kèm TONGTIENHDBAN)
    INSERT INTO DONDATHANG (NGAYGIONHANBANH, MAKH, MANV_LAP, MATRANGTHAI, TONGTIENHDBAN, TIENDACOC, HINHTHUCNHAN, DIACHIGIAO)
    VALUES (P_NGAYGIONHANBANH, P_MAKH, P_MANV_LAP, P_MATRANGTHAI, NVL(V_TONGTIEN, 0), NVL(P_TIENDACOC, 0), P_HINHTHUCNHAN, P_DIACHIGIAO)

    -- 3. Đẩy chi tiết bánh bán sẵn
    INSERT INTO CTDONHANG (MADON, MASP, SOLUONG, DONGIA)
    SELECT P_MADON_OUT, J.MASP, J.SOLUONG, J.DONGIA
    FROM JSON_TABLE(P_JSONCHITIET, '$[*]'
        COLUMNS (
            MASP NUMBER PATH '$.maSP',
            SOLUONG NUMBER PATH '$.soLuong',
            DONGIA NUMBER PATH '$.donGia',
            IS_CUSTOM VARCHAR2(10) PATH '$.isCustom'
        )
    ) J
    WHERE LOWER(NVL(J.IS_CUSTOM, 'false')) = 'false'; 

    -- 4. Đẩy chi tiết bánh Tùy Chỉnh
    INSERT INTO CTDONTUYCHINH (MADON, MASP, SOLUONG, DONGIA, LOICHUCTRENBANH, GHICHUTHOBANH)
    SELECT P_MADON_OUT, J.MASP, J.SOLUONG, J.DONGIA, J.GHICHU, J.PHUKIEN
    FROM JSON_TABLE(P_JSONCHITIET, '$[*]'
        COLUMNS (
            MASP NUMBER PATH '$.maSP',
            SOLUONG NUMBER PATH '$.soLuong',
            DONGIA NUMBER PATH '$.donGia',
            IS_CUSTOM VARCHAR2(10) PATH '$.isCustom',
            GHICHU NVARCHAR2(200) PATH '$.ghiChu',
            PHUKIEN NVARCHAR2(500) PATH '$.phuKien'
        )
    ) J
    WHERE LOWER(J.IS_CUSTOM) = 'true';

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HUY_TAO_DON, 'Lỗi hệ thống khi Tạo Đơn Hàng: ' || SQLERRM);
END;
/
