-- Procedure thêm phương thức thanh toán
CREATE OR REPLACE PROCEDURE PROC_THEM_PHUONGTHUCTT (
    P_TENPTTT IN PHUONGTHUCTT.TENPTTT%type,
    P_MAPTTT_OUT OUT PHUONGTHUCTT.MAPTTT%type
)
IS
BEGIN
    INSERT INTO PHUONGTHUCTT (TENPTTT, THOIDIEMXOA, MANX)
    VALUES (P_TENPTTT, NULL, NULL)
    RETURNING MAPTTT INTO P_MAPTTT_OUT;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_PTTT_THEM_HE_THONG, 'Loi he thong khi them Phuong thuc thanh toan: ' || SQLERRM);
END;
/

-- Procedure sửa phương thức thanh toán
CREATE OR REPLACE PROCEDURE PROC_SUA_PHUONGTHUCTT (
    P_MAPTTT IN PHUONGTHUCTT.MAPTTT%type,
    P_TENPTTT IN PHUONGTHUCTT.TENPTTT%type
)
IS
BEGIN
    UPDATE PHUONGTHUCTT
    SET TENPTTT = NVL(P_TENPTTT, TENPTTT)
    WHERE MAPTTT = P_MAPTTT;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_PTTT_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Phuong thuc thanh toan de cap nhat.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_PTTT_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_PTTT_CAPNHAT_HE_THONG, 'Loi he thong khi cap nhat Phuong thuc thanh toan: ' || SQLERRM);
END;
/

-- Procedure xóa phương thức thanh toán
CREATE OR REPLACE PROCEDURE PROC_XOA_PHUONGTHUCTT (
    P_MAPTTT IN PHUONGTHUCTT.MAPTTT%type,
    P_MANX IN NHANVIEN.MANV%type
)
IS
BEGIN
    UPDATE PHUONGTHUCTT
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANX
    WHERE MAPTTT = P_MAPTTT;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_PTTT_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay Phuong thuc thanh toan de xoa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_PTTT_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_PTTT_XOA_HE_THONG, 'Loi he thong khi xoa Phuong thuc thanh toan: ' || SQLERRM);
END;
/

-- Procedure thêm loại thu chi
CREATE OR REPLACE PROCEDURE PROC_THEM_LOAITHUCHI (
    P_TENLOAITHUCHI IN LOAITHUCHI.TENLOAITHUCHI%type,
    P_PHANLOAI IN LOAITHUCHI.PHANLOAI%type,
    P_MALOAITHUCHI_OUT OUT LOAITHUCHI.MALOAITHUCHI%type
)
IS
BEGIN
    INSERT INTO LOAITHUCHI (TENLOAITHUCHI, PHANLOAI, THOIDIEMXOA, MANX)
    VALUES (P_TENLOAITHUCHI, P_PHANLOAI, NULL, NULL)
    RETURNING MALOAITHUCHI INTO P_MALOAITHUCHI_OUT;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_LOAITHUCHI_THEM_HE_THONG, 'Loi he thong khi them Loai thu chi: ' || SQLERRM);
END;
/

-- Procedure sửa loại thu chi
CREATE OR REPLACE PROCEDURE PROC_SUA_LOAITHUCHI (
    P_MALOAITHUCHI IN LOAITHUCHI.MALOAITHUCHI%type,
    P_TENLOAITHUCHI IN LOAITHUCHI.TENLOAITHUCHI%type,
    P_PHANLOAI IN LOAITHUCHI.PHANLOAI%type
)
IS
BEGIN
    UPDATE LOAITHUCHI
    SET TENLOAITHUCHI = NVL(P_TENLOAITHUCHI, TENLOAITHUCHI),
        PHANLOAI = NVL(P_PHANLOAI, PHANLOAI)
    WHERE MALOAITHUCHI = P_MALOAITHUCHI;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_LOAITHUCHI_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Loai thu chi de cap nhat.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_LOAITHUCHI_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_LOAITHUCHI_CAPNHAT_HE_THONG, 'Loi he thong khi cap nhat Loai thu chi: ' || SQLERRM);
END;
/

-- Procedure xóa loại thu chi
CREATE OR REPLACE PROCEDURE PROC_XOA_LOAITHUCHI(
    P_MALOAITHUCHI IN LOAITHUCHI.MALOAITHUCHI%type,
    P_MANX IN NHANVIEN.MANV%type
)
IS
BEGIN
    UPDATE LOAITHUCHI
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANX
    WHERE MALOAITHUCHI = P_MALOAITHUCHI;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_LOAITHUCHI_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay Loai thu chi de xoa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_LOAITHUCHI_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_LOAITHUCHI_XOA_HE_THONG, 'Loi he thong khi xoa Loai thu chi: ' || SQLERRM);
END;
/

-- Procedure tạo phiếu thu chi
CREATE OR REPLACE PROCEDURE PROC_TAOPHIEUTHUCHI (
    P_MALOAITHUCHI IN PHIEUTHUCHI.MALOAITHUCHI%type,
    P_SOTIEN IN PHIEUTHUCHI.SOTIEN%type,
    P_MANV IN PHIEUTHUCHI.MANV%type,
    P_MAHD IN PHIEUTHUCHI.MAHD%type DEFAULT NULL,
    P_MAPN IN PHIEUTHUCHI.MAPN%type DEFAULT NULL,
    P_MACA IN PHIEUTHUCHI.MACA%type,
    P_GHICHU IN PHIEUTHUCHI.GHICHU%type DEFAULT NULL,
    P_MAPHIEUTC_OUT OUT PHIEUTHUCHI.MAPHIEUTC%type
)
IS
BEGIN
    INSERT INTO PHIEUTHUCHI (MALOAITHUCHI, SOTIEN, MANV, MAHD, MAPN, MACA, GHICHU)
    VALUES (P_MALOAITHUCHI, P_SOTIEN, P_MANV, P_MAHD, P_MAPN, P_MACA, P_GHICHU)
    RETURNING MAPHIEUTC INTO P_MAPHIEUTC_OUT;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_PHIEUTHUCHI_THEM_HE_THONG, 'Loi he thong khi tao Phieu thu chi: ' || SQLERRM);
END;
/

-- Procedure tạo hóa đơn
CREATE OR REPLACE PROCEDURE PROC_TAOHOADON (
    P_MADON IN HOADON.MADON%type,
    P_MACA IN HOADON.MACA%type,
    P_THUEVAT IN HOADON.THUEVAT%type,
    P_TIENHANGGOC IN HOADON.TIENHANGGOC%type,
    P_TONGTIENTHANHTOAN IN HOADON.TONGTIENTHANHTOAN%type,
    P_MAPTTT IN HOADON.MAPTTT%type,
    P_LOAIHD IN HOADON.LOAIHD%type,
    P_MAHD_OUT OUT HOADON.MAHD%type
)
IS
BEGIN
    INSERT INTO HOADON (MADON, MACA, THUEVAT, TIENHANGGOC, TONGTIENTHANHTOAN, MAPTTT, LOAIHD)
    VALUES (P_MADON, P_MACA, NVL(P_THUEVAT, 0), NVL(P_TIENHANGGOC, 0), NVL(P_TONGTIENTHANHTOAN, 0), P_MAPTTT, P_LOAIHD)
    RETURNING MAHD INTO P_MAHD_OUT;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HOADON_THEM_HE_THONG, 'Loi he thong khi tao Hoa don: ' || SQLERRM);
END;
/
