-- Procedure thêm vai trò
CREATE OR REPLACE PROCEDURE PROC_THEM_VAITRO (
    P_TENVAITRO IN VAITRO.TENVAITRO%type,
    P_MOTA IN VAITRO.MOTA%type DEFAULT NULL,
    P_MAVAITRO_OUT OUT VAITRO.MAVAITRO%type
)
IS
BEGIN
    INSERT INTO VAITRO (TENVAITRO, MOTA, THOIDIEMXOA, MANX)
    VALUES (P_TENVAITRO, P_MOTA, NULL, NULL)
    RETURNING MAVAITRO INTO P_MAVAITRO_OUT;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_VAITRO_THEM_HE_THONG, 'Lỗi hệ thống khi thêm Vai trò: ' || SQLERRM);
END;
/

-- Procedure sửa vai trò
CREATE OR REPLACE PROCEDURE PROC_SUA_VAITRO (
    P_MAVAITRO IN VAITRO.MAVAITRO%type,
    P_TENVAITRO IN VAITRO.TENVAITRO%type,
    P_MOTA IN VAITRO.MOTA%type
)
IS
BEGIN
    UPDATE VAITRO
    SET TENVAITRO = NVL(P_TENVAITRO, TENVAITRO),
        MOTA = NVL(P_MOTA, MOTA)
    WHERE MAVAITRO = P_MAVAITRO;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_VAITRO_KHONG_TON_TAI_CN, 'Lỗi: Không tìm thấy Vai trò để cập nhật.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_VAITRO_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_VAITRO_CAPNHAT_HE_THONG, 'Lỗi hệ thống khi cập nhật Vai trò: ' || SQLERRM);
END;
/

-- Procedure xóa vai trò
CREATE OR REPLACE PROCEDURE PROC_XOA_VAITRO (
    P_MAVAITRO IN VAITRO.MAVAITRO%type,
    P_MANV_XOA IN NHANVIEN.MANV%type
)
IS
BEGIN
    UPDATE VAITRO
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANV_XOA
    WHERE MAVAITRO = P_MAVAITRO;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_VAITRO_KHONG_TON_TAI_XOA, 'Lỗi: Không tìm thấy Vai trò để xóa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_VAITRO_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_VAITRO_XOA_HE_THONG, 'Lỗi hệ thống khi xoá Vai trò: ' || SQLERRM);
END;
/

-- Procedure thêm nhân viên (Đã cập nhật cho N-N)
CREATE OR REPLACE PROCEDURE PROC_THEM_NHANVIEN (
    P_HOTEN IN NHANVIEN.HOTEN%type,
    P_NGAYSINH IN NHANVIEN.NGAYSINH%type,
    P_SDT IN NHANVIEN.SDT%type,
    P_TENDANGNHAP IN NHANVIEN.TENDANGNHAP%type,
    P_MATKHAU IN NHANVIEN.MATKHAU%type,
    P_TRANGTHAILAMVIEC IN NHANVIEN.TRANGTHAILAMVIEC%type,
    P_MANV_OUT OUT NHANVIEN.MANV%type
)
IS
    V_COUNT NUMBER;
BEGIN
    -- 1. Kiểm tra trùng SĐT
    SELECT COUNT(*) INTO V_COUNT FROM NHANVIEN WHERE SDT = P_SDT;
    IF V_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NV_SDT_TON_TAI, 'Lỗi: Số điện thoại này đã được sử dụng bởi nhân viên khác.');
    END IF;

    -- 2. Kiểm tra trùng Tên đăng nhập
    SELECT COUNT(*) INTO V_COUNT FROM NHANVIEN WHERE UPPER(TENDANGNHAP) = UPPER(P_TENDANGNHAP);
    IF V_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NV_TENDANGNHAP_TON_TAI, 'Lỗi: Tên đăng nhập này đã tồn tại trong hệ thống.');
    END IF;

    INSERT INTO NHANVIEN (HOTEN, NGAYSINH, SDT, TENDANGNHAP, MATKHAU, TRANGTHAILAMVIEC)
    VALUES (P_HOTEN, P_NGAYSINH, P_SDT, P_TENDANGNHAP, P_MATKHAU, NVL(P_TRANGTHAILAMVIEC, 1))
    RETURNING MANV INTO P_MANV_OUT;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- Procedure gán vai trò cho nhân viên
CREATE OR REPLACE PROCEDURE PROC_GAN_VAITRO_NHANVIEN (
    P_MANV IN NUMBER,
    P_MAVAITRO IN NUMBER
)
IS
BEGIN
    INSERT INTO NHANVIEN_VAITRO (MANV, MAVAITRO)
    SELECT P_MANV, P_MAVAITRO FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM NHANVIEN_VAITRO WHERE MANV = P_MANV AND MAVAITRO = P_MAVAITRO);
    COMMIT;
END;
/

-- Procedure cập nhật ma trận quyền chi tiết cho vai trò
CREATE OR REPLACE PROCEDURE PROC_CAPNHAT_QUYEN_CHI_TIET (
    P_MAVAITRO IN NUMBER,
    P_MACHUCNANG IN NUMBER,
    P_VIEW IN NUMBER,
    P_ADD IN NUMBER,
    P_EDIT IN NUMBER,
    P_DELETE IN NUMBER,
    P_DOWNLOAD IN NUMBER
)
IS
BEGIN
    MERGE INTO VAITRO_CHUCNANG vc
    USING (SELECT P_MAVAITRO as VT, P_MACHUCNANG as CN FROM DUAL) src
    ON (vc.MAVAITRO = src.VT AND vc.MACHUCNANG = src.CN)
    WHEN MATCHED THEN
        UPDATE SET CAN_VIEW = P_VIEW, CAN_ADD = P_ADD, CAN_EDIT = P_EDIT, 
                   CAN_DELETE = P_DELETE, CAN_DOWNLOAD = P_DOWNLOAD
    WHEN NOT MATCHED THEN
        INSERT (MAVAITRO, MACHUCNANG, CAN_VIEW, CAN_ADD, CAN_EDIT, CAN_DELETE, CAN_DOWNLOAD)
        VALUES (P_MAVAITRO, P_MACHUCNANG, P_VIEW, P_ADD, P_EDIT, P_DELETE, P_DOWNLOAD);
    COMMIT;
END;
/

-- Procedure sửa nhân viên (Đã cập nhật cho N-N)
CREATE OR REPLACE PROCEDURE PROC_SUA_NHANVIEN (
    P_MANV IN NHANVIEN.MANV%type,
    P_HOTEN IN NHANVIEN.HOTEN%type,
    P_NGAYSINH IN NHANVIEN.NGAYSINH%type,
    P_SDT IN NHANVIEN.SDT%type,
    P_TENDANGNHAP IN NHANVIEN.TENDANGNHAP%type,
    P_MATKHAU IN NHANVIEN.MATKHAU%type,
    P_TRANGTHAILAMVIEC IN NHANVIEN.TRANGTHAILAMVIEC%type
)
IS
    V_COUNT NUMBER;
BEGIN
    UPDATE NHANVIEN
    SET HOTEN = NVL(P_HOTEN, HOTEN),
        NGAYSINH = NVL(P_NGAYSINH, NGAYSINH),
        SDT = NVL(P_SDT, SDT),
        TENDANGNHAP = NVL(P_TENDANGNHAP, TENDANGNHAP),
        MATKHAU = NVL(P_MATKHAU, MATKHAU),
        TRANGTHAILAMVIEC = NVL(P_TRANGTHAILAMVIEC, TRANGTHAILAMVIEC)
    WHERE MANV = P_MANV;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NV_KHONG_TON_TAI_CN, 'Lỗi: Không tìm thấy Nhân viên để cập nhật.');
    END IF;

    COMMIT;
END;
/

-- Procedure xóa nhân viên
CREATE OR REPLACE PROCEDURE PROC_XOA_NHANVIEN (
    P_MANV IN NUMBER
)
IS
BEGIN
    UPDATE NHANVIEN
    SET TRANGTHAILAMVIEC = 0
    WHERE MANV = P_MANV;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NV_KHONG_TON_TAI_XOA, 'Lỗi: Không tìm thấy Nhân viên để xóa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_NV_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NV_XOA_HE_THONG, 'Lỗi hệ thống khi xóa Nhân viên: ' || SQLERRM);
END;
/
