-- Procedure thêm nguyên liệu
CREATE OR REPLACE PROCEDURE PROC_THEM_NGUYENLIEU (
    P_TENNL IN NGUYENLIEU.TENNL%type,
    P_XUATXU IN NGUYENLIEU.XUATXU%type,
    P_MUCTONANTOAN IN NGUYENLIEU.MUCTONANTOAN%type,
    P_MADVT IN DONVITINH.MADVT%type,
    P_MANL_OUT OUT NGUYENLIEU.MANL%type
)
IS
BEGIN
    INSERT INTO NGUYENLIEU (TENNL, XUATXU, MUCTONANTOAN, MADVT, THOIDIEMXOA, MANX)
    VALUES (P_TENNL, P_XUATXU, P_MUCTONANTOAN, P_MADVT, NULL, NULL)
    RETURNING MANL INTO P_MANL_OUT;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NL_THEM_MOI, 'Loi he thong khi tao moi Nguyen Lieu: ' || SQLERRM);
END;
/

-- Procedure sửa nguyên liệu
CREATE OR REPLACE PROCEDURE PROC_SUA_NGUYENLIEU (
    P_MANL IN NGUYENLIEU.MANL%type,
    P_TENNL IN NGUYENLIEU.TENNL%type,
    P_XUATXU IN NGUYENLIEU.XUATXU%type,
    P_MADVT IN NGUYENLIEU.MADVT%type,
    P_MUCTONANTOAN IN NGUYENLIEU.MUCTONANTOAN%type
)
IS
BEGIN
    UPDATE NGUYENLIEU
    SET TENNL = NVL(P_TENNL, TENNL),
        XUATXU = NVL(P_XUATXU, XUATXU),
        MADVT = NVL(P_MADVT, MADVT),
        MUCTONANTOAN = NVL(P_MUCTONANTOAN, MUCTONANTOAN),
        PHIENBAN = PHIENBAN + 1
    WHERE MANL = P_MANL;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NL_KHONG_TON_TAI_CN, 'Loi: Khong tim thay Nguyen lieu de cap nhat.');
    END IF;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_NL_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NL_CAPNHAT_HE_THONG, 'Loi he thong khi cap nhat Nguyen Lieu: ' || SQLERRM);
END;
/

-- Procedure Xóa nguyên liệu
CREATE OR REPLACE PROCEDURE PROC_XOA_NGUYENLIEU(
    P_MANL IN NGUYENLIEU.MANL%type,
    P_MANX IN NHANVIEN.MANV%type
)
IS
    V_LST_COUNT NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO V_LST_COUNT FROM CTPHIEUNHAP WHERE MANL = P_MANL;

    IF V_LST_COUNT > 0 THEN
        UPDATE NGUYENLIEU
        SET THOIDIEMXOA = SYSDATE,
            MANX = P_MANX,
            PHIENBAN = PHIENBAN + 1
        WHERE MANL = P_MANL;
    ELSE
        DELETE FROM NGUYENLIEU WHERE MANL = P_MANL;
    END IF;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NL_KHONG_TON_TAI_XOA, 'Loi: Khong tim thay Nguyen lieu de xoa.');
    END IF;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_NL_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_NL_XOA_HE_THONG, 'Loi he thong khi xoa Nguyen Lieu: ' || SQLERRM);
END;
/
