-- ==============================================================
-- PROCEDURE CUD (Create, Update, Delete) - MODULE TÙY CHỈNH BÁNH
-- Gồm: KÍCH CỠ, CỐT BÁNH, NHÂN BÁNH, KIỂU TRANG TRÍ
-- Tác giả: Antigravity
-- ==============================================================

-- --------------------------------------------------------------
-- 1. CUD KÍCH CỠ BÁNH
-- --------------------------------------------------------------
CREATE OR REPLACE PROCEDURE PROC_THEM_KICHCOBANH(P_TENKC IN NVARCHAR2, P_PHUPHI IN NUMBER, P_MAKC_OUT OUT NUMBER) IS BEGIN INSERT INTO KICHCOBANH (TENKC, PHUPHI) VALUES (P_TENKC, NVL(P_PHUPHI, 0)) RETURNING MAKC INTO P_MAKC_OUT; COMMIT; END;
/
CREATE OR REPLACE PROCEDURE PROC_CAPNHAT_KICHCOBANH(P_MAKC IN NUMBER, P_TENKC IN NVARCHAR2, P_PHUPHI IN NUMBER) IS BEGIN UPDATE KICHCOBANH SET TENKC = NVL(P_TENKC, TENKC), PHUPHI = NVL(P_PHUPHI, PHUPHI) WHERE MAKC = P_MAKC; IF SQL%ROWCOUNT = 0 THEN RAISE_APPLICATION_ERROR(-20631, 'Không tìm thấy.'); END IF; COMMIT; END;
/
CREATE OR REPLACE PROCEDURE PROC_XOA_KICHCOBANH(P_MAKC IN NUMBER, P_MANX IN NUMBER) IS BEGIN UPDATE KICHCOBANH SET THOIDIEMXOA = SYSDATE, MANX = P_MANX WHERE MAKC = P_MAKC; COMMIT; END;
/

-- --------------------------------------------------------------
-- 2. CUD CỐT BÁNH
-- --------------------------------------------------------------
CREATE OR REPLACE PROCEDURE PROC_THEM_COTBANH(P_TENCOT IN NVARCHAR2, P_PHUPHI IN NUMBER, P_MACOT_OUT OUT NUMBER) IS BEGIN INSERT INTO COTBANH (TENCOT, PHUPHI) VALUES (P_TENCOT, NVL(P_PHUPHI, 0)) RETURNING MACOT INTO P_MACOT_OUT; COMMIT; END;
/
CREATE OR REPLACE PROCEDURE PROC_CAPNHAT_COTBANH(P_MACOT IN NUMBER, P_TENCOT IN NVARCHAR2, P_PHUPHI IN NUMBER) IS BEGIN UPDATE COTBANH SET TENCOT = NVL(P_TENCOT, TENCOT), PHUPHI = NVL(P_PHUPHI, PHUPHI) WHERE MACOT = P_MACOT; IF SQL%ROWCOUNT = 0 THEN RAISE_APPLICATION_ERROR(-20632, 'Không tìm thấy.'); END IF; COMMIT; END;
/
CREATE OR REPLACE PROCEDURE PROC_XOA_COTBANH(P_MACOT IN NUMBER, P_MANX IN NUMBER) IS BEGIN UPDATE COTBANH SET THOIDIEMXOA = SYSDATE, MANX = P_MANX WHERE MACOT = P_MACOT; COMMIT; END;
/

-- --------------------------------------------------------------
-- 3. CUD NHÂN BÁNH
-- --------------------------------------------------------------
CREATE OR REPLACE PROCEDURE PROC_THEM_NHANBANH(P_TENNHAN IN NVARCHAR2, P_PHUPHI IN NUMBER, P_MANHAN_OUT OUT NUMBER) IS BEGIN INSERT INTO NHANBANH (TENNHAN, PHUPHI) VALUES (P_TENNHAN, NVL(P_PHUPHI, 0)) RETURNING MANHAN INTO P_MANHAN_OUT; COMMIT; END;
/
CREATE OR REPLACE PROCEDURE PROC_CAPNHAT_NHANBANH(P_MANHAN IN NUMBER, P_TENNHAN IN NVARCHAR2, P_PHUPHI IN NUMBER) IS BEGIN UPDATE NHANBANH SET TENNHAN = NVL(P_TENNHAN, TENNHAN), PHUPHI = NVL(P_PHUPHI, PHUPHI) WHERE MANHAN = P_MANHAN; IF SQL%ROWCOUNT = 0 THEN RAISE_APPLICATION_ERROR(-20633, 'Không tìm thấy.'); END IF; COMMIT; END;
/
CREATE OR REPLACE PROCEDURE PROC_XOA_NHANBANH(P_MANHAN IN NUMBER, P_MANX IN NUMBER) IS BEGIN UPDATE NHANBANH SET THOIDIEMXOA = SYSDATE, MANX = P_MANX WHERE MANHAN = P_MANHAN; COMMIT; END;
/

-- --------------------------------------------------------------
-- 4. CUD KIỂU TRANG TRÍ
-- --------------------------------------------------------------
CREATE OR REPLACE PROCEDURE PROC_THEM_KIEUTRANGTRI(P_TENTRANGTRI IN NVARCHAR2, P_PHUPHI IN NUMBER, P_MATRANGTRI_OUT OUT NUMBER) IS BEGIN INSERT INTO KIEUTRANGTRI (TENTRANGTRI, PHUPHI) VALUES (P_TENTRANGTRI, NVL(P_PHUPHI, 0)) RETURNING MATRANGTRI INTO P_MATRANGTRI_OUT; COMMIT; END;
/
CREATE OR REPLACE PROCEDURE PROC_CAPNHAT_KIEUTRANGTRI(P_MATRANGTRI IN NUMBER, P_TENTRANGTRI IN NVARCHAR2, P_PHUPHI IN NUMBER) IS BEGIN UPDATE KIEUTRANGTRI SET TENTRANGTRI = NVL(P_TENTRANGTRI, TENTRANGTRI), PHUPHI = NVL(P_PHUPHI, PHUPHI) WHERE MATRANGTRI = P_MATRANGTRI; IF SQL%ROWCOUNT = 0 THEN RAISE_APPLICATION_ERROR(-20634, 'Không tìm thấy.'); END IF; COMMIT; END;
/
CREATE OR REPLACE PROCEDURE PROC_XOA_KIEUTRANGTRI(P_MATRANGTRI IN NUMBER, P_MANX IN NUMBER) IS BEGIN UPDATE KIEUTRANGTRI SET THOIDIEMXOA = SYSDATE, MANX = P_MANX WHERE MATRANGTRI = P_MATRANGTRI; COMMIT; END;
/
