-- Procedure thêm hạng thành viên
CREATE OR REPLACE PROCEDURE PROC_THEM_HANGTHANHVIEN (
    P_TENHANG IN HANGTHANHVIEN.TENHANG%type,
    P_DIEMTOITHIEU IN HANGTHANHVIEN.DIEMTOITHIEU%type,
    P_PHANTRAMGIAMGIA IN HANGTHANHVIEN.PHANTRAMGIAMGIA%type,
    P_MAHANG_OUT OUT HANGTHANHVIEN.TENHANG%type
)
IS
BEGIN
    INSERT INTO HANGTHANHVIEN (TENHANG, DIEMTOITHIEU, PHANTRAMGIAMGIA, THOIDIEMXOA, MANX)
    VALUES (P_TENHANG, NVL(P_DIEMTOITHIEU, 0), NVL(P_PHANTRAMGIAMGIA, 0), NULL, NULL)
    RETURNING MAHANG INTO P_MAHANG_OUT;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HANGTV_THEM_HE_THONG, 'Lỗi hệ thống khi thêm Hạng thành viên: ' || SQLERRM);
END;
/

-- Procedure sửa hạng thành viên
CREATE OR REPLACE PROCEDURE PROC_SUA_HANGTHANHVIEN (
    P_MAHANG IN HANGTHANHVIEN.MAHANG%type,
    P_TENHANG IN HANGTHANHVIEN.TENHANG%type,
    P_DIEMTOITHIEU IN HANGTHANHVIEN.DIEMTOITHIEU%type,
    P_PHANTRAMGIAMGIA IN HANGTHANHVIEN.PHANTRAMGIAMGIA%type
)
IS
BEGIN
    UPDATE HANGTHANHVIEN
    SET TENHANG = NVL(P_TENHANG, TENHANG),
        DIEMTOITHIEU = NVL(P_DIEMTOITHIEU, DIEMTOITHIEU),
        PHANTRAMGIAMGIA = NVL(P_PHANTRAMGIAMGIA, PHANTRAMGIAMGIA)
    WHERE MAHANG = P_MAHANG;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HANGTV_KHONG_TON_TAI_CN, 'Lỗi: Không tìm thấy Hạng thành viên để cập nhật.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_HANGTV_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HANGTV_CAPNHAT_HE_THONG, 'Lỗi hệ thống khi cập nhật Hạng thành viên: ' || SQLERRM);
END;
/

-- Procedure xóa hạng thành viên
CREATE OR REPLACE PROCEDURE PROC_XOA_HANGTHANHVIEN (
    P_MAHANG IN HANGTHANHVIEN.MAHANG%type,
    P_MANV_XOA IN NHANVIEN.MANV%type
)
IS
BEGIN
    UPDATE HANGTHANHVIEN
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANV_XOA
    WHERE MAHANG = P_MAHANG;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HANGTV_KHONG_TON_TAI_XOA, 'Lỗi: Không tìm thấy Hạng thành viên để xóa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_HANGTV_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HANGTV_XOA_HE_THONG, 'Lỗi hệ thống khi xóa Hạng thành viên: ' || SQLERRM);
END;
/

-- Procedure thêm khách hàng
CREATE OR REPLACE PROCEDURE PROC_THEM_KHACHHANG (
    P_HOTEN IN NVARCHAR2,
    P_SDT IN VARCHAR2,
    P_DIACHI IN NVARCHAR2,
    P_DIEMTICHLUY IN NUMBER DEFAULT 0,
    P_MAHANG IN NUMBER DEFAULT NULL,
    P_MAKH_OUT OUT NUMBER
)
IS
BEGIN
    INSERT INTO KHACHHANG (HOTEN, SDT, DIACHI, NGAYDANGKY, DIEMTICHLUY, MAHANG, THOIDIEMXOA, MANX)
    VALUES (P_HOTEN, P_SDT, P_DIACHI, SYSDATE, P_DIEMTICHLUY, P_MAHANG, NULL, NULL)
    RETURNING MAKH INTO P_MAKH_OUT;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KH_THEM_HE_THONG, 'Lỗi hệ thống khi thêm Khách hàng: ' || SQLERRM);
END;
/

-- Procedure sửa khách hàng
CREATE OR REPLACE PROCEDURE PROC_SUA_KHACHHANG (
    P_MAKH IN KHACHHANG.MAKH%type,
    P_HOTEN IN KHACHHANG.HOTEN%type,
    P_SDT IN KHACHHANG.SDT%type,
    P_DIACHI IN KHACHHANG.DIACHI%type,
    P_DIEMTICHLUY IN KHACHHANG.DIEMTICHLUY%type,
    P_MAHANG IN KHACHHANG.MAHANG%type
)
IS
BEGIN
    UPDATE KHACHHANG
    SET HOTEN = NVL(P_HOTEN, HOTEN),
        SDT = NVL(P_SDT, SDT),
        DIACHI = NVL(P_DIACHI, DIACHI),
        DIEMTICHLUY = NVL(P_DIEMTICHLUY, DIEMTICHLUY),
        MAHANG = NVL(P_MAHANG, MAHANG)
    WHERE MAKH = P_MAKH;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KH_KHONG_TON_TAI_CN, 'Lỗi: Không tìm thấy Khách hàng để cập nhật.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_KH_KHONG_TON_TAI_CN THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KH_CAPNHAT_HE_THONG, 'Lỗi hệ thống khi cập nhật Khách hàng: ' || SQLERRM);
END;
/

-- Procedure xóa khách hàng
CREATE OR REPLACE PROCEDURE PROC_XOA_KHACHHANG (
    P_MAKH IN KHACHHANG.MAKH%type,
    P_MANV_XOA IN NHANVIEN.MANV%type
)
IS
BEGIN
    UPDATE KHACHHANG
    SET THOIDIEMXOA = SYSDATE,
        MANX = P_MANV_XOA
    WHERE MAKH = P_MAKH;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KH_KHONG_TON_TAI_XOA, 'Lỗi: Không tìm thấy Khách hàng để xóa.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF SQLCODE = PKG_ERROR_CODES.ERR_KH_KHONG_TON_TAI_XOA THEN RAISE; END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KH_XOA_HE_THONG, 'Lỗi hệ thống khi xóa Khách hàng: ' || SQLERRM);
END;
/
