@startuml
left to right direction


  usecase "Quản lý công thức và sản xuất" as UC_Main
  usecase "Thêm công thức" as UC_Add
  usecase "Sửa công thức" as UC_Edit
  usecase "Tra cứu công thức" as UC_Search
  usecase "Tính toán số lượng bánh làm ra" as UC_Calc
  usecase "Cấu hình giới hạn nhận đơn" as UC_Limit



UC_Add .up.> UC_Main : <<extend>>
UC_Edit .up.> UC_Main : <<extend>>
UC_Search .up.> UC_Main : <<extend>>
UC_Calc .up.> UC_Main : <<extend>>
UC_Limit .up.> UC_Main : <<extend>>

UC_Edit ..> UC_Search : <<include>>
UC_Calc ..> UC_Search : <<include>>

@enduml
