@startuml
left to right direction


  usecase "Quản lý nhà cung cấp" as UC_Main
  usecase "Thêm nhà cung cấp" as UC_Add
  usecase "Sửa nhà cung cấp" as UC_Edit
  usecase "Cập nhật trạng thái nhà cung cấp" as UC_Status
  usecase "Tra cứu nhà cung cấp" as UC_Search
  usecase "Truy vết nguồn gốc" as UC_Trace



UC_Add .up.> UC_Main : <<extend>>
UC_Edit .up.> UC_Main : <<extend>>
UC_Status .up.> UC_Main : <<extend>>
UC_Search .up.> UC_Main : <<extend>>
UC_Trace .up.> UC_Main : <<extend>>

UC_Edit ..> UC_Search : <<include>>
UC_Status ..> UC_Search : <<include>>

@enduml
