@startuml
left to right direction


  usecase "Quản lý nhân sự" as UC_Main
  usecase "Thêm nhân sự" as UC_Add
  usecase "Sửa nhân sự" as UC_Edit
  usecase "Cập nhật trạng thái nhân sự" as UC_Status
  usecase "Tra cứu nhân sự" as UC_Search
  usecase "Phân quyền tài khoản" as UC_Perm
  usecase "Xem nhật ký hoạt động" as UC_Log



UC_Add .up.> UC_Main : <<extend>>
UC_Edit .up.> UC_Main : <<extend>>
UC_Status .up.> UC_Main : <<extend>>
UC_Search .up.> UC_Main : <<extend>>
UC_Perm .up.> UC_Main : <<extend>>
UC_Log .up.> UC_Main : <<extend>>

UC_Edit ..> UC_Search : <<include>>
UC_Status ..> UC_Search : <<include>>
UC_Perm ..> UC_Search : <<include>>

@enduml
