@startuml DoiMatKhauCaNhan
mainframe sd Seq_DoiMatKhauCaNhan
autonumber "<b>##."
skinparam sequenceMessageAlign center
skinparam style strictuml

    skinparam noteBackgroundColor transparent
    skinparam noteBorderColor transparent

actor "Nhân viên" as NV #White
boundary "Form_DoiMatKhauCaNhan" as FRM #White
boundary "GUI_DoiMatKhau" as UI #White
control "Controller_XacThuc" as SYS #White
entity ": TAIKHOAN" as DB_TK #White


NV -> UI: Chọn chức năng đổi mật khẩu cá nhân
activate UI
deactivate UI

UI -->> FRM: Hiển thị biểu mẫu nhập liệu

NV -> FRM: Nhập mật khẩu hiện tại, mật khẩu mới và xác nhận
activate FRM
deactivate FRM

FRM -> SYS: Gửi yêu cầu đổi mật khẩu
activate SYS
deactivate SYS

SYS -> SYS: Kiểm tra mật khẩu hiện tại và mật khẩu mới trùng khớp
activate SYS
deactivate SYS

group alt Kiểm tra mật khẩu hiện tại và mật khẩu mới trùng khớp
    note over of NV: [Mật khẩu không khớp hoặc sai mật khẩu cũ]
    autonumber stop
    NV -[hidden]-> DB_TK
    autonumber resume "<b>##."
    SYS -->> UI: Thông báo lỗi
else 
    note over of NV: [Thông tin hợp lệ]
    autonumber stop
    NV -[hidden]-> DB_TK
    autonumber resume "<b>##."
    SYS -> DB_TK: Lưu mật khẩu mới
    activate DB_TK
    deactivate DB_TK
    
    group alt Lưu mật khẩu mới
        note over of NV: [Lỗi lưu cơ sở dữ liệu]
        autonumber stop
        NV -[hidden]-> DB_TK
        autonumber resume "<b>##."
        SYS -->> UI: Thông báo lỗi hệ thống
    else 
        note over of NV: [Lưu thành công]
        autonumber stop
        NV -[hidden]-> DB_TK
        autonumber resume "<b>##."
        SYS -->> UI: Thông báo thành công và đóng biểu mẫu
    end
end

@enduml
