ALTER TABLE VAITRO MODIFY (ThoiDiemXoa DEFAULT NULL, MaNX DEFAULT NULL);
ALTER TABLE HANGTHANHVIEN MODIFY (ThoiDiemXoa DEFAULT NULL, MaNX DEFAULT NULL);
ALTER TABLE KHACHHANG MODIFY (ThoiDiemXoa DEFAULT NULL, MaNX DEFAULT NULL);