ALTER TABLE KHACHHANG ADD CONSTRAINT CK_KH_DIEM CHECK (DIEMTICHLUY >= 0);
ALTER TABLE KHACHHANG ADD CONSTRAINT CK_KH_SDT CHECK (LENGTH(SDT) BETWEEN 9 AND 15);

ALTER TABLE HANGTHANHVIEN ADD CONSTRAINT CK_HANGTV_DIEM CHECK (DIEMTOITHIEU >= 0);
ALTER TABLE HANGTHANHVIEN ADD CONSTRAINT CK_HANGTV_GIAM CHECK (PHANTRAMGIAMGIA BETWEEN 0 AND 100);

ALTER TABLE NHANVIEN ADD CONSTRAINT CK_NV_TRANGTHAI CHECK (TRANGTHAILAMVIEC IN (0,1));
ALTER TABLE NHANVIEN ADD CONSTRAINT CK_NV_SDT CHECK (LENGTH(SDT) BETWEEN 9 AND 15);

ALTER TABLE CALAMVIEC ADD CONSTRAINT CK_CA_THOIGIAN CHECK (THOIGIANDONGCA IS NULL OR THOIGIANDONGCA >= ThoiGianMoCa);
ALTER TABLE CALAMVIEC ADD CONSTRAINT CK_CA_TRANGTHAI CHECK (TrangThai IN ('Đang mở', 'Đã đóng'));

ALTER TABLE HANGTHANHVIEN ADD CONSTRAINT CK_HANGTV_TEN CHECK ( TENHANG IN ('Không', 'Bạc','Vàng','Kim cương'));

ALTER TABLE HANGTHANHVIEN MODIFY ( TENHANG DEFAULT 'Không', PHANTRAMGIAMGIA  default  0)