ALTER TABLE KHACHHANG ADD CONSTRAINT CK_KH_DIEM CHECK (DiemTichLuy >= 0);
ALTER TABLE KHACHHANG ADD CONSTRAINT CK_KH_SDT CHECK (LENGTH(SDT) BETWEEN 9 AND 15);
ALTER TABLE HANGTHANHVIEN ADD CONSTRAINT CK_HANGTV_DIEM CHECK (DiemToiThieu >= 0);
ALTER TABLE HANGTHANHVIEN ADD CONSTRAINT CK_HANGTV_GIAM CHECK (PhanTramGiamGia BETWEEN 0 AND 100);
ALTER TABLE NHANVIEN ADD CONSTRAINT CK_NV_TRANGTHAI CHECK (TrangThaiLamViec IN (0,1));
ALTER TABLE NHANVIEN ADD CONSTRAINT CK_NV_SDT CHECK (LENGTH(SDT) BETWEEN 9 AND 15);




ALTER TABLE DANHMUCSP MODIFY (ThoiDiemXoa DEFAULT NULL, MaNX DEFAULT NULL);
ALTER TABLE SANPHAM MODIFY (ThoiDiemXoa DEFAULT NULL, MaNX DEFAULT NULL);
ALTER TABLE KICHCOBANH MODIFY (ThoiDiemXoa DEFAULT NULL, MaNX DEFAULT NULL);
ALTER TABLE COTBANH MODIFY (ThoiDiemXoa DEFAULT NULL, MaNX DEFAULT NULL);
ALTER TABLE NHANBANH MODIFY (ThoiDiemXoa DEFAULT NULL, MaNX DEFAULT NULL);
ALTER TABLE KIEUTRANGTRI MODIFY (ThoiDiemXoa DEFAULT NULL, MaNX DEFAULT NULL);