ALTER TABLE SANPHAM ADD CONSTRAINT CK_SP_GIA CHECK (GIACOBAN > 0);
ALTER TABLE SANPHAM ADD CONSTRAINT CK_SP_CUSTOM CHECK (CHOPHEPTUYCHINH IN (0,1));
ALTER TABLE SANPHAM ADD CONSTRAINT CK_SP_BAOQUAN CHECK (ThoiGianBaoQuan > 0);
ALTER TABLE SANPHAM ADD CONSTRAINT CK_SP_CHUANBI CHECK (THOIGIANCHUANBI >= 0);
ALTER TABLE SANPHAM ADD CONSTRAINT CK_SP_SOLUONGTON CHECK (SOLUONGTON >= 0);




ALTER TABLE KICHCOBANH ADD CONSTRAINT CK_SIZE_PHUPHI CHECK (PHUPHI >= 0);

ALTER TABLE COTBANH ADD CONSTRAINT CK_COT_PHUPHI CHECK (PHUPHI >= 0);

ALTER TABLE NHANBANH ADD CONSTRAINT CK_NHAN_PHUPHI CHECK (PHUPHI >= 0);

ALTER TABLE KIEUTRANGTRI ADD CONSTRAINT CK_TT_PHUPHI CHECK (PHUPHI >= 0);

ALTER TABLE CONGTHUC ADD CONSTRAINT CK_CT_TIEUHAO CHECK (SOLUONGTIEUHAO > 0);

