ALTER TABLE SANPHAM ADD CONSTRAINT CK_SP_GIA CHECK (GiaCoBan > 0);
ALTER TABLE SANPHAM ADD CONSTRAINT CK_SP_CUSTOM CHECK (ChoPhepCustom IN (0,1));
ALTER TABLE KICHCOBANH ADD CONSTRAINT CK_SIZE_PHUPHI CHECK (PhuPhi >= 0);
ALTER TABLE COTBANH ADD CONSTRAINT CK_COT_PHUPHI CHECK (PhuPhi >= 0);
ALTER TABLE NHANBANH ADD CONSTRAINT CK_NHAN_PHUPHI CHECK (PhuPhi >= 0);
ALTER TABLE KIEUTRANGTRI ADD CONSTRAINT CK_TT_PHUPHI CHECK (PhuPhi >= 0);
ALTER TABLE CONGTHUC ADD CONSTRAINT CK_CT_TIEUHAO CHECK (SoLuongTieuHao > 0);