ALTER TABLE NGUYENLIEU ADD CONSTRAINT CK_NL_MUCTON CHECK (MUCTONANTOAN >= 0);
ALTER TABLE NGUYENLIEU ADD CONSTRAINT CK_NL_TONTONG CHECK (SOLUONGTONTONG >= 0);
ALTER TABLE NGUYENLIEU ADD CONSTRAINT CK_NL_TENNL UNIQUE (TENNL);
ALTER TABLE NGUYENLIEU ADD CONSTRAINT CK_NL_VSATTP CHECK (DATCHUANVSATTP IN (0,1));

ALTER TABLE CTPHIEUNHAP ADD CONSTRAINT CK_CTPN_SOLUONG CHECK (SOLUONG > 0);
ALTER TABLE CTPHIEUNHAP ADD CONSTRAINT CK_CTPN_DONGIA CHECK (DONGIA >= 0);
ALTER TABLE CTPHIEUNHAP ADD CONSTRAINT CK_CTPN_CONLAI CHECK (SOLUONGCONLAI >= 0);

ALTER TABLE PHIEUXUATKHO ADD CONSTRAINT CK_PX_LYDO CHECK ( LYDOXUAT IN ( 'Lam banh', 'San pham hong', 'Nguyen lieu hong', 'Sai sot trong qua trinh lam banh'));

ALTER TABLE PHIEUNHAPKHO ADD CONSTRAINT CK_PN_TONGTIEN CHECK (TONGTIENNHAP >= 0);

ALTER TABLE CTPHIEUXUAT_NL ADD CONSTRAINT CK_CTPX_NL_SL CHECK (SOLUONG > 0);

ALTER TABLE CTPHIEUXUAT_TP ADD CONSTRAINT CK_CTPX_TP_SL CHECK (SOLUONG > 0);