ALTER TABLE DONDATHANG ADD CONSTRAINT CK_DON_TONGTIEN CHECK (TONGTIENHDBAN >= 0);
ALTER TABLE DONDATHANG ADD CONSTRAINT CK_DON_TIENDACOC CHECK (TIENDACOC >= 0);
ALTER TABLE DONDATHANG ADD CONSTRAINT CK_DON_NGAYNHAN CHECK (NGAYGIONHANBANH IS NULL OR NGAYGIONHANBANH >= NGAYLAP);
ALTER TABLE DONDATHANG ADD CONSTRAINT CK_DON_THANHTOAN CHECK (TONGTIENHDBAN >= TIENDACOC);
ALTER TABLE DONDATHANG ADD CONSTRAINT CK_DON_HINHTHUC CHECK (HINHTHUCNHAN IN (1, 2));
ALTER TABLE DONDATHANG ADD CONSTRAINT CK_DON_DIACHI CHECK (HINHTHUCNHAN = 1 OR (HINHTHUCNHAN = 2 AND DIACHIGIAO IS NOT NULL));

ALTER TABLE CTDONHANG ADD CONSTRAINT CK_CTDH_SOLUONG CHECK (SOLUONG > 0);
ALTER TABLE CTDONHANG ADD CONSTRAINT CK_CTDH_DONGIA CHECK (DONGIA >= 0);
ALTER TABLE CTDONHANG ADD CONSTRAINT CK_CTDH_GIAM CHECK (PhanTramGiam BETWEEN 0 AND 100);

ALTER TABLE CTDONTUYCHINH ADD CONSTRAINT CK_CTDC_SOLUONG CHECK (SOLUONG > 0);
ALTER TABLE CTDONTUYCHINH ADD CONSTRAINT CK_CTDC_DONGIA CHECK (DONGIA >= 0);
ALTER TABLE CTDONTUYCHINH ADD CONSTRAINT CK_CTDC_CHUANBI CHECK (THOIGIANCHUANBI >= 0);

ALTER TABLE NANGLUCSANXUAT ADD CONSTRAINT CK_NSX_GIOIHAN CHECK (GIOIHANSOBANH > 0);
ALTER TABLE NANGLUCSANXUAT ADD CONSTRAINT CK_NSX_DANHAN CHECK (SOBANHDANHAN >= 0);
ALTER TABLE NANGLUCSANXUAT ADD CONSTRAINT CK_NSX_KHANANG CHECK (SOBANHDANHAN <= GIOIHANSOBANH);

ALTER TABLE TRANGTHAIDON ADD CONSTRAINT CK_TT_TEN CHECK (TENTRANGTHAI IN ('Mới đặt', 'Đã cọc', 'Đang sản xuất', 'Chờ giao', 'Hoàn thành', 'Hủy', 'Hoàn hàng'));