ALTER TABLE NGUYENLIEU ADD CONSTRAINT CK_NL_MUCTON CHECK (MucTonAnToan >= 0);
ALTER TABLE NGUYENLIEU ADD CONSTRAINT CK_NL_TONTONG CHECK (SoLuongTonTong >= 0);
ALTER TABLE NGUYENLIEU ADD CONSTRAINT CK_NL_TENNL UNIQUE (TenNL);
ALTER TABLE NGUYENLIEU ADD CONSTRAINT CK_NL_VSATTP CHECK (DatChuanVSATTP IN (0,1));

ALTER TABLE CTPHIEUNHAP ADD CONSTRAINT CK_CTPN_SOLUONG CHECK (SoLuong > 0);
ALTER TABLE CTPHIEUNHAP ADD CONSTRAINT CK_CTPN_DONGIA CHECK (DonGia > 0);
ALTER TABLE CTPHIEUNHAP ADD CONSTRAINT CK_CTPN_CONLAI CHECK (SoLuongConLai >= 0);
ALTER TABLE PHIEUNHAPKHO ADD CONSTRAINT CK_PN_TONGTIEN CHECK (TongTienNhap >= 0);
ALTER TABLE CTPHIEUNHAP ADD CONSTRAINT CK_CTPN_HSD CHECK (HanSuDung >= NgayNhapKho + 10);

ALTER TABLE CTPHIEUXUAT_NL ADD CONSTRAINT CK_CTPX_NL_SL CHECK (SoLuong > 0);
ALTER TABLE CTPHIEUXUAT_TP ADD CONSTRAINT CK_CTPX_TP_SL CHECK (SoLuong > 0);