ALTER TABLE HOADON ADD CONSTRAINT CK_HD_VAT CHECK (THUEVAT BETWEEN 0 AND 100);
ALTER TABLE HOADON ADD CONSTRAINT CK_HD_TIEN_THANHTOAN CHECK (TONGTIENTHANHTOAN >= 0);

ALTER TABLE PHIEUTHUCHI ADD CONSTRAINT CK_TC_SOTIEN CHECK (SOTIEN > 0);