ALTER TABLE DONDATHANG ADD CONSTRAINT CK_DON_TONGTIEN CHECK (TongTienHDBan >= 0);
ALTER TABLE DONDATHANG ADD CONSTRAINT CK_DON_TIENDACOC CHECK (TienDaCoc >= 0);
ALTER TABLE DONDATHANG ADD CONSTRAINT CK_DON_NGAYNHAN CHECK (NgayGioNhanBanh IS NULL OR NgayGioNhanBanh >= NgayLap);
ALTER TABLE DONDATHANG ADD CONSTRAINT CK_DON_THANHTOAN CHECK (TongTienHDBan >= TienDaCoc);

ALTER TABLE CTDONHANG ADD CONSTRAINT CK_CTDH_SOLUONG CHECK (SoLuong > 0);
ALTER TABLE CTDONHANG ADD CONSTRAINT CK_CTDH_DONGIA CHECK (DonGia > 0);
ALTER TABLE CTDONHANG ADD CONSTRAINT CK_CTDH_MADON CHECK (MaDon IS NOT NULL);

ALTER TABLE CTDONCUSTOM ADD CONSTRAINT CK_CTDC_SOLUONG CHECK (SoLuong > 0);
ALTER TABLE CTDONCUSTOM ADD CONSTRAINT CK_CTDC_DONGIA CHECK (DonGia > 0);

ALTER TABLE NANGLUCSANXUAT ADD CONSTRAINT CK_NSX_GIOIHAN CHECK (GioiHanSoBanh > 0);
ALTER TABLE NANGLUCSANXUAT ADD CONSTRAINT CK_NSX_DANHAN CHECK (SoBanhDaNhan >= 0);
ALTER TABLE NANGLUCSANXUAT ADD CONSTRAINT CK_NSX_KHANANG CHECK (SoBanhDaNhan <= GioiHanSoBanh);