ALTER TABLE HOADON ADD CONSTRAINT CK_HD_VAT CHECK (ThueVAT BETWEEN 0 AND 100);
ALTER TABLE HOADON ADD CONSTRAINT CK_HD_TIEN_THANHTOAN CHECK (TongTienThanhToan >= 0);

ALTER TABLE PHIEUTHUCHI ADD CONSTRAINT CK_TC_SOTIEN CHECK (SoTien > 0);
ALTER TABLE PHIEUTHUCHI ADD CONSTRAINT CK_TC_MAHD CHECK (MaHD IS NOT NULL OR MaPN IS NOT NULL);
ALTER TABLE PHIEUTHUCHI ADD CONSTRAINT CK_TC_MANV CHECK (MaNV IS NOT NULL);


ALTER TABLE PHUONGTHUCTT MODIFY (ThoiDiemXoa DEFAULT NULL, MaNX DEFAULT NULL);
ALTER TABLE LOAITHUCHI MODIFY (ThoiDiemXoa DEFAULT NULL, MaNX DEFAULT NULL);

-- Cần đổi kiểu dữ liệu trước nếu đang là NUMBER
ALTER TABLE CALAMVIEC MODIFY (MaMayPOS VARCHAR2(10));



ALTER TABLE CALAMVIEC ADD CONSTRAINT CK_CA_POS CHECK (MaMayPOS IN ('POS1', 'POS2', 'POS3'));