ALTER TABLE VAITRO MODIFY (THOIDIEMXOA DEFAULT NULL, MaNX DEFAULT NULL);

ALTER TABLE HANGTHANHVIEN MODIFY (THOIDIEMXOA DEFAULT NULL, MaNX DEFAULT NULL);

ALTER TABLE KHACHHANG MODIFY (THOIDIEMXOA DEFAULT NULL, MaNX DEFAULT NULL);

ALTER TABLE DANHMUCSP MODIFY (THOIDIEMXOA DEFAULT NULL, MaNX DEFAULT NULL);

ALTER TABLE SANPHAM MODIFY (THOIDIEMXOA DEFAULT NULL, MaNX DEFAULT NULL);

ALTER TABLE KICHCOBANH MODIFY (THOIDIEMXOA DEFAULT NULL, MaNX DEFAULT NULL);

ALTER TABLE COTBANH MODIFY (THOIDIEMXOA DEFAULT NULL, MaNX DEFAULT NULL);

ALTER TABLE NHANBANH MODIFY (THOIDIEMXOA DEFAULT NULL, MaNX DEFAULT NULL);

ALTER TABLE KIEUTRANGTRI MODIFY (THOIDIEMXOA DEFAULT NULL, MaNX DEFAULT NULL);

ALTER TABLE PHUONGTHUCTT MODIFY (THOIDIEMXOA DEFAULT NULL, MaNX DEFAULT NULL);

ALTER TABLE LOAITHUCHI MODIFY (THOIDIEMXOA DEFAULT NULL, MaNX DEFAULT NULL);
