' ==========================================
' 2.3.3. Thêm/Xóa/Sửa nhân sự
' ==========================================
@startuml 03_ThemXoaSuaNhanSu
left to right direction
skinparam shadowing false

usecase "Cập nhật nhân sự" as UC_ManageStaff
usecase "Thêm nhân sự" as UC_AddStaff
usecase "Sửa nhân sự" as UC_EditStaff
usecase "Xóa/Vô hiệu hóa nhân sự" as UC_DelStaff

usecase "Hủy bỏ điền biểu mẫu" as UC_Cancel
usecase "Từ chối hộp thoại vô hiệu hóa" as UC_CancelDel
usecase "Cảnh báo bỏ trống trường bắt buộc" as UC_ErrEmpty
usecase "Báo lỗi trùng tên đăng nhập" as UC_ErrDup

UC_AddStaff --|> UC_ManageStaff
UC_EditStaff --|> UC_ManageStaff
UC_DelStaff --|> UC_ManageStaff

UC_Cancel ..> UC_ManageStaff : <<extend>>
UC_CancelDel ..> UC_DelStaff : <<extend>>
UC_ErrEmpty ..> UC_ManageStaff : <<extend>>
UC_ErrDup ..> UC_AddStaff : <<extend>>
@enduml
