' ==========================================
' 2.3.6. Xem nhật ký hoạt động
' ==========================================
@startuml 06_XemNhatKyHoatDong
left to right direction
skinparam shadowing false

usecase "Xem nhật ký hoạt động" as UC_Logs
usecase "Xuất báo cáo nhật ký" as UC_Export
usecase "Thông báo lỗi mất kết nối máy chủ" as UC_ErrConnect

UC_Export ..> UC_Logs : <<extend>>
UC_ErrConnect ..> UC_Logs : <<extend>>
@enduml
