' ==========================================
' 2.3.9. Tra cứu khách hàng
' ==========================================
@startuml 09_TraCuuKhachHang
left to right direction
skinparam shadowing false

usecase "Tra cứu khách hàng" as UC_SearchCust
usecase "Xóa từ khóa (Hiển thị lại)" as UC_ClearSearch
usecase "Không tìm thấy & Gợi ý tạo mới" as UC_ErrNotFound

UC_ClearSearch ..> UC_SearchCust : <<extend>>
UC_ErrNotFound ..> UC_SearchCust : <<extend>>
@enduml
