' ==========================================
' 2.3.10. Tra cứu lịch sử mua hàng
' ==========================================
@startuml 10_TraCuuLichSuMuaHang
left to right direction
skinparam shadowing false

usecase "Tra cứu lịch sử mua hàng" as UC_History
usecase "Thiết lập bộ lọc khoảng thời gian" as UC_FilterTime
usecase "Thông báo khách hàng mới (Trống)" as UC_ErrEmpty

UC_FilterTime ..> UC_History : <<extend>>
UC_ErrEmpty ..> UC_History : <<extend>>
@enduml
