' ==========================================
' 2.3.12. Lập hóa đơn bán lẻ
' ==========================================
@startuml 12_LapHoaDonBanLe
left to right direction
skinparam shadowing false

usecase "Lập hóa đơn bán lẻ" as UC_Retail
usecase "Kiểm tra thông tin thành viên" as UC_CheckMember
usecase "Khách vãng lai (Bỏ qua nhập SĐT)" as UC_Guest
usecase "Xóa bớt món trước khi thanh toán" as UC_RemoveItem
usecase "Lỗi nhập thiếu tiền khách đưa" as UC_ErrMoney

UC_Retail ..> UC_CheckMember : <<include>>
UC_Guest ..> UC_CheckMember : <<extend>>
UC_RemoveItem ..> UC_Retail : <<extend>>
UC_ErrMoney ..> UC_Retail : <<extend>>
@enduml
