' ==========================================
' 2.3.14. Cập nhật trạng thái đơn
' ==========================================
@startuml 14_CapNhatTrangThaiDon
left to right direction
skinparam shadowing false

usecase "Cập nhật trạng thái đơn" as UC_UpdateStatus
usecase "Chuyển trạng thái: Đang làm" as UC_StsDoing
usecase "Chuyển trạng thái: Chờ giao" as UC_StsWait
usecase "Chuyển trạng thái: Hoàn thành" as UC_StsDone
usecase "Cảnh báo vi phạm (Chuyển tắt trạng thái)" as UC_ErrSkip

UC_StsDoing --|> UC_UpdateStatus
UC_StsWait --|> UC_UpdateStatus
UC_StsDone --|> UC_UpdateStatus

UC_ErrSkip ..> UC_UpdateStatus : <<extend>>
@enduml
