' ==========================================
' 2.3.15. Tra cứu danh sách đơn
' ==========================================
@startuml 15_TraCuuDanhSachDon
left to right direction
skinparam shadowing false

usecase "Tra cứu danh sách đơn" as UC_SearchOrder
usecase "Xóa trắng các bộ lọc" as UC_ClearFilter
usecase "Thông báo không tìm thấy kết quả" as UC_ErrNotFound

UC_ClearFilter ..> UC_SearchOrder : <<extend>>
UC_ErrNotFound ..> UC_SearchOrder : <<extend>>
@enduml
