' ==========================================
' 2.3.16. Hủy đơn và hoàn cọc
' ==========================================
@startuml 16_HuyDonVaHoanCoc
left to right direction
skinparam shadowing false

usecase "Hủy đơn và hoàn cọc" as UC_CancelOrder
usecase "Khách hàng đổi ý (Không hủy nữa)" as UC_Abort
usecase "Chặn hủy (Bánh đã làm xong / Chờ giao)" as UC_ErrDone

UC_Abort ..> UC_CancelOrder : <<extend>>
UC_ErrDone ..> UC_CancelOrder : <<extend>>
@enduml
