' ==========================================
' 2.3.18. Thêm/Xóa/Sửa sản phẩm
' ==========================================
@startuml 18_ThemXoaSuaSanPham
left to right direction
skinparam shadowing false

usecase "Quản lý sản phẩm" as UC_ManageProd
usecase "Thêm mới sản phẩm" as UC_AddProd
usecase "Chỉnh sửa sản phẩm" as UC_EditProd
usecase "Ngừng bán sản phẩm" as UC_StopProd

usecase "Lỗi giá bán âm hoặc bằng không" as UC_ErrPrice
usecase "Cảnh báo (Sản phẩm đang nằm trong đơn chờ)" as UC_WarnOrder

UC_AddProd --|> UC_ManageProd
UC_EditProd --|> UC_ManageProd
UC_StopProd --|> UC_ManageProd

UC_ErrPrice ..> UC_ManageProd : <<extend>>
UC_WarnOrder ..> UC_StopProd : <<extend>>
@enduml
