' ==========================================
' 2.3.20. Thêm/Xóa/Sửa công thức
' ==========================================
@startuml 20_ThemXoaSuaCongThuc
left to right direction
skinparam shadowing false

usecase "Quản lý công thức" as UC_ManageRecipe
usecase "Thêm công thức" as UC_AddRecipe
usecase "Sửa công thức" as UC_EditRecipe
usecase "Xóa công thức" as UC_DelRecipe

usecase "Hủy bỏ lưu" as UC_Cancel
usecase "Lỗi định lượng âm hoặc bằng không" as UC_ErrQty
usecase "Lỗi trùng lặp bánh đã có công thức" as UC_ErrDup

UC_AddRecipe --|> UC_ManageRecipe
UC_EditRecipe --|> UC_ManageRecipe
UC_DelRecipe --|> UC_ManageRecipe

UC_Cancel ..> UC_ManageRecipe : <<extend>>
UC_ErrQty ..> UC_ManageRecipe : <<extend>>
UC_ErrDup ..> UC_AddRecipe : <<extend>>
@enduml
