' ==========================================
' 2.3.21. Tra cứu công thức
' ==========================================
@startuml 21_TraCuuCongThuc
left to right direction
skinparam shadowing false

usecase "Tra cứu công thức" as UC_SearchRecipe
usecase "Xóa trắng từ khóa tìm kiếm" as UC_Clear
usecase "Thông báo không tìm thấy kết quả" as UC_ErrNotFound

UC_Clear ..> UC_SearchRecipe : <<extend>>
UC_ErrNotFound ..> UC_SearchRecipe : <<extend>>
@enduml
