' ==========================================
' 2.3.22. Tính toán số lượng bánh làm ra
' ==========================================
@startuml 22_TinhToanSoLuongBanhLamRa
left to right direction
skinparam shadowing false

usecase "Tính toán số lượng bánh làm ra" as UC_Calc
usecase "Dừng tính toán (Phát hiện vật tư tồn bằng 0)" as UC_ErrZeroStock

UC_ErrZeroStock ..> UC_Calc : <<extend>>
@enduml
