' ==========================================
' 2.3.23. Cấu hình giới hạn nhận đơn
' ==========================================
@startuml 23_CauHinhGioiHanNhanDon
left to right direction
skinparam shadowing false

usecase "Cấu hình giới hạn nhận đơn" as UC_LimitConfig
usecase "Hủy bỏ cài đặt" as UC_Cancel
usecase "Báo lỗi điền số âm" as UC_ErrNegative
usecase "Từ chối hạ mức (Nhỏ hơn số đơn đã lỡ nhận)" as UC_ErrLower

UC_Cancel ..> UC_LimitConfig : <<extend>>
UC_ErrNegative ..> UC_LimitConfig : <<extend>>
UC_ErrLower ..> UC_LimitConfig : <<extend>>
@enduml
