' ==========================================
' 2.3.29. Tra cứu thẻ kho
' ==========================================
@startuml 29_TraCuuTheKho
left to right direction
skinparam shadowing false

usecase "Tra cứu thẻ kho" as UC_Card
usecase "Xuất báo cáo dạng bảng tính" as UC_Export
usecase "Báo lỗi chọn khoảng thời gian không hợp lệ" as UC_ErrDate

UC_Export ..> UC_Card : <<extend>>
UC_ErrDate ..> UC_Card : <<extend>>
@enduml
