' ==========================================
' 2.3.30. Truy vết nguồn gốc
' ==========================================
@startuml 30_TruyVetNguonGoc
left to right direction
skinparam shadowing false

usecase "Truy vết nguồn gốc" as UC_Trace
usecase "Báo lỗi không tìm thấy dữ liệu chứng từ" as UC_ErrNotFound

UC_ErrNotFound ..> UC_Trace : <<extend>>
@enduml
