' ==========================================
' 2.3.32. Tra cứu nhà cung cấp
' ==========================================
@startuml 32_TraCuuNhaCungCap
left to right direction
skinparam shadowing false

usecase "Tra cứu nhà cung cấp" as UC_SearchSup
usecase "Xóa trắng từ khóa (Tải lại ban đầu)" as UC_Clear
usecase "Thông báo không tìm thấy đối tác" as UC_ErrNotFound

UC_Clear ..> UC_SearchSup : <<extend>>
UC_ErrNotFound ..> UC_SearchSup : <<extend>>
@enduml
