' ==========================================
' 2.3.33. Báo cáo lợi nhuận
' ==========================================
@startuml 33_BaoCaoLoiNhuan
left to right direction
skinparam shadowing false

usecase "Báo cáo lợi nhuận" as UC_RepProfit
usecase "Kết xuất báo cáo tải về máy" as UC_Export
usecase "Thông báo không có dữ liệu để tính toán" as UC_ErrNoData

UC_Export ..> UC_RepProfit : <<extend>>
UC_ErrNoData ..> UC_RepProfit : <<extend>>
@enduml
