@startuml Package4_BOH
left to right direction
skinparam packageStyle rectangle
skinparam DefaultFontSize 14

actor "Thợ bánh" as Baker
actor "Quản lý" as Manager

Manager --|> Baker

rectangle "HỆ THỐNG QUẢN LÝ TIỆM BÁNH" {
    package "IV. Khối Hậu sảnh & Sản xuất" {
        usecase "Tra cứu công thức" as UC_Recipe
        usecase "Cập nhật công thức" as UC_UdtRecipe
        usecase "Thêm công thức" as UC_AddRecipe
        usecase "Xóa công thức" as UC_DelRecipe
        usecase "Sửa công thức" as UC_EditRecipe
        usecase "Thống kê nguyên liệu" as UC_Material
        usecase "Cập nhật nguyên liệu" as UC_UdtMaterial
        usecase "Quy đổi đơn vị tính" as UC_Conversion
        usecase "Quản lý mức độ ưu tiên" as UC_Priority
        usecase "Hiển thị thời gian chờ" as UC_TimeWaiting
        usecase "Danh sách đơn (Hàng đợi)" as UC_Queue
        usecase "Trạng thái món" as UC_ProductStatus
        usecase "Trạng thái đơn hàng" as UC_OrderStatus
        usecase "Hoàn thành" as UC_Done
        usecase "Đang xử lý" as UC_InProgress
        usecase "Chưa xử lý" as UC_None
        usecase "Lỗi" as UC_Fail
        usecase "Báo cáo rủi ro" as UC_Caution
        usecase "Ghi nhận chi tiết lỗi" as UC_FailureDetail
        usecase "Trừ hao năng lực sản xuất" as UC_Estimate

        UC_Recipe ..> UC_UdtRecipe : <<include>>
        UC_UdtRecipe <|-- UC_AddRecipe
        UC_UdtRecipe <|-- UC_DelRecipe
        UC_UdtRecipe <|-- UC_EditRecipe
        UC_Material ..> UC_UdtMaterial : <<include>>
        UC_Recipe ..> UC_Conversion : <<extend>>
        UC_Material ..> UC_Conversion : <<extend>>

        UC_Queue ..> UC_TimeWaiting : <<extend>>
        UC_Queue ..> UC_Priority : <<extend>>
        UC_OrderStatus ..> UC_ProductStatus : <<include>>
        UC_Fail ..> UC_Caution : <<include>>
        UC_Caution ..> UC_FailureDetail : <<include>>
        UC_FailureDetail ..> UC_Estimate : <<extend>>
        UC_OrderStatus <|-- UC_Done
        UC_OrderStatus <|-- UC_None
        UC_OrderStatus <|-- UC_InProgress
        UC_OrderStatus <|-- UC_Fail
    }
}

Baker --> UC_Queue
Baker --> UC_Recipe
Baker --> UC_OrderStatus
Baker --> UC_Caution
@enduml