@startuml Package3_CRM
left to right direction
skinparam packageStyle rectangle
skinparam DefaultFontSize 14

actor "Thu ngân" as Cashier
actor "Quản lý" as Manager

Manager --|> Cashier

rectangle "HỆ THỐNG QUẢN LÝ TIỆM BÁNH" {
    package "III. Khối Quản trị Khách hàng" {
        usecase "Tạo hồ sơ khách hàng" as UC_Customer
        usecase "Tra cứu thông tin" as UC_SearchCus
        usecase "Cập nhật thông tin" as UC_CusInfo
        usecase "Lập bản đồ sự kiện" as UC_EventMapping
        usecase "Tra cứu lịch sử mua hàng" as UC_PurchaseHistory
        usecase "Thông báo sự kiện sắp tới" as UC_Announcement
        usecase "Tạo danh sách cần liên hệ" as UC_TaskGeneration
        usecase "Cấu hình tích điểm" as UC_Regulation
        usecase "Nâng hạng thành viên" as UC_Ranking
        usecase "Quy đổi điểm" as UC_Redemption
        usecase "Thu thập hành vi mua" as UC_Behavior

        UC_SearchCus ..> UC_CusInfo : <<include>>
        UC_Announcement ..> UC_EventMapping : <<include>>
        UC_TaskGeneration ..> UC_EventMapping : <<include>>
        UC_EventMapping ..> UC_CusInfo : <<include>>
        UC_Customer ..> UC_SearchCus : <<include>>
        UC_Customer ..> UC_TaskGeneration : <<extend>>
        UC_Customer ..> UC_Announcement : <<extend>>
        UC_PurchaseHistory ..> UC_Regulation : <<extend>>
        UC_PurchaseHistory ..> UC_Redemption : <<extend>>
        UC_PurchaseHistory ..> UC_Ranking : <<extend>>
        UC_Behavior ..> UC_PurchaseHistory : <<include>>
    }
}

Cashier --> UC_Customer
Cashier --> UC_SearchCus
Cashier --> UC_Behavior

Manager --> UC_Regulation
@enduml