@startuml Package5_Inventory
left to right direction
skinparam packageStyle rectangle
skinparam DefaultFontSize 14

actor "Thủ kho" as Stocker
actor "Quản lý" as Manager

Manager --|> Stocker

rectangle "HỆ THỐNG QUẢN LÝ TIỆM BÁNH" {
    package "V. Khối Quản trị Kho" {
        usecase "Tra cứu mặt hàng" as UC_SearchStock
        usecase "Cập nhật mặt hàng" as UC_UdtStock
        usecase "Sửa mặt hàng" as UC_EditStock
        usecase "Thêm mặt hàng" as UC_AddStock
        usecase "Xóa mặt hàng" as UC_DelStock
        usecase "Cơ chế trừ kho ngầm" as UC_AutoDecrease
        usecase "Xác định mức tiêu hao" as UC_Used
        usecase "Trạng thái nguyên liệu" as UC_MaterialStatus
        usecase "Xuất kho" as UC_Export
        usecase "Thuật toán xuất kho" as UC_Release
        usecase "Truy xuất hạn sử dụng" as UC_DueDate
        usecase "Cảnh báo tồn kho" as UC_StockAlert
        usecase "Gợi ý mua hàng" as UC_BuyItem
        usecase "Luồng phê duyệt" as UC_Pending
        usecase "Nhập kho" as UC_Import
        usecase "Truy vết ngược" as UC_Traceability
        usecase "Lưu lịch sử xuất nhập" as UC_LogisticsHistory

        UC_SearchStock ..> UC_UdtStock : <<include>>
        UC_UdtStock <|-- UC_AddStock
        UC_UdtStock <|-- UC_EditStock
        UC_UdtStock <|-- UC_DelStock
        UC_AutoDecrease ..> UC_Used : <<include>>
        UC_MaterialStatus ..> UC_SearchStock : <<include>>
        UC_MaterialStatus ..> UC_AutoDecrease : <<include>>
        UC_BuyItem ..> UC_MaterialStatus : <<include>>

        UC_Export ..> UC_Release : <<include>>
        UC_Release ..> UC_DueDate : <<include>>
        UC_Release ..> UC_MaterialStatus : <<include>>
        UC_Release ..> UC_StockAlert : <<extend>>
        UC_Release ..> UC_Pending : <<include>>

        UC_Import ..> UC_BuyItem : <<extend>>

        UC_Traceability ..> UC_MaterialStatus : <<include>>
        UC_Traceability ..> UC_LogisticsHistory : <<include>>
        UC_LogisticsHistory ..> UC_Import : <<include>>
        UC_LogisticsHistory ..> UC_Export : <<include>>
    }
}

Stocker --> UC_SearchStock
Stocker --> UC_MaterialStatus
Stocker --> UC_Import
Stocker --> UC_Export
Stocker --> UC_BuyItem
Stocker --> UC_Traceability

Manager --> UC_Pending
@enduml