@startuml Package1_SystemAdmin
left to right direction
skinparam packageStyle rectangle
skinparam DefaultFontSize 14

actor "Quản trị viên" as Admin
actor "Quản lý" as Manager
actor "Nhân viên chung\n(Thu ngân, Thợ bánh, Kho)" as Staff

Admin --|> Manager
Manager --|> Staff

rectangle "HỆ THỐNG QUẢN LÝ TIỆM BÁNH" {
    package "I. Khối quản trị hệ thống" {
        usecase "Đăng nhập hệ thống" as UC_Login
        usecase "Xác thực tài khoản" as UC_Verified
        usecase "Xử lý quên mật khẩu" as UC_Forget
        usecase "Định tuyến không gian làm việc" as UC_Routing
        usecase "Đăng xuất hệ thống" as UC_Logout
        usecase "Cập nhật phiên làm việc" as UC_Session
        usecase "Phân quyền người dùng" as UC_Auth
        usecase "Kiểm soát quyền hạn" as UC_GrantPermissions
        usecase "Cập nhật nhân sự" as UC_Hire
        usecase "Thêm mới nhân sự" as UC_NewHR
        usecase "Chỉnh sửa thông tin nhân sự" as UC_ModifyHR
        usecase "Xóa nhân sự / vô hiệu hóa" as UC_DeleteHR
        usecase "Tra cứu nhân sự" as UC_SearchHR

        UC_Login ..> UC_Verified : <<extend>>
        UC_Login ..> UC_Forget : <<extend>>
        UC_Login ..> UC_Routing : <<include>>
        UC_Logout ..> UC_Session : <<include>>

        UC_Auth ..> UC_GrantPermissions : <<extend>>
        UC_SearchHR ..> UC_Hire : <<include>>
        UC_Hire <|-- UC_NewHR
        UC_Hire <|-- UC_ModifyHR
        UC_Hire <|-- UC_DeleteHR
    }
}

Staff --> UC_Login
Staff --> UC_Logout
Admin --> UC_Auth
Admin --> UC_SearchHR
@enduml