@startuml Package6_Dashboard
left to right direction
skinparam packageStyle rectangle
skinparam DefaultFontSize 14

actor "Quản lý" as Manager

rectangle "HỆ THỐNG QUẢN LÝ TIỆM BÁNH" {
    package "VI. Khối Báo cáo Dashboard" {
        usecase "Thao tác thời gian thực" as UC_RealTime
        usecase "Tính toán lợi nhuận gộp" as UC_Profit
        usecase "Doanh thu" as UC_KPI
        usecase "Chi phí nhập kho" as UC_ImportCost
        usecase "Chi phí phát sinh khác" as UC_OtherCost
        usecase "Phân tích xu hướng" as UC_Trending
        usecase "Tính toán dữ liệu hao hụt" as UC_Lost
        usecase "Mức độ dịch vụ" as UC_ServiceRate

        UC_Profit <|-- UC_KPI 
        UC_Profit <|-- UC_ImportCost
        UC_Profit <|-- UC_OtherCost
    }
}

Manager --> UC_RealTime
Manager --> UC_Profit
Manager --> UC_Trending
Manager --> UC_ServiceRate
Manager --> UC_Lost
@enduml