------------------------------------------------
-- I. NHÂN SỰ & KHÁCH HÀNG
------------------------------------------------
CREATE TABLE VAITRO (
    MaVaiTro NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenVaiTro NVARCHAR2(100) UNIQUE NOT NULL,
    MoTa NVARCHAR2(255),
    IsDeleted NUMBER(1) DEFAULT 0
);

CREATE TABLE CHUCNANG (
    MaChucNang NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenChucNang NVARCHAR2(150) NOT NULL,
    MoTa NVARCHAR2(255)
);

CREATE TABLE VAITRO_CHUCNANG (
    MaVaiTro NUMBER NOT NULL,
    MaChucNang NUMBER NOT NULL,
    CONSTRAINT PK_VAITRO_CHUCNANG PRIMARY KEY (MaVaiTro, MaChucNang),
    CONSTRAINT FK_VTCN_VT FOREIGN KEY (MaVaiTro) REFERENCES VAITRO(MaVaiTro),
    CONSTRAINT FK_VTCN_CN FOREIGN KEY (MaChucNang) REFERENCES CHUCNANG(MaChucNang)
);



CREATE TABLE NHANVIEN (
    MaNV NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaVaiTro NUMBER NOT NULL,
    HoTen NVARCHAR2(150) NOT NULL,
    NgaySinh DATE,
    SDT VARCHAR2(15),
    Username VARCHAR2(50) UNIQUE NOT NULL,
    Password VARCHAR2(255) NOT NULL,
    TrangThaiLamViec NUMBER(1) DEFAULT 1,
    CONSTRAINT FK_NV_VAITRO FOREIGN KEY (MaVaiTro) REFERENCES VAITRO(MaVaiTro)
);

CREATE TABLE HANGTHANHVIEN (
    MaHang NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenHang NVARCHAR2(100) NOT NULL,
    DiemToiThieu NUMBER NOT NULL,
    PhanTramGiamGia NUMBER(5,2) DEFAULT 0,
    IsDeleted NUMBER(1) DEFAULT 0
);

CREATE TABLE KHACHHANG (
    MaKH NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    HoTen NVARCHAR2(150) NOT NULL,
    SDT VARCHAR2(15) UNIQUE NOT NULL,
    --Email
    DiaChi NVARCHAR2(255),
    NgayDangKy DATE DEFAULT SYSDATE,
    DiemTichLuy NUMBER DEFAULT 0,
    MaHang NUMBER,
    IsDeleted NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_KH_HANG FOREIGN KEY (MaHang) REFERENCES HANGTHANHVIEN(MaHang)
);

------------------------------------------------
-- II. SẢN PHẨM & CUSTOM
------------------------------------------------

CREATE TABLE DANHMUCSP (
    MaDM NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenDM NVARCHAR2(150) NOT NULL,
    IsDeleted NUMBER(1) DEFAULT 0
);

CREATE TABLE SANPHAM (
    MaSP NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaDM NUMBER NOT NULL,
    TenSP NVARCHAR2(150) NOT NULL,
    GiaCoBan NUMBER(18,2) NOT NULL,
    HinhAnh NVARCHAR2(255),
    ChoPhepCustom NUMBER(1) DEFAULT 0,
    IsDeleted NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_SP_DM FOREIGN KEY (MaDM) REFERENCES DANHMUCSP(MaDM)
);

CREATE TABLE KICHCOBANH (
    MaSize NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenSize NVARCHAR2(50) NOT NULL,
    PhuPhi NUMBER(18,2) DEFAULT 0
);

CREATE TABLE COTBANH (
    MaCot NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenCot NVARCHAR2(100) NOT NULL,
    PhuPhi NUMBER(18,2) DEFAULT 0
);

CREATE TABLE NHANBANH (
    MaNhan NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenNhan NVARCHAR2(100) NOT NULL,
    PhuPhi NUMBER(18,2) DEFAULT 0
);

CREATE TABLE KIEUTRANGTRI (
    MaTrangTri NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenTrangTri NVARCHAR2(150) NOT NULL,
    PhuPhi NUMBER(18,2) DEFAULT 0
);

------------------------------------------------
-- III. KHO & CÔNG THỨC
------------------------------------------------

CREATE TABLE DONVITINH (
    MaDVT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenDVT NVARCHAR2(50) NOT NULL
);

CREATE TABLE NGUYENLIEU (
    MaNL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenNL NVARCHAR2(150) NOT NULL,
    MaDVT NUMBER NOT NULL,
    XuatXu VARCHAR2(50),
    DatChuanVSATTP NUMBER(1) DEFAULT 1,
    MucTonAnToan NUMBER(18,2) DEFAULT 0,
    SoLuongTonTong NUMBER(18,2) DEFAULT 0,
    IsDeleted NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_NL_DVT FOREIGN KEY (MaDVT) REFERENCES DONVITINH(MaDVT)
);


CREATE TABLE CONGTHUC (
    MaSP NUMBER NOT NULL,
    MaNL NUMBER NOT NULL,
    SoLuongTieuHao NUMBER(18,2) NOT NULL,
    CONSTRAINT PK_CONGTHUC PRIMARY KEY (MaSP, MaNL),
    CONSTRAINT FK_CT_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP),
    CONSTRAINT FK_CT_NL FOREIGN KEY (MaNL) REFERENCES NGUYENLIEU(MaNL)
);

CREATE TABLE NHACUNGCAP (
    MaNCC NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenNCC NVARCHAR2(150) NOT NULL,
    SDT VARCHAR2(15),
    DiaChi NVARCHAR2(255),
    IsDeleted NUMBER(1) DEFAULT 0
);

CREATE TABLE PHIEUNHAPKHO (
    MaPN NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NgayNhap DATE DEFAULT SYSDATE,
    MaNV NUMBER NOT NULL,
    MaNCC NUMBER NOT NULL,
    TongTienNhap NUMBER(18,2) DEFAULT 0,
    CONSTRAINT FK_PN_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_PN_NCC FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)
);

CREATE TABLE CTPHIEUNHAP (
    MaPN NUMBER NOT NULL,
    MaNL NUMBER NOT NULL,
    SoLuongNhap NUMBER(18,2) NOT NULL,
    DonGiaNhap NUMBER(18,2) NOT NULL,
    NgayNhapKho DATE NOT NULL ,
    HanSuDung DATE,
    SoLuongConLai NUMBER(18,2) NOT NULL,
    CONSTRAINT PK_CTPN PRIMARY KEY (MaPN, MaNL),
    CONSTRAINT FK_CTPN_PN FOREIGN KEY (MaPN) REFERENCES PHIEUNHAPKHO(MaPN),
    CONSTRAINT FK_CTPN_NL FOREIGN KEY (MaNL) REFERENCES NGUYENLIEU(MaNL)
);

------------------------------------------------
-- IV. ĐƠN HÀNG
------------------------------------------------

CREATE TABLE TRANGTHAIDON (
    MaTrangThai NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenTrangThai NVARCHAR2(100) NOT NULL
);

CREATE TABLE DONDATHANG (
    MaDon NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NgayLap DATE DEFAULT SYSDATE,
    NgayGioNhanBanh DATE,
    MaKH NUMBER NOT NULL,
    MaNV_Lap NUMBER NOT NULL,
    MaTrangThai NUMBER NOT NULL,
    TongTienHDBan NUMBER(18,2) DEFAULT 0,
    TienDaCoc NUMBER(18,2) DEFAULT 0,
    CONSTRAINT FK_DON_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    CONSTRAINT FK_DON_NV FOREIGN KEY (MaNV_Lap) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_DON_TT FOREIGN KEY (MaTrangThai) REFERENCES TRANGTHAIDON(MaTrangThai)
);

CREATE TABLE CTDONHANG (
    MaCTDH NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaDon NUMBER NOT NULL,
    MaSP NUMBER NOT NULL,
    SoLuong NUMBER NOT NULL,
    DonGia NUMBER(18,2) NOT NULL,
    GiaVonDong NUMBER(18,2) NOT NULL,
    PhanTramGiam NUMBER(5,2) DEFAULT 0,
    CONSTRAINT FK_CTDH_DON FOREIGN KEY (MaDon) REFERENCES DONDATHANG(MaDon),
    CONSTRAINT FK_CTDH_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE CTDONCUSTOM (
    MaCTCustom NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaDon NUMBER NOT NULL,
    MaSP NUMBER NOT NULL,
    SoLuong NUMBER NOT NULL,
    MaSize NUMBER,
    MaCot NUMBER,
    GiaVonDong NUMBER(18,2) NOT NULL,
    MaNhan NUMBER,
    MaTrangTri NUMBER,
    LoiChucTrenBanh NVARCHAR2(255),
    GhiChuThoBanh NVARCHAR2(255),
    DonGia NUMBER(18,2) NOT NULL,
    CONSTRAINT FK_CTDC_DON FOREIGN KEY (MaDon) REFERENCES DONDATHANG(MaDon),
    CONSTRAINT FK_CTDC_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP),
    CONSTRAINT FK_CTDC_SIZE FOREIGN KEY (MaSize) REFERENCES KICHCOBANH(MaSize),
    CONSTRAINT FK_CTDC_COT FOREIGN KEY (MaCot) REFERENCES COTBANH(MaCot),
    CONSTRAINT FK_CTDC_NHAN FOREIGN KEY (MaNhan) REFERENCES NHANBANH(MaNhan),
    CONSTRAINT FK_CTDC_TT FOREIGN KEY (MaTrangTri) REFERENCES KIEUTRANGTRI(MaTrangTri)
);

CREATE TABLE LICHSUDONHANG (
    MaLog NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaDon NUMBER NOT NULL,
    MaTrangThai_Cu NUMBER,
    MaTrangThai_Moi NUMBER,
    ThoiGianThayDoi DATE DEFAULT SYSDATE,
    MaNV_CapNhat NUMBER,
    CONSTRAINT FK_LS_DON FOREIGN KEY (MaDon) REFERENCES DONDATHANG(MaDon),
    CONSTRAINT FK_LS_TT_CU FOREIGN KEY (MaTrangThai_Cu) REFERENCES TRANGTHAIDON(MaTrangThai),
    CONSTRAINT FK_LS_TT_MOI FOREIGN KEY (MaTrangThai_Moi) REFERENCES TRANGTHAIDON(MaTrangThai),
    CONSTRAINT FK_LS_NV FOREIGN KEY (MaNV_CapNhat) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE NANGLUCSANXUAT (
    NgaySanXuat DATE PRIMARY KEY,
    GioiHanSoBanh NUMBER NOT NULL,
    SoBanhDaNhan NUMBER DEFAULT 0
);

------------------------------------------------
-- V. TÀI CHÍNH
------------------------------------------------

CREATE TABLE PHUONGTHUCTT (
    MaPTTT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenPTTT NVARCHAR2(100) NOT NULL
);

CREATE TABLE HOADON (
    MaHD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaDon NUMBER NOT NULL,
    NgayXuatHD DATE DEFAULT SYSDATE,
    ThueVAT NUMBER(5,2) DEFAULT 0,
    TongTienTruocThue NUMBER(18,2) NOT NULL,
    TongTienThanhToan NUMBER(18,2) NOT NULL,
    MaPTTT NUMBER NOT NULL,
    LoaiHD NVARCHAR2(50),
    CONSTRAINT FK_HD_DON FOREIGN KEY (MaDon) REFERENCES DONDATHANG(MaDon),
    CONSTRAINT FK_HD_PTTT FOREIGN KEY (MaPTTT) REFERENCES PHUONGTHUCTT(MaPTTT)
);

CREATE TABLE LOAITHUCHI (
    MaLoaiThuChi NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenLoaiThuChi NVARCHAR2(150) NOT NULL,
    PhanLoai VARCHAR2(10) CHECK (PhanLoai IN ('IN','OUT'))
);

CREATE TABLE PHIEUTHUCHI (
    MaPhieuTC NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NgayTao DATE DEFAULT SYSDATE,
    MaLoaiThuChi NUMBER NOT NULL,
    SoTien NUMBER(18,2) NOT NULL,
    MaNV NUMBER NOT NULL,
    MaHD NUMBER,
    MaPN NUMBER,
    GhiChu NVARCHAR2(255),
    CONSTRAINT FK_TC_LOAI FOREIGN KEY (MaLoaiThuChi) REFERENCES LOAITHUCHI(MaLoaiThuChi),
    CONSTRAINT FK_TC_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_TC_HD FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
    CONSTRAINT FK_TC_PN FOREIGN KEY (MaPN) REFERENCES PHIEUNHAPKHO(MaPN)
);

