-- Seed du lieu POS cho man hinh Tao don + Thanh toan
-- Chay sau khi da tao schema bang/constraint

-- 1) Danh muc san pham
INSERT INTO DANHMUCSP (TENDM)
SELECT N'Cake' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DANHMUCSP WHERE UPPER(TENDM) = 'CAKE');

INSERT INTO DANHMUCSP (TENDM)
SELECT N'Cookie' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DANHMUCSP WHERE UPPER(TENDM) = 'COOKIE');

INSERT INTO DANHMUCSP (TENDM)
SELECT N'Bread' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DANHMUCSP WHERE UPPER(TENDM) = 'BREAD');

-- 2) Trang thai don hang
INSERT INTO TRANGTHAIDON (TENTRANGTHAI)
SELECT N'Mới đặt' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TRANGTHAIDON WHERE TENTRANGTHAI = N'Mới đặt');

INSERT INTO TRANGTHAIDON (TENTRANGTHAI)
SELECT N'Đã cọc' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TRANGTHAIDON WHERE TENTRANGTHAI = N'Đã cọc');

INSERT INTO TRANGTHAIDON (TENTRANGTHAI)
SELECT N'Đang sản xuất' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TRANGTHAIDON WHERE TENTRANGTHAI = N'Đang sản xuất');

INSERT INTO TRANGTHAIDON (TENTRANGTHAI)
SELECT N'Chờ giao' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TRANGTHAIDON WHERE TENTRANGTHAI = N'Chờ giao');

INSERT INTO TRANGTHAIDON (TENTRANGTHAI)
SELECT N'Chờ khách lấy' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TRANGTHAIDON WHERE TENTRANGTHAI = N'Chờ khách lấy');

INSERT INTO TRANGTHAIDON (TENTRANGTHAI)
SELECT N'Hoàn thành' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TRANGTHAIDON WHERE TENTRANGTHAI = N'Hoàn thành');

INSERT INTO TRANGTHAIDON (TENTRANGTHAI)
SELECT N'Hủy' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TRANGTHAIDON WHERE TENTRANGTHAI = N'Hủy');

INSERT INTO TRANGTHAIDON (TENTRANGTHAI)
SELECT N'Hoàn hàng' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TRANGTHAIDON WHERE TENTRANGTHAI = N'Hoàn hàng');

-- 3) San pham mau cho POS (10-15 item)
INSERT INTO SANPHAM (MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, SOLUONGTON, THOIGIANCHUANBI)
SELECT (SELECT MADM FROM DANHMUCSP WHERE UPPER(TENDM) = 'CAKE' FETCH FIRST 1 ROW ONLY),
       N'Bánh kem vani 16cm', 260000, '/images/products/cake_vani_16.png', 0, 48, 20, 60
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SANPHAM WHERE TENSP = N'Bánh kem vani 16cm');

INSERT INTO SANPHAM (MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, SOLUONGTON, THOIGIANCHUANBI)
SELECT (SELECT MADM FROM DANHMUCSP WHERE UPPER(TENDM) = 'CAKE' FETCH FIRST 1 ROW ONLY),
       N'Bánh kem socola 18cm', 320000, '/images/products/cake_socola_18.png', 0, 48, 18, 70
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SANPHAM WHERE TENSP = N'Bánh kem socola 18cm');

INSERT INTO SANPHAM (MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, SOLUONGTON, THOIGIANCHUANBI)
SELECT (SELECT MADM FROM DANHMUCSP WHERE UPPER(TENDM) = 'CAKE' FETCH FIRST 1 ROW ONLY),
       N'Bánh red velvet 16cm', 290000, '/images/products/cake_redvelvet_16.png', 0, 48, 12, 70
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SANPHAM WHERE TENSP = N'Bánh red velvet 16cm');

INSERT INTO SANPHAM (MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, SOLUONGTON, THOIGIANCHUANBI)
SELECT (SELECT MADM FROM DANHMUCSP WHERE UPPER(TENDM) = 'CAKE' FETCH FIRST 1 ROW ONLY),
       N'Bánh tiramisu mini', 125000, '/images/products/cake_tiramisu_mini.png', 0, 36, 25, 35
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SANPHAM WHERE TENSP = N'Bánh tiramisu mini');

INSERT INTO SANPHAM (MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, SOLUONGTON, THOIGIANCHUANBI)
SELECT (SELECT MADM FROM DANHMUCSP WHERE UPPER(TENDM) = 'CAKE' FETCH FIRST 1 ROW ONLY),
       N'Cupcake vani', 38000, '/images/products/cupcake_vani.png', 0, 24, 30, 20
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SANPHAM WHERE TENSP = N'Cupcake vani');

INSERT INTO SANPHAM (MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, SOLUONGTON, THOIGIANCHUANBI)
SELECT (SELECT MADM FROM DANHMUCSP WHERE UPPER(TENDM) = 'COOKIE' FETCH FIRST 1 ROW ONLY),
       N'Cookie bơ', 45000, '/images/products/cookie_bo.png', 0, 60, 60, 10
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SANPHAM WHERE TENSP = N'Cookie bơ');

INSERT INTO SANPHAM (MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, SOLUONGTON, THOIGIANCHUANBI)
SELECT (SELECT MADM FROM DANHMUCSP WHERE UPPER(TENDM) = 'COOKIE' FETCH FIRST 1 ROW ONLY),
       N'Cookie socola chip', 55000, '/images/products/cookie_chip.png', 0, 60, 70, 10
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SANPHAM WHERE TENSP = N'Cookie socola chip');

INSERT INTO SANPHAM (MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, SOLUONGTON, THOIGIANCHUANBI)
SELECT (SELECT MADM FROM DANHMUCSP WHERE UPPER(TENDM) = 'COOKIE' FETCH FIRST 1 ROW ONLY),
       N'Cookie matcha hạnh nhân', 62000, '/images/products/cookie_matcha_hanhnhan.png', 0, 60, 45, 12
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SANPHAM WHERE TENSP = N'Cookie matcha hạnh nhân');

INSERT INTO SANPHAM (MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, SOLUONGTON, THOIGIANCHUANBI)
SELECT (SELECT MADM FROM DANHMUCSP WHERE UPPER(TENDM) = 'COOKIE' FETCH FIRST 1 ROW ONLY),
       N'Biscotti hạnh nhân', 68000, '/images/products/biscotti_hanhnhan.png', 0, 75, 35, 15
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SANPHAM WHERE TENSP = N'Biscotti hạnh nhân');

INSERT INTO SANPHAM (MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, SOLUONGTON, THOIGIANCHUANBI)
SELECT (SELECT MADM FROM DANHMUCSP WHERE UPPER(TENDM) = 'BREAD' FETCH FIRST 1 ROW ONLY),
       N'Bánh mì bơ tỏi', 30000, '/images/products/bread_garlic.png', 0, 24, 40, 15
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SANPHAM WHERE TENSP = N'Bánh mì bơ tỏi');

INSERT INTO SANPHAM (MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, SOLUONGTON, THOIGIANCHUANBI)
SELECT (SELECT MADM FROM DANHMUCSP WHERE UPPER(TENDM) = 'BREAD' FETCH FIRST 1 ROW ONLY),
       N'Brioche mini', 32000, '/images/products/brioche_mini.png', 0, 24, 36, 20
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SANPHAM WHERE TENSP = N'Brioche mini');

INSERT INTO SANPHAM (MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, SOLUONGTON, THOIGIANCHUANBI)
SELECT (SELECT MADM FROM DANHMUCSP WHERE UPPER(TENDM) = 'BREAD' FETCH FIRST 1 ROW ONLY),
       N'Croissant bơ', 35000, '/images/products/croissant_bo.png', 0, 24, 50, 25
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SANPHAM WHERE TENSP = N'Croissant bơ');

COMMIT;
select * from SANPHAM