-- Hàm quét cảnh báo nguyên liệu chạm mức tồn kho an toàn
CREATE OR REPLACE FUNCTION FUNC_KIEMTRATONKHOTOITHIEU
RETURN SYS_REFCURSOR
IS
    V_REFCURSOR SYS_REFCURSOR;
BEGIN
    OPEN V_REFCURSOR FOR
        SELECT 
            N.MANL, 
            N.TENNL, 
            N.SOLUONGTONTONG, 
            N.MUCTONANTOAN, 
            D.TENDVT
        FROM NGUYENLIEU N
        JOIN DONVITINH D ON N.MADVT = D.MADVT
        WHERE N.THOIDIEMXOA IS NULL
          AND N.SOLUONGTONTONG <= NVL(N.MUCTONANTOAN, 0)
        ORDER BY N.SOLUONGTONTONG ASC;
        
    RETURN V_REFCURSOR;
EXCEPTION
    WHEN OTHERS THEN
        OPEN V_REFCURSOR FOR SELECT -1 AS MANL, 'Lỗi' AS TENNL, 0 AS SOLUONGTONTONG, 0 AS MUCTONANTOAN, '' AS TENDVT FROM DUAL WHERE 1=0;
        RETURN V_REFCURSOR;
END;
/
