-- Trigger trừ số lượng tồn tổng của một nguyên liệu khi thực hiện việc xuất nguyên liệu để làm bánh
CREATE OR REPLACE TRIGGER TRG_XUATSLNGUYENLIEU
AFTER INSERT OR UPDATE OR DELETE ON CTPHIEUXUAT_NL
FOR EACH ROW
DECLARE
    V_MALO NUMBER;
    V_MANL NUMBER;
    V_CHENHLECH NUMBER := 0;
BEGIN
    IF INSERTING THEN
        V_CHENHLECH := :NEW.SOLUONG;
        V_MALO := :NEW.MALO;
    ELSIF UPDATING THEN
        V_CHENHLECH := :NEW.SOLUONG - :OLD.SOLUONG;
        V_MALO := :NEW.MALO;
    ELSIF DELETING THEN
        V_CHENHLECH := -(:OLD.SOLUONG);
        V_MALO := :OLD.MALO;
    END IF;

    SELECT MANL INTO V_MANL
    FROM CTPHIEUNHAP
    WHERE MALO = V_MALO;

    UPDATE CTPHIEUNHAP
    SET SOLUONGCONLAI = SOLUONGCONLAI - V_CHENHLECH
    WHERE MALO = V_MALO;

    UPDATE NGUYENLIEU
    SET SOLUONGTONTONG = SOLUONGTONTONG - V_CHENHLECH
    WHERE MANL = V_MANL;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'Loi: Khong tim thay lo hang trong kho.');
END;
/

-- Trigger cập nhật giá vốn trung bình và số lượng tồn tổng
CREATE OR REPLACE TRIGGER TRG_GIAVONTRUNGBINH_SOLUONGTONTONG
AFTER INSERT ON CTPHIEUNHAP
FOR EACH ROW
DECLARE
    V_TONCU NUMBER(10,2) := 0;
    V_GIACU NUMBER(15,2) := 0;
    V_TONGSOLUONGMOI NUMBER(10,2) := 0;
    V_GIAVONMOI NUMBER(15,2) := 0;
BEGIN
    SELECT NVL(SOLUONGTONTONG, 0), NVL(GIAVONTRUNGBINH, 0)
    INTO V_TONCU, V_GIACU
    FROM NGUYENLIEU
    WHERE MANL = :NEW.MANL;

    V_TONGSOLUONGMOI := V_TONCU + :NEW.SOLUONG;

    IF V_TONGSOLUONGMOI > 0 THEN
        V_GIAVONMOI := ((V_TONCU * V_GIACU) + (:NEW.SOLUONG * :NEW.DONGIA)) / V_TONGSOLUONGMOI;
    ELSE
        V_GIAVONMOI := V_GIACU;
    END IF;

    UPDATE NGUYENLIEU
    SET GIAVONTRUNGBINH = V_GIAVONMOI,
        SOLUONGTONTONG = V_TONGSOLUONGMOI
    WHERE MANL = :NEW.MANL;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'Loi: Khong tim thay du lieu nguyen lieu.');
END;
/

-- Trigger tính tổng tiền phiếu nhập kho
CREATE OR REPLACE TRIGGER TRG_TONGTIENNHAP
AFTER INSERT OR UPDATE OR DELETE ON CTPHIEUNHAP
FOR EACH ROW
DECLARE
    V_MAPN NUMBER;
    V_CHENHLECH NUMBER(15,2);
BEGIN
    IF INSERTING THEN
        V_CHENHLECH := :NEW.DONGIA * :NEW.SOLUONG;
        V_MAPN := :NEW.MAPN;
    ELSIF UPDATING THEN
        V_CHENHLECH := :NEW.DONGIA * :NEW.SOLUONG - :OLD.DONGIA * :OLD.SOLUONG;
        V_MAPN := :NEW.MAPN;
    ELSIF DELETING THEN
        V_CHENHLECH := -(:OLD.DONGIA * :OLD.SOLUONG);
        V_MAPN := :OLD.MAPN;
    END IF;

    UPDATE PHIEUNHAPKHO
    SET TONGTIENNHAP = NVL(TONGTIENNHAP, 0) + V_CHENHLECH
    WHERE MAPN = V_MAPN;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'Loi: Khong tim thay du lieu phieu nhap.');
END;
/

-- Trigger kiểm tra vệ sinh an toàn thực phẩm
CREATE OR REPLACE TRIGGER TRG_KIEMTRAVSATTP
BEFORE INSERT OR UPDATE ON NGUYENLIEU
FOR EACH ROW
BEGIN
    IF :NEW.DATCHUANVSATTP = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'NGUYEN_LIEU_KHONG_DAT_CHUAN: Nguyen lieu khong dat chuan, cam nhap kho');
    END IF;
END;
/

-- Trigger chặn hạn sử dụng chỉ còn 10 ngày kể từ lúc nhập & chống gian lận hạn sử dụng
CREATE OR REPLACE TRIGGER TRG_KIEMTRA_HSD
BEFORE INSERT OR UPDATE OF HANSUDUNG ON CTPHIEUNHAP
FOR EACH ROW
DECLARE
    V_NGAYNHAP DATE;
BEGIN
    -- Chống gian lận hạn sử dụng
    IF UPDATING THEN
        IF :NEW.HANSUDUNG > :OLD.HANSUDUNG THEN
            RAISE_APPLICATION_ERROR(-20002,
                'CANH BAO GIAN LAN: Han su dung moi (' || TO_CHAR(:NEW.HANSUDUNG, 'DD/MM/YYYY') ||
                ') khong duoc phep lon hon han su dung cu (' || TO_CHAR(:OLD.HANSUDUNG, 'DD/MM/YYYY') || ').');
        END IF;
    END IF;

    -- Chặn hạn sử dụng chỉ còn 10 ngày kể từ lúc nhập
    SELECT NGAYNHAP INTO V_NGAYNHAP
    FROM PHIEUNHAPKHO
    WHERE MAPN = :NEW.MAPN;

    IF TRUNC(:NEW.HANSUDUNG) <= TRUNC(V_NGAYNHAP) THEN
        RAISE_APPLICATION_ERROR(-20003,
            'LOI NGHIEP VU: Han su dung cua lo nay (' || TO_CHAR(:NEW.HANSUDUNG, 'DD/MM/YYYY') ||
            ') va ngay nhap kho (' || TO_CHAR(V_NGAYNHAP, 'DD/MM/YYYY') || ') da qua han!.');
    END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20004, 'Loi: Khong tim thay phieu nhap kho.');
END;
/

-- Trigger trừ số lượng bánh khi hủy bánh đã hết hạn, không còn bán
CREATE OR REPLACE TRIGGER TRG_TRUKHO_PHIEUXUATTP
AFTER INSERT OR UPDATE OR DELETE ON CTPHIEUXUAT_TP
FOR EACH ROW
DECLARE
    V_MASP NUMBER;
    V_CHENHLECH NUMBER(10,2) := 0;
    V_SOLUONGTON NUMBER(10,2) := 0;
BEGIN
    IF INSERTING THEN
        V_CHENHLECH := :NEW.SOLUONG;
        V_MASP := :NEW.MASP;
    ELSIF UPDATING THEN
        V_CHENHLECH := :NEW.SOLUONG - :OLD.SOLUONG;
        V_MASP := :NEW.MASP;
    ELSIF DELETING THEN
        V_CHENHLECH := -(:OLD.SOLUONG);
        V_MASP := :OLD.MASP;
    END IF;

    UPDATE SANPHAM
    SET SOLUONGTON = SOLUONGTON - V_CHENHLECH
    WHERE MASP = V_MASP;

    SELECT SOLUONGTON INTO V_SOLUONGTON
    FROM SANPHAM
    WHERE MASP = V_MASP;

    IF V_SOLUONGTON < 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'So luong banh da het!');
    END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20003, 'Loi: Khong tim thay san pham.');
END;
/
