-- Trigger cập nhật giá vốn trung bình và số lượng tồn tổng
CREATE OR REPLACE TRIGGER TRG_GIAVONTRUNGBINH_UPDATE
AFTER INSERT ON CTPHIEUNHAP
FOR EACH ROW
DECLARE
    V_TONCU NUMBER(10,2) := 0;
    V_GIACU NUMBER(15,2) := 0;
    V_TONGSOLUONGMOI NUMBER(10,2) := 0;
    V_GIAVONMOI NUMBER(15,2) := 0;
BEGIN
    SELECT NVL(SOLUONGTONTONG, 0), NVL(GIAVONTRUNGBINH, 0)
    INTO V_TONCU, V_GIACU
    FROM NGUYENLIEU
    WHERE MANL = :NEW.MANL;

    V_TONGSOLUONGMOI := V_TONCU + :NEW.SOLUONG;

    IF V_TONGSOLUONGMOI > 0 THEN
        V_GIAVONMOI := ((V_TONCU * V_GIACU) + (:NEW.SOLUONG * :NEW.DONGIA)) / V_TONGSOLUONGMOI;
    ELSE
        V_GIAVONMOI := V_GIACU;
    END IF;

    UPDATE NGUYENLIEU
    SET GIAVONTRUNGBINH = V_GIAVONMOI,
        SOLUONGTONTONG = V_TONGSOLUONGMOI
    WHERE MANL = :NEW.MANL;

EXCEPTION
    WHEN NO_DATA_FOUND THEN DBMS_OUTPUT.PUT_LINE('Lỗi: Không tìm thấy dữ liệu nguyên liệu.');
END;
/

-- Trigger trừ số lượng tồn tổng của một nguyên liệu khi thực hiện việc xuất nguyên liệu để làm bánh
CREATE OR REPLACE TRIGGER TRG_XUATSLNGUYENLIEU_UPDATE
AFTER INSERT OR UPDATE OR DELETE ON CTPHIEUXUAT_NL
FOR EACH ROW
DECLARE
    V_MALO NUMBER;
    V_MANL NUMBER;
    V_CHENHLECH NUMBER := 0;
BEGIN
    IF INSERTING THEN
        V_CHENHLECH := :NEW.SOLUONG;
        V_MALO := :NEW.MALO;
    ELSIF UPDATING THEN
        V_CHENHLECH := :NEW.SOLUONG - :OLD.SOLUONG;
        V_MALO := :NEW.MALO;
    ELSIF DELETING THEN
        V_CHENHLECH := -(:OLD.SOLUONG);
        V_MALO := :OLD.MALO;
    END IF;

    SELECT MANL INTO V_MANL
    FROM CTPHIEUNHAP
    WHERE MALO = V_MALO;

    UPDATE CTPHIEUNHAP
    SET SOLUONGCONLAI = SOLUONGCONLAI - V_CHENHLECH
    WHERE MALO = V_MALO;

    UPDATE NGUYENLIEU
    SET SOLUONGTONTONG = SOLUONGTONTONG - V_CHENHLECH
    WHERE MANL = V_MANL;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'Lỗi: Không tìm thấy lô hàng này trong kho!');
END;

-- Trigger kiểm tra vệ sinh an toa thực phẩm
CREATE OR REPLACE TRIGGER TRG_KIEMTRAVSATTP
BEFORE INSERT OR UPDATE ON NGUYENLIEU
FOR EACH ROW
BEGIN
    IF :NEW.DATCHUANVSATTP = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'NGUYEN_LIEU_KHONG_DAT_CHUAN: Nguyen lieu khong dat chuan, cam nhap kho');
    END IF;
END;
/

-- Trigger chống gian lận hạn sử dụng
CREATE OR REPLACE TRIGGER TRG_CHONGGIANLANHSD
AFTER UPDATE OF HANSUDUNG ON CTPHIEUNHAP
FOR EACH ROW
BEGIN
    IF :NEW.HANSUDUNG > :OLD.HANSUDUNG THEN
        RAISE_APPLICATION_ERROR(-20002,
            'CANH_BAO_GIAN_LAN: Han su dung moi (' || TO_CHAR(:NEW.HANSUDUNG, 'DD/MM/YYYY') ||
            ') khong duoc phep muon hon han cu (' || TO_CHAR(:OLD.HANSUDUNG, 'DD/MM/YYYY') || ').');
    END IF;
END;
/