-- Trigger cộng trừ tiền khi có thay đổi hóa đơn (insert, update, delete)
CREATE OR REPLACE TRIGGER TRG_CTDONHANG_UPDATE
AFTER INSERT OR UPDATE OR DELETE ON CTDONHANG
FOR EACH ROW
DECLARE
    V_CHENHLECH NUMBER := 0;
    V_MADON NUMBER;
BEGIN
    IF INSERTING THEN
        V_CHENHLECH := :NEW.SOLUONG * :NEW.DONGIA;
        V_MADON := :NEW.MADON;
    ELSIF UPDATING THEN
        V_CHENHLECH := (:NEW.SOLUONG * :NEW.DONGIA) - (:OLD.SOLUONG * :OLD.DONGIA);
        V_MADON := :NEW.MADON;
    ELSIF DELETING THEN
        V_CHENHLECH := -(:OLD.SOLUONG * :OLD.DONGIA);
        V_MADON := :OLD.MADON;
    END IF;

    UPDATE DONDATHANG
    SET TONGTIENHDBAN = NVL(TONGTIENHDBAN, 0) + V_CHENHLECH
    WHERE MADON = V_MADON;
END;
/

-- Trigger trừ số lượng bánh khi bán, cộng số lượng khi hoàn đơn
CREATE OR REPLACE TRIGGER TRG_TRUKHO_DONHANG
AFTER INSERT OR UPDATE OR DELETE ON CTDONHANG
FOR EACH ROW
DECLARE
    V_MASP NUMBER;
    V_CHENHLECH NUMBER(10,2) := 0;
    V_SOLUONGTON NUMBER(10,2) := 0;
BEGIN
    IF INSERTING THEN
        V_CHENHLECH := :NEW.SOLUONG;
        V_MASP := :NEW.MASP;
    ELSIF UPDATING THEN
        V_CHENHLECH := :NEW.SOLUONG - :OLD.SOLUONG;
        V_MASP := :NEW.MASP;
    ELSIF DELETING THEN
        V_CHENHLECH := -(:OLD.SOLUONG);
        V_MASP := :OLD.MASP;
    END IF;

    UPDATE SANPHAM
    SET SOLUONGTON = SOLUONGTON - V_CHENHLECH
    WHERE MASP = V_MASP;

    SELECT SOLUONGTON INTO V_SOLUONGTON
    FROM SANPHAM
    WHERE MASP = V_MASP;

    IF V_SOLUONGTON < 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'So luong banh da het!');
    END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20003, 'Loi: Khong tim thay san pham.');
END;
/

-- Trigger cộng dồn số bánh khách đặt (đơn hàng)
CREATE OR REPLACE TRIGGER TRG_KIEMSOAT_CONGSUAT_DONHANG
AFTER INSERT OR UPDATE OR DELETE ON CTDONHANG
FOR EACH ROW
DECLARE
    V_MADON NUMBER;
    V_CHENHLECH NUMBER(10,2) := 0;
    V_NGAYGIAO DATE;
    V_SOBANH_HIENTAI NUMBER;
    V_GIOIHAN NUMBER;
BEGIN
    IF INSERTING THEN
        V_CHENHLECH := :NEW.SOLUONG;
        V_MADON := :NEW.MADON;
    ELSIF UPDATING THEN
        V_CHENHLECH := :NEW.SOLUONG - :OLD.SOLUONG;
        V_MADON := :NEW.MADON;
    ELSIF DELETING THEN
        V_CHENHLECH := -(:OLD.SOLUONG);
        V_MADON := :OLD.MADON;
    END IF;

    SELECT TRUNC(NGAYGIONHANBANH) INTO V_NGAYGIAO
    FROM DONDATHANG
    WHERE MADON = V_MADON;

    SELECT NVL(SOBANHDANHAN, 0), NVL(GIOIHANSOBANH, 0)
    INTO V_SOBANH_HIENTAI, V_GIOIHAN
    FROM NANGLUCSANXUAT
    WHERE TRUNC(NGAYSANXUAT) = V_NGAYGIAO
    FOR UPDATE;

    IF (V_SOBANH_HIENTAI + V_CHENHLECH) > V_GIOIHAN THEN
        RAISE_APPLICATION_ERROR(-20005,
            'TU CHOI NHAN DON: Ngay ' || TO_CHAR(V_NGAYGIAO, 'DD/MM/YYYY') ||
            ' xuong da dat cong suat toi da! (Da nhan: ' || V_SOBANH_HIENTAI || '/' || V_GIOIHAN || ' banh, Khach dat them: ' || V_CHENHLECH || ' banh). ' ||
            'Vui long khuyen khich khach doi sang ngay khac!');
    END IF;

    UPDATE NANGLUCSANXUAT
    SET SOBANHDANHAN = V_SOBANH_HIENTAI + V_CHENHLECH
    WHERE TRUNC(NGAYSANXUAT) = V_NGAYGIAO;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Luu y: Chua co du lieu gioi han cong suat cho ngay ' || TO_CHAR(V_NGAYGIAO, 'DD/MM/YYYY'));
END;
/

-- Trigger cộng dồn số bánh khách đặt (tùy chỉnh)
CREATE OR REPLACE TRIGGER TRG_KIEMSOAT_CONGSUAT_TUYCHINH
AFTER INSERT OR UPDATE OR DELETE ON CTDONTUYCHINH
FOR EACH ROW
DECLARE
    V_MADON NUMBER;
    V_CHENHLECH NUMBER(10,2) := 0;
    V_NGAYGIAO DATE;
    V_SOBANH_HIENTAI NUMBER;
    V_GIOIHAN NUMBER;
BEGIN
    IF INSERTING THEN
        V_CHENHLECH := :NEW.SOLUONG;
        V_MADON := :NEW.MADON;
    ELSIF UPDATING THEN
        V_CHENHLECH := :NEW.SOLUONG - :OLD.SOLUONG;
        V_MADON := :NEW.MADON;
    ELSIF DELETING THEN
        V_CHENHLECH := -(:OLD.SOLUONG);
        V_MADON := :OLD.MADON;
    END IF;

    SELECT TRUNC(NGAYGIONHANBANH) INTO V_NGAYGIAO
    FROM DONDATHANG
    WHERE MADON = V_MADON;

    SELECT NVL(SOBANHDANHAN, 0), NVL(GIOIHANSOBANH, 0)
    INTO V_SOBANH_HIENTAI, V_GIOIHAN
    FROM NANGLUCSANXUAT
    WHERE TRUNC(NGAYSANXUAT) = V_NGAYGIAO
    FOR UPDATE;

    IF (V_SOBANH_HIENTAI + V_CHENHLECH) > V_GIOIHAN THEN
        RAISE_APPLICATION_ERROR(-20005,
            'TU CHOI NHAN DON: Ngay ' || TO_CHAR(V_NGAYGIAO, 'DD/MM/YYYY') ||
            ' xuong da dat cong suat toi da! (Da nhan: ' || V_SOBANH_HIENTAI || '/' || V_GIOIHAN || ' banh, Khach dat them: ' || V_CHENHLECH || ' banh). ' ||
            'Vui long khuyen khich khach doi sang ngay khac!');
    END IF;

    UPDATE NANGLUCSANXUAT
    SET SOBANHDANHAN = V_SOBANH_HIENTAI + V_CHENHLECH
    WHERE TRUNC(NGAYSANXUAT) = V_NGAYGIAO;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Luu y: Chua co du lieu gioi han cong suat cho ngay ' || TO_CHAR(V_NGAYGIAO, 'DD/MM/YYYY'));
END;
/

-- Trigger gán giá vốn tại thời điểm bán cho chi tiết đơn hàng
CREATE OR REPLACE TRIGGER TRG_CTDONHANG_GIAVON
BEFORE INSERT ON CTDONHANG
FOR EACH ROW
BEGIN
    :NEW.DONGIAVON := FUNC_TinhGiaVonDong(:NEW.MASP);
END;
/

-- Trigger gán giá vốn tại thời điểm bán cho chi tiết đơn tùy chỉnh
CREATE OR REPLACE TRIGGER TRG_CTDONTUYCHINH_GIAVON
BEFORE INSERT ON CTDONTUYCHINH
FOR EACH ROW
BEGIN
    :NEW.DONGIAVON := FUNC_TinhGiaVonDong(:NEW.MASP);
END;
/


