-- =======================================================
-- CONFIGURATION SCRIPTS (Drop/Fix/Update/Test)
-- =======================================================

-- Test Trigger --
DECLARE
    V_MANV NUMBER;
    V_MAVAITRO NUMBER;
    V_MANL NUMBER;
    V_MANCC NUMBER;
    V_MADVT NUMBER;
    V_MAPN NUMBER;
    V_MAPX NUMBER;
    V_MALO NUMBER;
    V_SOLUONGCONLAI NUMBER;
    V_SOLUONGTONTONG NUMBER;
BEGIN
    -- 1. TẠO DỮ LIỆU CÓ LIÊN QUAN
    INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO;
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU) VALUES (V_MAVAITRO, 'ABC', '999999999', 'USER', '12345') RETURNING MANV INTO V_MANV;
    INSERT INTO DONVITINH(TENDVT) VALUES ('kg') RETURNING MADVT INTO V_MADVT;

    INSERT INTO NGUYENLIEU(TENNL, MADVT, GIAVONTRUNGBINH, SOLUONGTONTONG)
    VALUES (N'Bột mì', V_MADVT, 20000, 20) RETURNING MANL INTO V_MANL;

    INSERT INTO NHACUNGCAP(TENNCC) VALUES ('NCC') RETURNING MANCC INTO V_MANCC;
    INSERT INTO PHIEUNHAPKHO(MANV, MANCC) VALUES (V_MANV, V_MANCC) RETURNING MAPN INTO V_MAPN;
    INSERT INTO PHIEUXUATKHO(MANV) VALUES (V_MANV) RETURNING MAPX INTO V_MAPX;

    -- 2. TẠO DỮ LIỆU KÍCH HOẠT TRIGGER
    INSERT INTO CTPHIEUNHAP(MAPN, MANL, SOLUONG, DONGIA, SOLUONGCONLAI)
    VALUES (V_MAPN, V_MANL, 5, 26000, 10) RETURNING MALO INTO V_MALO;

    INSERT INTO CTPHIEUXUAT_NL(MAPX, MALO, SOLUONG) VALUES (V_MAPX, V_MALO, 5);

    -- 4. ĐỌC LẠI DỮ LIỆU TỪ BẢNG CHA
    SELECT CTPN.SOLUONGCONLAI, NL.SOLUONGTONTONG INTO V_SOLUONGCONLAI, V_SOLUONGTONTONG
    FROM NGUYENLIEU NL
    JOIN CTPHIEUNHAP CTPN ON CTPN.MANL = NL.MANL
    WHERE CTPN.MANL = NL.MANL;

    -- 5. XÓA DỮ LIỆU TẠM
    ROLLBACK;

    -- 6. BÁO CÁO KẾT QUA
    IF V_SOLUONGCONLAI = 5 AND V_SOLUONGTONTONG = 20 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Trigger hoat dong');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Trigger khong hoat dong');
    END IF;
END;
/

-- Test Procedure --
DECLARE
    V_MAVAITRO NUMBER;
    V_MANV NUMBER;
    V_THOIDIEMXOA TIMESTAMP;
    V_MANX NUMBER;
BEGIN
    -- BƯỚC 1: TẠO DỮ LIỆU CÓ LIÊN QUAN
    INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO;
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU)
    VALUES (V_MAVAITRO, 'ABC', '999999999', 'USER', '12345') RETURNING MANV INTO V_MANV;

    -- BƯỚC 2: TẠO HIỆN TRƯỜNG GIẢ
    UPDATE VAITRO
    SET THOIDIEMXOA = SYSDATE, MANX = V_MANV
    WHERE MAVAITRO = V_MAVAITRO;

    -- BƯỚC 3: GỌI PROCEDURE ĐỂ KHÔI PHỤC
    PROC_KHOIPHUCDULIEU('VAITRO', 'MAVAITRO', V_MAVAITRO);

    -- BƯỚC 4: KHÁM NGHIỆM LẠI HIỆN TRƯỜNG
    SELECT THOIDIEMXOA, MANX
    INTO V_THOIDIEMXOA, V_MANX
    FROM VAITRO
    WHERE MAVAITRO = V_MAVAITRO;

    -- BƯỚC 5: XÓA DỮ LIỆU TẠM
    DELETE FROM NHANVIEN WHERE MANV = V_MANV;
    DELETE FROM VAITRO WHERE MAVAITRO = V_MAVAITRO;
    COMMIT;

    -- BƯỚC 6: BÁO CÁO KẾT QUẢ
    IF V_THOIDIEMXOA IS NULL AND V_MANX IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'Procedure hoat dong');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Procedure khong hoat dong');
    END IF;
END;
/



