-- =======================================================
-- CONFIGURATION SCRIPTS (Drop/Fix/Update/Test)
-- =======================================================

-- Test Procedure --
DECLARE
    V_MAVAITRO NUMBER;
    V_MANV NUMBER;
    V_THOIDIEMXOA TIMESTAMP;
    V_MANX NUMBER;
BEGIN
    -- BƯỚC 1: TẠO DỮ LIỆU CÓ LIÊN QUAN
    INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO;
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU)
    VALUES (V_MAVAITRO, 'ABC', '999999999', 'USER', '12345') RETURNING MANV INTO V_MANV;

    -- BƯỚC 2: TẠO HIỆN TRƯỜNG GIẢ
    UPDATE VAITRO
    SET THOIDIEMXOA = SYSDATE, MANX = V_MANV
    WHERE MAVAITRO = V_MAVAITRO;

    -- BƯỚC 3: GỌI PROCEDURE ĐỂ KHÔI PHỤC
    PROC_KHOIPHUCDULIEU('VAITRO', 'MAVAITRO', V_MAVAITRO);

    -- BƯỚC 4: KHÁM NGHIỆM LẠI HIỆN TRƯỜNG
    SELECT THOIDIEMXOA, MANX
    INTO V_THOIDIEMXOA, V_MANX
    FROM VAITRO
    WHERE MAVAITRO = V_MAVAITRO;

    -- BƯỚC 5: XÓA DỮ LIỆU TẠM
    DELETE FROM NHANVIEN WHERE MANV = V_MANV;
    DELETE FROM VAITRO WHERE MAVAITRO = V_MAVAITRO;
    COMMIT;

    -- BƯỚC 6: BÁO CÁO KẾT QUẢ
    IF V_THOIDIEMXOA IS NULL AND V_MANX IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'Procedure hoat dong');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Procedure khong hoat dong');
    END IF;
END;
/

-- Test PROC_DONGCADOISOAT --
DECLARE
    V_MAVAITRO NUMBER;
    V_MANV NUMBER;
    V_MACA NUMBER;
    V_TIEN_HETHONG NUMBER;
    V_TIEN_THUCTE NUMBER := 1500000;
    V_CHENHLECH NUMBER;
    V_TRANGTHAI NVARCHAR2(50);
    V_COUNT_DOISOAT NUMBER;
BEGIN
    -- BƯỚC 1: TẠO DỮ LIỆU CÓ LIÊN QUAN
    INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO;
    
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU)
    VALUES (V_MAVAITRO, 'NV TEST DOISOAT', '0999999999', 'TESTDOISOAT', '123') 
    RETURNING MANV INTO V_MANV;

    INSERT INTO CALAMVIEC(MANV, MAMAYPOS, TRANGTHAI)
    VALUES (V_MANV, 'POS01', 'Đang mở')
    RETURNING MACA INTO V_MACA;

    -- BƯỚC 2: GỌI PROCEDURE CẦN TEST
    PROC_DONGCADOISOAT(V_MACA, V_TIEN_THUCTE, 'Khach boa them tien');

    -- BƯỚC 3: KIỂM TRA KẾT QUẢ
    -- Kiểm tra trạng thái ca làm việc
    SELECT TRANGTHAI INTO V_TRANGTHAI
    FROM CALAMVIEC
    WHERE MACA = V_MACA;

    -- Kiểm tra có bảng ghi đối soát không
    SELECT COUNT(*), NVL(MAX(TONGTIENHETHONG), 0), NVL(MAX(CHENHLECH), 0)
    INTO V_COUNT_DOISOAT, V_TIEN_HETHONG, V_CHENHLECH
    FROM DOISOAT
    WHERE MACA = V_MACA;

    -- BƯỚC 4: DỌN DẸP DỮ LIỆU
    DELETE FROM DOISOAT WHERE MACA = V_MACA;
    DELETE FROM CALAMVIEC WHERE MACA = V_MACA;
    DELETE FROM NHANVIEN WHERE MANV = V_MANV;
    DELETE FROM VAITRO WHERE MAVAITRO = V_MAVAITRO;
    COMMIT;

    -- BƯỚC 5: BÁO CÁO KẾT QUẢ
    IF V_TRANGTHAI = 'Đã đóng' AND V_COUNT_DOISOAT > 0 AND V_CHENHLECH = (V_TIEN_THUCTE - V_TIEN_HETHONG) THEN
        RAISE_APPLICATION_ERROR(-20001, 'Procedure PROC_DONGCADOISOAT hoat dong dung');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Procedure PROC_DONGCADOISOAT khong hoat dong hoac tinh sai');
    END IF;
END;
/

