-- =======================================================
-- VIEW TESTING SCRIPTS (Drop/Fix/Update/Test)
-- =======================================================

-- =======================================================
-- 1. Test VW_ChiTietHoaDonIn
-- =======================================================
DECLARE
    V_MAVAITRO NUMBER; V_MANV NUMBER; V_MACA NUMBER; V_MAPTTT NUMBER;
    V_MAHANG NUMBER; V_MAKH NUMBER; V_MADM NUMBER; V_MASP NUMBER;
    V_MATT NUMBER; V_MADON NUMBER; V_MAHD NUMBER;

    V_COUNT NUMBER := 0;
BEGIN
    -- 1. TẠO DỮ LIỆU
    INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO;
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU) VALUES (V_MAVAITRO, 'NV TEST HD', '0911111111', 'TESTHD', '123') RETURNING MANV INTO V_MANV;
    INSERT INTO CALAMVIEC(MANV, TRANGTHAI) VALUES (V_MANV, 'Đang mở') RETURNING MACA INTO V_MACA;
    INSERT INTO PHUONGTHUCTT(TENPTTT, MANX) VALUES ('Tiền mặt', V_MANV) RETURNING MAPTTT INTO V_MAPTTT;
    INSERT INTO HANGTHANHVIEN(TENHANG, MANX) VALUES ('Đồng', V_MANV) RETURNING MAHANG INTO V_MAHANG;
    INSERT INTO KHACHHANG(HOTEN, SDT, MAHANG, MANX) VALUES ('KH Test HD', '0922222222', V_MAHANG, V_MANV) RETURNING MAKH INTO V_MAKH;
    INSERT INTO DANHMUCSP(TENDM, MANX) VALUES ('Bánh Ngọt', V_MANV) RETURNING MADM INTO V_MADM;
    INSERT INTO SANPHAM(MADM, TENSP, GIACOBAN, MANX) VALUES (V_MADM, 'Bánh Kem HD', 250000, V_MANV) RETURNING MASP INTO V_MASP;
    INSERT INTO TRANGTHAIDON(TENTRANGTHAI) VALUES ('Hoàn thành') RETURNING MATRANGTHAI INTO V_MATT;

    INSERT INTO DONDATHANG(NGAYGIONHANBANH, MAKH, MANV_LAP, MATRANGTHAI) VALUES (SYSDATE, V_MAKH, V_MANV, V_MATT) RETURNING MADON INTO V_MADON;
    INSERT INTO CTDONHANG(MADON, MASP, SOLUONG, DONGIA) VALUES (V_MADON, V_MASP, 1, 250000);
    INSERT INTO HOADON(MADON, MACA, TONGTIENTHANHTOAN, MAPTTT) VALUES (V_MADON, V_MACA, 250000, V_MAPTTT) RETURNING MAHD INTO V_MAHD;

    -- 2. GỌI VIEW KIỂM TRA
    -- Đếm xem có dòng dữ liệu nào nối thành công ra đúng cái Hóa đơn vừa tạo không
    SELECT COUNT(*) INTO V_COUNT FROM VW_CHITIETINHOADON WHERE MAHD = V_MAHD;

    -- 3. XÓA DỮ LIỆU TẠM
    ROLLBACK;

    -- 4. BÁO CÁO KẾT QUẢ
    IF V_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'View VW_ChiTietHoaDonIn hoat dong toan dien!');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'View VW_ChiTietHoaDonIn sai logic JOIN, khong ra du lieu.');
    END IF;
END;
/


-- =======================================================
-- 2. Test VW_PhieuHenLayBanh
-- =======================================================
DECLARE
    V_MAVAITRO NUMBER; V_MANV NUMBER; V_MADM NUMBER; V_MASP NUMBER;
    V_MATT NUMBER; V_MADON NUMBER;

    V_COUNT NUMBER := 0;
BEGIN
    -- 1. TẠO DỮ LIỆU
    INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO;
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU) VALUES (V_MAVAITRO, 'NV TEST PHIEU', '0933333333', 'TESTPH', '123') RETURNING MANV INTO V_MANV;
    INSERT INTO DANHMUCSP(TENDM, MANX) VALUES ('Bánh Custom', V_MANV) RETURNING MADM INTO V_MADM;
    INSERT INTO SANPHAM(MADM, TENSP, GIACOBAN, MANX) VALUES (V_MADM, 'Bánh Tùy Chỉnh', 300000, V_MANV) RETURNING MASP INTO V_MASP;
    INSERT INTO TRANGTHAIDON(TENTRANGTHAI) VALUES ('Đang sản xuất') RETURNING MATRANGTHAI INTO V_MATT;

    -- Tạo đơn hẹn lấy ngày mai
    -- Dòng code đã được sếp Khiêm "độ" lại cho chuẩn nghiệp vụ:
    INSERT INTO DONDATHANG(NGAYGIONHANBANH, MANV_LAP, MATRANGTHAI, TONGTIENHDBAN, TIENDACOC)
    VALUES (SYSDATE + 1, V_MANV, V_MATT, 300000, 150000)
    RETURNING MADON INTO V_MADON;
    INSERT INTO CTDONTUYCHINH(MADON, MASP, SOLUONG, DONGIA, LOICHUCTRENBANH) VALUES (V_MADON, V_MASP, 1, 300000, 'HPBD KHIEM');

    -- 2. GỌI VIEW KIỂM TRA
    SELECT COUNT(*) INTO V_COUNT FROM VW_PHIEUHENLAYBANH WHERE MADON = V_MADON AND LOICHUCTRENBANH = 'HPBD KHIEM';

    -- 3. XÓA DỮ LIỆU TẠM
    ROLLBACK;

    -- 4. BÁO CÁO KẾT QUẢ
    IF V_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'View VW_PhieuHenLayBanh hoat dong toan dien!');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'View VW_PhieuHenLayBanh sai logic JOIN, khong ra du lieu.');
    END IF;
END;
/


-- =======================================================
-- 3. Test VW_TheKhoNguyenLieu
-- =======================================================
DECLARE
    V_MAVAITRO NUMBER; V_MANV NUMBER; V_MANCC NUMBER; V_MADVT NUMBER;
    V_MANL NUMBER; V_MAPN NUMBER; V_MALO NUMBER; V_MAPX NUMBER;

    V_COUNT NUMBER := 0;
BEGIN
    -- 1. TẠO DỮ LIỆU
    INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO;
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU) VALUES (V_MAVAITRO, 'NV TEST KHO', '0944444444', 'TESTKHO', '123') RETURNING MANV INTO V_MANV;
    INSERT INTO NHACUNGCAP(TENNCC, MANX) VALUES ('NCC Bột', V_MANV) RETURNING MANCC INTO V_MANCC;
    INSERT INTO DONVITINH(TENDVT, MANX) VALUES ('Kg', V_MANV) RETURNING MADVT INTO V_MADVT;
    INSERT INTO NGUYENLIEU(TENNL, MADVT, SOLUONGTONTONG, MANX) VALUES ('Bột Mì Test', V_MADVT, 100, V_MANV) RETURNING MANL INTO V_MANL;

    -- Tạo 1 phiếu nhập (Nhập 50kg)
    INSERT INTO PHIEUNHAPKHO(MANV, MANCC) VALUES (V_MANV, V_MANCC) RETURNING MAPN INTO V_MAPN;
    INSERT INTO CTPHIEUNHAP(MAPN, MANL, SOLUONG, DONGIA, SOLUONGCONLAI) VALUES (V_MAPN, V_MANL, 50, 10000, 40) RETURNING MALO INTO V_MALO;

    -- Tạo 1 phiếu xuất (Xuất 10kg từ Lô vừa nhập) -> Trigger TRG_XUATSLNGUYENLIEU sẽ trừ 10kg vào Tồn Tổng
    INSERT INTO PHIEUXUATKHO(LYDOXUAT, MANV) VALUES ('Test Xuất', V_MANV) RETURNING MAPX INTO V_MAPX;
    INSERT INTO CTPHIEUXUAT_NL(MAPX, MALO, SOLUONG) VALUES (V_MAPX, V_MALO, 10);

    -- 2. GỌI VIEW KIỂM TRA
    SELECT COUNT(*) INTO V_COUNT FROM VW_THEKHONGUYENLIEU WHERE MANL = V_MANL;

    -- 3. XÓA DỮ LIỆU TẠM
    ROLLBACK;

    -- 4. BÁO CÁO KẾT QUẢ
    IF V_COUNT = 2 THEN
        RAISE_APPLICATION_ERROR(-20001, 'View VW_TheKhoNguyenLieu hoat dong toan dien! Da gom duoc ca Nhap va Xuat.');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'View VW_TheKhoNguyenLieu sai logic. Thieu UNION hoac sai JOIN.');
    END IF;
END;
/


-- =======================================================
-- 4. Test VW_KDS_DonCanLam
-- =======================================================
DECLARE
    V_MAVAITRO NUMBER; V_MANV NUMBER; V_MADM NUMBER; V_MASP NUMBER;
    V_MATT_MOI NUMBER; V_MATT_HOANTHANH NUMBER;
    V_MADON_1 NUMBER; V_MADON_2 NUMBER;

    V_COUNT_1 NUMBER := 0;
    V_COUNT_2 NUMBER := 0;
BEGIN
    -- 1. TẠO DỮ LIỆU GIẢ
    INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO;
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU)
    VALUES (V_MAVAITRO, 'NV TEST KDS', '0955555555', 'TESTKDS', '123') RETURNING MANV INTO V_MANV;

    INSERT INTO DANHMUCSP(TENDM, MANX) VALUES ('Bánh Mì', V_MANV) RETURNING MADM INTO V_MADM;
    INSERT INTO SANPHAM(MADM, TENSP, GIACOBAN, MANX) VALUES (V_MADM, 'Bánh KDS', 50000, V_MANV) RETURNING MASP INTO V_MASP;

    INSERT INTO TRANGTHAIDON(TENTRANGTHAI) VALUES (N'Mới đặt') RETURNING MATRANGTHAI INTO V_MATT_MOI;
    INSERT INTO TRANGTHAIDON(TENTRANGTHAI) VALUES (N'Hoàn thành') RETURNING MATRANGTHAI INTO V_MATT_HOANTHANH;

    -- Đơn 1: Cần làm (Trạng thái: 'Mới đặt') -> VIEW PHẢI HIỆN
    INSERT INTO DONDATHANG(NGAYGIONHANBANH, MANV_LAP, MATRANGTHAI)
    VALUES (SYSDATE + 1, V_MANV, V_MATT_MOI) RETURNING MADON INTO V_MADON_1;
    INSERT INTO CTDONTUYCHINH(MADON, MASP, SOLUONG, DONGIA, THOIGIANCHUANBI)
    VALUES (V_MADON_1, V_MASP, 5, 50000, 2); -- Chuẩn bị trong 2 ngày

    -- Đơn 2: Đã xong (Trạng thái: 'Hoàn thành') -> VIEW PHẢI ẨN
    INSERT INTO DONDATHANG(NGAYGIONHANBANH, MANV_LAP, MATRANGTHAI)
    VALUES (SYSDATE, V_MANV, V_MATT_HOANTHANH) RETURNING MADON INTO V_MADON_2;
    INSERT INTO CTDONTUYCHINH(MADON, MASP, SOLUONG, DONGIA)
    VALUES (V_MADON_2, V_MASP, 3, 50000);

    -- 2. KIỂM TRA
    SELECT COUNT(*) INTO V_COUNT_1 FROM VW_KDS_DonCanLam WHERE MADON = V_MADON_1;
    SELECT COUNT(*) INTO V_COUNT_2 FROM VW_KDS_DonCanLam WHERE MADON = V_MADON_2;

    -- 3. XÓA DỮ LIỆU TẠM
    ROLLBACK;

    -- 4. BÁO CÁO
    IF V_COUNT_1 > 0 AND V_COUNT_2 = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'View VW_KDS_DonCanLam hoat dong chinh xac!');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Loi logic: View loc sai trang thai hoac khong thay don hang.');
    END IF;
END;
/