-- Thêm cột MODULE vào bảng CHUC_NANG để lưu thông tin Enum SystemModule
ALTER TABLE CHUCNANG ADD (MODULE VARCHAR2(50));

-- Cập nhật dữ liệu mẫu để phân quyền hoạt động ngay (tùy theo dữ liệu hiện có của bạn)
UPDATE CHUCNANG SET MODULE = 'POS' WHERE UPPER(TENCHUCNANG) LIKE '%BAN HANG%';
UPDATE CHUCNANG SET MODULE = 'INVENTORY' WHERE UPPER(TENCHUCNANG) LIKE '%KHO%' OR UPPER(TENCHUCNANG) LIKE '%NGUYEN LIEU%';
UPDATE CHUCNANG SET MODULE = 'REPORTS' WHERE UPPER(TENCHUCNANG) LIKE '%BAO CAO%';
UPDATE CHUCNANG SET MODULE = 'STAFF' WHERE UPPER(TENCHUCNANG) LIKE '%NHAN VIEN%' OR UPPER(TENCHUCNANG) LIKE '%PHAN QUYEN%';

COMMIT;
