-- =======================================================
-- CONFIGURATION SCRIPTS (Drop/Fix/Update/Test)
-- =======================================================

-- Test FUNC_DoanhThuTheoPhuongThucTT --
DECLARE
    V_MAVAITRO NUMBER;
    V_MANV NUMBER;
    V_MACA NUMBER;
    V_MAPTTT_TM NUMBER;
    V_MAPTTT_CK NUMBER;
    
    V_CURSOR SYS_REFCURSOR;
    V_TENPTTT NVARCHAR2(100);
    V_TONGDOANHTHU NUMBER;
    V_COUNT NUMBER := 0;
BEGIN
    -- 1. TẠO DỮ LIỆU GIẢ LẬP
    INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO;
    
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU) 
    VALUES (V_MAVAITRO, 'NV TEST DOANH THU', '0988765432', 'TESTDT', '123') 
    RETURNING MANV INTO V_MANV;

    INSERT INTO CALAMVIEC(MANV, TRANGTHAI) VALUES (V_MANV, 'Đang mở') RETURNING MACA INTO V_MACA;
    
    -- Tạo 2 phương thức thanh toán
    INSERT INTO PHUONGTHUCTT(TENPTTT, MANX) VALUES ('Tiền mặt', V_MANV) RETURNING MAPTTT INTO V_MAPTTT_TM;
    INSERT INTO PHUONGTHUCTT(TENPTTT, MANX) VALUES ('Chuyển khoản', V_MANV) RETURNING MAPTTT INTO V_MAPTTT_CK;
    
    -- Tạo 2 hóa đơn (1 cái TM 100k, 1 cái CK 250k)
    INSERT INTO HOADON(MACA, TONGTIENTHANHTOAN, MAPTTT, NGAYXUATHD) VALUES (V_MACA, 100000, V_MAPTTT_TM, SYSDATE);
    INSERT INTO HOADON(MACA, TONGTIENTHANHTOAN, MAPTTT, NGAYXUATHD) VALUES (V_MACA, 250000, V_MAPTTT_CK, SYSDATE);
    
    -- 2. GỌI HÀM (Lọc doanh thu của ngày hôm nay)
    V_CURSOR := FUNC_DOANHTHUTHEOPTTT(TRUNC(SYSDATE) - 1, TRUNC(SYSDATE) + 1);
    
    -- 3. KIỂM TRA BẢNG ẢO
    LOOP
        FETCH V_CURSOR INTO V_TENPTTT, V_TONGDOANHTHU;
        EXIT WHEN V_CURSOR%NOTFOUND;
        
        -- Nếu dòng trả về khớp với dữ liệu giả lập, đếm số lần khớp
        IF V_TENPTTT = 'Tiền mặt' AND V_TONGDOANHTHU = 100000 THEN
            V_COUNT := V_COUNT + 1;
        ELSIF V_TENPTTT = 'Chuyển khoản' AND V_TONGDOANHTHU = 250000 THEN
            V_COUNT := V_COUNT + 1;
        END IF;
    END LOOP;
    CLOSE V_CURSOR;
    
    -- 4. XÓA DỮ LIỆU RÁC
    ROLLBACK;
    
    -- 5. BÁO CÁO KẾT QUẢ
    IF V_COUNT = 2 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Function FUNC_DoanhThuTheoPhuongThucTT hoạt động!');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Function trả về sai dữ liệu hoặc thiếu dòng.');
    END IF;
END;
/

-- Test FUNC_XACDINHPHIEUNHAPFEFO --
DECLARE
    V_MAVAITRO NUMBER;
    V_MANV NUMBER;
    V_MANCC NUMBER;
    V_MADVT NUMBER;
    V_MANL NUMBER;
    V_MAPN NUMBER;
    V_MALO_1 NUMBER;
    V_MALO_2 NUMBER;
    
    V_CURSOR SYS_REFCURSOR;
    V_MALO_RESULT NUMBER;
    V_SL_CONLAI_RESULT NUMBER;
BEGIN
    -- 1. TẠO DỮ LIỆU
    INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO;
    
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU) 
    VALUES (V_MAVAITRO, 'NV TEST FEFO', '0999123123', 'TESTFEFO', '123') 
    RETURNING MANV INTO V_MANV;
    
    INSERT INTO DONVITINH(TENDVT) VALUES ('kg') RETURNING MADVT INTO V_MADVT;
    
    INSERT INTO NGUYENLIEU(TENNL, MADVT) 
    VALUES ('Bột TEST FEFO', V_MADVT) 
    RETURNING MANL INTO V_MANL;
    
    INSERT INTO NHACUNGCAP(TENNCC) VALUES ('NCC FEFO') RETURNING MANCC INTO V_MANCC;
    
    INSERT INTO PHIEUNHAPKHO(MANV, MANCC) 
    VALUES (V_MANV, V_MANCC) 
    RETURNING MAPN INTO V_MAPN;
    
    -- Lô số 1: Hết hạn sau 10 ngày (Xa)
    INSERT INTO CTPHIEUNHAP(MAPN, MANL, SOLUONG, DONGIA, SOLUONGCONLAI, HANSUDUNG) 
    VALUES (V_MAPN, V_MANL, 5, 10000, 5, SYSDATE + 10) 
    RETURNING MALO INTO V_MALO_1;
    
    -- Lô số 2: Hết hạn sau 2 ngày (FEFO sẽ phải ưu tiên lô này vì cận date hơn)
    INSERT INTO CTPHIEUNHAP(MAPN, MANL, SOLUONG, DONGIA, SOLUONGCONLAI, HANSUDUNG) 
    VALUES (V_MAPN, V_MANL, 10, 10000, 10, SYSDATE + 2) 
    RETURNING MALO INTO V_MALO_2;

    -- 2. GỌI HÀM FEFO
    V_CURSOR := FUNC_XACDINHPHIEUNHAPFEFO(V_MANL, 3); -- Giả sử cần xuất 3 kg
    
    FETCH V_CURSOR INTO V_MALO_RESULT, V_SL_CONLAI_RESULT;
    CLOSE V_CURSOR;
    
    -- 3. XOA DỮ LIỆU TẠM
    ROLLBACK;
    
    -- 4. BÁO CÁO KẾT QUẢ
    IF V_MALO_RESULT = V_MALO_2 AND V_SL_CONLAI_RESULT = 10 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Function FUNC_XACDINHPHIEUNHAPFEFO hoạt động!');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Function hoạt động sai quy tắc FEFO! (Chọn sai lô)');
    END IF;
END;
/

-- Test FUNC_TINHDIEMKHADUNG --
DECLARE
    V_MAVAITRO NUMBER;
    V_MANV NUMBER;
    V_MADVT NUMBER;
    V_MADM NUMBER;
    V_MASP NUMBER;
    V_MATT_MOI NUMBER;
    V_MATT_HUY NUMBER;
    V_MADON_1 NUMBER;
    V_MADON_2 NUMBER;
    V_MACTTC_1 NUMBER;
    V_MACTTC_2 NUMBER;
    
    V_KHA_DUNG NUMBER;
BEGIN
    -- 1. TẠO DỮ LIỆU
    INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO;
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU) 
    VALUES (V_MAVAITRO, 'NV TEST NANG LUC', '0999555666', 'TESTNL', '123') 
    RETURNING MANV INTO V_MANV;
    
    INSERT INTO DONVITINH(TENDVT) VALUES ('cai') RETURNING MADVT INTO V_MADVT;
    INSERT INTO DANHMUCSP(TENDM) VALUES ('BÁNH CUSTOM') RETURNING MADM INTO V_MADM;
    INSERT INTO SANPHAM(MADM, TENSP, GIACOBAN) VALUES (V_MADM, 'Bánh Kem Tùy Chỉnh', 200000) RETURNING MASP INTO V_MASP;
    
    -- Giới hạn công suất hôm nay là 20 cái
    INSERT INTO NANGLUCSANXUAT(NGAYSANXUAT, GIOIHANSOBANH, SOBANHDANHAN)
    VALUES (TRUNC(SYSDATE), 20, 0);

    -- Tạo 2 trạng thái: Mới đặt và Hủy
    INSERT INTO TRANGTHAIDON(TENTRANGTHAI) VALUES ('Mới đặt') RETURNING MATRANGTHAI INTO V_MATT_MOI;
    INSERT INTO TRANGTHAIDON(TENTRANGTHAI) VALUES ('Hủy') RETURNING MATRANGTHAI INTO V_MATT_HUY;
    
    -- Đơn 1: Mới đặt, đặt 8 cái Custom (Hợp lệ)
    INSERT INTO DONDATHANG(NGAYGIONHANBANH, MANV_LAP, MATRANGTHAI) 
    VALUES (SYSDATE, V_MANV, V_MATT_MOI) RETURNING MADON INTO V_MADON_1;
    
    INSERT INTO CTDONTUYCHINH(MADON, MASP, SOLUONG, DONGIA) 
    VALUES (V_MADON_1, V_MASP, 8, 250000) RETURNING MACTTC INTO V_MACTTC_1;
    
    -- Đơn 2: Bị Hủy, đặt 5 cái Custom (Sẽ bị loại trừ khỏi phép Sum)
    INSERT INTO DONDATHANG(NGAYGIONHANBANH, MANV_LAP, MATRANGTHAI) 
    VALUES (SYSDATE, V_MANV, V_MATT_HUY) RETURNING MADON INTO V_MADON_2;
    
    INSERT INTO CTDONTUYCHINH(MADON, MASP, SOLUONG, DONGIA) 
    VALUES (V_MADON_2, V_MASP, 5, 250000) RETURNING MACTTC INTO V_MACTTC_2;

    -- 2. GỌI HÀM KIỂM TRA CHO HÔM NAY
    -- Giới hạn: 20
    -- Tổng đã đặt: 8 (Lờ đi 5 cái đã bị hủy)
    -- Khả dụng = 20 - 8 = 12
    V_KHA_DUNG := FUNC_TinhDiemKhaDung(SYSDATE);
    
    -- 3. XOA DỮ LIỆU TẠM
    ROLLBACK;
    
    -- 4. BÁO CÁO KẾT QUẢ
    IF V_KHA_DUNG = 12 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Function FUNC_TinhDiemKhaDung hoạt động!');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Function hoạt động sai! Tính toán năng lực không đúng: ' || V_KHA_DUNG);
    END IF;
END;
/

-- Test FUNC_TINHLOINHUANGOP --
DECLARE
    V_MAVAITRO NUMBER;
    V_MANV NUMBER;
    V_MACA NUMBER;
    V_MAPTTT NUMBER;
    V_MATRANGTHAI NUMBER;
    V_MADVT NUMBER;
    V_MADM NUMBER;
    V_MASP NUMBER;
    
    V_MADVT_NL NUMBER;
    V_MANL NUMBER;
    
    V_MADON NUMBER;
    V_MAHD NUMBER;
    
    V_LOINHUANGOP NUMBER;
BEGIN
    -- 1. TẠO DỮ LIỆU
    INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO;
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU) 
    VALUES (V_MAVAITRO, 'NV TEST LOI NHUAN', '0999555777', 'TESTLN', '123') 
    RETURNING MANV INTO V_MANV;
    
    INSERT INTO CALAMVIEC(MANV, TRANGTHAI) VALUES (V_MANV, 'Đang mở') RETURNING MACA INTO V_MACA;
    INSERT INTO PHUONGTHUCTT(TENPTTT, MANX) VALUES ('Tiền mặt', V_MANV) RETURNING MAPTTT INTO V_MAPTTT;
    INSERT INTO TRANGTHAIDON(TENTRANGTHAI) VALUES ('Hoàn thành') RETURNING MATRANGTHAI INTO V_MATRANGTHAI;
    
    INSERT INTO DONVITINH(TENDVT) VALUES ('cai') RETURNING MADVT INTO V_MADVT;
    INSERT INTO DANHMUCSP(TENDM) VALUES ('BÁNH NGỌT') RETURNING MADM INTO V_MADM;
    -- San pham nay de ban
    INSERT INTO SANPHAM(MADM, TENSP, GIACOBAN, SOLUONGTON) VALUES (V_MADM, 'Bánh Kem', 100000, 100) RETURNING MASP INTO V_MASP;

    -- Trigger tinh gia von se chay, nen can phai co cong thuc
    INSERT INTO DONVITINH(TENDVT) VALUES ('kg') RETURNING MADVT INTO V_MADVT_NL;
    INSERT INTO NGUYENLIEU(TENNL, MADVT, GIAVONTRUNGBINH) VALUES ('Bột thử', V_MADVT_NL, 20000) RETURNING MANL INTO V_MANL;
    -- Cong thuc: 2kg bot * 20000 = 40000 tien nguyen lieu (Gia von = 40k)
    INSERT INTO CONGTHUC(MASP, MANL, SOLUONGTIEUHAO) VALUES (V_MASP, V_MANL, 2);

    -- Đơn hàng
    INSERT INTO DONDATHANG(NGAYGIONHANBANH, MANV_LAP, MATRANGTHAI) 
    VALUES (SYSDATE, V_MANV, V_MATRANGTHAI) RETURNING MADON INTO V_MADON;
    
    -- Chi tiết đơn hàng: Đơn giá 100k, Giá vốn trigger tinh 40k, Số lượng 2 => Lãi = (100 - 40)*2 = 120k
    INSERT INTO CTDONHANG(MADON, MASP, SOLUONG, DONGIA) 
    VALUES (V_MADON, V_MASP, 2, 100000);
    
    -- Chi tiết đơn tùy chỉnh: Đơn giá 150k, Giá vốn trigger tinh 40k, Số lượng 1 => Lãi = (150 - 40)*1 = 110k
    INSERT INTO CTDONTUYCHINH(MADON, MASP, SOLUONG, DONGIA) 
    VALUES (V_MADON, V_MASP, 1, 150000);
    
    -- Hóa đơn cho đơn hàng trên
    INSERT INTO HOADON(MADON, MACA, TONGTIENTHANHTOAN, MAPTTT) 
    VALUES (V_MADON, V_MACA, 350000, V_MAPTTT) RETURNING MAHD INTO V_MAHD;

    -- 2. GỌI HÀM TÍNH LỢI NHUẬN GỘP
    -- Lãi dự kiến = 120k + 110k = 230000
    V_LOINHUANGOP := FUNC_TINHLOINHUANGOP(V_MAHD);
    
    -- 3. XOA DỮ LIỆU TẠM
    ROLLBACK;
    
    -- 4. BÁO CÁO KẾT QUẢ
    IF V_LOINHUANGOP = 230000 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Function FUNC_TINHLOINHUANGOP hoạt động!');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Function hoạt động sai! Tính toán lợi nhuận không đúng: ' || V_LOINHUANGOP);
    END IF;
END;
/

-- Test FUNC_CHUYENDOITYLECONGTHUC --
DECLARE
    V_MADM NUMBER;
    V_MASP NUMBER;
    V_MADVT_BOT NUMBER;
    V_MADVT_DUONG NUMBER;
    V_MANL_BOT NUMBER;
    V_MANL_DUONG NUMBER;
    
    V_CURSOR SYS_REFCURSOR;
    V_MANL_RESULT NUMBER;
    V_TENNL_RESULT NVARCHAR2(100);
    V_TONG_RESULT NUMBER;
    V_TENDVT_RESULT NVARCHAR2(50);
    
    V_COUNT NUMBER := 0;
BEGIN
    -- 1. TẠO DỮ LIỆU
    INSERT INTO DANHMUCSP(TENDM) VALUES ('BÁNH NƯỚNG') RETURNING MADM INTO V_MADM;
    INSERT INTO SANPHAM(MADM, TENSP, GIACOBAN, SOLUONGTON) VALUES (V_MADM, 'Bánh Nướng Nguyên Ổ', 100000, 100) RETURNING MASP INTO V_MASP;

    -- Đơn vị tính và nguyên liệu
    INSERT INTO DONVITINH(TENDVT) VALUES ('kg') RETURNING MADVT INTO V_MADVT_BOT;
    INSERT INTO DONVITINH(TENDVT) VALUES ('gram') RETURNING MADVT INTO V_MADVT_DUONG;
    
    INSERT INTO NGUYENLIEU(TENNL, MADVT, GIAVONTRUNGBINH) VALUES ('Bột làm bánh', V_MADVT_BOT, 20000) RETURNING MANL INTO V_MANL_BOT;
    INSERT INTO NGUYENLIEU(TENNL, MADVT, GIAVONTRUNGBINH) VALUES ('Đường trắng', V_MADVT_DUONG, 15000) RETURNING MANL INTO V_MANL_DUONG;
    
    -- Công thức cho 1 cái bánh: 0.5 kg Bột và 200 gram Đường
    INSERT INTO CONGTHUC(MASP, MANL, SOLUONGTIEUHAO) VALUES (V_MASP, V_MANL_BOT, 0.5);
    INSERT INTO CONGTHUC(MASP, MANL, SOLUONGTIEUHAO) VALUES (V_MASP, V_MANL_DUONG, 200);

    -- 2. GỌI HÀM: Bếp trưởng Cần làm ráp vòng 10 cái bánh
    -- Kỳ vọng: Bột = 0.5 * 10 = 5 kg
    --          Đường = 200 * 10 = 2000 gram
    V_CURSOR := FUNC_CHUYENDOITYLECONGTHUC(V_MASP, 10);
    
    -- 3. KIỂM TRA KẾT QUẢ (Quét từng dòng của Bảng Ảo)
    LOOP
        FETCH V_CURSOR INTO V_MANL_RESULT, V_TENNL_RESULT, V_TONG_RESULT, V_TENDVT_RESULT;
        EXIT WHEN V_CURSOR%NOTFOUND;
        
        IF V_MANL_RESULT = V_MANL_BOT AND V_TONG_RESULT = 5 AND V_TENDVT_RESULT = 'kg' THEN
            V_COUNT := V_COUNT + 1;
        ELSIF V_MANL_RESULT = V_MANL_DUONG AND V_TONG_RESULT = 2000 AND V_TENDVT_RESULT = 'gram' THEN
            V_COUNT := V_COUNT + 1;
        END IF;
    END LOOP;
    CLOSE V_CURSOR;
    
    -- 4. XOA DỮ LIỆU TẠM
    ROLLBACK;
    
    -- 5. BÁO CÁO KẾT QUẢ
    IF V_COUNT = 2 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Function FUNC_CHUYENDOITYLECONGTHUC hoạt động!');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Function hoạt động sai tỷ lệ quy đổi hoặc thiếu dữ liệu!');
    END IF;
END;
/

-- Test FUNC_KIEMTRATONKHOTOITHIEU --
DECLARE
    V_MADVT_GRAM NUMBER;
    V_MADVT_KG NUMBER;
    V_MANL_BINHTHUONG NUMBER;
    V_MANL_CANHGIOI NUMBER;
    V_MANL_DAXOA NUMBER;
    
    V_CURSOR SYS_REFCURSOR;
    V_MANL_RESULT NUMBER;
    V_TENNL_RESULT NVARCHAR2(100);
    V_TON_RESULT NUMBER;
    V_ANTOAN_RESULT NUMBER;
    V_TENDVT_RESULT NVARCHAR2(50);
    
    V_COUNT NUMBER := 0;
BEGIN
    -- 1. TẠO DỮ LIỆU
    INSERT INTO DONVITINH(TENDVT) VALUES ('kg') RETURNING MADVT INTO V_MADVT_KG;
    INSERT INTO DONVITINH(TENDVT) VALUES ('gram') RETURNING MADVT INTO V_MADVT_GRAM;
    
    -- Nguyên liệu 1: Còn dư dả (Tồn 50 > An toàn 10) -> Hàm sẽ BỎ QUA
    INSERT INTO NGUYENLIEU(TENNL, MADVT, SOLUONGTONTONG, MUCTONANTOAN, THOIDIEMXOA) 
    VALUES ('Bột Mì Thường', V_MADVT_KG, 50, 10, NULL) RETURNING MANL INTO V_MANL_BINHTHUONG;
    
    -- Nguyên liệu 2: Chạm đáy nguy hiểm (Tồn 5 < An toàn 15) -> Hàm phải BẮT LẤY
    INSERT INTO NGUYENLIEU(TENNL, MADVT, SOLUONGTONTONG, MUCTONANTOAN, THOIDIEMXOA) 
    VALUES ('Đường Kính', V_MADVT_GRAM, 5, 15, NULL) RETURNING MANL INTO V_MANL_CANHGIOI;
    
    -- Nguyên liệu 3: Cũng cạn kiệt (Tồn 0 <= An toàn 5) nhưng đã bị XÓA MỀM -> Hàm sẽ BỎ QUA
    INSERT INTO NGUYENLIEU(TENNL, MADVT, SOLUONGTONTONG, MUCTONANTOAN, THOIDIEMXOA) 
    VALUES ('Phẩm màu ngưng sx', V_MADVT_GRAM, 0, 5, SYSDATE) RETURNING MANL INTO V_MANL_DAXOA;

    -- 2. GỌI HÀM
    V_CURSOR := FUNC_KIEMTRATONKHOTOITHIEU();
    
    -- 3. KIỂM TRA KẾT QUẢ
    LOOP
        FETCH V_CURSOR INTO V_MANL_RESULT, V_TENNL_RESULT, V_TON_RESULT, V_ANTOAN_RESULT, V_TENDVT_RESULT;
        EXIT WHEN V_CURSOR%NOTFOUND;
        
        -- Nếu bắt đúng thằng bị cạn kiệt
        IF V_MANL_RESULT = V_MANL_CANHGIOI AND V_TON_RESULT = 5 THEN
            V_COUNT := V_COUNT + 1;
        END IF;
        
        -- Nếu vô tình dính thằng Bình thường hoặc Đã xóa, đánh rớt bài test
        IF V_MANL_RESULT = V_MANL_BINHTHUONG OR V_MANL_RESULT = V_MANL_DAXOA THEN
            V_COUNT := -999;
        END IF;
    END LOOP;
    CLOSE V_CURSOR;
    
    -- 4. XOA DỮ LIỆU TẠM
    ROLLBACK;
    
    -- 5. BÁO CÁO KẾT QUẢ
    IF V_COUNT = 1 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Function FUNC_KIEMTRATONKHOTOITHIEU hoạt động!');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Function hoạt động sai! Kết quả bị tràn ra ngoài hoặc không bắt đúng điểm cảnh giới.');
    END IF;
END;
/

-- Test FUNC_TINHGIABANHTUYCHINH --
DECLARE
    V_MADM NUMBER;
    V_MASP NUMBER;
    V_MAKC NUMBER;
    V_MACOT NUMBER;
    V_MANHAN NUMBER;
    V_MATT NUMBER;
    
    V_GIA_FULL NUMBER;
    V_GIA_KHT NUMBER; -- Khong co nhan, khong co trang tri
BEGIN
    -- 1. TẠO DỮ LIỆU ĐỂ TEST
    INSERT INTO DANHMUCSP(TENDM) VALUES ('BÁNH NƯỚNG') RETURNING MADM INTO V_MADM;
    -- Giá cơ bản của mẫu bánh là 200k
    INSERT INTO SANPHAM(MADM, TENSP, GIACOBAN, SOLUONGTON) VALUES (V_MADM, 'Bánh Kem Sữa Tươi', 200000, 100) RETURNING MASP INTO V_MASP;

    -- Thêm các tùy chọn cấu hình phụ phí
    INSERT INTO KICHCOBANH(TENKC, PHUPHI) VALUES ('Size M 25cm', 50000) RETURNING MAKC INTO V_MAKC;
    INSERT INTO COTBANH(TENCOT, PHUPHI) VALUES ('Cốt Vani', 10000) RETURNING MACOT INTO V_MACOT;
    INSERT INTO NHANBANH(TENNHAN, PHUPHI) VALUES ('Nhân Dâu', 15000) RETURNING MANHAN INTO V_MANHAN;
    INSERT INTO KIEUTRANGTRI(TENTRANGTRI, PHUPHI) VALUES ('Gắn Nơ', 25000) RETURNING MATRANGTRI INTO V_MATT;

    -- 2. GỌI HÀM KIỂM TRA
    -- Case 1: Khách đại gia chọn "Full topping" (200k + 50k + 10k + 15k + 25k = 300k)
    V_GIA_FULL := FUNC_TINHGIABANHTUYCHINH(V_MASP, V_MAKC, V_MACOT, V_MANHAN, V_MATT);
    
    -- Case 2: Khách tiết kiệm chỉ mua cốt bánh size M, không cần nhân và trang trí (200k + 50k + 10k = 260k)
    V_GIA_KHT := FUNC_TINHGIABANHTUYCHINH(V_MASP, V_MAKC, V_MACOT, NULL, NULL);
    
    -- 3. XÓA DỮ LIỆU TẠM THỜI
    ROLLBACK;
    
    -- 4. BÁO CÁO KẾT QUẢ CHO CONSOLE
    IF V_GIA_FULL = 300000 AND V_GIA_KHT = 260000 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Function FUNC_TINHGIABANHTUYCHINH hoạt động!');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Function hoạt động sai! Tính giá Full: ' || V_GIA_FULL || ', Tính giá KHT: ' || V_GIA_KHT);
    END IF;
END;
/

-- Test FUNC_SOLUONGKHADUNG --
DECLARE
    V_MADM NUMBER;
    V_MASP NUMBER;
    V_MADVT_BOT NUMBER;
    V_MADVT_TRUNG NUMBER;
    V_MANL_BOT NUMBER;
    V_MANL_TRUNG NUMBER;
    
    V_SO_LUONG_MAX NUMBER;
BEGIN
    -- 1. TẠO DỮ LIỆU ĐỂ TEST
    INSERT INTO DANHMUCSP(TENDM) VALUES ('BÁNH NƯỚNG') RETURNING MADM INTO V_MADM;
    INSERT INTO SANPHAM(MADM, TENSP, GIACOBAN, SOLUONGTON) VALUES (V_MADM, 'Bánh Thử Thắt Cổ Chai', 100000, 0) RETURNING MASP INTO V_MASP;

    -- Đơn vị tính
    INSERT INTO DONVITINH(TENDVT) VALUES ('gram') RETURNING MADVT INTO V_MADVT_BOT;
    INSERT INTO DONVITINH(TENDVT) VALUES ('qua') RETURNING MADVT INTO V_MADVT_TRUNG;
    
    -- Tồn kho hiện tại: Kho còn dư dả 1000 gram Bột, nhưng Trứng thì chỉ còn vỏn vẹn 10 quả
    INSERT INTO NGUYENLIEU(TENNL, MADVT, GIAVONTRUNGBINH, SOLUONGTONTONG) 
    VALUES ('Bột Bắp', V_MADVT_BOT, 100, 1000) RETURNING MANL INTO V_MANL_BOT;
    
    INSERT INTO NGUYENLIEU(TENNL, MADVT, GIAVONTRUNGBINH, SOLUONGTONTONG) 
    VALUES ('Trứng Gà', V_MADVT_TRUNG, 3000, 10) RETURNING MANL INTO V_MANL_TRUNG;
    
    -- Công thức: Đề bài yêu cầu 1 bánh cần 100 gram bột và 2 quả trứng
    INSERT INTO CONGTHUC(MASP, MANL, SOLUONGTIEUHAO) VALUES (V_MASP, V_MANL_BOT, 100);
    INSERT INTO CONGTHUC(MASP, MANL, SOLUONGTIEUHAO) VALUES (V_MASP, V_MANL_TRUNG, 2);

    -- 2. GỌI HÀM KIỂM TRA MỨC ĐỘ THẮT CỔ CHAI
    -- Bột đủ làm: 1000 / 100 = 10 cái bánh
    -- Trứng đủ làm: 10 / 2 = 5 cái bánh
    -- Suy ra điểm thắt cổ chai bị chặn lại ở Trứng => Chỉ nướng được tối đa 5 cái!
    V_SO_LUONG_MAX := FUNC_SOLUONGKHADUNG(V_MASP);
    
    -- 3. XÓA DỮ LIỆU TẠM THỜI
    ROLLBACK;
    
    -- 4. BÁO CÁO KẾT QUẢ CHO CONSOLE
    IF V_SO_LUONG_MAX = 5 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Function FUNC_SOLUONGKHADUNG hoạt động!');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Function hoạt động gặp lỗi sai thuật toán! Tính capacity bị lệch, kết quả hiện tại là: ' || V_SO_LUONG_MAX);
    END IF;
END;
/

-- Test FUNC_TOPSANPHAMBANCHAY --
DECLARE
    V_MAVAITRO NUMBER;
    V_MANV NUMBER;
    V_MATT_HT NUMBER;
    V_MATT_HUY NUMBER;
    
    V_MADM NUMBER;
    V_MASP_1 NUMBER;
    V_MASP_2 NUMBER;
    V_MASP_3 NUMBER;
    
    V_MADON_1 NUMBER;
    V_MADON_2 NUMBER;
    
    V_CURSOR SYS_REFCURSOR;
    V_TENSP_RESULT NVARCHAR2(100);
    V_TONG_RESULT NUMBER;
    V_COUNT NUMBER := 0;
BEGIN
    -- 1. TẠO DỮ LIỆU ĐỂ TEST
    INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO;
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU) 
    VALUES (V_MAVAITRO, 'NV TEST TOP', '0999555888', 'TESTTOP', '123') 
    RETURNING MANV INTO V_MANV;

    INSERT INTO TRANGTHAIDON(TENTRANGTHAI) VALUES ('Hoàn thành') RETURNING MATRANGTHAI INTO V_MATT_HT;
    -- Tạo trạng thái Hủy để thử thách thuật toán
    INSERT INTO TRANGTHAIDON(TENTRANGTHAI) VALUES ('Hủy') RETURNING MATRANGTHAI INTO V_MATT_HUY;
    
    INSERT INTO DANHMUCSP(TENDM) VALUES ('BÁNH NGỌT') RETURNING MADM INTO V_MADM;
    
    -- TOP 1: Bánh A (Bán 50 cái, Hợp Lệ)
    INSERT INTO SANPHAM(MADM, TENSP, GIACOBAN, SOLUONGTON) VALUES (V_MADM, 'Bánh A', 100000, 100) RETURNING MASP INTO V_MASP_1;
    -- TOP 2: Bánh B (Bán 30 cái, Hợp Lệ)
    INSERT INTO SANPHAM(MADM, TENSP, GIACOBAN, SOLUONGTON) VALUES (V_MADM, 'Bánh B', 100000, 100) RETURNING MASP INTO V_MASP_2;
    -- Bánh C: Bán siêu khủng 100 cái NHƯNG đã bị HỦY (Bom Hàng) -> Phải lờ đi!
    INSERT INTO SANPHAM(MADM, TENSP, GIACOBAN, SOLUONGTON) VALUES (V_MADM, 'Bánh C', 100000, 100) RETURNING MASP INTO V_MASP_3;

    -- Đơn hàng 1 (Nhà vua mua hàng: Hoàn thành)
    INSERT INTO DONDATHANG(NGAYLAP, NGAYGIONHANBANH, MANV_LAP, MATRANGTHAI) 
    VALUES (SYSDATE, SYSDATE, V_MANV, V_MATT_HT) RETURNING MADON INTO V_MADON_1;
    
    INSERT INTO CTDONHANG(MADON, MASP, SOLUONG, DONGIA) VALUES (V_MADON_1, V_MASP_1, 50, 100000);
    INSERT INTO CTDONHANG(MADON, MASP, SOLUONG, DONGIA) VALUES (V_MADON_1, V_MASP_2, 30, 100000);
    
    -- Đơn hàng 2 (Khách bom hàng: Hủy) -> Bánh C bị bom
    INSERT INTO DONDATHANG(NGAYLAP, NGAYGIONHANBANH, MANV_LAP, MATRANGTHAI) 
    VALUES (SYSDATE, SYSDATE, V_MANV, V_MATT_HUY) RETURNING MADON INTO V_MADON_2;
    
    INSERT INTO CTDONHANG(MADON, MASP, SOLUONG, DONGIA) VALUES (V_MADON_2, V_MASP_3, 100, 100000);

    -- 2. GỌI HÀM KIỂM TRA RANKING (Từ hôm qua đến ngày mai)
    V_CURSOR := FUNC_TOPSANPHAMBANCHAY(TRUNC(SYSDATE) - 1, TRUNC(SYSDATE) + 1);
    
    -- 3. KIỂM TRA KẾT QUẢ (Cần quét trúng chính xác Bánh A - 50 và Bánh B - 30)
    LOOP
        FETCH V_CURSOR INTO V_TENSP_RESULT, V_TONG_RESULT;
        EXIT WHEN V_CURSOR%NOTFOUND;
        
        IF V_TENSP_RESULT = 'Bánh A' AND V_TONG_RESULT = 50 THEN
            V_COUNT := V_COUNT + 1;
        ELSIF V_TENSP_RESULT = 'Bánh B' AND V_TONG_RESULT = 30 THEN
            V_COUNT := V_COUNT + 1;
        -- Nếu phát hiện lọt Bánh C "ảo" vào danh sách, đánh sập test ngay lập tức
        ELSIF V_TENSP_RESULT = 'Bánh C' THEN
            V_COUNT := -999;
        END IF;
    END LOOP;
    CLOSE V_CURSOR;
    
    -- 4. XÓA DỮ LIỆU TẠM THỜI
    ROLLBACK;
    
    -- 5. BÁO CÁO KẾT QUẢ CHO CONSOLE
    IF V_COUNT = 2 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Function FUNC_TOPSANPHAMBANCHAY hoạt động!');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Function hoạt động sai! Lọc sai trạng thái hoặc mang ra thể loại bánh bị bom.');
    END IF;
END;
/

