-- ==========================================
-- SCRIPT CẤP QUYỀN CHO THU NGÂN ĐĂNG NHẬP
-- Chạy script này trong Oracle SQL Developer
-- ==========================================

DECLARE
    V_MAVAITRO NUMBER;
    V_MACHUCNANG_POS NUMBER;
    V_MACHUCNANG_DON NUMBER;
    V_MACHUCNANG_KHACH NUMBER;
    V_MACHUCNANG_LICHSU NUMBER;
    V_MACHUCNANG_DOISOAT NUMBER;
BEGIN
    -- 1. Tìm hoặc tạo Vai trò "Thu ngân"
    BEGIN
        SELECT MAVAITRO INTO V_MAVAITRO FROM VAITRO WHERE UPPER(TENVAITRO) = 'THU NGÂN' OR UPPER(TENVAITRO) = 'THU NGAN' FETCH FIRST 1 ROW ONLY;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            INSERT INTO VAITRO (TENVAITRO, MOTA) VALUES ('Thu ngân', 'Nhân viên phụ trách giao dịch, hóa đơn và tiền mặt')
            RETURNING MAVAITRO INTO V_MAVAITRO;
    END;

    -- 2. Tìm hoặc tạo các Chức năng (Chỉ tạo nếu chưa tồn tại)
    -- Chức năng POS
    BEGIN
        SELECT MACHUCNANG INTO V_MACHUCNANG_POS FROM CHUCNANG WHERE UPPER(TENCHUCNANG) = 'BÁN HÀNG POS' FETCH FIRST 1 ROW ONLY;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            INSERT INTO CHUCNANG (TENCHUCNANG, MOTA) VALUES ('Bán hàng POS', 'Giao diện tính tiền tại quầy') RETURNING MACHUCNANG INTO V_MACHUCNANG_POS;
    END;

    -- Chức năng Đơn Đặt Bánh (Custom)
    BEGIN
        SELECT MACHUCNANG INTO V_MACHUCNANG_DON FROM CHUCNANG WHERE UPPER(TENCHUCNANG) = 'ĐƠN ĐẶT BÁNH TÙY CHỈNH' FETCH FIRST 1 ROW ONLY;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            INSERT INTO CHUCNANG (TENCHUCNANG, MOTA) VALUES ('Đơn đặt bánh tùy chỉnh', 'Quản lý đơn hàng đặc biệt, hẹn giờ giao') RETURNING MACHUCNANG INTO V_MACHUCNANG_DON;
    END;

    -- Chức năng Khách Hàng
    BEGIN
        SELECT MACHUCNANG INTO V_MACHUCNANG_KHACH FROM CHUCNANG WHERE UPPER(TENCHUCNANG) = 'QUẢN LÝ KHÁCH HÀNG' FETCH FIRST 1 ROW ONLY;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            INSERT INTO CHUCNANG (TENCHUCNANG, MOTA) VALUES ('Quản lý Khách hàng', 'Quản lý hội viên, hạng thẻ') RETURNING MACHUCNANG INTO V_MACHUCNANG_KHACH;
    END;

    -- Chức năng Lịch sử giao dịch
    BEGIN
        SELECT MACHUCNANG INTO V_MACHUCNANG_LICHSU FROM CHUCNANG WHERE UPPER(TENCHUCNANG) = 'LỊCH SỬ GIAO DỊCH' FETCH FIRST 1 ROW ONLY;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            INSERT INTO CHUCNANG (TENCHUCNANG, MOTA) VALUES ('Lịch sử giao dịch', 'Tra cứu hóa đơn, chứng từ bán hàng') RETURNING MACHUCNANG INTO V_MACHUCNANG_LICHSU;
    END;

    -- 3. Cấp phát quyền vào bảng VAITRO_CHUCNANG (Bỏ qua nếu đã có)
    BEGIN INSERT INTO VAITRO_CHUCNANG (MAVAITRO, MACHUCNANG) VALUES (V_MAVAITRO, V_MACHUCNANG_POS); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
    BEGIN INSERT INTO VAITRO_CHUCNANG (MAVAITRO, MACHUCNANG) VALUES (V_MAVAITRO, V_MACHUCNANG_DON); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
    BEGIN INSERT INTO VAITRO_CHUCNANG (MAVAITRO, MACHUCNANG) VALUES (V_MAVAITRO, V_MACHUCNANG_KHACH); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
    BEGIN INSERT INTO VAITRO_CHUCNANG (MAVAITRO, MACHUCNANG) VALUES (V_MAVAITRO, V_MACHUCNANG_LICHSU); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Đã cấp quyền thành công cho Thu Ngân!');
END;
/
