-- =======================================================
-- CONFIGURATION SCRIPTS (Drop/Fix/Update/Test)
-- =======================================================

-- Test Procedure --
DECLARE
    V_MAVAITRO NUMBER;
    V_MANV NUMBER;
    V_THOIDIEMXOA TIMESTAMP;
    V_MANX NUMBER;
BEGIN
    -- BƯỚC 1: TẠO DỮ LIỆU CÓ LIÊN QUAN
    INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO;
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU)
    VALUES (V_MAVAITRO, 'ABC', '999999999', 'USER', '12345') RETURNING MANV INTO V_MANV;

    -- BƯỚC 2: TẠO HIỆN TRƯỜNG GIẢ
    UPDATE VAITRO
    SET THOIDIEMXOA = SYSDATE, MANX = V_MANV
    WHERE MAVAITRO = V_MAVAITRO;

    -- BƯỚC 3: GỌI PROCEDURE ĐỂ KHÔI PHỤC
    PROC_KHOIPHUCDULIEU('VAITRO', 'MAVAITRO', V_MAVAITRO);

    -- BƯỚC 4: KHÁM NGHIỆM LẠI HIỆN TRƯỜNG
    SELECT THOIDIEMXOA, MANX
    INTO V_THOIDIEMXOA, V_MANX
    FROM VAITRO
    WHERE MAVAITRO = V_MAVAITRO;

    -- BƯỚC 5: XÓA DỮ LIỆU TẠM
    DELETE FROM NHANVIEN WHERE MANV = V_MANV;
    DELETE FROM VAITRO WHERE MAVAITRO = V_MAVAITRO;
    COMMIT;

    -- BƯỚC 6: BÁO CÁO KẾT QUẢ
    IF V_THOIDIEMXOA IS NULL AND V_MANX IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'Procedure hoat dong');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Procedure khong hoat dong');
    END IF;
END;
/

-- Test PROC_DONGCADOISOAT --
DECLARE
    V_MAVAITRO NUMBER;
    V_MANV NUMBER;
    V_MACA NUMBER;
    V_TIEN_HETHONG NUMBER;
    V_TIEN_THUCTE NUMBER := 1500000;
    V_CHENHLECH NUMBER;
    V_TRANGTHAI NVARCHAR2(50);
    V_COUNT_DOISOAT NUMBER;
BEGIN
    -- BƯỚC 1: TẠO DỮ LIỆU CÓ LIÊN QUAN
    INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO;
    
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU)
    VALUES (V_MAVAITRO, 'NV TEST DOISOAT', '0999999999', 'TESTDOISOAT', '123') 
    RETURNING MANV INTO V_MANV;

    INSERT INTO CALAMVIEC(MANV, MAMAYPOS, TRANGTHAI)
    VALUES (V_MANV, 'POS01', 'Đang mở')
    RETURNING MACA INTO V_MACA;

    -- BƯỚC 2: GỌI PROCEDURE CẦN TEST
    PROC_DONGCADOISOAT(V_MACA, V_TIEN_THUCTE, 'Khach boa them tien');

    -- BƯỚC 3: KIỂM TRA KẾT QUẢ
    -- Kiểm tra trạng thái ca làm việc
    SELECT TRANGTHAI INTO V_TRANGTHAI
    FROM CALAMVIEC
    WHERE MACA = V_MACA;

    -- Kiểm tra có bảng ghi đối soát không
    SELECT COUNT(*), NVL(MAX(TONGTIENHETHONG), 0), NVL(MAX(CHENHLECH), 0)
    INTO V_COUNT_DOISOAT, V_TIEN_HETHONG, V_CHENHLECH
    FROM DOISOAT
    WHERE MACA = V_MACA;

    -- BƯỚC 4: DỌN DẸP DỮ LIỆU
    DELETE FROM DOISOAT WHERE MACA = V_MACA;
    DELETE FROM CALAMVIEC WHERE MACA = V_MACA;
    DELETE FROM NHANVIEN WHERE MANV = V_MANV;
    DELETE FROM VAITRO WHERE MAVAITRO = V_MAVAITRO;
    COMMIT;

    -- BƯỚC 5: BÁO CÁO KẾT QUẢ
    IF V_TRANGTHAI = 'Đã đóng' AND V_COUNT_DOISOAT > 0 AND V_CHENHLECH = (V_TIEN_THUCTE - V_TIEN_HETHONG) THEN
        RAISE_APPLICATION_ERROR(-20001, 'Procedure PROC_DONGCADOISOAT hoat dong dung');
    ELSE
    END IF;
END;
/

-- Test PROC_THANHTOANVATHANGHANG --
DECLARE
    V_MAVAITRO NUMBER;
    V_MANV NUMBER;
    V_MAPTTT NUMBER;
    V_MACA NUMBER;

    V_MATT_MOIDAT NUMBER;
    V_MATT_HOANTHANH NUMBER;

    V_MAHANG_KHONG NUMBER;
    V_MAHANG_BAC NUMBER;
    V_MAHANG_VANG NUMBER;

    V_MAKH NUMBER;
    V_MADON NUMBER;
    V_MAHD NUMBER;

    V_TT_RESULT NUMBER;
    V_DIEM_RESULT NUMBER;
    V_HANG_RESULT NUMBER;

    -- Randomizer để tạo thông tin User không bị trùng lặp cột UNIQUE
    V_RANDOM_SUFFIX VARCHAR2(10) := DBMS_RANDOM.STRING('A', 5);
    V_RANDOM_PHONE VARCHAR2(15) := '09' || TRUNC(DBMS_RANDOM.VALUE(10000000, 99999999));
BEGIN
    -- 1. KHỞI TẠO MÔI TRƯỜNG & VƯỢT RÀO CÁC CONSTRAINTS
    -- Tái sử dụng hoặc tạo mới Vai trò
    BEGIN SELECT MAVAITRO INTO V_MAVAITRO FROM VAITRO WHERE TENVAITRO = 'NV' FETCH FIRST 1 ROW ONLY; EXCEPTION WHEN NO_DATA_FOUND THEN INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO; END;

    -- Ràng buộc CK_NV_TRANGTHAI và UNIQUE SDT/TENDANGNHAP
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU, TRANGTHAILAMVIEC)
    VALUES (V_MAVAITRO, 'NV TEST TT', V_RANDOM_PHONE, 'TT_' || V_RANDOM_SUFFIX, '123', 1)
    RETURNING MANV INTO V_MANV;

    -- Tái sử dụng Trạng Thái Đơn
    BEGIN SELECT MATRANGTHAI INTO V_MATT_MOIDAT FROM TRANGTHAIDON WHERE TENTRANGTHAI = 'Mới đặt' FETCH FIRST 1 ROW ONLY; EXCEPTION WHEN NO_DATA_FOUND THEN INSERT INTO TRANGTHAIDON(TENTRANGTHAI) VALUES ('Mới đặt') RETURNING MATRANGTHAI INTO V_MATT_MOIDAT; END;
    BEGIN SELECT MATRANGTHAI INTO V_MATT_HOANTHANH FROM TRANGTHAIDON WHERE TENTRANGTHAI = 'Hoàn thành' FETCH FIRST 1 ROW ONLY; EXCEPTION WHEN NO_DATA_FOUND THEN INSERT INTO TRANGTHAIDON(TENTRANGTHAI) VALUES ('Hoàn thành') RETURNING MATRANGTHAI INTO V_MATT_HOANTHANH; END;

    -- Tái sử dụng Phương Thức TT
    BEGIN SELECT MAPTTT INTO V_MAPTTT FROM PHUONGTHUCTT WHERE TENPTTT = 'Tiền mặt' FETCH FIRST 1 ROW ONLY; EXCEPTION WHEN NO_DATA_FOUND THEN INSERT INTO PHUONGTHUCTT(TENPTTT) VALUES ('Tiền mặt') RETURNING MAPTTT INTO V_MAPTTT; END;

    INSERT INTO CALAMVIEC(MANV, MAMAYPOS, TRANGTHAI, THOIGIANMOCA) VALUES (V_MANV, 'POS01', 'Đang mở', SYSDATE) RETURNING MACA INTO V_MACA;

    -- Tái sử dụng Hạng Thành Viên
    BEGIN SELECT MAHANG INTO V_MAHANG_KHONG FROM HANGTHANHVIEN WHERE TENHANG = 'Không' FETCH FIRST 1 ROW ONLY; EXCEPTION WHEN NO_DATA_FOUND THEN INSERT INTO HANGTHANHVIEN(TENHANG, DIEMTOITHIEU) VALUES ('Không', 0) RETURNING MAHANG INTO V_MAHANG_KHONG; END;
    BEGIN SELECT MAHANG INTO V_MAHANG_BAC FROM HANGTHANHVIEN WHERE TENHANG = 'Bạc' FETCH FIRST 1 ROW ONLY; EXCEPTION WHEN NO_DATA_FOUND THEN INSERT INTO HANGTHANHVIEN(TENHANG, DIEMTOITHIEU) VALUES ('Bạc', 10) RETURNING MAHANG INTO V_MAHANG_BAC; END;
    BEGIN SELECT MAHANG INTO V_MAHANG_VANG FROM HANGTHANHVIEN WHERE TENHANG = 'Vàng' FETCH FIRST 1 ROW ONLY; EXCEPTION WHEN NO_DATA_FOUND THEN INSERT INTO HANGTHANHVIEN(TENHANG, DIEMTOITHIEU) VALUES ('Vàng', 100) RETURNING MAHANG INTO V_MAHANG_VANG; END;

    V_RANDOM_PHONE := '08' || TRUNC(DBMS_RANDOM.VALUE(10000000, 99999999));
    INSERT INTO KHACHHANG(HOTEN, SDT, DIEMTICHLUY, MAHANG) VALUES ('Khách Test Up Rank', V_RANDOM_PHONE, 0, V_MAHANG_KHONG) RETURNING MAKH INTO V_MAKH;

    -- Ràng buộc CK_DON_TONGTIEN, CK_DON_TIENDACOC, CK_DON_THANHTOAN bắt buộc tiền hợp lệ
    INSERT INTO DONDATHANG(NGAYGIONHANBANH, MANV_LAP, MATRANGTHAI, MAKH, HINHTHUCNHAN, TONGTIENHDBAN, TIENDACOC)
    VALUES (SYSDATE, V_MANV, V_MATT_MOIDAT, V_MAKH, 1, 500000, 0) RETURNING MADON INTO V_MADON;

    -- Khởi tạo hóa đơn cần đóng
    INSERT INTO HOADON(MADON, MACA, TONGTIENTHANHTOAN, MAPTTT)
    VALUES (V_MADON, V_MACA, 500000, V_MAPTTT) RETURNING MAHD INTO V_MAHD;

    -- 2. GỌI PROCEDURE CẦN TEST
    PROC_THANHTOANVATHANGHANG(V_MAHD, V_MAKH, 500000);

    -- 3. ĐỌC KẾT QUẢ ĐÃ CHỐT SỔ TRONG DB
    SELECT MATRANGTHAI INTO V_TT_RESULT FROM DONDATHANG WHERE MADON = V_MADON;
    SELECT DIEMTICHLUY, MAHANG INTO V_DIEM_RESULT, V_HANG_RESULT FROM KHACHHANG WHERE MAKH = V_MAKH;

    -- 4. CLEANUP MANUALLY (Loại trừ dữ liệu động rác)
    DELETE FROM HOADON WHERE MAHD = V_MAHD;
    DELETE FROM DONDATHANG WHERE MADON = V_MADON;
    DELETE FROM KHACHHANG WHERE MAKH = V_MAKH;
    DELETE FROM CALAMVIEC WHERE MACA = V_MACA;
    DELETE FROM NHANVIEN WHERE MANV = V_MANV;
    DELETE FROM HANGTHANHVIEN WHERE MAHANG = V_MAHANG_KHONG;
    DELETE FROM HANGTHANHVIEN WHERE MAHANG = V_MAHANG_BAC;
    DELETE FROM HANGTHANHVIEN WHERE MAHANG = V_MAHANG_VANG;
    DELETE FROM TRANGTHAIDON WHERE MATRANGTHAI = V_MATT_HOANTHANH;
    DELETE FROM TRANGTHAIDON WHERE MATRANGTHAI = V_MATT_MOIDAT;
    DELETE FROM VAITRO WHERE MAVAITRO = V_MAVAITRO;
    COMMIT;

    -- 5. ĐÁNH GIÁ (Mong muốn: Đơn "Hoàn thành", Khách nhảy lên hạng "Bạc", Điểm = 50)
    IF V_TT_RESULT = V_MATT_HOANTHANH AND V_DIEM_RESULT = 50 AND V_HANG_RESULT = V_MAHANG_BAC THEN
        RAISE_APPLICATION_ERROR(-20001, 'Procedure PROC_THANHTOANVATHANGHANG hoat dong!');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Procedure hoat dong sai! TrangThai=' || V_TT_RESULT || ', Diem=' || V_DIEM_RESULT || ', Hang=' || V_HANG_RESULT);
    END IF;
END;
/

-- Test PROC_HUYDONVAHOANKHO --
DECLARE
    V_MAVAITRO NUMBER;
    V_MANV NUMBER;
    V_MADM NUMBER;
    V_MASP NUMBER;
    V_MATT_MOIDAT NUMBER;
    V_MATT_HUY NUMBER;
    V_MADON NUMBER;
    V_TONKHO_TRUOC NUMBER;
    V_TONKHO_SAU NUMBER;
    V_TT_HIENTAI NUMBER;
    V_COUNT_LOG NUMBER;
    V_GHICHU_LOG NVARCHAR2(500);
    
    V_RANDOM_SUFFIX VARCHAR2(10) := DBMS_RANDOM.STRING('A', 5);
    V_RANDOM_PHONE VARCHAR2(15) := '09' || TRUNC(DBMS_RANDOM.VALUE(10000000, 99999999));
BEGIN
    -- [HOTFIX]: Cập nhật nóng cột GhiChú cho bảng Logs (Đảm bảo chạy thành công 100%)
    BEGIN
        EXECUTE IMMEDIATE 'ALTER TABLE LICHSUDONHANG ADD GHICHU NVARCHAR2(500)';
    EXCEPTION WHEN OTHERS THEN NULL; -- Lờ đi nếu bạn đã cài nó rồi!
    END;

    -- 1. KHỞI TẠO MÔI TRƯỜNG & VƯỢT RÀO CONSTRAINTS
    BEGIN SELECT MAVAITRO INTO V_MAVAITRO FROM VAITRO WHERE TENVAITRO = 'NV' FETCH FIRST 1 ROW ONLY; EXCEPTION WHEN NO_DATA_FOUND THEN INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO; END;
    
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU, TRANGTHAILAMVIEC)
    VALUES (V_MAVAITRO, 'NV TEST HUY', V_RANDOM_PHONE, 'HUY_' || V_RANDOM_SUFFIX, '123', 1)
    RETURNING MANV INTO V_MANV;

    BEGIN SELECT MATRANGTHAI INTO V_MATT_MOIDAT FROM TRANGTHAIDON WHERE TENTRANGTHAI = 'Mới đặt' FETCH FIRST 1 ROW ONLY; EXCEPTION WHEN NO_DATA_FOUND THEN INSERT INTO TRANGTHAIDON(TENTRANGTHAI) VALUES ('Mới đặt') RETURNING MATRANGTHAI INTO V_MATT_MOIDAT; END;
    BEGIN SELECT MATRANGTHAI INTO V_MATT_HUY FROM TRANGTHAIDON WHERE TENTRANGTHAI = 'Hủy' FETCH FIRST 1 ROW ONLY; EXCEPTION WHEN NO_DATA_FOUND THEN INSERT INTO TRANGTHAIDON(TENTRANGTHAI) VALUES ('Hủy') RETURNING MATRANGTHAI INTO V_MATT_HUY; END;

    BEGIN SELECT MADM INTO V_MADM FROM DANHMUCSP WHERE TENDM = 'Kho Hủy' FETCH FIRST 1 ROW ONLY; EXCEPTION WHEN NO_DATA_FOUND THEN INSERT INTO DANHMUCSP(TENDM) VALUES ('Kho Hủy') RETURNING MADM INTO V_MADM; END;

    INSERT INTO SANPHAM(MADM, TENSP, GIACOBAN, SOLUONGTON) 
    VALUES (V_MADM, 'Bánh Tiramisu Demo', 50000, 10) RETURNING MASP INTO V_MASP;

    V_TONKHO_TRUOC := 10;
    INSERT INTO DONDATHANG(NGAYGIONHANBANH, MANV_LAP, MATRANGTHAI, HINHTHUCNHAN)
    VALUES (SYSDATE, V_MANV, V_MATT_MOIDAT, 1) RETURNING MADON INTO V_MADON;

    -- Khách mua 5 cái
    INSERT INTO NANGLUCSANXUAT(NGAYSANXUAT, GIOIHANSOBANH) VALUES (SYSDATE, 100);
    INSERT INTO CTDONHANG(MADON, MASP, SOLUONG, DONGIA)
    VALUES (V_MADON, V_MASP, 5, 50000); 

    -- 2. GỌI HOẠT ĐỘNG KIỂM TRA (Test Hủy Đơn & Kích hoạt Hoàn Kho)
    PROC_HUYDONVAHOANKHO(V_MADON, 'Khách hàng bị tai nạn không thể nhận bánh', V_MANV);

    -- 3. QUÉT GIAO DỊCH SAU KHI VÀO LƯỚI
    SELECT SOLUONGTON INTO V_TONKHO_SAU FROM SANPHAM WHERE MASP = V_MASP;
    SELECT MATRANGTHAI INTO V_TT_HIENTAI FROM DONDATHANG WHERE MADON = V_MADON;
    SELECT COUNT(*), MAX(GHICHU) INTO V_COUNT_LOG, V_GHICHU_LOG FROM LICHSUDONHANG WHERE MADON = V_MADON;

    -- 4. CLEAN DỮ LIỆU ĐÃ COMMIT
    DELETE FROM LICHSUDONHANG WHERE MADON = V_MADON;
    DELETE FROM CTDONHANG WHERE MADON = V_MADON;
    DELETE FROM DONDATHANG WHERE MADON = V_MADON;
    DELETE FROM SANPHAM WHERE MASP = V_MASP;
    DELETE FROM NHANVIEN WHERE MANV = V_MANV;
    COMMIT;
    -- 5. BÁO CÁO NHẬN ĐỊNH
    IF V_TONKHO_SAU = 10 AND V_TT_HIENTAI = V_MATT_HUY AND V_COUNT_LOG = 1 AND V_GHICHU_LOG = 'Khách hàng bị tai nạn không thể nhận bánh' THEN
        RAISE_APPLICATION_ERROR(-20001, 'Procedure PROC_HUYDONVAHOANKHO hoat dong!');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Lỗi Procedure! Không hoàn trả đủ hàng hoặc Log ghi chép lỗi!');
    END IF;
END;
/

-- Test PROC_XUATHUYBANH --
DECLARE
    V_MAVAITRO NUMBER;
    V_MANV NUMBER;
    V_MADM NUMBER;
    V_MASP NUMBER;
    V_MAPX NUMBER;
    V_TONKHO_TRUOC NUMBER := 20;
    V_SOLUONGHUY NUMBER := 5;
    V_TONKHO_SAU NUMBER;
    
    V_COUNT_PX NUMBER;
    V_COUNT_CTPX NUMBER;
    
    V_RANDOM_SUFFIX VARCHAR2(10) := DBMS_RANDOM.STRING('A', 5);
    V_RANDOM_PHONE VARCHAR2(15) := '09' || TRUNC(DBMS_RANDOM.VALUE(10000000, 99999999));
BEGIN
    -- 1. KHỞI TẠO MÔI TRƯỜNG & VƯỢT RÀO CONSTRAINTS
    BEGIN SELECT MAVAITRO INTO V_MAVAITRO FROM VAITRO WHERE TENVAITRO = 'NV' FETCH FIRST 1 ROW ONLY; EXCEPTION WHEN NO_DATA_FOUND THEN INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO; END;
    
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU, TRANGTHAILAMVIEC)
    VALUES (V_MAVAITRO, 'NV TEST HUY BANH', V_RANDOM_PHONE, 'XHB_' || V_RANDOM_SUFFIX, '123', 1)
    RETURNING MANV INTO V_MANV;

    BEGIN SELECT MADM INTO V_MADM FROM DANHMUCSP WHERE TENDM = 'Kho Hủy Lỗi' FETCH FIRST 1 ROW ONLY; EXCEPTION WHEN NO_DATA_FOUND THEN INSERT INTO DANHMUCSP(TENDM) VALUES ('Kho Hủy Lỗi') RETURNING MADM INTO V_MADM; END;

    INSERT INTO SANPHAM(MADM, TENSP, GIACOBAN, SOLUONGTON) 
    VALUES (V_MADM, 'Bánh Thiu 01', 15000, V_TONKHO_TRUOC) RETURNING MASP INTO V_MASP;

    -- 2. GỌI HOẠT ĐỘNG KIỂM TRA
    PROC_XUATHUYBANH(V_MASP, V_SOLUONGHUY, 'Bánh mốc do trời nồm ẩm', V_MANV);

    -- 3. QUÉT GIAO DỊCH SAU KHI VÀO LƯỚI
    SELECT SOLUONGTON INTO V_TONKHO_SAU FROM SANPHAM WHERE MASP = V_MASP;
    
    SELECT COUNT(*) INTO V_COUNT_PX FROM PHIEUXUATKHO WHERE MANV = V_MANV;
    SELECT COUNT(*) INTO V_COUNT_CTPX FROM CTPHIEUXUAT_TP WHERE MASP = V_MASP;

    SELECT MAPX INTO V_MAPX FROM PHIEUXUATKHO WHERE MANV = V_MANV FETCH FIRST 1 ROW ONLY;

    -- 4. CLEAN DỮ LIỆU ĐÃ COMMIT
    DELETE FROM CTPHIEUXUAT_TP WHERE MAPX = V_MAPX;
    DELETE FROM PHIEUXUATKHO WHERE MAPX = V_MAPX;
    DELETE FROM SANPHAM WHERE MASP = V_MASP;
    DELETE FROM NHANVIEN WHERE MANV = V_MANV;
    DELETE FROM VAITRO WHERE MAVAITRO = V_MAVAITRO;
    DELETE FROM DANHMUCSP WHERE MADM = V_MADM;
    COMMIT;

    -- 5. BÁO CÁO NHẬN ĐỊNH
    IF V_TONKHO_SAU = (V_TONKHO_TRUOC - V_SOLUONGHUY) AND V_COUNT_PX = 1 AND V_COUNT_CTPX = 1 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Procedure PROC_XUATHUYBANH hoat dong!');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Lỗi Procedure! Không trừ được kho (' || V_TONKHO_SAU || ') hoặc không tạo đủ chi tiết Xuất!');
    END IF;
END;
/

-- Test PROC_NHAPKHO (Truyền tham số qua Data Array/JSON) --
DECLARE
    V_MAVAITRO NUMBER;
    V_MANV NUMBER;
    V_MADVT NUMBER;
    V_MANL_1 NUMBER;
    V_MANL_2 NUMBER;
    V_MANCC NUMBER;
    V_JSON_PAYLOAD CLOB;
    V_MAPN NUMBER;
    
    V_TONGTIENNHAP NUMBER;
    V_KHO_NL1 NUMBER;
    V_KHO_NL2 NUMBER;
    V_COUNT_CT NUMBER;
    
    V_RANDOM_SUFFIX VARCHAR2(10) := DBMS_RANDOM.STRING('A', 5);
    V_RANDOM_PHONE VARCHAR2(15) := '09' || TRUNC(DBMS_RANDOM.VALUE(10000000, 99999999));
    V_RANDOM_NCC_PHONE VARCHAR2(15) := '08' || TRUNC(DBMS_RANDOM.VALUE(10000000, 99999999));
BEGIN
    -- 1. KHỞI TẠO MÔI TRƯƠNG & VƯỢT RÀO CONSTRAINTS
    BEGIN SELECT MAVAITRO INTO V_MAVAITRO FROM VAITRO WHERE TENVAITRO = 'NV' FETCH FIRST 1 ROW ONLY; EXCEPTION WHEN NO_DATA_FOUND THEN INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO; END;
    
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU, TRANGTHAILAMVIEC)
    VALUES (V_MAVAITRO, 'NV TEST NHAP KHO', V_RANDOM_PHONE, 'NK_' || V_RANDOM_SUFFIX, '123', 1)
    RETURNING MANV INTO V_MANV;

    BEGIN SELECT MADVT INTO V_MADVT FROM DONVITINH WHERE TENDVT = 'Kg' FETCH FIRST 1 ROW ONLY; EXCEPTION WHEN NO_DATA_FOUND THEN INSERT INTO DONVITINH(TENDVT) VALUES ('Kg') RETURNING MADVT INTO V_MADVT; END;

    INSERT INTO NGUYENLIEU(TENNL, MADVT, SOLUONGTONTONG, GIAVONTRUNGBINH) VALUES ('Bột Mì X_' || V_RANDOM_SUFFIX, V_MADVT, 10, 20000) RETURNING MANL INTO V_MANL_1;
    INSERT INTO NGUYENLIEU(TENNL, MADVT, SOLUONGTONTONG, GIAVONTRUNGBINH) VALUES ('Đường T_' || V_RANDOM_SUFFIX, V_MADVT, 5, 10000) RETURNING MANL INTO V_MANL_2;

    INSERT INTO NHACUNGCAP(TENNCC, SDT) VALUES ('NCC Bột Toàn Cầu ' || V_RANDOM_SUFFIX, V_RANDOM_NCC_PHONE) RETURNING MANCC INTO V_MANCC;

    -- 2. DỰNG MÔ HÌNH DỮ LIỆU JSON DẠNG MẢNG (Mô phỏng dữ liệu từ Java truyền xuống DB)
    V_JSON_PAYLOAD := '
    [
        {
            "MaNL": ' || V_MANL_1 || ',
            "SoLuong": 50,
            "DonGia": 22000,
            "NgaySanXuat": "' || TO_CHAR(SYSDATE - 10, 'YYYY-MM-DD') || '",
            "HanSuDung": "' || TO_CHAR(SYSDATE + 180, 'YYYY-MM-DD') || '"
        },
        {
            "MaNL": ' || V_MANL_2 || ',
            "SoLuong": 20,
            "DonGia": 12000,
            "NgaySanXuat": "' || TO_CHAR(SYSDATE - 5, 'YYYY-MM-DD') || '",
            "HanSuDung": "' || TO_CHAR(SYSDATE + 360, 'YYYY-MM-DD') || '"
        }
    ]';

    -- 3. GỌI PROCEDURE KHÉP KÍN (Batch-Insert & Triggers)
    PROC_NHAPKHO(V_MANV, V_MANCC, V_JSON_PAYLOAD);

    -- 4. BÓC TÁCH KẾT QUẢ TỪ DATABASE
    -- Lấy mã phiếu nhập khớp với nhân viên Test (do test độc lập sinh riêng NV)
    SELECT MAPN, TONGTIENNHAP INTO V_MAPN, V_TONGTIENNHAP FROM PHIEUNHAPKHO WHERE MANV = V_MANV FETCH FIRST 1 ROW ONLY;
    
    -- Kiểm tra xem Tồn Kho Tổng có được Trigger âm thầm cộng dồn không?
    SELECT SOLUONGTONTONG INTO V_KHO_NL1 FROM NGUYENLIEU WHERE MANL = V_MANL_1;
    SELECT SOLUONGTONTONG INTO V_KHO_NL2 FROM NGUYENLIEU WHERE MANL = V_MANL_2;
    SELECT COUNT(*) INTO V_COUNT_CT FROM CTPHIEUNHAP WHERE MAPN = V_MAPN;

    -- 5. CLEANUP DỮ LIỆU RÁC
    DELETE FROM CTPHIEUNHAP WHERE MAPN = V_MAPN;
    DELETE FROM PHIEUNHAPKHO WHERE MAPN = V_MAPN;
    DELETE FROM NGUYENLIEU WHERE MANL IN (V_MANL_1, V_MANL_2);
    DELETE FROM NHACUNGCAP WHERE MANCC = V_MANCC;
    DELETE FROM NHANVIEN WHERE MANV = V_MANV;
    DELETE FROM VAITRO WHERE MAVAITRO = V_MAVAITRO;
    COMMIT;

    -- 6. ĐÁNH GIÁ LUỒNG NGHIỆP VỤ (Batch-insert thành công 2 tiết, NL1 tăng 10->60, NL2 từ 5->25)
    IF V_KHO_NL1 = 60 AND V_KHO_NL2 = 25 AND V_COUNT_CT = 2 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Procedure PROC_NHAPKHO hoạt động!');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Lỗi Procedure Nhập Kho JSON! KQ Không Khớp! KhoNL1=' || V_KHO_NL1 || ', KhoNL2=' || V_KHO_NL2 || ', CountCT=' || V_COUNT_CT);
    END IF;
END;
/
