-- =========================================================================
-- SEED DỮ LIỆU BẤT BIẾN — H3K BAKERY MANAGEMENT SYSTEM
-- MỤC ĐÍCH: Khởi tạo cấu hình cố định cho hệ thống (không thay đổi theo nghiệp vụ)
-- CÁCH DÙNG: Chạy sau khi đã tạo xong Schema (Bảng, Ràng buộc, Procedure, Trigger)
-- ĐẶC ĐIỂM: Idempotent — Có thể chạy lại nhiều lần không gây trùng lặp
-- =========================================================================


-- =========================================================================
-- 1. VAI TRÒ HỆ THỐNG (5 vai trò, insert theo thứ tự ID 1→5)
-- =========================================================================
INSERT INTO VAITRO (TENVAITRO, MOTA) SELECT N'Quản lý',  N'Điều hành và quản lý toàn bộ hệ thống'       FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM VAITRO WHERE TENVAITRO = N'Quản lý');
INSERT INTO VAITRO (TENVAITRO, MOTA) SELECT N'Thu ngân', N'Bán hàng và chăm sóc khách hàng tại quầy'    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM VAITRO WHERE TENVAITRO = N'Thu ngân');
INSERT INTO VAITRO (TENVAITRO, MOTA) SELECT N'Thợ bếp',  N'Sản xuất bánh và điều phối đơn trong bếp'    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM VAITRO WHERE TENVAITRO = N'Thợ bếp');
INSERT INTO VAITRO (TENVAITRO, MOTA) SELECT N'Thủ kho',  N'Quản lý kho nguyên liệu và nhập xuất kho'    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM VAITRO WHERE TENVAITRO = N'Thủ kho');
COMMIT;


-- =========================================================================
-- 2. CHỨC NĂNG HỆ THỐNG (Module phân quyền — ID thủ công)
-- =========================================================================
INSERT INTO CHUCNANG (MACHUCNANG, TENCHUCNANG, MOTA, MODULE) SELECT 1, N'Hệ thống',  N'Quản lý cấu hình và phân quyền hệ thống', 'SYSTEM'    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CHUCNANG WHERE MACHUCNANG = 1);
INSERT INTO CHUCNANG (MACHUCNANG, TENCHUCNANG, MOTA, MODULE) SELECT 2, N'Nhân sự',   N'Quản lý nhân viên và vai trò',             'HR'         FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CHUCNANG WHERE MACHUCNANG = 2);
INSERT INTO CHUCNANG (MACHUCNANG, TENCHUCNANG, MOTA, MODULE) SELECT 3, N'Khách hàng',N'Quản lý khách hàng và hạng thành viên',    'CRM'        FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CHUCNANG WHERE MACHUCNANG = 3);
INSERT INTO CHUCNANG (MACHUCNANG, TENCHUCNANG, MOTA, MODULE) SELECT 4, N'Sản phẩm',  N'Quản lý danh mục và sản phẩm',             'INVENTORY'  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CHUCNANG WHERE MACHUCNANG = 4);
INSERT INTO CHUCNANG (MACHUCNANG, TENCHUCNANG, MOTA, MODULE) SELECT 5, N'Kho',       N'Quản lý nguyên liệu và nhập xuất kho',     'INVENTORY'  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CHUCNANG WHERE MACHUCNANG = 5);
INSERT INTO CHUCNANG (MACHUCNANG, TENCHUCNANG, MOTA, MODULE) SELECT 6, N'Bán hàng',  N'Màn hình bán hàng POS',                    'POS'        FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CHUCNANG WHERE MACHUCNANG = 6);
INSERT INTO CHUCNANG (MACHUCNANG, TENCHUCNANG, MOTA, MODULE) SELECT 7, N'Đơn hàng',  N'Quản lý đơn đặt hàng và trạng thái',       'POS'        FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CHUCNANG WHERE MACHUCNANG = 7);
INSERT INTO CHUCNANG (MACHUCNANG, TENCHUCNANG, MOTA, MODULE) SELECT 8, N'Báo cáo',   N'Xem báo cáo và thống kê doanh thu',        'REPORTS'    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CHUCNANG WHERE MACHUCNANG = 8);
COMMIT;


-- =========================================================================
-- 3. PHÂN QUYỀN MẶC ĐỊNH (VAITRO_CHUCNANG)
-- Quản lý (1): Toàn quyền tất cả module
-- Thu ngân (2): Bán hàng, Khách hàng, Đơn hàng
-- Kế toán  (3): Báo cáo (xem)
-- Thợ bếp  (4): Đơn hàng (xem), Kho (xem công thức)
-- Thủ kho  (5): Kho (toàn quyền), Sản phẩm (xem)
-- =========================================================================

-- Quản lý — toàn quyền 8 module
INSERT INTO VAITRO_CHUCNANG (MAVAITRO, MACHUCNANG, CAN_VIEW, CAN_ADD, CAN_EDIT, CAN_DELETE, CAN_DOWNLOAD)
SELECT VT.MAVAITRO, CN.MACHUCNANG, 1, 1, 1, 1, 1
FROM VAITRO VT, CHUCNANG CN
WHERE VT.TENVAITRO = N'Quản lý'
  AND NOT EXISTS (SELECT 1 FROM VAITRO_CHUCNANG VC WHERE VC.MAVAITRO = VT.MAVAITRO AND VC.MACHUCNANG = CN.MACHUCNANG);

-- Thu ngân — Bán hàng(6), Khách hàng(3), Đơn hàng(7)
INSERT INTO VAITRO_CHUCNANG (MAVAITRO, MACHUCNANG, CAN_VIEW, CAN_ADD, CAN_EDIT, CAN_DELETE, CAN_DOWNLOAD)
SELECT VT.MAVAITRO, CN.MACHUCNANG, 1, 1, 1, 0, 0
FROM VAITRO VT, CHUCNANG CN
WHERE VT.TENVAITRO = N'Thu ngân' AND CN.MACHUCNANG IN (3, 6, 7)
  AND NOT EXISTS (SELECT 1 FROM VAITRO_CHUCNANG VC WHERE VC.MAVAITRO = VT.MAVAITRO AND VC.MACHUCNANG = CN.MACHUCNANG);

-- Thợ bếp — Đơn hàng(7): xem; Kho(5): xem
INSERT INTO VAITRO_CHUCNANG (MAVAITRO, MACHUCNANG, CAN_VIEW, CAN_ADD, CAN_EDIT, CAN_DELETE, CAN_DOWNLOAD)
SELECT VT.MAVAITRO, CN.MACHUCNANG, 1, 0, 0, 0, 0
FROM VAITRO VT, CHUCNANG CN
WHERE VT.TENVAITRO = N'Thợ bếp' AND CN.MACHUCNANG IN (5, 7)
  AND NOT EXISTS (SELECT 1 FROM VAITRO_CHUCNANG VC WHERE VC.MAVAITRO = VT.MAVAITRO AND VC.MACHUCNANG = CN.MACHUCNANG);

-- Thủ kho — Kho(5): toàn quyền; Sản phẩm(4): xem
INSERT INTO VAITRO_CHUCNANG (MAVAITRO, MACHUCNANG, CAN_VIEW, CAN_ADD, CAN_EDIT, CAN_DELETE, CAN_DOWNLOAD)
SELECT VT.MAVAITRO, 5 AS MACHUCNANG, 1, 1, 1, 1, 0
FROM VAITRO VT
WHERE VT.TENVAITRO = N'Thủ kho'
  AND NOT EXISTS (SELECT 1 FROM VAITRO_CHUCNANG VC WHERE VC.MAVAITRO = VT.MAVAITRO AND VC.MACHUCNANG = 5);

INSERT INTO VAITRO_CHUCNANG (MAVAITRO, MACHUCNANG, CAN_VIEW, CAN_ADD, CAN_EDIT, CAN_DELETE, CAN_DOWNLOAD)
SELECT VT.MAVAITRO, 4 AS MACHUCNANG, 1, 0, 0, 0, 0
FROM VAITRO VT
WHERE VT.TENVAITRO = N'Thủ kho'
  AND NOT EXISTS (SELECT 1 FROM VAITRO_CHUCNANG VC WHERE VC.MAVAITRO = VT.MAVAITRO AND VC.MACHUCNANG = 4);

COMMIT;


-- =========================================================================
-- 4. HẠNG THÀNH VIÊN (4 hạng cố định)
-- =========================================================================
INSERT INTO HANGTHANHVIEN (TENHANG, DIEMTOITHIEU, PHANTRAMGIAMGIA) SELECT N'Không',     0,    0  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM HANGTHANHVIEN WHERE TENHANG = N'Không');
INSERT INTO HANGTHANHVIEN (TENHANG, DIEMTOITHIEU, PHANTRAMGIAMGIA) SELECT N'Bạc',      100,   5  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM HANGTHANHVIEN WHERE TENHANG = N'Bạc');
INSERT INTO HANGTHANHVIEN (TENHANG, DIEMTOITHIEU, PHANTRAMGIAMGIA) SELECT N'Vàng',     500,  10  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM HANGTHANHVIEN WHERE TENHANG = N'Vàng');
INSERT INTO HANGTHANHVIEN (TENHANG, DIEMTOITHIEU, PHANTRAMGIAMGIA) SELECT N'Kim cương',2000, 15  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM HANGTHANHVIEN WHERE TENHANG = N'Kim cương');
COMMIT;


-- =========================================================================
-- 5. PHƯƠNG THỨC THANH TOÁN
-- =========================================================================
INSERT INTO PHUONGTHUCTT (TENPTTT) SELECT N'Tiền mặt'    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PHUONGTHUCTT WHERE TENPTTT = N'Tiền mặt');
INSERT INTO PHUONGTHUCTT (TENPTTT) SELECT N'Chuyển khoản' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PHUONGTHUCTT WHERE TENPTTT = N'Chuyển khoản');
COMMIT;


-- =========================================================================
-- 6. DANH MỤC SẢN PHẨM (4 danh mục chính)
-- =========================================================================
INSERT INTO DANHMUCSP (TENDM) SELECT N'Cake'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM DANHMUCSP WHERE UPPER(TENDM) = 'CAKE');
INSERT INTO DANHMUCSP (TENDM) SELECT N'Cookie'   FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM DANHMUCSP WHERE UPPER(TENDM) = 'COOKIE');
INSERT INTO DANHMUCSP (TENDM) SELECT N'Bread'    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM DANHMUCSP WHERE UPPER(TENDM) = 'BREAD');
INSERT INTO DANHMUCSP (TENDM) SELECT N'Bánh Đặt' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM DANHMUCSP WHERE UPPER(TENDM) = N'BÁNH ĐẶT');
COMMIT;


-- =========================================================================
-- 7. ĐƠN VỊ TÍNH KHO
-- =========================================================================
INSERT INTO DONVITINH (TENDVT) SELECT N'Kg'   FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM DONVITINH WHERE TENDVT = N'Kg');
INSERT INTO DONVITINH (TENDVT) SELECT N'Lít'  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM DONVITINH WHERE TENDVT = N'Lít');
INSERT INTO DONVITINH (TENDVT) SELECT N'Quả'  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM DONVITINH WHERE TENDVT = N'Quả');
INSERT INTO DONVITINH (TENDVT) SELECT N'Gram' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM DONVITINH WHERE TENDVT = N'Gram');
INSERT INTO DONVITINH (TENDVT) SELECT N'Hộp'  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM DONVITINH WHERE TENDVT = N'Hộp');
COMMIT;


-- =========================================================================
-- 8. LOẠI THU CHI
-- =========================================================================
INSERT INTO LOAITHUCHI (TENLOAITHUCHI, PHANLOAI) SELECT N'Bán hàng',  N'Thu' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LOAITHUCHI WHERE TENLOAITHUCHI = N'Bán hàng');
INSERT INTO LOAITHUCHI (TENLOAITHUCHI, PHANLOAI) SELECT N'Nhập hàng', N'Chi' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LOAITHUCHI WHERE TENLOAITHUCHI = N'Nhập hàng');
INSERT INTO LOAITHUCHI (TENLOAITHUCHI, PHANLOAI) SELECT N'Chi phí khác', N'Chi' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LOAITHUCHI WHERE TENLOAITHUCHI = N'Chi phí khác');
COMMIT;


-- =========================================================================
-- 9. TÙY CHỈNH BÁNH (Kích cỡ, Cốt, Nhân, Trang trí — cấu hình cố định)
-- =========================================================================

-- Kích cỡ bánh
INSERT INTO KICHCOBANH (TENKC, PHUPHI) SELECT N'16cm', 0      FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM KICHCOBANH WHERE TENKC = N'16cm');
INSERT INTO KICHCOBANH (TENKC, PHUPHI) SELECT N'18cm', 50000  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM KICHCOBANH WHERE TENKC = N'18cm');
INSERT INTO KICHCOBANH (TENKC, PHUPHI) SELECT N'20cm', 100000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM KICHCOBANH WHERE TENKC = N'20cm');
INSERT INTO KICHCOBANH (TENKC, PHUPHI) SELECT N'22cm', 150000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM KICHCOBANH WHERE TENKC = N'22cm');

-- Cốt bánh
INSERT INTO COTBANH (TENCOT, PHUPHI) SELECT N'Vani',     0      FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM COTBANH WHERE TENCOT = N'Vani');
INSERT INTO COTBANH (TENCOT, PHUPHI) SELECT N'Socola',   20000  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM COTBANH WHERE TENCOT = N'Socola');
INSERT INTO COTBANH (TENCOT, PHUPHI) SELECT N'Matcha',   25000  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM COTBANH WHERE TENCOT = N'Matcha');
INSERT INTO COTBANH (TENCOT, PHUPHI) SELECT N'Hồng trà', 25000  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM COTBANH WHERE TENCOT = N'Hồng trà');

-- Nhân bánh
INSERT INTO NHANBANH (TENNHAN, PHUPHI) SELECT N'Dâu tây',    15000  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NHANBANH WHERE TENNHAN = N'Dâu tây');
INSERT INTO NHANBANH (TENNHAN, PHUPHI) SELECT N'Việt quất',  20000  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NHANBANH WHERE TENNHAN = N'Việt quất');
INSERT INTO NHANBANH (TENNHAN, PHUPHI) SELECT N'Kem phô mai',25000  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NHANBANH WHERE TENNHAN = N'Kem phô mai');
INSERT INTO NHANBANH (TENNHAN, PHUPHI) SELECT N'Trái cây hỗn hợp', 18000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NHANBANH WHERE TENNHAN = N'Trái cây hỗn hợp');

-- Kiểu trang trí
INSERT INTO KIEUTRANGTRI (TENTRANGTRI, PHUPHI) SELECT N'Đơn giản',  0      FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM KIEUTRANGTRI WHERE TENTRANGTRI = N'Đơn giản');
INSERT INTO KIEUTRANGTRI (TENTRANGTRI, PHUPHI) SELECT N'Hoa kem',   30000  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM KIEUTRANGTRI WHERE TENTRANGTRI = N'Hoa kem');
INSERT INTO KIEUTRANGTRI (TENTRANGTRI, PHUPHI) SELECT N'Fondant',   80000  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM KIEUTRANGTRI WHERE TENTRANGTRI = N'Fondant');
INSERT INTO KIEUTRANGTRI (TENTRANGTRI, PHUPHI) SELECT N'In hình ảnh', 50000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM KIEUTRANGTRI WHERE TENTRANGTRI = N'In hình ảnh');

COMMIT;

-- =========================================================================
-- END OF SEED — Dữ liệu nghiệp vụ (Sản phẩm, Khách hàng, Nguyên liệu,
-- Nhà cung cấp) được tạo qua giao diện Java.
-- =========================================================================


-- =========================================================================
-- 10. TÀI KHOẢN MẶC ĐỊNH (5 nhân viên — 1 mỗi vai trò)
-- Mật khẩu mặc định: Admin@123 — YÊU CẦU đổi sau lần đăng nhập đầu tiên
-- =========================================================================
DECLARE
    v_manv_1 NUMBER; -- Quản lý
    v_manv_2 NUMBER; -- Thu ngân
    v_manv_3 NUMBER; -- Kế toán
    v_manv_4 NUMBER; -- Thợ bếp
    v_manv_5 NUMBER; -- Thủ kho
BEGIN
    -- Quản lý
    IF NOT EXISTS (SELECT 1 FROM TAIKHOAN WHERE TENDANGNHAP = 'quanly') THEN
        INSERT INTO NHANVIEN (HOTEN, SDT, TRANGTHAILAMVIEC)
        VALUES (N'Nguyễn Văn Minh', '0901000001', 1) RETURNING MANV INTO v_manv_1;
        INSERT INTO TAIKHOAN (MANV, TENDANGNHAP, MATKHAU, TRANGTHAITK)
        VALUES (v_manv_1, 'quanly', 'Admin@123', 1);
        INSERT INTO NHANVIEN_VAITRO (MANV, MAVAITRO)
        SELECT v_manv_1, MAVAITRO FROM VAITRO WHERE TENVAITRO = N'Quản lý';
    END IF;

    -- Thu ngân
    IF NOT EXISTS (SELECT 1 FROM TAIKHOAN WHERE TENDANGNHAP = 'thungan') THEN
        INSERT INTO NHANVIEN (HOTEN, SDT, TRANGTHAILAMVIEC)
        VALUES (N'Trần Thị Lan', '0901000002', 1) RETURNING MANV INTO v_manv_2;
        INSERT INTO TAIKHOAN (MANV, TENDANGNHAP, MATKHAU, TRANGTHAITK)
        VALUES (v_manv_2, 'thungan', 'Admin@123', 1);
        INSERT INTO NHANVIEN_VAITRO (MANV, MAVAITRO)
        SELECT v_manv_2, MAVAITRO FROM VAITRO WHERE TENVAITRO = N'Thu ngân';
    END IF;

    -- Kế toán
    IF NOT EXISTS (SELECT 1 FROM TAIKHOAN WHERE TENDANGNHAP = 'ketoan') THEN
        INSERT INTO NHANVIEN (HOTEN, SDT, TRANGTHAILAMVIEC)
        VALUES (N'Lê Hoàng Nam', '0901000003', 1) RETURNING MANV INTO v_manv_3;
        INSERT INTO TAIKHOAN (MANV, TENDANGNHAP, MATKHAU, TRANGTHAITK)
        VALUES (v_manv_3, 'ketoan', 'Admin@123', 1);
        INSERT INTO NHANVIEN_VAITRO (MANV, MAVAITRO)
        SELECT v_manv_3, MAVAITRO FROM VAITRO WHERE TENVAITRO = N'Kế toán';
    END IF;

    -- Thợ bếp
    IF NOT EXISTS (SELECT 1 FROM TAIKHOAN WHERE TENDANGNHAP = 'thobep') THEN
        INSERT INTO NHANVIEN (HOTEN, SDT, TRANGTHAILAMVIEC)
        VALUES (N'Phạm Văn Hùng', '0901000004', 1) RETURNING MANV INTO v_manv_4;
        INSERT INTO TAIKHOAN (MANV, TENDANGNHAP, MATKHAU, TRANGTHAITK)
        VALUES (v_manv_4, 'thobep', 'Admin@123', 1);
        INSERT INTO NHANVIEN_VAITRO (MANV, MAVAITRO)
        SELECT v_manv_4, MAVAITRO FROM VAITRO WHERE TENVAITRO = N'Thợ bếp';
    END IF;

    -- Thủ kho
    IF NOT EXISTS (SELECT 1 FROM TAIKHOAN WHERE TENDANGNHAP = 'thukho') THEN
        INSERT INTO NHANVIEN (HOTEN, SDT, TRANGTHAILAMVIEC)
        VALUES (N'Võ Thị Hoa', '0901000005', 1) RETURNING MANV INTO v_manv_5;
        INSERT INTO TAIKHOAN (MANV, TENDANGNHAP, MATKHAU, TRANGTHAITK)
        VALUES (v_manv_5, 'thukho', 'Admin@123', 1);
        INSERT INTO NHANVIEN_VAITRO (MANV, MAVAITRO)
        SELECT v_manv_5, MAVAITRO FROM VAITRO WHERE TENVAITRO = N'Thủ kho';
    END IF;

    COMMIT;
END;
/