-- =========================================================================
-- SEED DỮ LIỆU HỆ THỐNG (POS, KHO, NHÂN SỰ, KHÁCH HÀNG)
-- MỤC ĐÍCH: Khởi tạo dữ liệu mẫu cho toàn bộ hệ thống
-- CÁCH DÙNG: Chạy sau khi đã tạo xong Schema (Bảng, Ràng buộc, Procedure)
-- ĐẶC ĐIỂM: Idempotent (Có thể chạy nhiều lần mà không gây trùng lặp dữ liệu)
-- =========================================================================

-- 1) DANH MỤC SẢN PHẨM
INSERT INTO DANHMUCSP (TENDM) SELECT N'Cake' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM DANHMUCSP WHERE UPPER(TENDM) = 'CAKE');
INSERT INTO DANHMUCSP (TENDM) SELECT N'Cookie' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM DANHMUCSP WHERE UPPER(TENDM) = 'COOKIE');
INSERT INTO DANHMUCSP (TENDM) SELECT N'Bread' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM DANHMUCSP WHERE UPPER(TENDM) = 'BREAD');
INSERT INTO DANHMUCSP (TENDM) SELECT N'Bánh Đặt' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM DANHMUCSP WHERE UPPER(TENDM) = N'BÁNH ĐẶT');
COMMIT;

-- 2) TRẠNG THÁI ĐƠN HÀNG
INSERT INTO TRANGTHAIDON (TENTRANGTHAI) SELECT N'Mới đặt' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TRANGTHAIDON WHERE TENTRANGTHAI = N'Mới đặt');
INSERT INTO TRANGTHAIDON (TENTRANGTHAI) SELECT N'Đã cọc' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TRANGTHAIDON WHERE TENTRANGTHAI = N'Đã cọc');
INSERT INTO TRANGTHAIDON (TENTRANGTHAI) SELECT N'Đang sản xuất' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TRANGTHAIDON WHERE TENTRANGTHAI = N'Đang sản xuất');
INSERT INTO TRANGTHAIDON (TENTRANGTHAI) SELECT N'Chờ giao' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TRANGTHAIDON WHERE TENTRANGTHAI = N'Chờ giao');
INSERT INTO TRANGTHAIDON (TENTRANGTHAI) SELECT N'Chờ khách lấy' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TRANGTHAIDON WHERE TENTRANGTHAI = N'Chờ khách lấy');
INSERT INTO TRANGTHAIDON (TENTRANGTHAI) SELECT N'Hoàn thành' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TRANGTHAIDON WHERE TENTRANGTHAI = N'Hoàn thành');
INSERT INTO TRANGTHAIDON (TENTRANGTHAI) SELECT N'Hủy' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TRANGTHAIDON WHERE TENTRANGTHAI = N'Hủy');
INSERT INTO TRANGTHAIDON (TENTRANGTHAI) SELECT N'Hoàn hàng' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TRANGTHAIDON WHERE TENTRANGTHAI = N'Hoàn hàng');
COMMIT;

-- 3) SẢN PHẨM MẪU CHO POS
INSERT INTO SANPHAM (MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, SOLUONGTON, THOIGIANCHUANBI)
SELECT (SELECT MADM FROM DANHMUCSP WHERE UPPER(TENDM) = 'CAKE' FETCH FIRST 1 ROW ONLY), N'Bánh kem vani 16cm', 260000, '/images/products/cake_vani_16.png', 0, 48, 20, 60
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM SANPHAM WHERE TENSP = N'Bánh kem vani 16cm');

INSERT INTO SANPHAM (MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, SOLUONGTON, THOIGIANCHUANBI)
SELECT (SELECT MADM FROM DANHMUCSP WHERE UPPER(TENDM) = 'CAKE' FETCH FIRST 1 ROW ONLY), N'Bánh kem socola 18cm', 320000, '/images/products/cake_socola_18.png', 0, 48, 18, 70
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM SANPHAM WHERE TENSP = N'Bánh kem socola 18cm');

INSERT INTO SANPHAM (MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, SOLUONGTON, THOIGIANCHUANBI)
SELECT (SELECT MADM FROM DANHMUCSP WHERE UPPER(TENDM) = 'COOKIE' FETCH FIRST 1 ROW ONLY), N'Cookie bơ', 45000, '/images/products/cookie_bo.png', 0, 60, 60, 10
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM SANPHAM WHERE TENSP = N'Cookie bơ');

INSERT INTO SANPHAM (MADM, TENSP, GIACOBAN, HINHANH, CHOPHEPTUYCHINH, THOIGIANBAOQUAN, SOLUONGTON, THOIGIANCHUANBI)
SELECT (SELECT MADM FROM DANHMUCSP WHERE UPPER(TENDM) = 'BREAD' FETCH FIRST 1 ROW ONLY), N'Bánh mì bơ tỏi', 30000, '/images/products/bread_garlic.png', 0, 24, 40, 15
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM SANPHAM WHERE TENSP = N'Bánh mì bơ tỏi');
COMMIT;

-- 4) VAI TRÒ & NHÂN VIÊN
INSERT INTO VAITRO (TENVAITRO) SELECT N'Quản lý' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM VAITRO WHERE TENVAITRO = N'Quản lý');
INSERT INTO VAITRO (TENVAITRO) SELECT N'Nhân viên' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM VAITRO WHERE TENVAITRO = N'Nhân viên');

INSERT INTO NHANVIEN (MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU, TRANGTHAILAMVIEC)
SELECT (SELECT MAVAITRO FROM VAITRO WHERE TENVAITRO = N'Quản lý' FETCH FIRST 1 ROW ONLY), N'Quản trị viên', '0123456789', 'admin', '123', 1
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE TENDANGNHAP = 'admin');

INSERT INTO NHANVIEN (MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU, TRANGTHAILAMVIEC)
SELECT (SELECT MAVAITRO FROM VAITRO WHERE TENVAITRO = N'Quản lý' FETCH FIRST 1 ROW ONLY), N'Viên Đăng Khoa', '0889812723', 'khoavien', '123', 1
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE TENDANGNHAP = 'khoavien');
COMMIT;

-- 5) HẠNG THÀNH VIÊN
INSERT INTO HANGTHANHVIEN (TENHANG, DIEMTOITHIEU, PHANTRAMGIAMGIA) SELECT N'Không', 0, 0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM HANGTHANHVIEN WHERE TENHANG = N'Không');
INSERT INTO HANGTHANHVIEN (TENHANG, DIEMTOITHIEU, PHANTRAMGIAMGIA) SELECT N'Bạc', 100, 5 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM HANGTHANHVIEN WHERE TENHANG = N'Bạc');
INSERT INTO HANGTHANHVIEN (TENHANG, DIEMTOITHIEU, PHANTRAMGIAMGIA) SELECT N'Vàng', 500, 10 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM HANGTHANHVIEN WHERE TENHANG = N'Vàng');
INSERT INTO HANGTHANHVIEN (TENHANG, DIEMTOITHIEU, PHANTRAMGIAMGIA) SELECT N'Kim cương', 2000, 15 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM HANGTHANHVIEN WHERE TENHANG = N'Kim cương');
COMMIT;

-- 6) PHƯƠNG THỨC THANH TOÁN
INSERT INTO PHUONGTHUCTT (TENPTTT) SELECT N'Tiền mặt' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PHUONGTHUCTT WHERE TENPTTT = N'Tiền mặt');
INSERT INTO PHUONGTHUCTT (TENPTTT) SELECT N'Chuyển khoản' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PHUONGTHUCTT WHERE TENPTTT = N'Chuyển khoản');
COMMIT;

-- 7) CHỨC NĂNG HỆ THỐNG & PHÂN QUYỀN
INSERT INTO CHUCNANG (TENCHUCNANG, MOTA) SELECT N'Hệ thống', N'Quản lý cấu hình hệ thống' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CHUCNANG WHERE TENCHUCNANG = N'Hệ thống');
INSERT INTO CHUCNANG (TENCHUCNANG, MOTA) SELECT N'Nhân sự', N'Quản lý nhân viên và vai trò' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CHUCNANG WHERE TENCHUCNANG = N'Nhân sự');
INSERT INTO CHUCNANG (TENCHUCNANG, MOTA) SELECT N'Khách hàng', N'Quản lý khách hàng và hạng thành viên' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CHUCNANG WHERE TENCHUCNANG = N'Khách hàng');
INSERT INTO CHUCNANG (TENCHUCNANG, MOTA) SELECT N'Sản phẩm', N'Quản lý danh mục và sản phẩm' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CHUCNANG WHERE TENCHUCNANG = N'Sản phẩm');
INSERT INTO CHUCNANG (TENCHUCNANG, MOTA) SELECT N'Kho', N'Quản lý nguyên liệu và nhập xuất kho' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CHUCNANG WHERE TENCHUCNANG = N'Kho');
INSERT INTO CHUCNANG (TENCHUCNANG, MOTA) SELECT N'Bán hàng', N'Màn hình bán hàng POS' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CHUCNANG WHERE TENCHUCNANG = N'Bán hàng');
INSERT INTO CHUCNANG (TENCHUCNANG, MOTA) SELECT N'Đơn hàng', N'Quản lý đơn đặt hàng và trạng thái' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CHUCNANG WHERE TENCHUCNANG = N'Đơn hàng');
INSERT INTO CHUCNANG (TENCHUCNANG, MOTA) SELECT N'Báo cáo', N'Xem báo cáo thống kê doanh thu' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CHUCNANG WHERE TENCHUCNANG = N'Báo cáo');

-- Phân quyền cho Quản lý (Full Access)
INSERT INTO VAITRO_CHUCNANG (MAVAITRO, MACHUCNANG)
SELECT (SELECT MAVAITRO FROM VAITRO WHERE TENVAITRO = N'Quản lý' FETCH FIRST 1 ROW ONLY), MACHUCNANG
FROM CHUCNANG WHERE NOT EXISTS (
    SELECT 1 FROM VAITRO_CHUCNANG 
    WHERE MAVAITRO = (SELECT MAVAITRO FROM VAITRO WHERE TENVAITRO = N'Quản lý' FETCH FIRST 1 ROW ONLY)
    AND MACHUCNANG = CHUCNANG.MACHUCNANG
);
COMMIT;

-- 8) TÙY CHỈNH BÁNH (Kích cỡ, Cốt, Nhân, Trang trí)
INSERT INTO KICHCOBANH (TENKC, PHUPHI) SELECT N'16cm', 0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM KICHCOBANH WHERE TENKC = N'16cm');
INSERT INTO KICHCOBANH (TENKC, PHUPHI) SELECT N'18cm', 50000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM KICHCOBANH WHERE TENKC = N'18cm');
INSERT INTO COTBANH (TENCOT, PHUPHI) SELECT N'Vani', 0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM COTBANH WHERE TENCOT = N'Vani');
INSERT INTO COTBANH (TENCOT, PHUPHI) SELECT N'Socola', 20000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM COTBANH WHERE TENCOT = N'Socola');
INSERT INTO NHANBANH (TENNHAN, PHUPHI) SELECT N'Dâu tây', 15000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NHANBANH WHERE TENNHAN = N'Dâu tây');
INSERT INTO KIEUTRANGTRI (TENTRANGTRI, PHUPHI) SELECT N'Đơn giản', 0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM KIEUTRANGTRI WHERE TENTRANGTRI = N'Đơn giản');
INSERT INTO KIEUTRANGTRI (TENTRANGTRI, PHUPHI) SELECT N'Hoa kem', 30000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM KIEUTRANGTRI WHERE TENTRANGTRI = N'Hoa kem');
COMMIT;

-- 9) DANH MỤC KHO & NHÀ CUNG CẤP
INSERT INTO DONVITINH (TENDVT) SELECT N'Kg' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM DONVITINH WHERE TENDVT = N'Kg');
INSERT INTO DONVITINH (TENDVT) SELECT N'Lít' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM DONVITINH WHERE TENDVT = N'Lít');
INSERT INTO DONVITINH (TENDVT) SELECT N'Quả' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM DONVITINH WHERE TENDVT = N'Quả');

INSERT INTO NHACUNGCAP (TENNCC, SDT, DIACHI) SELECT N'Công ty TNHH Bột Mì Vĩnh Thuận', '0901234567', N'Số 1, Đường Trần Hưng Đạo, Quận 5, TP.HCM' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NHACUNGCAP WHERE TENNCC = N'Công ty TNHH Bột Mì Vĩnh Thuận');
INSERT INTO NHACUNGCAP (TENNCC, SDT, DIACHI) SELECT N'Đại lý Sữa Tươi Vinamilk', '19001568', N'Số 10, Tân Trào, Quận 7, TP.HCM' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NHACUNGCAP WHERE TENNCC = N'Đại lý Sữa Tươi Vinamilk');
INSERT INTO NHACUNGCAP (TENNCC, SDT, DIACHI) SELECT N'Nông Trại Trứng Gà Ba Huân', '02811223344', N'Khu Công Nghiệp Tân Tạo, TP.HCM' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NHACUNGCAP WHERE TENNCC = N'Nông Trại Trứng Gà Ba Huân');
INSERT INTO NHACUNGCAP (TENNCC, SDT, DIACHI) SELECT N'Công ty Cổ phần Đường Biên Hòa', '02513836199', N'Biên Hòa, Đồng Nai' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NHACUNGCAP WHERE TENNCC = N'Công ty Cổ phần Đường Biên Hòa');
COMMIT;

-- 10) KHÁCH HÀNG MẪU
INSERT INTO KHACHHANG (HOTEN, SDT, DIACHI, MAHANG)
SELECT N'Nguyễn Văn Khách', '0988777666', N'123 Đường ABC, Quận 1', (SELECT MAHANG FROM HANGTHANHVIEN WHERE TENHANG = N'Bạc' FETCH FIRST 1 ROW ONLY)
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM KHACHHANG WHERE SDT = '0988777666');

INSERT INTO KHACHHANG (HOTEN, SDT, DIACHI, MAHANG)
SELECT N'Trần Minh Châu', '0901112233', N'78 Hai Bà Trưng, Quận Bình Thạnh', (SELECT MAHANG FROM HANGTHANHVIEN WHERE TENHANG = N'Vàng' FETCH FIRST 1 ROW ONLY)
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM KHACHHANG WHERE SDT = '0901112233');
COMMIT;

-- 11) LOẠI THU CHI & NĂNG LỰC SẢN XUẤT
INSERT INTO LOAITHUCHI (TENLOAITHUCHI, PHANLOAI) SELECT N'Bán hàng', N'Thu' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LOAITHUCHI WHERE TENLOAITHUCHI = N'Bán hàng');
INSERT INTO LOAITHUCHI (TENLOAITHUCHI, PHANLOAI) SELECT N'Nhập hàng', N'Chi' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LOAITHUCHI WHERE TENLOAITHUCHI = N'Nhập hàng');

INSERT INTO NANGLUCSANXUAT (NGAYSANXUAT, GIOIHANSOBANH, SOBANHDANHAN)
SELECT TRUNC(SYSDATE), 50, 0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NANGLUCSANXUAT WHERE NGAYSANXUAT = TRUNC(SYSDATE));
COMMIT;
