-- =======================================================
-- Seed du lieu mau cho CRM (Khach hang)
-- Muc tieu: du de test danh sach, tim kiem, thong ke, xoa mem, khoi phuc.
-- Uu tien chay tren database trong.
-- =======================================================

-- SET DEFINE OFF;

DECLARE
    v_mavaitro_admin   VAITRO.MAVAITRO%TYPE;
    v_mavaitro_cskh    VAITRO.MAVAITRO%TYPE;
    v_manv_admin       NHANVIEN.MANV%TYPE;

    v_mahang_khong     HANGTHANHVIEN.MAHANG%TYPE;
    v_mahang_bac       HANGTHANHVIEN.MAHANG%TYPE;
    v_mahang_vang      HANGTHANHVIEN.MAHANG%TYPE;
    v_mahang_kimcuong  HANGTHANHVIEN.MAHANG%TYPE;
BEGIN
    -- 1) Vai tro (cho NHANVIEN)
    INSERT INTO VAITRO (TENVAITRO, MOTA)
    SELECT 'Quản lý', 'Quản trị hệ thống CRM'
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM VAITRO WHERE TENVAITRO = 'ADMIN');

    INSERT INTO VAITRO (TENVAITRO, MOTA)
    SELECT 'CSKH', 'Cham soc khach hang'
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM VAITRO WHERE TENVAITRO = 'CSKH');

    SELECT MAVAITRO INTO v_mavaitro_admin FROM VAITRO WHERE TENVAITRO = 'ADMIN' FETCH FIRST 1 ROW ONLY;
    SELECT MAVAITRO INTO v_mavaitro_cskh  FROM VAITRO WHERE TENVAITRO = 'CSKH'  FETCH FIRST 1 ROW ONLY;

    -- 2) Nhan vien (dam bao co user de xoa mem KH)
    INSERT INTO NHANVIEN (MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU, TRANGTHAILAMVIEC)
    SELECT v_mavaitro_admin, 'Admin CRM', '0900000001', 'admin.crm', '123456', 1
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE TENDANGNHAP = 'admin.crm');

    INSERT INTO NHANVIEN (MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU, TRANGTHAILAMVIEC)
    SELECT v_mavaitro_cskh, 'Nhan vien CSKH', '0900000002', 'cskh.crm', '123456', 1
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE TENDANGNHAP = 'cskh.crm');

    SELECT MANV INTO v_manv_admin FROM NHANVIEN WHERE TENDANGNHAP = 'admin.crm' FETCH FIRST 1 ROW ONLY;

    -- 3) Hang thanh vien (giu dung ten theo CHECK CONSTRAINT)
    INSERT INTO HANGTHANHVIEN (TENHANG, DIEMTOITHIEU, PHANTRAMGIAMGIA)
    SELECT N'Không', 0, 0
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM HANGTHANHVIEN WHERE TENHANG = N'Không');

    INSERT INTO HANGTHANHVIEN (TENHANG, DIEMTOITHIEU, PHANTRAMGIAMGIA)
    SELECT N'Bạc', 200, 2
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM HANGTHANHVIEN WHERE TENHANG = N'Bạc');

    INSERT INTO HANGTHANHVIEN (TENHANG, DIEMTOITHIEU, PHANTRAMGIAMGIA)
    SELECT N'Vàng', 500, 5
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM HANGTHANHVIEN WHERE TENHANG = N'Vàng');

    INSERT INTO HANGTHANHVIEN (TENHANG, DIEMTOITHIEU, PHANTRAMGIAMGIA)
    SELECT N'Kim cương', 1000, 10
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM HANGTHANHVIEN WHERE TENHANG = N'Kim cương');

    SELECT MAHANG INTO v_mahang_khong    FROM HANGTHANHVIEN WHERE TENHANG = N'Không' FETCH FIRST 1 ROW ONLY;
    SELECT MAHANG INTO v_mahang_bac      FROM HANGTHANHVIEN WHERE TENHANG = N'Bạc' FETCH FIRST 1 ROW ONLY;
    SELECT MAHANG INTO v_mahang_vang     FROM HANGTHANHVIEN WHERE TENHANG = N'Vàng' FETCH FIRST 1 ROW ONLY;
    SELECT MAHANG INTO v_mahang_kimcuong FROM HANGTHANHVIEN WHERE TENHANG = N'Kim cương' FETCH FIRST 1 ROW ONLY;

    -- 4) Khach hang ACTIVE (du lieu vua du test CRM)
    INSERT INTO KHACHHANG (HOTEN, SDT, DIACHI, NGAYDANGKY, DIEMTICHLUY, MAHANG)
    SELECT 'Nguyen An', '0912345601', 'Q1, TP.HCM', TRUNC(SYSDATE) - 45, 50, v_mahang_khong
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM KHACHHANG WHERE SDT = '0912345601');

    INSERT INTO KHACHHANG (HOTEN, SDT, DIACHI, NGAYDANGKY, DIEMTICHLUY, MAHANG)
    SELECT 'Tran Binh', '0912345602', 'Q3, TP.HCM', TRUNC(SYSDATE) - 20, 240, v_mahang_bac
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM KHACHHANG WHERE SDT = '0912345602');

    INSERT INTO KHACHHANG (HOTEN, SDT, DIACHI, NGAYDANGKY, DIEMTICHLUY, MAHANG)
    SELECT 'Le Chau', '0912345603', 'Thu Duc, TP.HCM', TRUNC(SYSDATE) - 7, 530, v_mahang_vang
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM KHACHHANG WHERE SDT = '0912345603');

    INSERT INTO KHACHHANG (HOTEN, SDT, DIACHI, NGAYDANGKY, DIEMTICHLUY, MAHANG)
    SELECT 'Pham Dung', '0912345604', 'Bien Hoa, Dong Nai', TRUNC(SYSDATE) - 2, 1200, v_mahang_kimcuong
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM KHACHHANG WHERE SDT = '0912345604');

    INSERT INTO KHACHHANG (HOTEN, SDT, DIACHI, NGAYDANGKY, DIEMTICHLUY, MAHANG)
    SELECT 'Vo Giang', '0912345605', 'Da Nang', TRUNC(SYSDATE), 0, v_mahang_khong
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM KHACHHANG WHERE SDT = '0912345605');

    INSERT INTO KHACHHANG (HOTEN, SDT, DIACHI, NGAYDANGKY, DIEMTICHLUY, MAHANG)
    SELECT 'Hoang Hanh', '0912345606', 'Hai Chau, Da Nang', TRUNC(SYSDATE), 210, v_mahang_bac
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM KHACHHANG WHERE SDT = '0912345606');

    INSERT INTO KHACHHANG (HOTEN, SDT, DIACHI, NGAYDANGKY, DIEMTICHLUY, MAHANG)
    SELECT 'Bui Khoa', '0912345607', 'Nha Be, TP.HCM', TRUNC(SYSDATE) - 1, 510, v_mahang_vang
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM KHACHHANG WHERE SDT = '0912345607');

    INSERT INTO KHACHHANG (HOTEN, SDT, DIACHI, NGAYDANGKY, DIEMTICHLUY, MAHANG)
    SELECT 'Do Lam', '0912345608', 'Go Vap, TP.HCM', TRUNC(SYSDATE) - 90, 20, v_mahang_khong
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM KHACHHANG WHERE SDT = '0912345608');

    -- 5) Khach hang DELETED (test man hinh thung rac + khoi phuc)
    INSERT INTO KHACHHANG (HOTEN, SDT, DIACHI, NGAYDANGKY, DIEMTICHLUY, MAHANG, THOIDIEMXOA, MANX)
    SELECT 'Deleted One', '0912345691', 'Q7, TP.HCM', TRUNC(SYSDATE) - 60, 80, v_mahang_khong, SYSTIMESTAMP - INTERVAL '3' DAY, v_manv_admin
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM KHACHHANG WHERE SDT = '0912345691');

    INSERT INTO KHACHHANG (HOTEN, SDT, DIACHI, NGAYDANGKY, DIEMTICHLUY, MAHANG, THOIDIEMXOA, MANX)
    SELECT 'Deleted Two', '0912345692', 'Can Tho', TRUNC(SYSDATE) - 15, 350, v_mahang_bac, SYSTIMESTAMP - INTERVAL '1' DAY, v_manv_admin
    FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM KHACHHANG WHERE SDT = '0912345692');

    COMMIT;
END;
/

SELECT * FROM NHANVIEN;
SELECT * FROM KHACHHANG;


-- Goi y nhanh de kiem tra sau khi seed:
-- SELECT COUNT(*) FROM KHACHHANG WHERE THOIDIEMXOA IS NULL;
-- SELECT COUNT(*) FROM KHACHHANG WHERE THOIDIEMXOA IS NOT NULL;
-- SELECT MAKH, HOTEN, SDT, NGAYDANGKY, DIEMTICHLUY, MAHANG, THOIDIEMXOA FROM KHACHHANG ORDER BY MAKH;
