-- =======================================================
-- CONFIGURATION SCRIPTS (Drop/Fix/Update/Test)
-- =======================================================

-- Test Trigger --
DECLARE
    V_MANV NUMBER;
    V_MAVAITRO NUMBER;
    V_MANL NUMBER;
    V_MANCC NUMBER;
    V_MADVT NUMBER;
    V_MAPN NUMBER;
    V_MAPX NUMBER;
    V_MALO NUMBER;
    V_MADM NUMBER;
    V_MASP NUMBER;
    V_MADON NUMBER;
    V_MACTHD NUMBER;
    V_MAKH NUMBER;
    V_MATT NUMBER;
    V_SOLUONGTON NUMBER;
BEGIN
    -- 1. TẠO DỮ LIỆU CÓ LIÊN QUAN
    INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO;
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU) VALUES (V_MAVAITRO, 'ABC', '999999999', 'USER', '12345') RETURNING MANV INTO V_MANV;
    INSERT INTO DONVITINH(TENDVT) VALUES ('kg') RETURNING MADVT INTO V_MADVT;
    INSERT INTO DANHMUCSP(TENDM) VALUES ('BANH') RETURNING MADM INTO V_MADM;
    INSERT INTO SANPHAM(MADM, TENSP, GIACOBAN, SOLUONGTON) VALUES (V_MADM, 'DONUT', 10000, 10) RETURNING MASP INTO V_MASP;
    INSERT INTO NGUYENLIEU(TENNL, MADVT, GIAVONTRUNGBINH, SOLUONGTONTONG)
    VALUES (N'Bột mì', V_MADVT, 20000, 20) RETURNING MANL INTO V_MANL;
    INSERT INTO NHACUNGCAP(TENNCC) VALUES ('NCC') RETURNING MANCC INTO V_MANCC;
    INSERT INTO PHIEUNHAPKHO(MANV, MANCC) VALUES (V_MANV, V_MANCC) RETURNING MAPN INTO V_MAPN;
    INSERT INTO PHIEUXUATKHO(MANV) VALUES (V_MANV) RETURNING MAPX INTO V_MAPX;
    INSERT INTO TRANGTHAIDON(TENTRANGTHAI) VALUES ('Mới đặt') RETURNING MATRANGTHAI INTO V_MATT;
    INSERT INTO DONDATHANG(NGAYGIONHANBANH, MANV_LAP, MATRANGTHAI) VALUES (SYSDATE, V_MANV, V_MATT) RETURNING MADON INTO V_MADON;

    -- 2. TẠO DỮ LIỆU KÍCH HOẠT TRIGGER
    INSERT INTO CTDONHANG(MADON, MASP, SOLUONG, DONGIA) VALUES (V_MADON, V_MASP, 5, 5000) RETURNING MACTHD INTO V_MACTHD;

    -- 4. ĐỌC LẠI DỮ LIỆU TỪ BẢNG CHA
    SELECT SOLUONGTON INTO V_SOLUONGTON
    FROM SANPHAM
    WHERE MASP = V_MASP;
    -- 5. XÓA DỮ LIỆU TẠM
    ROLLBACK;

    -- 6. BÁO CÁO KẾT QUA
    IF V_SOLUONGTON = 5 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Trigger hoạt động');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Trigger không hoạt động');
    END IF;
END;
/

-- Test TRG_CTDONHANG_GIAVON --
DECLARE
    V_MAVAITRO NUMBER;
    V_MANV NUMBER;
    V_MADVT NUMBER;
    V_MADM NUMBER;
    V_MASP NUMBER;
    V_MANL NUMBER;
    V_MADON NUMBER;
    V_MATRANGTHAI NUMBER;
    V_MACTHD NUMBER;
    V_DONGIAVON NUMBER;
BEGIN
    -- 1. TẠO DỮ LIỆU CÓ LIÊN QUAN
    INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO;

    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU)
    VALUES (V_MAVAITRO, 'NV TEST GIAVON', '0887654321', 'TESTGIAVON', '123')
    RETURNING MANV INTO V_MANV;

    INSERT INTO DONVITINH(TENDVT) VALUES ('kg') RETURNING MADVT INTO V_MADVT;

    INSERT INTO DANHMUCSP(TENDM) VALUES ('BANH') RETURNING MADM INTO V_MADM;

    INSERT INTO SANPHAM(MADM, TENSP, GIACOBAN, SOLUONGTON)
    VALUES (V_MADM, 'BANH TEST GIA VON', 50000, 10)
    RETURNING MASP INTO V_MASP;

    INSERT INTO NGUYENLIEU(TENNL, MADVT, GIAVONTRUNGBINH)
    VALUES ('Bột test', V_MADVT, 20000)
    RETURNING MANL INTO V_MANL;

    -- Thêm công thức: 1 bánh tốn 0.5 kg Bột (Giá vốn lý thuyết = 0.5 * 20000 = 10000)
    INSERT INTO CONGTHUC(MASP, MANL, SOLUONGTIEUHAO)
    VALUES (V_MASP, V_MANL, 0.5);

    INSERT INTO TRANGTHAIDON(TENTRANGTHAI) VALUES ('Mới đặt') RETURNING MATRANGTHAI INTO V_MATRANGTHAI;

    INSERT INTO DONDATHANG(NGAYGIONHANBANH, MANV_LAP, MATRANGTHAI)
    VALUES (SYSDATE, V_MANV, V_MATRANGTHAI)
    RETURNING MADON INTO V_MADON;

    -- 2. KÍCH HOẠT TRIGGER (Thêm chi tiết đơn hàng)
    INSERT INTO CTDONHANG(MADON, MASP, SOLUONG, DONGIA)
    VALUES (V_MADON, V_MASP, 1, 50000)
    RETURNING MACTHD INTO V_MACTHD;

    -- 3. KIỂM TRA KẾT QUẢ GÁN GIÁ VỐN
    SELECT DONGIAVON INTO V_DONGIAVON
    FROM CTDONHANG
    WHERE MACTHD = V_MACTHD;

    -- 4. DỌN DẸP DỮ LIỆU TẠM
    ROLLBACK;

    -- 5. BÁO CÁO KẾT QUẢ
    IF V_DONGIAVON = 10000 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Trigger TRG_CTDONHANG_GIAVON hoạt động đúng');
    ELSE
        RAISE_APPLICATION_ERROR(-20002, 'Trigger TRG_CTDONHANG_GIAVON không hoạt động hoặc tính sai');
    END IF;
END;
/

-- Test TRG_KIEMSOAT_CONGSUAT_DONHANG & TRG_KIEMSOAT_CONGSUAT_TUYCHINH --
DECLARE
    V_MAVAITRO NUMBER;
    V_MANV NUMBER;
    V_MADM NUMBER;
    V_MASP NUMBER;
    V_MADON NUMBER;
    V_MATRANGTHAI NUMBER;
    V_MACTHD NUMBER;
BEGIN
    -- 1. TẠO DỮ LIỆU CÓ LIÊN QUAN
    INSERT INTO VAITRO(TENVAITRO) VALUES ('NV') RETURNING MAVAITRO INTO V_MAVAITRO;
    
    INSERT INTO NHANVIEN(MAVAITRO, HOTEN, SDT, TENDANGNHAP, MATKHAU) 
    VALUES (V_MAVAITRO, 'NV TEST CONGSUAT', '0887654322', 'TESTCS', '123') 
    RETURNING MANV INTO V_MANV;
    
    INSERT INTO DANHMUCSP(TENDM) VALUES ('BANH') RETURNING MADM INTO V_MADM;
    INSERT INTO SANPHAM(MADM, TENSP, GIACOBAN, SOLUONGTON) 
    VALUES (V_MADM, 'BANH CONG SUAT', 50000, 100) 
    RETURNING MASP INTO V_MASP;
    
    -- Thêm giới hạn công suất cho ngày hôm nay (giới hạn 5 cái)
    INSERT INTO NANGLUCSANXUAT(NGAYSANXUAT, GIOIHANSOBANH, SOBANHDANHAN) 
    VALUES (TRUNC(SYSDATE), 5, 0);
    
    INSERT INTO TRANGTHAIDON(TENTRANGTHAI) VALUES ('Mới đặt') RETURNING MATRANGTHAI INTO V_MATRANGTHAI;
    
    INSERT INTO DONDATHANG(NGAYGIONHANBANH, MANV_LAP, MATRANGTHAI) 
    VALUES (SYSDATE, V_MANV, V_MATRANGTHAI) 
    RETURNING MADON INTO V_MADON;

    -- 2. KÍCH HOẠT TRIGGER (Thêm 6 cái -> Vượt mốc 5 cái)
    BEGIN
        INSERT INTO CTDONHANG(MADON, MASP, SOLUONG, DONGIA) 
        VALUES (V_MADON, V_MASP, 6, 50000)
        RETURNING MACTHD INTO V_MACTHD;
        
        -- Nếu vượt qua block trên mà không bị lỗi -> Trigger sai (hoặc không hoạt động)
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20002, 'Trigger TRG_KIEMSOAT_CONGSUAT không hoạt động để chặn giao dịch');
    EXCEPTION
        WHEN OTHERS THEN
            -- SQLCODE cua Raise_Application_Error(-20005) la -20005
            IF SQLCODE = -20005 THEN
                ROLLBACK;
                RAISE_APPLICATION_ERROR(-20001, 'Trigger TRG_KIEMSOAT_CONGSUAT hoạt động đúng: ' || SQLERRM);
            ELSE
                ROLLBACK;
                RAISE_APPLICATION_ERROR(-20002, 'Lỗi khác bất ngờ: ' || SQLERRM);
            END IF;
    END;
END;
/
