-- Hàm thống kê Top 5 sản phẩm (Bánh) bán chạy nhất
CREATE OR REPLACE FUNCTION FUNC_TOPSANPHAMBANCHAY(
    P_TUNGAY IN DATE,
    P_DENNGAY IN DATE
) RETURN SYS_REFCURSOR
IS
    V_REFCURSOR SYS_REFCURSOR;
BEGIN
    OPEN V_REFCURSOR FOR
        SELECT 
            SP.TENSP, 
            SUM(CT.SOLUONG) AS TONGSOLUONGBAN
        FROM CTDONHANG CT
        JOIN DONDATHANG DDH ON CT.MADON = DDH.MADON
        JOIN SANPHAM SP ON CT.MASP = SP.MASP
        JOIN TRANGTHAIDON TT ON DDH.MATRANGTHAI = TT.MATRANGTHAI
        WHERE TRUNC(DDH.NGAYLAP) BETWEEN TRUNC(P_TUNGAY) AND TRUNC(P_DENNGAY)
          AND UPPER(TT.TENTRANGTHAI) = 'HOÀN THÀNH'
        GROUP BY SP.MASP, SP.TENSP
        ORDER BY SUM(CT.SOLUONG) DESC
        FETCH FIRST 5 ROWS ONLY;
        
    RETURN V_REFCURSOR;
EXCEPTION
    WHEN OTHERS THEN
        OPEN V_REFCURSOR FOR SELECT 'Lỗi' AS TENSP, 0 AS TONGSOLUONGBAN FROM DUAL WHERE 1=0;
        RETURN V_REFCURSOR;
END;
/
