-- Hàm xác định lô nguyên liệu cần xuất theo tiêu chuẩn FEFO (First Expired, First Out)
CREATE OR REPLACE FUNCTION FUNC_XACDINHPHIEUNHAPFEFO(
    P_MANL IN NGUYENLIEU.MANL%type
) RETURN SYS_REFCURSOR
IS
    V_REFCURSOR SYS_REFCURSOR;
BEGIN
    OPEN V_REFCURSOR FOR
        SELECT MALO, SOLUONGCONLAI
        FROM CTPHIEUNHAP
        WHERE MANL = P_MANL 
          AND SOLUONGCONLAI > 0
        ORDER BY HANSUDUNG NULLS LAST
        FETCH FIRST 1 ROWS ONLY;
        
    RETURN V_REFCURSOR;
EXCEPTION
    WHEN OTHERS THEN
        OPEN V_REFCURSOR FOR SELECT -1 AS MALO, 0 AS SOLUONGCONLAI FROM DUAL WHERE 1=0;
        RETURN V_REFCURSOR;
END;
/
