create FUNCTION TINHSOBANHTOIDA(
    P_TENSP IN SANPHAM.TENSP%type
)
RETURN NUMBER
IS
    V_SOBANH NUMBER;
BEGIN

    SELECT MIN(FLOOR(NL.SOLUONGTONTONG / CT.SOLUONGTIEUHAO))
    INTO V_SOBANH
    FROM SANPHAM SP
    JOIN CONGTHUC CT ON SP.MASP = CT.MASP
    JOIN NGUYENLIEU NL ON CT.MANL = NL.MANL
    WHERE SP.TENSP = P_TENSP;

    RETURN V_SOBANH;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;

CREATE OR REPLACE FUNCTION FUNC_DIEMKHADUNG(
    P_NGAYCANKIEMTRA IN NANGLUCSANXUAT.NGAYSANXUAT%type
) RETURN NUMBER
IS
    V_GIOIHAN NUMBER := 0;
    V_TONG_DADAT NUMBER := 0;
    V_KHA_DUNG NUMBER := 0;
BEGIN

    BEGIN
        SELECT GIOIHANSOBANH
        INTO V_GIOIHAN
        FROM NANGLUCSANXUAT
        WHERE TRUNC(NGAYSANXUAT) = TRUNC(P_NGAYCANKIEMTRA);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            V_GIOIHAN := 0; -- Náº¿u xÆ°á»Ÿng chÆ°a cáº¥u hÃ¬nh táº£i trá»ng cho ngÃ y nÃ y, máº·c Ä‘á»‹nh lÃ  0 (KhÃ´ng nháº­n)
    END;


    SELECT NVL(SUM(CTC.SOLUONG), 0)
    INTO V_TONG_DADAT
    FROM DONDATHANG DDH
    JOIN CTDONTUYCHINH CTC ON DDH.MADON = CTC.MADON
    JOIN TRANGTHAIDON TT ON DDH.MATRANGTHAI = TT.MATRANGTHAI
    WHERE TRUNC(DDH.NGAYGIONHANBANH) = TRUNC(P_NGAYCANKIEMTRA)
      AND UPPER(TT.TENTRANGTHAI) NOT LIKE '%Há»¦Y%';

    V_KHA_DUNG := V_GIOIHAN - V_TONG_DADAT;


    IF V_KHA_DUNG < 0 THEN
        RETURN 0;
    ELSE
        RETURN V_KHA_DUNG;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 0;
END;
/