-- Hàm chuyển đổi tỷ lệ công thức làm bánh
CREATE OR REPLACE FUNCTION FUNC_CHUYENDOITYLECONGTHUC(
    P_MASP IN SANPHAM.MASP%type,
    P_SOLUONGBANHCANLAM IN CONGTHUC.SOLUONGTIEUHAO%type
) RETURN SYS_REFCURSOR
IS
    V_REFCURSOR SYS_REFCURSOR;
BEGIN
    OPEN V_REFCURSOR FOR
        SELECT C.MANL, N.TENNL, D.TENDVT,
            (C.SOLUONGTIEUHAO * P_SOLUONGBANHCANLAM) AS TONGSOLUONGCANXUAT
        FROM CONGTHUC C
        JOIN NGUYENLIEU N ON C.MANL = N.MANL
        JOIN DONVITINH D ON N.MADVT = D.MADVT
        WHERE C.MASP = P_MASP;
        
    RETURN V_REFCURSOR;
EXCEPTION
    WHEN OTHERS THEN
        OPEN V_REFCURSOR FOR SELECT -1 AS MANL, 'Lỗi' AS TENNL, 0 AS TONGSOLUONGCANXUAT, '' AS TENDVT FROM DUAL WHERE 1=0;
        RETURN V_REFCURSOR;
END;
/
