-- Hàm tính toán giá bán tự động cho bánh Tùy chỉnh
CREATE OR REPLACE FUNCTION FUNC_TINHGIABANHTUYCHINH(
    P_MASP IN NUMBER,
    P_MAKICHCO IN NUMBER DEFAULT NULL,
    P_MACOT IN NUMBER DEFAULT NULL,
    P_MANHAN IN NUMBER DEFAULT NULL,
    P_MATRANGTRI IN NUMBER DEFAULT NULL
) RETURN NUMBER
IS
    V_GIACOBAN NUMBER := 0;
    V_PHUPHI_KC NUMBER := 0;
    V_PHUPHI_COT NUMBER := 0;
    V_PHUPHI_NHAN NUMBER := 0;
    V_PHUPHI_TT NUMBER := 0;
    V_TONGGIA NUMBER := 0;
BEGIN
    -- 1. Lấy giá gốc
    BEGIN
        SELECT NVL(GIACOBAN, 0) INTO V_GIACOBAN
        FROM SANPHAM
        WHERE MASP = P_MASP;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            V_GIACOBAN := 0;
    END;

    -- 2. Quét phụ phí kích cỡ
    IF P_MAKICHCO IS NOT NULL THEN
        BEGIN
            SELECT NVL(PHUPHI, 0) INTO V_PHUPHI_KC
            FROM KICHCOBANH
            WHERE MAKC = P_MAKICHCO;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN V_PHUPHI_KC := 0;
        END;
    END IF;

    -- 3. Quét phụ phí cốt bánh
    IF P_MACOT IS NOT NULL THEN
        BEGIN
            SELECT NVL(PHUPHI, 0) INTO V_PHUPHI_COT
            FROM COTBANH
            WHERE MACOT = P_MACOT;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN V_PHUPHI_COT := 0;
        END;
    END IF;

    -- 4. Quét phụ phí nhân bánh
    IF P_MANHAN IS NOT NULL THEN
        BEGIN
            SELECT NVL(PHUPHI, 0) INTO V_PHUPHI_NHAN
            FROM NHANBANH
            WHERE MANHAN = P_MANHAN;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN V_PHUPHI_NHAN := 0;
        END;
    END IF;

    -- 5. Quét phụ phí trang trí
    IF P_MATRANGTRI IS NOT NULL THEN
        BEGIN
            SELECT NVL(PHUPHI, 0) INTO V_PHUPHI_TT
            FROM KIEUTRANGTRI
            WHERE MATRANGTRI = P_MATRANGTRI;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN V_PHUPHI_TT := 0;
        END;
    END IF;

    -- 6. Tính tổng giá bán
    V_TONGGIA := V_GIACOBAN + V_PHUPHI_KC + V_PHUPHI_COT + V_PHUPHI_NHAN + V_PHUPHI_TT;

    RETURN V_TONGGIA;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 0;
END;
/
