CREATE OR REPLACE FUNCTION TINHSOBANHTOIDA(
    P_TENSP VARCHAR2
)
RETURN NUMBER
IS
    V_SOBANH NUMBER;
BEGIN

    SELECT MIN(FLOOR(NL.SOLUONGTONTONG / CT.SOLUONGTIEUHAO))
    INTO V_SOBANH
    FROM SANPHAM SP
    JOIN CONGTHUC CT ON SP.MASP = CT.MASP
    JOIN NGUYENLIEU NL ON CT.MANL = NL.MANL
    WHERE SP.TENSP = P_TENSP;

    RETURN V_SOBANH;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;