-- Hàm tính giá vốn của một sản phẩm dựa trên định mức nguyên liệu
CREATE OR REPLACE FUNCTION FUNC_TONGGIAVON(
    P_MASP IN NUMBER
)
RETURN NUMBER
IS
    V_TONG_GIAVON NUMBER := 0;
BEGIN
    SELECT NVL(SUM(CT.SOLUONGTIEUHAO * NL.GIAVONTRUNGBINH), 0)
    INTO V_TONG_GIAVON
    FROM CONGTHUC CT
    JOIN NGUYENLIEU NL ON CT.MANL = NL.MANL
    WHERE CT.MASP = P_MASP;

    RETURN V_TONG_GIAVON;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 0;
END;
/
