-- Hàm quét danh sách nguyên liệu chạm/dưới mức tồn an toàn
-- Trả cursor: MANL, TENNL, SOLUONGTONTONG, MUCTONANTOAN, TENDVT
-- Dùng cho cảnh báo dashboard và màn hình kho
CREATE OR REPLACE FUNCTION FUNC_TONKHOTOITHIEU
RETURN SYS_REFCURSOR
IS
    V_REFCURSOR SYS_REFCURSOR;
BEGIN
    OPEN V_REFCURSOR FOR
        SELECT N.MANL,
               N.TENNL,
               NVL(N.SOLUONGTONTONG, 0)  AS SOLUONGTONTONG,
               NVL(N.MUCTONANTOAN,   0)  AS MUCTONANTOAN,
               DVT.TENDVT
        FROM NGUYENLIEU N
        LEFT JOIN DONVITINH DVT ON N.MADVT = DVT.MADVT
        WHERE N.THOIDIEMXOA IS NULL
          AND NVL(N.SOLUONGTONTONG, 0) <= NVL(N.MUCTONANTOAN, 0)
        ORDER BY N.SOLUONGTONTONG ASC;

    RETURN V_REFCURSOR;
EXCEPTION
    WHEN OTHERS THEN
        OPEN V_REFCURSOR FOR
            SELECT -1 AS MANL,'Lỗi' AS TENNL,0 AS SOLUONGTONTONG,0 AS MUCTONANTOAN,'' AS TENDVT
            FROM DUAL WHERE 1=0;
        RETURN V_REFCURSOR;
END;
/
