-- Hàm tính toán giá bán tự động cho bánh Tùy chỉnh
-- IMP-01: Gộp 5 SELECT riêng lẻ thành 1 câu LEFT JOIN duy nhất (5 round-trip → 1)
CREATE OR REPLACE FUNCTION FUNC_GIABANHTUYCHINH(
    P_MASP IN SANPHAM.MASP%type,
    P_MAKICHCO IN KICHCOBANH.MAKC%type DEFAULT NULL,
    P_MACOT IN COTBANH.MACOT%type DEFAULT NULL,
    P_MANHAN IN NHANBANH.MANHAN%type DEFAULT NULL,
    P_MATRANGTRI IN KIEUTRANGTRI.MATRANGTRI%type DEFAULT NULL
) RETURN NUMBER
IS
    V_GIACOBAN NUMBER := 0;
    V_PHUPHI_KC NUMBER := 0;
    V_PHUPHI_COT NUMBER := 0;
    V_PHUPHI_NHAN NUMBER := 0;
    V_PHUPHI_TT NUMBER := 0;
BEGIN
    -- 1. Lấy giá gốc + tất cả phụ phí trong 1 câu SELECT duy nhất
    SELECT
        NVL(SP.GIABAN, 0),
        NVL(KC.PHUPHI, 0),
        NVL(COT.PHUPHI, 0),
        NVL(NH.PHUPHI, 0),
        NVL(TT.PHUPHI, 0)
    INTO V_GIACOBAN, V_PHUPHI_KC, V_PHUPHI_COT, V_PHUPHI_NHAN, V_PHUPHI_TT
    FROM SANPHAM SP
    LEFT JOIN KICHCOBANH KC ON KC.MAKC = P_MAKICHCO AND KC.THOIDIEMXOA IS NULL
    LEFT JOIN COTBANH COT ON COT.MACOT = P_MACOT AND COT.THOIDIEMXOA IS NULL
    LEFT JOIN NHANBANH NH ON NH.MANHAN = P_MANHAN AND NH.THOIDIEMXOA IS NULL
    LEFT JOIN KIEUTRANGTRI TT ON TT.MATRANGTRI = P_MATRANGTRI AND TT.THOIDIEMXOA IS NULL
    WHERE SP.MASP = P_MASP;

    -- 2. Tính tổng giá bán
    RETURN V_GIACOBAN + V_PHUPHI_KC + V_PHUPHI_COT + V_PHUPHI_NHAN + V_PHUPHI_TT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
    WHEN OTHERS THEN
        RETURN 0;
END;
/
