-- Hàm tính tổng doanh thu nhóm theo Phương thức thanh toán
CREATE OR REPLACE FUNCTION FUNC_DOANHTHUTHEOPTTT(
    P_TUNGAY IN HOADON.NGAYXUATHD%type,
    P_DENNGAY IN HOADON.NGAYXUATHD%type
) RETURN SYS_REFCURSOR
IS
    V_REFCURSOR SYS_REFCURSOR;
BEGIN
    OPEN V_REFCURSOR FOR
        SELECT PT.TENPTTT, NVL(SUM(HD.TONGTIENTHANHTOAN), 0) AS TONGDOANHTHU
        FROM HOADON HD
        JOIN PHUONGTHUCTT PT ON HD.MAPTTT = PT.MAPTTT
        WHERE TRUNC(HD.NGAYXUATHD) BETWEEN TRUNC(P_TUNGAY) AND TRUNC(P_DENNGAY)
        GROUP BY PT.MAPTTT, PT.TENPTTT
        ORDER BY TONGDOANHTHU DESC;
        
    RETURN V_REFCURSOR;
EXCEPTION
    WHEN OTHERS THEN
        -- Trả về cursor rỗng nếu có lỗi xảy ra
        OPEN V_REFCURSOR FOR SELECT 'Lỗi phát sinh' AS TENPTTT, 0 AS TONGDOANHTHU FROM DUAL WHERE 1=0;
        RETURN V_REFCURSOR;
END;
/
