-- Trigger cộng dồn số bánh khách đặt và kiểm soát năng lực (đơn hàng)
CREATE OR REPLACE TRIGGER TRG_KIEMSOAT_CONGSUAT_DONHANG
AFTER INSERT OR UPDATE OR DELETE ON CTDONHANG
FOR EACH ROW
DECLARE
    V_MADON CTDONHANG.MADON%type;
    V_MASP CTDONHANG.MASP%type;
    V_CHENHLECH CTDONHANG.SOLUONG%type := 0;
    V_NGAYGIAO DATE;
    V_THOIGIANCHUANBI SANPHAM.THOIGIANCHUANBI%type := 0;
    V_NGAYSANXUAT DATE;
    V_SOBANH_HIENTAI NANGLUCSANXUAT.SOBANHDANHAN%type;
    V_GIOIHAN NANGLUCSANXUAT.GIOIHANSOBANH%type;
BEGIN
    IF INSERTING THEN
        V_CHENHLECH := :NEW.SOLUONG;
        V_MADON := :NEW.MADON;
        V_MASP := :NEW.MASP;
    ELSIF UPDATING THEN
        V_CHENHLECH := :NEW.SOLUONG - :OLD.SOLUONG;
        V_MADON := :NEW.MADON;
        V_MASP := :NEW.MASP;
    ELSIF DELETING THEN
        V_CHENHLECH := -(:OLD.SOLUONG);
        V_MADON := :OLD.MADON;
        V_MASP := :OLD.MASP;
    END IF;

    SELECT NVL(THOIGIANCHUANBI, 0) INTO V_THOIGIANCHUANBI
    FROM SANPHAM
    WHERE MASP = V_MASP;

    SELECT TRUNC(NGAYGIONHANBANH) INTO V_NGAYGIAO
    FROM DONDATHANG
    WHERE MADON = V_MADON;

    -- Tính ngày sản xuất thực tế bằng cách lùi thời gian giao hàng lại
    V_NGAYSANXUAT := V_NGAYGIAO - V_THOIGIANCHUANBI;

    SELECT NVL(SOBANHDANHAN, 0), NVL(GIOIHANSOBANH, 0)
    INTO V_SOBANH_HIENTAI, V_GIOIHAN
    FROM NANGLUCSANXUAT
    WHERE TRUNC(NGAYSANXUAT) = V_NGAYSANXUAT
    FOR UPDATE;

    IF (V_SOBANH_HIENTAI + V_CHENHLECH) > V_GIOIHAN THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DON_VUOT_CONG_SUAT,
            'TỪ CHỐI NHẬN ĐƠN: Ngày Sản Xuất Thực Tế (' || TO_CHAR(V_NGAYSANXUAT, 'DD/MM/YYYY') || ') ' ||
            ' đã đạt công suất tối đa! (Đã nhận: ' || V_SOBANH_HIENTAI || '/' || V_GIOIHAN || ' bánh, Khách đặt thêm: ' || V_CHENHLECH || ' bánh). ' ||
            'Vui lòng khuyến khích khách đổi sang ngày khác!');
    END IF;

    UPDATE NANGLUCSANXUAT
    SET SOBANHDANHAN = V_SOBANH_HIENTAI + V_CHENHLECH
    WHERE TRUNC(NGAYSANXUAT) = V_NGAYSANXUAT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_KHONG_GIOI_HAN_SX, 'Lưu ý: Chưa có dữ liệu giới hạn công suất cho ngày sản xuất ' || TO_CHAR(V_NGAYSANXUAT, 'DD/MM/YYYY'));
END;
/
