-- Trigger trừ số lượng bánh khi bán, cộng số lượng khi hoàn đơn
CREATE OR REPLACE TRIGGER TRG_TRUKHO_DONHANG
AFTER INSERT OR UPDATE OR DELETE ON CTDONHANG
FOR EACH ROW
DECLARE
    V_MASP SANPHAM.MASP%type;
    V_CHENHLECH CTDONHANG.SOLUONG%type := 0;
    V_SOLUONGTON SANPHAM.SOLUONGTON%type := 0;
BEGIN
    IF INSERTING THEN
        V_CHENHLECH := :NEW.SOLUONG;
        V_MASP := :NEW.MASP;
    ELSIF UPDATING THEN
        V_CHENHLECH := :NEW.SOLUONG - :OLD.SOLUONG;
        V_MASP := :NEW.MASP;
    ELSIF DELETING THEN
        V_CHENHLECH := -(:OLD.SOLUONG);
        V_MASP := :OLD.MASP;
    END IF;

    SELECT SOLUONGTON INTO V_SOLUONGTON
    FROM SANPHAM
    WHERE MASP = V_MASP;

    IF V_SOLUONGTON < 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SP_HET_HANG, 'So luong banh da het!');
    END IF;

    UPDATE SANPHAM
    SET SOLUONGTON = SOLUONGTON - V_CHENHLECH
    WHERE MASP = V_MASP;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SP_KHONG_TON_TAI, 'Loi: Khong tim thay san pham.');
END;
/