-- Trigger trừ số lượng bánh khi bán, cộng số lượng khi hoàn đơn
CREATE OR REPLACE TRIGGER TRG_TRUKHO_DONHANG
AFTER INSERT OR UPDATE OR DELETE ON CTDONHANG
FOR EACH ROW
DECLARE
    V_MASP NUMBER;
    V_CHENHLECH NUMBER(10,2) := 0;
    V_SOLUONGTON NUMBER(10,2) := 0;
BEGIN
    IF INSERTING THEN
        V_CHENHLECH := NVL(:NEW.SOLUONG, 0);
        V_MASP := :NEW.MASP;
    ELSIF UPDATING THEN
        V_CHENHLECH := NVL(:NEW.SOLUONG, 0) - NVL(:OLD.SOLUONG, 0);
        V_MASP := :NEW.MASP;
    ELSIF DELETING THEN
        V_CHENHLECH := -(NVL(:OLD.SOLUONG, 0));
        V_MASP := :OLD.MASP;
    END IF;

    UPDATE SANPHAM
    SET SOLUONGTON = NVL(SOLUONGTON, 0) - V_CHENHLECH
    WHERE MASP = V_MASP
    RETURNING SOLUONGTON INTO V_SOLUONGTON;

    IF V_SOLUONGTON < 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SP_HET_HANG, 'Số lượng bánh đã hết!');
    END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_SP_KHONG_TON_TAI, 'Lỗi: Không tìm thấy sản phẩm.');
END;
/