-- Trigger cộng trừ tiền khi có thay đổi hóa đơn (insert, update, delete)
CREATE OR REPLACE TRIGGER TRG_CAPNHAT_CTDONHANG
AFTER INSERT OR UPDATE OR DELETE ON CTDONHANG
FOR EACH ROW
DECLARE
    V_CHENHLECH CTDONHANG.SOLUONG%type := 0;
    V_MADON CTDONHANG.MADON%type;
BEGIN
    IF INSERTING THEN
        V_CHENHLECH := :NEW.SOLUONG * :NEW.DONGIA;
        V_MADON := :NEW.MADON;
    ELSIF UPDATING THEN
        V_CHENHLECH := (:NEW.SOLUONG * :NEW.DONGIA) - (:OLD.SOLUONG * :OLD.DONGIA);
        V_MADON := :NEW.MADON;
    ELSIF DELETING THEN
        V_CHENHLECH := -(:OLD.SOLUONG * :OLD.DONGIA);
        V_MADON := :OLD.MADON;
    END IF;

    UPDATE DONDATHANG
    SET TONGTIENHDBAN = NVL(TONGTIENHDBAN, 0) + V_CHENHLECH
    WHERE MADON = V_MADON;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DONDATHANG_KHONG_TON_TAI, 'Lỗi: Không tìm thấy đơn hàng để cập nhật tổng tiền. Mã đơn = ' || V_MADON);
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = PKG_ERROR_CODES.ERR_DONDATHANG_KHONG_TON_TAI THEN RAISE;
        END IF;
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_HUY_CAPNHAT_TONGTIEN, 'Lỗi hệ thống khi cập nhật tổng tiền đơn hàng: ' || SQLERRM);
END;
/
