-- Trigger cộng dồn số bánh khách đặt và kiểm soát năng lực (tùy chỉnh)
-- IMP-07: Tự động INSERT row năng lực với giới hạn mặc định khi chưa có cấu hình cho ngày đó
CREATE OR REPLACE TRIGGER TRG_KIEMSOAT_CONGSUAT_TUYCHINH
AFTER INSERT OR UPDATE OR DELETE ON CTDONTUYCHINH
FOR EACH ROW
DECLARE
    V_MADON CTDONTUYCHINH.MADON%type;
    V_CHENHLECH CTDONTUYCHINH.SOLUONG%type := 0;
    V_NGAYGIAO DATE;
    V_THOIGIANCHUANBI CTDONTUYCHINH.THOIGIANCHUANBI%type := 0;
    V_NGAYSANXUAT DATE;
    V_SOBANH_HIENTAI NANGLUCSANXUAT.SOBANHDANHAN%type;
    V_GIOIHAN NANGLUCSANXUAT.GIOIHANSOBANH%type;
    V_GIOIHAN_MACDINH CONSTANT NUMBER := 50; -- Giới hạn mặc định khi chưa cấu hình
BEGIN
    IF INSERTING THEN
        V_CHENHLECH := :NEW.SOLUONG;
        V_MADON := :NEW.MADON;
        V_THOIGIANCHUANBI := NVL(:NEW.THOIGIANCHUANBI, 0);
    ELSIF UPDATING THEN
        V_CHENHLECH := :NEW.SOLUONG - :OLD.SOLUONG;
        V_MADON := :NEW.MADON;
        V_THOIGIANCHUANBI := NVL(:NEW.THOIGIANCHUANBI, 0);
    ELSIF DELETING THEN
        V_CHENHLECH := -(:OLD.SOLUONG);
        V_MADON := :OLD.MADON;
        V_THOIGIANCHUANBI := NVL(:OLD.THOIGIANCHUANBI, 0);
    END IF;

    SELECT TRUNC(NGAYGIONHANBANH) INTO V_NGAYGIAO
    FROM DONDATHANG
    WHERE MADON = V_MADON;

    -- Lùi thời gian giao cho khớp với chuẩn bị thực tế
    V_NGAYSANXUAT := V_NGAYGIAO - V_THOIGIANCHUANBI;

    -- IMP-07: Tự động tạo row năng lực nếu chưa có, thay vì RAISE lỗi
    BEGIN
        SELECT NVL(SOBANHDANHAN, 0), NVL(GIOIHANSOBANH, 0)
        INTO V_SOBANH_HIENTAI, V_GIOIHAN
        FROM NANGLUCSANXUAT
        WHERE TRUNC(NGAYSANXUAT) = V_NGAYSANXUAT
        FOR UPDATE;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            -- Tự động khởi tạo ngày sản xuất mới với giới hạn mặc định
            INSERT INTO NANGLUCSANXUAT (NGAYSANXUAT, GIOIHANSOBANH, SOBANHDANHAN)
            VALUES (V_NGAYSANXUAT, V_GIOIHAN_MACDINH, 0);

            V_SOBANH_HIENTAI := 0;
            V_GIOIHAN := V_GIOIHAN_MACDINH;
    END;

    IF (V_SOBANH_HIENTAI + V_CHENHLECH) > V_GIOIHAN THEN
        RAISE_APPLICATION_ERROR(PKG_ERROR_CODES.ERR_DON_VUOT_CONG_SUAT,
            'TU CHOI NHAN DON: Ngay San Xuat Thuc Te (' || TO_CHAR(V_NGAYSANXUAT, 'DD/MM/YYYY') || ') ' ||
            ' da dat cong suat toi da! (Da nhan: ' || V_SOBANH_HIENTAI || '/' || V_GIOIHAN || ' banh, Khach dat them: ' || V_CHENHLECH || ' banh). ' ||
            'Vui long khuyen khich khach doi sang ngay khac!');
    END IF;

    UPDATE NANGLUCSANXUAT
    SET SOBANHDANHAN = V_SOBANH_HIENTAI + V_CHENHLECH
    WHERE TRUNC(NGAYSANXUAT) = V_NGAYSANXUAT;

END;
/
