@startuml LapDonDatBanhTuyChinh
mainframe sd Seq_LapDonDatBanhTuyChinh
autonumber "<b>##."
skinparam sequenceMessageAlign center
skinparam style strictuml

skinparam noteBackgroundColor transparent
skinparam noteBorderColor transparent

actor "Thu ngân" as TN #White
boundary "Form_DatBanh" as FRM #White
boundary "GUI_BanHang" as UI #White
control "Controller_BanHang" as SYS #White
entity ": KHACHHANG" as DB_KH #White
entity ": DONDATHANG" as DB_DDH #White

TN -> UI: Chọn sản phẩm, tùy chỉnh và nhấn "Thanh toán"
activate UI
deactivate UI

UI -->> FRM: Mở hộp thoại thông tin khách
activate FRM
deactivate FRM

TN -> FRM: Nhập SĐT tìm khách và nhấn "Tiếp theo"
activate FRM
deactivate FRM

FRM -> SYS: Tìm kiếm khách hàng
activate SYS
deactivate SYS

SYS -> DB_KH: Truy vấn khách hàng
activate DB_KH
deactivate DB_KH

SYS -->> FRM: Trả kết quả (Có/Khách vãng lai)

TN -> FRM: Chọn ngày giờ nhận, địa chỉ, số tiền cọc
activate FRM
deactivate FRM

TN -> FRM: Chọn hình thức thanh toán cọc và nhấn "Xác nhận"
activate FRM
deactivate FRM

FRM -> SYS: Gửi yêu cầu lưu đơn đặt hàng
activate SYS
deactivate SYS

SYS -> SYS: Kiểm tra điều kiện đặt (ngày, tiền cọc >= 50%)
activate SYS
deactivate SYS

group alt Kiểm tra điều kiện
    note over of TN: [Dữ liệu không hợp lệ]
    autonumber stop
    TN -[hidden]-> DB_DDH
    autonumber resume "<b>##."
    SYS -->> FRM: Thông báo lỗi
else
    note over of TN: [Hợp lệ]
    autonumber stop
    TN -[hidden]-> DB_DDH
    autonumber resume "<b>##."
    SYS -> DB_DDH: Lưu đơn hàng (Đã cọc)
    activate DB_DDH
    deactivate DB_DDH
    
    SYS -> DB_DDH: Lưu phiếu thu cọc
    activate DB_DDH
    deactivate DB_DDH
    
    SYS -->> UI: Thông báo thành công
end
@enduml
