@startuml CapNhatTrangThaiDon
mainframe sd Seq_CapNhatTrangThaiDon
autonumber "<b>##."
skinparam sequenceMessageAlign center
skinparam style strictuml

skinparam noteBackgroundColor transparent
skinparam noteBorderColor transparent

actor "Thu ngân" as TN #White
boundary "GUI_BanHang" as UI #White
control "Controller_BanHang" as SYS #White
entity ": DONDATHANG" as DB_DDH #White
entity ": HOADON" as DB_HD #White

TN -> UI: Xem danh sách và chọn trạng thái mới cho đơn
activate UI
deactivate UI

TN -> UI: Nhấn "Cập nhật"
activate UI
deactivate UI

UI -> SYS: Yêu cầu cập nhật trạng thái
activate SYS
deactivate SYS

SYS -> SYS: Kiểm tra trạng thái hiện tại
activate SYS
deactivate SYS

group alt Kiểm tra trạng thái hiện tại
    note over of TN: [Đã Hoàn thành/Trùng lặp]
    autonumber stop
    TN -[hidden]-> DB_HD
    autonumber resume "<b>##."
    SYS -->> UI: Thông báo lỗi
else
    note over of TN: [Chuyển sang Hoàn thành]
    autonumber stop
    TN -[hidden]-> DB_HD
    autonumber resume "<b>##."
    SYS -->> UI: Yêu cầu xác nhận và thanh toán phần còn lại
    TN -> UI: Xác nhận thu tiền
    activate UI
    deactivate UI
    UI -> SYS: Xác nhận hoàn thành
    activate SYS
    deactivate SYS
    SYS -> DB_DDH: Cập nhật trạng thái (Hoàn thành)
    activate DB_DDH
    deactivate DB_DDH
    SYS -> DB_HD: Tạo hóa đơn và lưu phiếu thu
    activate DB_HD
    deactivate DB_HD
    SYS -->> UI: Cập nhật thành công
else
    note over of TN: [Trạng thái khác]
    autonumber stop
    TN -[hidden]-> DB_HD
    autonumber resume "<b>##."
    SYS -> DB_DDH: Cập nhật trạng thái
    activate DB_DDH
    deactivate DB_DDH
    SYS -->> UI: Cập nhật thành công
end
@enduml
