@startuml ThemDanhMucSanPham
mainframe sd Seq_ThemDanhMucSanPham
autonumber "<b>##."
skinparam sequenceMessageAlign center
skinparam style strictuml

skinparam noteBackgroundColor transparent
skinparam noteBorderColor transparent

actor "Quản lý" as QL #White
boundary "GUI_SanPham" as UI #White
control "Controller_SanPham" as SYS #White
entity ": DANHMUCSANPHAM" as DB_DM #White

QL -> UI: Nhập tên danh mục và nhấn "Thêm mới"
activate UI
deactivate UI

UI -> SYS: Gửi dữ liệu tạo danh mục
activate SYS
deactivate SYS

SYS -> SYS: Kiểm tra rỗng và trùng lặp
activate SYS
deactivate SYS

SYS -> DB_DM: Truy vấn kiểm tra tên
activate DB_DM
deactivate DB_DM

group alt Kiểm tra tính hợp lệ
    note over of QL: [Lỗi/Trùng lặp]
    autonumber stop
    QL -[hidden]-> DB_DM
    autonumber resume "<b>##."
    SYS -->> UI: Thông báo lỗi, giữ nguyên dữ liệu
else
    note over of QL: [Hợp lệ]
    autonumber stop
    QL -[hidden]-> DB_DM
    autonumber resume "<b>##."
    SYS -> DB_DM: Lưu danh mục mới
    activate DB_DM
    deactivate DB_DM
    
    SYS -->> UI: Báo thành công, xóa trắng ô nhập và làm mới danh sách
end
@enduml
