@startuml SuaDanhMucSanPham
mainframe sd Seq_SuaDanhMucSanPham
autonumber "<b>##."
skinparam sequenceMessageAlign center
skinparam style strictuml

skinparam noteBackgroundColor transparent
skinparam noteBorderColor transparent

actor "Quản lý" as QL #White
boundary "GUI_SanPham" as UI #White
control "Controller_SanPham" as SYS #White
entity ": DANHMUCSANPHAM" as DB_DM #White

QL -> UI: Chọn hàng danh mục cần sửa
activate UI
deactivate UI

UI -->> QL: Hiển thị tên danh mục hiện tại lên ô nhập

QL -> UI: Chỉnh sửa tên và nhấn "Lưu thay đổi"
activate UI
deactivate UI

UI -> SYS: Gửi dữ liệu cập nhật
activate SYS
deactivate SYS

SYS -> SYS: Kiểm tra tính hợp lệ
activate SYS
deactivate SYS

SYS -> DB_DM: Kiểm tra trùng lặp tên
activate DB_DM
deactivate DB_DM

group alt Kiểm tra
    note over of QL: [Lỗi/Trùng lặp]
    autonumber stop
    QL -[hidden]-> DB_DM
    autonumber resume "<b>##."
    SYS -->> UI: Báo lỗi, giữ nguyên ô nhập
else
    note over of QL: [Hợp lệ]
    autonumber stop
    QL -[hidden]-> DB_DM
    autonumber resume "<b>##."
    SYS -> DB_DM: Cập nhật tên danh mục
    activate DB_DM
    deactivate DB_DM
    
    SYS -->> UI: Báo thành công và làm mới danh sách
end
@enduml
