@startuml TinhToanSoLuongBanhLamRa
mainframe sd Seq_TinhToanSoLuongBanhLamRa
autonumber "<b>##."
skinparam sequenceMessageAlign center
skinparam style strictuml

skinparam noteBackgroundColor transparent
skinparam noteBorderColor transparent

actor "Quản lý" as QL #White
boundary "GUI_CongThuc" as UI #White
control "Controller_CongThuc" as SYS #White
entity ": CONGTHUC" as DB_CT #White
entity ": NGUYENLIEU" as DB_NL #White

QL -> UI: Chọn sản phẩm để tính
activate UI
deactivate UI

UI -> SYS: Yêu cầu tính toán tối đa
activate SYS
deactivate SYS

SYS -> DB_CT: Lấy công thức sản phẩm
activate DB_CT
deactivate DB_CT

SYS -> DB_NL: Truy vấn tồn kho nguyên liệu tương ứng
activate DB_NL
deactivate DB_NL

SYS -> SYS: Tính toán số lượng tối đa
activate SYS
deactivate SYS

SYS -->> UI: Hiển thị kết quả và đánh dấu nguyên liệu giới hạn
@enduml
