@startuml QuanLySanPham
mainframe sd Seq_QuanLySanPham
autonumber "<b>##."
skinparam sequenceMessageAlign center
skinparam style strictuml

skinparam noteBackgroundColor transparent
skinparam noteBorderColor transparent

actor "Quản lý / Thu ngân" as NV #White
boundary "GUI_SanPham" as UI #White
control "Controller_SanPham" as SYS #White
entity ": DANHMUCSANPHAM" as DB_DMSP #White
entity ": SANPHAM" as DB_SP #White

UI -> UI: Mở màn hình quản lý sản phẩm
activate UI
deactivate UI

UI -> SYS: Yêu cầu tải dữ liệu
activate SYS
deactivate SYS

SYS -> DB_DMSP: Truy vấn danh mục
activate DB_DMSP
deactivate DB_DMSP

SYS -> DB_SP: Truy vấn sản phẩm
activate DB_SP
deactivate DB_SP

SYS -->> UI: Hiển thị danh sách

NV -> UI: Chọn chức năng
activate UI
deactivate UI

group opt Thêm danh mục
    autonumber stop
    NV -[hidden]-> DB_SP
    autonumber resume "<b>##."
    ref over NV, DB_SP: Thêm danh mục (Seq_ThemDanhMucSanPham)
end

group opt Sửa danh mục
    autonumber stop
    NV -[hidden]-> DB_SP
    autonumber resume "<b>##."
    ref over NV, DB_SP: Sửa danh mục (Seq_SuaDanhMucSanPham)
end

group opt Cập nhật trạng thái danh mục
    autonumber stop
    NV -[hidden]-> DB_SP
    autonumber resume "<b>##."
    ref over NV, DB_SP: Cập nhật trạng thái DM (Seq_CapNhatTrangThaiDanhMuc)
end

group opt Thêm sản phẩm
    autonumber stop
    NV -[hidden]-> DB_SP
    autonumber resume "<b>##."
    ref over NV, DB_SP: Thêm sản phẩm (Seq_ThemSanPham)
end

group opt Sửa sản phẩm
    autonumber stop
    NV -[hidden]-> DB_SP
    autonumber resume "<b>##."
    ref over NV, DB_SP: Sửa sản phẩm (Seq_SuaSanPham)
end

group opt Cập nhật trạng thái sản phẩm
    autonumber stop
    NV -[hidden]-> DB_SP
    autonumber resume "<b>##."
    ref over NV, DB_SP: Cập nhật trạng thái SP (Seq_CapNhatTrangThaiSanPham)
end

group opt Tra cứu sản phẩm
    autonumber stop
    NV -[hidden]-> DB_SP
    autonumber resume "<b>##."
    ref over NV, DB_SP: Tra cứu sản phẩm (Seq_TraCuuSanPham)
end
@enduml
