    @startuml DangNhap
    mainframe sd Seq_DangNhap
    autonumber "<b>##."
    skinparam sequenceMessageAlign center
    skinparam style strictuml

    skinparam noteBackgroundColor transparent
    skinparam noteBorderColor transparent

    actor "Nhân viên" as NV #White
    boundary "GUI_DangNhap" as UI #White
    control "Controller_DangNhap" as SYS #White
    entity ": TAIKHOAN" as DB_TK #White
    entity ": ACCOUNT_TOKEN" as DB_AT #White
    entity ": VAITRO" as DB_VT #White
    entity ": CALAMVIEC" as DB_CLV #White

    UI -> UI: Hiển thị trang đăng nhập
    activate UI
    deactivate UI

    NV -> UI: Nhập tên đăng nhập, mật khẩu và nhấn nút "Đăng Nhập"
    activate UI
    deactivate UI

    UI -> SYS: Gửi yêu cầu đăng nhập
    activate SYS
    deactivate SYS

    SYS -> SYS: Kiểm tra định dạng
    activate SYS
    deactivate SYS

    group alt Kiểm tra định dạng

        note over of NV: [Thiếu thông tin]
    
        autonumber stop
        NV -[hidden]-> DB_CLV
        autonumber resume "<b>##."
        SYS -->> UI: Thông báo lỗi thiếu thông tin

    else 
        note over of NV: [Thông tin đầy đủ]
        autonumber stop
        NV -[hidden]-> DB_CLV
        autonumber resume "<b>##."
        SYS -> DB_TK: Truy vấn xác thực tài khoản
        activate DB_TK
        deactivate DB_TK

        SYS -> SYS: Kiểm tra thông tin xác thực tài khoản
        activate SYS
        deactivate SYS

        

        group alt Kiểm tra thông tin xác thực tài khoản
            note over of NV: [Thông tin sai hoặc tài khoản bị khóa]
            autonumber stop
            NV -[hidden]-> DB_CLV
            autonumber resume "<b>##."
            SYS -->> UI: Thông báo lỗi xác thực
        else 
            note over of NV: [Xác thực thành công]
            autonumber stop
            NV -[hidden]-> DB_CLV
            autonumber resume "<b>##."
            SYS -> DB_AT: Tạo và lưu token phiên đăng nhập
            activate DB_AT
            deactivate DB_AT
            
            SYS -> SYS: Lưu thông tin vào phiên làm việc
            activate SYS
            deactivate SYS
            SYS -> DB_VT: Truy vấn thông tin phân quyền vai trò trò của tài khoản
            activate DB_VT
            deactivate DB_VT

            SYS -> SYS: Kiểm tra vai trò của nhân viên
            activate SYS
            deactivate SYS

            

            group alt Kiểm tra vai trò của nhân viên
                note over of NV: [Vai trò là Thu ngân]
                SYS -> DB_CLV: Kiểm tra thu ngân đã mở ca chưa
                activate DB_CLV
                deactivate DB_CLV

                group alt Kiểm tra thu ngân đã mở ca chưa
                    note over of NV: [Chưa mở ca]
                    autonumber stop
                    NV -[hidden]-> DB_CLV
                    autonumber resume "<b>##."
                    SYS -->> UI: Hiển thị màn hình Mở ca làm việc
                else 
                    note over of NV: [Đã mở ca]
                    autonumber stop
                    NV -[hidden]-> DB_CLV
                    autonumber resume "<b>##."
                    SYS -->> UI: Hiển thị màn hình làm việc tương ứng
                end
            else 
                note over of NV: [Các vai trò khác]
                autonumber stop
                NV -[hidden]-> DB_CLV
                autonumber resume "<b>##."
                SYS -->> UI: Hiển thị màn hình làm việc tương ứng
            end
        end
    end

    @enduml
