@startuml DangXuat
mainframe sd Seq_DangXuat
autonumber "<b>##."
skinparam sequenceMessageAlign center
skinparam style strictuml

    skinparam noteBackgroundColor transparent
    skinparam noteBorderColor transparent

actor "Nhân viên" as NV #White
boundary "GUI_TrangChu" as UI #White
control "Controller_XacThuc" as SYS #White
entity ": ACCOUNT_TOKEN" as DB_AT #White

NV -> UI: Nhấn nút "Đăng xuất"
activate UI
deactivate UI

UI -> SYS: Yêu cầu đăng xuất
activate SYS
deactivate SYS

SYS -> DB_AT: Truy vấn và thu hồi token phiên làm việc
activate DB_AT
deactivate DB_AT

SYS -> SYS: Xóa toàn bộ thông tin phiên làm việc 
activate SYS
deactivate SYS

SYS -->> UI: Chuyển về màn hình đăng nhập

@enduml
