@startuml XoaKhachHang
mainframe sd Seq_XoaKhachHang
autonumber "<b>##."
skinparam sequenceMessageAlign center
skinparam style strictuml

    skinparam noteBackgroundColor transparent
    skinparam noteBorderColor transparent

actor "Nhân viên" as NV #White
boundary "GUI_KhachHang" as UI #White
control "Controller_KhachHang" as SYS #White
entity ": KHACHHANG" as DB_KH #White

NV -> UI: Chọn khách hàng cần xóa
activate UI
deactivate UI

UI -> UI: Hiển thị hộp thoại xác nhận
activate UI
deactivate UI

group alt Hiển thị hộp thoại xác nhận
    note over of NV: [Nhấn "Hủy"]
    autonumber stop
    NV -[hidden]-> DB_KH
    autonumber resume "<b>##."
    NV -> UI: Chọn "Hủy"
    activate UI
    deactivate UI

    UI -> UI: Đóng hộp thoại xác nhận
    activate UI
    deactivate UI

else 
    note over of NV: [Nhấn "OK"]
    autonumber stop
    NV -[hidden]-> DB_KH
    autonumber resume "<b>##."
    NV -> UI: Chọn "OK"
    activate UI
    deactivate UI
    
    UI -> SYS: Yêu cầu vô hiệu hóa khách hàng
    activate SYS
    deactivate SYS
    
    SYS -> DB_KH: Cập nhật thời điểm xóa \n và mã người xóa 
    activate DB_KH
    deactivate DB_KH
    
    SYS -> SYS: Xử lý kết quả cập nhật
    activate SYS
    deactivate SYS
    
    group alt Xử lý kết quả cập nhật
        note over of NV: [Lỗi cập nhật]
        autonumber stop
        NV -[hidden]-> DB_KH
        autonumber resume "<b>##."
        SYS -->> UI: Báo lỗi cơ sở dữ liệu
    else 
        note over of NV: [Thành công]
        autonumber stop
        NV -[hidden]-> DB_KH
        autonumber resume "<b>##."
        SYS -->> UI: Ẩn khách hàng và thông báo
    end
end

@enduml
