-- Recompile view VW_HoatDongNhanVien
CREATE OR REPLACE VIEW VW_HoatDongNhanVien AS
SELECT
    H.MAHOATDONG,
    H.MANV,
    NV.HOTEN  AS TENNHANVIEN,

    (SELECT VT2.TENVAITRO
     FROM TAIKHOAN TK2
              JOIN TAIKHOAN_VAITRO TKVT2 ON TKVT2.MATAIKHOAN = TK2.MATAIKHOAN
              JOIN VAITRO VT2 ON VT2.MAVAITRO = TKVT2.MAVAITRO
     WHERE TK2.MANV = H.MANV
       AND TKVT2.MAVAITRO = (SELECT MIN(TKVT3.MAVAITRO)
                             FROM TAIKHOAN TK3
                                      JOIN TAIKHOAN_VAITRO TKVT3 ON TKVT3.MATAIKHOAN = TK3.MATAIKHOAN
                             WHERE TK3.MANV = H.MANV)) AS VAITRO,
    H.NHOM    AS MODULE,
    H.NHOM,
    H.HANHDONG,
    H.ENTITY_ID,
    H.THOIGIAN
FROM HOATDONGNHANVIEN H
         JOIN NHANVIEN NV ON NV.MANV = H.MANV
;