-- View phục vụ màn hình Lịch sử hệ thống (Employee Activity Audit Log)
CREATE OR REPLACE VIEW VW_HoatDongNhanVien AS
SELECT
    H.MAHOATDONG,
    H.MANV,
    NV.HOTEN       AS TENNHANVIEN,
    VT.TENVAITRO AS VAITRO,
    CN.MODULE AS MODULE,
    H.NHOM,
    H.HANHDONG,
    H.ENTITY_ID,
    H.THOIGIAN
FROM HOATDONGNHANVIEN H
         JOIN NHANVIEN NV ON NV.MANV = H.MANV
         JOIN NHANVIEN_VAITRO NVVT ON NVVT.MANV = NV.MANV
         JOIN VAITRO VT ON  VT.MAVAITRO= NVVT.MAVAITRO
         JOIN VAITRO_CHUCNANG VTCN ON VTCN.MAVAITRO = VT.MAVAITRO
         JOIN CHUCNANG CN ON CN.MACHUCNANG= VTCN.MACHUCNANG
;
