-- View phục vụ màn hình Theo dõi đơn hàng (POS Tracking)
CREATE OR REPLACE VIEW VW_DanhSachDonHang AS
SELECT
    DDH.MADON,
    DDH.MAKH,
    KH.HOTEN AS TENKHACHHANG,
    DDH.MATRANGTHAI,
    TT.TENTRANGTHAI,
    DDH.NGAYGIONHANBANH,
    DDH.TONGTIENHDBAN,
    DDH.TIENDACOC,
    DDH.HINHTHUCNHAN,
    DDH.DIACHIGIAO
FROM DONDATHANG DDH
         JOIN TRANGTHAIDON TT ON TT.MATRANGTHAI = DDH.MATRANGTHAI
         LEFT JOIN KHACHHANG KH ON KH.MAKH = DDH.MAKH;