-- ==========================================
-- I. NHÓM QUẢN LÝ NHÂN SỰ & KHÁCH HÀNG (Sửa đổi cho N-N)
-- ==========================================

CREATE TABLE VAITRO (
                        MAVAITRO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                        TENVAITRO NVARCHAR2(100) UNIQUE NOT NULL,
                        MOTA NVARCHAR2(500),
                        THOIDIEMXOA TIMESTAMP,
                        MANX NUMBER
);

CREATE TABLE NHANVIEN (
    MANV NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    HOTEN NVARCHAR2(100) NOT NULL,
    NGAYSINH DATE,
    SDT VARCHAR2(15) UNIQUE NOT NULL,
    TENDANGNHAP VARCHAR2(50) UNIQUE NOT NULL,
    MATKHAU VARCHAR2(255) NOT NULL,
    TRANGTHAILAMVIEC NUMBER(1) DEFAULT 1
);

CREATE TABLE NHANVIEN_VAITRO (
    MANV NUMBER NOT NULL,
    MAVAITRO NUMBER NOT NULL,
    PRIMARY KEY (MANV, MAVAITRO),
    CONSTRAINT FK_NVVT_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_NVVT_VT FOREIGN KEY (MAVAITRO) REFERENCES VAITRO(MAVAITRO)
);

CREATE TABLE CALAMVIEC (
                           MACA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                           MANV NUMBER NOT NULL,
                           MAMAYPOS VARCHAR(10),
                           THOIGIANMOCA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                           THOIGIANDONGCA TIMESTAMP,
                           TRANGTHAI NVARCHAR2(50) DEFAULT 'Đang mở',
                           CONSTRAINT FK_CA_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);


ALTER TABLE VAITRO ADD CONSTRAINT FK_VAITRO_NX FOREIGN KEY (MANX) REFERENCES NHANVIEN(MANV);

CREATE TABLE CHUCNANG (
                          MACHUCNANG NUMBER PRIMARY KEY,
                          TENCHUCNANG NVARCHAR2(100) UNIQUE NOT NULL,
                          MOTA NVARCHAR2(500),
                          MODULE VARCHAR2(50) NOT NULL
);

-- Bảng phân quyền chi tiết (Flags)
CREATE TABLE VAITRO_CHUCNANG (
                                 MAVAITRO NUMBER NOT NULL,
                                 MACHUCNANG NUMBER NOT NULL,
                                 CAN_VIEW NUMBER(1) DEFAULT 0,
                                 CAN_ADD NUMBER(1) DEFAULT 0,
                                 CAN_EDIT NUMBER(1) DEFAULT 0,
                                 CAN_DELETE NUMBER(1) DEFAULT 0,
                                 CAN_DOWNLOAD NUMBER(1) DEFAULT 0,
                                 THOIDIEMXOA TIMESTAMP,
                                 CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                 PRIMARY KEY (MAVAITRO, MACHUCNANG),
                                 CONSTRAINT FK_VC_VAITRO FOREIGN KEY (MAVAITRO) REFERENCES VAITRO(MAVAITRO),
                                 CONSTRAINT FK_VC_CHUCNANG FOREIGN KEY (MACHUCNANG) REFERENCES CHUCNANG(MACHUCNANG)
);


CREATE TABLE HANGTHANHVIEN (
                               MAHANG NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                               TENHANG NVARCHAR2(50) NOT NULL,
                               DIEMTOITHIEU NUMBER(10,0) DEFAULT 0,
                               PHANTRAMGIAMGIA NUMBER(5,2) DEFAULT 0,
                               THOIDIEMXOA TIMESTAMP,
                               MANX NUMBER,
                               CONSTRAINT FK_HANGTV_NX FOREIGN KEY (MANX) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE KHACHHANG (
                           MAKH NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                           HOTEN NVARCHAR2(100) NOT NULL,
                           SDT VARCHAR2(15) UNIQUE NOT NULL,
                           DIACHI NVARCHAR2(255),
                           NGAYDANGKY DATE DEFAULT SYSDATE,
                           DIEMTICHLUY NUMBER(10,0) DEFAULT 0,
                           MAHANG NUMBER,
                           THOIDIEMXOA TIMESTAMP,
                           MANX NUMBER,
                           CONSTRAINT FK_KH_HANG FOREIGN KEY (MAHANG) REFERENCES HANGTHANHVIEN(MAHANG),
                           CONSTRAINT FK_KH_NX FOREIGN KEY (MANX) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE USER_SESSIONS (
                               SESSION_ID  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                               USER_ID     NUMBER NOT NULL,
                               TOKEN       VARCHAR2(256 CHAR) NOT NULL,
                               ISSUED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP,
                               EXPIRES_AT  TIMESTAMP ,
                               STATUS      VARCHAR2(20) DEFAULT 'active' NOT NULL,
                               CONSTRAINT FK_US_NV FOREIGN KEY (USER_ID) REFERENCES NHANVIEN(MANV)
);

