-- ==========================================
-- I. NHÓM QUẢN LÝ NHÂN SỰ & KHÁCH HÀNG
-- ==========================================

CREATE TABLE VAITRO (
    MAVAITRO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TENVAITRO NVARCHAR2(100) NOT NULL,
    MOTA NVARCHAR2(500),
    THOIDIEMXOA TIMESTAMP,
    MANX NUMBER
);

CREATE TABLE NHANVIEN (
    MANV NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MAVAITRO NUMBER NOT NULL,
    HOTEN NVARCHAR2(100) NOT NULL,
    NGAYSINH DATE,
    SDT VARCHAR2(15) UNIQUE NOT NULL,
    TENDANGNHAP VARCHAR2(50) UNIQUE NOT NULL,
    MATKHAU VARCHAR2(255) NOT NULL,
    TRANGTHAILAMVIEC NUMBER(1) DEFAULT 1,
    CONSTRAINT FK_NV_VAITRO FOREIGN KEY (MAVAITRO) REFERENCES VAITRO(MAVAITRO)
);

CREATE TABLE CALAMVIEC (
    MACA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MANV NUMBER NOT NULL,
    MAMAYPOS VARCHAR(10),
    THOIGIANMOCA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    THOIGIANDONGCA TIMESTAMP,
    TRANGTHAI NVARCHAR2(50) DEFAULT 'Đang mở',
    CONSTRAINT FK_CA_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- Xử lý tham chiếu vòng
ALTER TABLE VAITRO ADD CONSTRAINT FK_VAITRO_NX FOREIGN KEY (MANX) REFERENCES NHANVIEN(MANV);

CREATE TABLE CHUCNANG (
    MACHUCNANG NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TENCHUCNANG NVARCHAR2(100) NOT NULL,
    MOTA NVARCHAR2(500)
);

CREATE TABLE VAITRO_CHUCNANG (
    MAVAITRO NUMBER NOT NULL,
    MACHUCNANG NUMBER NOT NULL,
    PRIMARY KEY (MAVAITRO, MACHUCNANG),
    CONSTRAINT FK_VC_VAITRO FOREIGN KEY (MAVAITRO) REFERENCES VAITRO(MAVAITRO),
    CONSTRAINT FK_VC_CHUCNANG FOREIGN KEY (MACHUCNANG) REFERENCES CHUCNANG(MACHUCNANG)
);

CREATE TABLE HANGTHANHVIEN (
    MAHANG NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TENHANG NVARCHAR2(50) NOT NULL,
    DIEMTOITHIEU NUMBER(10,0) DEFAULT 0,
    PHANTRAMGIAMGIA NUMBER(5,2) DEFAULT 0,
    THOIDIEMXOA TIMESTAMP,
    MANX NUMBER,
    CONSTRAINT FK_HANGTV_NX FOREIGN KEY (MANX) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE KHACHHANG (
    MAKH NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    HOTEN NVARCHAR2(100) NOT NULL,
    SDT VARCHAR2(15) UNIQUE NOT NULL,
    DIACHI NVARCHAR2(255),
    NGAYDANGKY DATE DEFAULT SYSDATE,
    DIEMTICHLUY NUMBER(10,0) DEFAULT 0,
    MAHANG NUMBER,
    THOIDIEMXOA TIMESTAMP,
    MANX NUMBER,
    CONSTRAINT FK_KH_HANG FOREIGN KEY (MAHANG) REFERENCES HANGTHANHVIEN(MAHANG),
    CONSTRAINT FK_KH_NX FOREIGN KEY (MANX) REFERENCES NHANVIEN(MANV)
);