CREATE TABLE VAITRO (
    MaVaiTro NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenVaiTro NVARCHAR2(100) UNIQUE NOT NULL,
    MoTa NVARCHAR2(255),
    DaXoa NUMBER(1) DEFAULT 1
);

CREATE TABLE CHUCNANG (
    MaChucNang NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenChucNang NVARCHAR2(150) NOT NULL,
    MoTa NVARCHAR2(255)
);

CREATE TABLE VAITRO_CHUCNANG (
    MaVaiTro NUMBER NOT NULL,
    MaChucNang NUMBER NOT NULL,
    CONSTRAINT PK_VAITRO_CHUCNANG PRIMARY KEY (MaVaiTro, MaChucNang),
    CONSTRAINT FK_VTCN_VT FOREIGN KEY (MaVaiTro) REFERENCES VAITRO(MaVaiTro),
    CONSTRAINT FK_VTCN_CN FOREIGN KEY (MaChucNang) REFERENCES CHUCNANG(MaChucNang)
);



CREATE TABLE NHANVIEN (
    MaNV NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaVaiTro NUMBER NOT NULL,
    HoTen NVARCHAR2(150) NOT NULL,
    NgaySinh DATE,
    SDT VARCHAR2(15),
    Username VARCHAR2(50) UNIQUE NOT NULL,
    Password VARCHAR2(255) NOT NULL,
    TrangThaiLamViec NUMBER(1) DEFAULT 1,
    CONSTRAINT FK_NV_VAITRO FOREIGN KEY (MaVaiTro) REFERENCES VAITRO(MaVaiTro)
);

CREATE TABLE HANGTHANHVIEN (
    MaHang NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenHang NVARCHAR2(100) NOT NULL,
    DiemToiThieu NUMBER NOT NULL,
    PhanTramGiamGia NUMBER(5,2) DEFAULT 0,
    DaXoa NUMBER(1) DEFAULT 0
);

CREATE TABLE KHACHHANG (
    MaKH NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    HoTen NVARCHAR2(150) NOT NULL,
    SDT VARCHAR2(15) UNIQUE NOT NULL,
    --Email
    DiaChi NVARCHAR2(255),
    NgayDangKy DATE DEFAULT SYSDATE,
    DiemTichLuy NUMBER DEFAULT 0,
    MaHang NUMBER,
    DaXoa NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_KH_HANG FOREIGN KEY (MaHang) REFERENCES HANGTHANHVIEN(MaHang)
);