CREATE TABLE DANHMUCSP (
    MaDM NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenDM NVARCHAR2(150) NOT NULL,
    DaXoa NUMBER(1) DEFAULT 0
);

CREATE TABLE SANPHAM (
    MaSP NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaDM NUMBER NOT NULL,
    TenSP NVARCHAR2(150) NOT NULL,
    GiaCoBan NUMBER(18,2) NOT NULL,
    HinhAnh NVARCHAR2(255),
    ChoPhepCustom NUMBER(1) DEFAULT 0,
    ThoiGianBaoQuan NUMBER DEFAULT 0,
    SoLuongTon NUMBER(18,2) DEFAULT 0,
    DaXoa NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_SP_DM FOREIGN KEY (MaDM) REFERENCES DANHMUCSP(MaDM)
);

CREATE TABLE KICHCOBANH (
    MaSize NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenSize NVARCHAR2(50) NOT NULL,
    PhuPhi NUMBER(18,2) DEFAULT 0,
    DaXoa NUMBER(1) DEFAULT 0
);

CREATE TABLE COTBANH (
    MaCot NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenCot NVARCHAR2(100) NOT NULL,
    PhuPhi NUMBER(18,2) DEFAULT 0,
    DaXoa NUMBER(1) DEFAULT 0
);

CREATE TABLE NHANBANH (
    MaNhan NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenNhan NVARCHAR2(100) NOT NULL,
    PhuPhi NUMBER(18,2) DEFAULT 0,
    DaXoa NUMBER(1) DEFAULT 0
);

CREATE TABLE KIEUTRANGTRI (
    MaTrangTri NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenTrangTri NVARCHAR2(150) NOT NULL,
    PhuPhi NUMBER(18,2) DEFAULT 0,
    DaXoa NUMBER(1) DEFAULT 0
);