-- ==========================================
-- II. NHÓM QUẢN LÝ SẢN PHẨM & TÙY CHỈNH BÁNH
-- ==========================================

CREATE TABLE DANHMUCSP (
    MADM NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TENDM NVARCHAR2(100) NOT NULL,
    THOIDIEMXOA TIMESTAMP,
    MANX NUMBER,
    CONSTRAINT FK_DMSP_NX FOREIGN KEY (MANX) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE SANPHAM (
    MASP NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MADM NUMBER NOT NULL,
    TENSP NVARCHAR2(200) NOT NULL,
    GIACOBAN NUMBER(15,2) NOT NULL,
    HINHANH VARCHAR2(500),
    CHOPHEPTUYCHINH NUMBER(1) DEFAULT 0,
    THOIGIANBAOQUAN NUMBER(5,0),
    SOLUONGTON NUMBER(10,2) DEFAULT 0,
    PHIENBAN NUMBER(10,0) DEFAULT 1,
    THOIDIEMXOA TIMESTAMP,
    THOIGIANCHUANBI NUMBER,
    MANX NUMBER,
    CONSTRAINT FK_SP_DM FOREIGN KEY (MADM) REFERENCES DANHMUCSP(MADM),
    CONSTRAINT FK_SP_NX FOREIGN KEY (MANX) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE KICHCOBANH (
    MAKC NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TENKC NVARCHAR2(50) NOT NULL,
    PHUPHI NUMBER(15,2) DEFAULT 0,
    THOIDIEMXOA TIMESTAMP,
    MANX NUMBER,
    CONSTRAINT FK_KCB_NX FOREIGN KEY (MANX) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE COTBANH (
    MACOT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TENCOT NVARCHAR2(100) NOT NULL,
    PHUPHI NUMBER(15,2) DEFAULT 0,
    THOIDIEMXOA TIMESTAMP,
    MANX NUMBER,
    CONSTRAINT FK_CB_NX FOREIGN KEY (MANX) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE NHANBANH (
    MANHAN NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TENNHAN NVARCHAR2(100) NOT NULL,
    PHUPHI NUMBER(15,2) DEFAULT 0,
    THOIDIEMXOA TIMESTAMP,
    MANX NUMBER,
    CONSTRAINT FK_NB_NX FOREIGN KEY (MANX) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE KIEUTRANGTRI (
    MATRANGTRI NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TENTRANGTRI NVARCHAR2(100) NOT NULL,
    PHUPHI NUMBER(15,2) DEFAULT 0,
    THOIDIEMXOA TIMESTAMP,
    MANX NUMBER,
    CONSTRAINT FK_KTT_NX FOREIGN KEY (MANX) REFERENCES NHANVIEN(MANV)
);