-- ==========================================
-- III. NHÓM QUẢN LÝ KHO & CÔNG THỨC
-- ==========================================

CREATE TABLE DONVITINH (
    MaDVT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenDVT NVARCHAR2(50) NOT NULL,
    ThoiDiemXoa TIMESTAMP,
    MaNX NUMBER,
    CONSTRAINT FK_DVT_NX FOREIGN KEY (MaNX) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE NGUYENLIEU (
    MaNL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenNL NVARCHAR2(200) NOT NULL,
    XuatXu NVARCHAR2(100),
    MaDVT NUMBER NOT NULL,
    GiaVonTrungBinh NUMBER(15,2) DEFAULT 0,
    MucTonAnToan NUMBER(10,2) DEFAULT 0,
    SoLuongTonTong NUMBER(10,2) DEFAULT 0,
    DatChuanVSATTP NUMBER(1) DEFAULT 1,
    PhienBan NUMBER(10,0) DEFAULT 1,
    ThoiDiemXoa TIMESTAMP,
    MaNX NUMBER,
    CONSTRAINT FK_NL_DVT FOREIGN KEY (MaDVT) REFERENCES DONVITINH(MaDVT),
    CONSTRAINT FK_NL_NX FOREIGN KEY (MaNX) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE CONGTHUC (
    MaSP NUMBER NOT NULL,
    MaNL NUMBER NOT NULL,
    SoLuongTieuHao NUMBER(10,3) NOT NULL,
    PRIMARY KEY (MaSP, MaNL),
    CONSTRAINT FK_CT_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP),
    CONSTRAINT FK_CT_NL FOREIGN KEY (MaNL) REFERENCES NGUYENLIEU(MaNL)
);

CREATE TABLE NHACUNGCAP (
    MaNCC NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenNCC NVARCHAR2(200) NOT NULL,
    SDT VARCHAR2(15),
    DiaChi NVARCHAR2(255),
    ThoiDiemXoa TIMESTAMP,
    MaNX NUMBER,
    CONSTRAINT FK_NCC_NX FOREIGN KEY (MaNX) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE PHIEUNHAPKHO (
    MaPN NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NgayNhap TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MaNV NUMBER NOT NULL,
    MaNCC NUMBER NOT NULL,
    TongTienNhap NUMBER(15,2) DEFAULT 0,
    CONSTRAINT FK_PN_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_PN_NCC FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)
);

CREATE TABLE CTPHIEUNHAP (
    MaLo NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaPN NUMBER NOT NULL,
    MaNL NUMBER NOT NULL,
    SoLuong NUMBER(10,2) NOT NULL,
    DonGia NUMBER(15,2) NOT NULL,
    SoLuongConLai NUMBER(10,2) NOT NULL,
    NgaySanXuat DATE,
    HanSuDung DATE,
    MaVach_Lo VARCHAR2(100),
    CONSTRAINT FK_CTPN_PN FOREIGN KEY (MaPN) REFERENCES PHIEUNHAPKHO(MaPN),
    CONSTRAINT FK_CTPN_NL FOREIGN KEY (MaNL) REFERENCES NGUYENLIEU(MaNL)
);

CREATE TABLE PHIEUXUATKHO (
    MaPX NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NgayXuat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LyDoXuat NVARCHAR2(500),
    MaNV NUMBER NOT NULL,
    CONSTRAINT FK_PX_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE CTPHIEUXUAT_NL (
    MaPX NUMBER NOT NULL,
    MaLo NUMBER NOT NULL,
    SoLuong NUMBER(10,2) NOT NULL,
    PRIMARY KEY (MaPX, MaLo),
    CONSTRAINT FK_CTPXNL_PX FOREIGN KEY (MaPX) REFERENCES PHIEUXUATKHO(MaPX),
    CONSTRAINT FK_CTPXNL_Lo FOREIGN KEY (MaLo) REFERENCES CTPHIEUNHAP(MaLo)
);

CREATE TABLE CTPHIEUXUAT_TP (
    MaPX NUMBER NOT NULL,
    MaSP NUMBER NOT NULL,
    SoLuong NUMBER(10,2) NOT NULL,
    DonGiaVon NUMBER(15,2),
    PRIMARY KEY (MaPX, MaSP),
    CONSTRAINT FK_CTPXTP_PX FOREIGN KEY (MaPX) REFERENCES PHIEUXUATKHO(MaPX),
    CONSTRAINT FK_CTPXTP_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);