CREATE TABLE DONVITINH (
    MaDVT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenDVT NVARCHAR2(50) NOT NULL,
    DaXoa NUMBER(1) DEFAULT 0
);

CREATE TABLE NGUYENLIEU (
    MaNL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenNL NVARCHAR2(150) NOT NULL,
    XuatXu VARCHAR2(50),
    MaDVT NUMBER NOT NULL,
    DatChuanVSATTP NUMBER(1) DEFAULT 1,
    MucTonAnToan NUMBER(18,2) DEFAULT 0,
    SoLuongTonTong NUMBER(18,2) DEFAULT 0,
    DaXoa NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_NL_DVT FOREIGN KEY (MaDVT) REFERENCES DONVITINH(MaDVT)
);


CREATE TABLE CONGTHUC (
    MaSP NUMBER NOT NULL,
    MaNL NUMBER NOT NULL,
    SoLuongTieuHao NUMBER(18,2) NOT NULL,
    CONSTRAINT PK_CONGTHUC PRIMARY KEY (MaSP, MaNL),
    CONSTRAINT FK_CT_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP),
    CONSTRAINT FK_CT_NL FOREIGN KEY (MaNL) REFERENCES NGUYENLIEU(MaNL)
);

CREATE TABLE NHACUNGCAP (
    MaNCC NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenNCC NVARCHAR2(150) NOT NULL,
    SDT VARCHAR2(15),
    DiaChi NVARCHAR2(255),
    DaXoa NUMBER(1) DEFAULT 0
);

CREATE TABLE PHIEUNHAPKHO (
    MaPN NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NgayNhap DATE DEFAULT SYSDATE,
    MaNV NUMBER NOT NULL,
    MaNCC NUMBER NOT NULL,
    TongTienNhap NUMBER(18,2) DEFAULT 0,
    CONSTRAINT FK_PN_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_PN_NCC FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)
);

CREATE TABLE CTPHIEUNHAP (
    MaPN NUMBER NOT NULL,
    MaNL NUMBER NOT NULL,
    SoLuong NUMBER(18,2) NOT NULL,
    DonGia NUMBER(18,2) NOT NULL,
    NgayNhapKho DATE NOT NULL,
    HanSuDung DATE,
    SoLuongConLai NUMBER(18,2) NOT NULL,
    CONSTRAINT PK_CTPN PRIMARY KEY (MaPN, MaNL),
    CONSTRAINT FK_CTPN_PN FOREIGN KEY (MaPN) REFERENCES PHIEUNHAPKHO(MaPN),
    CONSTRAINT FK_CTPN_NL FOREIGN KEY (MaNL) REFERENCES NGUYENLIEU(MaNL)
);

CREATE TABLE PHIEUXUATKHO (
    MaPX NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NgayXuat DATE DEFAULT SYSDATE,
    LyDoXuat NVARCHAR2(255),
    MaNV NUMBER NOT NULL,
    CONSTRAINT FK_PX_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE CTPHIEUXUAT_NL (
    MaPX NUMBER NOT NULL,
    MaNL NUMBER NOT NULL,
    SoLuong NUMBER(18,2) NOT NULL,
    CONSTRAINT PK_CTPX_NL PRIMARY KEY (MaPX, MaNL),
    CONSTRAINT FK_CTPX_NL_PX FOREIGN KEY (MaPX) REFERENCES PHIEUXUATKHO(MaPX),
    CONSTRAINT FK_CTPX_NL_NL FOREIGN KEY (MaNL) REFERENCES NGUYENLIEU(MaNL)
);

CREATE TABLE CTPHIEUXUAT_TP (
    MaPX NUMBER NOT NULL,
    MaSP NUMBER NOT NULL,
    SoLuong NUMBER(18,2) NOT NULL,
    DonGiaVon NUMBER(18,2) NOT NULL,
    CONSTRAINT PK_CTPX_TP PRIMARY KEY (MaPX, MaSP),
    CONSTRAINT FK_CTPX_TP_PX FOREIGN KEY (MaPX) REFERENCES PHIEUXUATKHO(MaPX),
    CONSTRAINT FK_CTPX_TP_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);