-- ==========================================
-- IV. NHÓM QUẢN LÝ ĐẶT HÀNG & TIẾN ĐỘ
-- ==========================================

CREATE TABLE TRANGTHAIDON (
    MATRANGTHAI NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TENTRANGTHAI NVARCHAR2(100) NOT NULL
);

CREATE TABLE NANGLUCSANXUAT (
    NGAYSANXUAT DATE DEFAULT TRUNC(SYSDATE) PRIMARY KEY,
    GIOIHANSOBANH NUMBER(10,0) NOT NULL,
    SOBANHDANHAN NUMBER(10,0) DEFAULT 0
);

CREATE TABLE DONDATHANG (
    MADON NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NGAYLAP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NGAYGIONHANBANH TIMESTAMP NOT NULL,
    MAKH NUMBER,
    MANV_LAP NUMBER NOT NULL,
    MATRANGTHAI NUMBER NOT NULL,
    TONGTIENHDBAN NUMBER(15,2) DEFAULT 0,
    TIENDACOC NUMBER(15,2) DEFAULT 0,
    PHIENBAN NUMBER(10,0) DEFAULT 1,
    HINHTHUCNHAN NUMBER,
    DIACHIGIAO NVARCHAR2(255),
    CONSTRAINT FK_DDH_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    CONSTRAINT FK_DDH_NV FOREIGN KEY (MANV_LAP) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_DDH_TT FOREIGN KEY (MATRANGTHAI) REFERENCES TRANGTHAIDON(MATRANGTHAI)
);

CREATE TABLE CTDONHANG (
    MACTHD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MADON NUMBER NOT NULL,
    MASP NUMBER NOT NULL,
    SOLUONG NUMBER(10,0) NOT NULL,
    DONGIA NUMBER(15,2) NOT NULL,
    PHANTRAMGIAM NUMBER(5,2) DEFAULT 0,
    DONGIAVON NUMBER(15,2),
    CONSTRAINT FK_CTDH_DON FOREIGN KEY (MADON) REFERENCES DONDATHANG(MADON),
    CONSTRAINT FK_CTDH_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);

CREATE TABLE CTDONTUYCHINH (
    MACTTC NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MADON NUMBER NOT NULL,
    MASP NUMBER NOT NULL,
    SOLUONG NUMBER(10,0) NOT NULL,
    MAKC NUMBER,
    MACOT NUMBER,
    MANHAN NUMBER,
    MATRANGTRI NUMBER,
    LOICHUCTRENBANH NVARCHAR2(200),
    GHICHUTHOBANH NVARCHAR2(500),
    HINHANHTHAMKHAO VARCHAR2(500),
    DONGIA NUMBER(15,2) NOT NULL,
    DONGIAVON NUMBER(15,2),
    THOIGIANCHUANBI NUMBER,
    CONSTRAINT FK_CTTC_DON FOREIGN KEY (MADON) REFERENCES DONDATHANG(MADON),
    CONSTRAINT FK_CTTC_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
    CONSTRAINT FK_CTTC_KC FOREIGN KEY (MAKC) REFERENCES KICHCOBANH(MAKC),
    CONSTRAINT FK_CTTC_COT FOREIGN KEY (MACOT) REFERENCES COTBANH(MACOT),
    CONSTRAINT FK_CTTC_NHAN FOREIGN KEY (MANHAN) REFERENCES NHANBANH(MANHAN),
    CONSTRAINT FK_CTTC_TT FOREIGN KEY (MATRANGTRI) REFERENCES KIEUTRANGTRI(MATRANGTRI)
);

CREATE TABLE LICHSUDONHANG (
    MALOG NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MADON NUMBER NOT NULL,
    MATRANGTHAI_CU NUMBER,
    MATRANGTHAI_MOI NUMBER NOT NULL,
    THOIGIANTHAYDOI TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MANV_CAPNHAT NUMBER NOT NULL,
    GHICHU NVARCHAR2(100),
    CONSTRAINT FK_LOG_DON FOREIGN KEY (MADON) REFERENCES DONDATHANG(MADON),
    CONSTRAINT FK_LOG_NV FOREIGN KEY (MANV_CAPNHAT) REFERENCES NHANVIEN(MANV)
);