CREATE TABLE TRANGTHAIDON (
    MaTrangThai NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenTrangThai NVARCHAR2(100) NOT NULL
);

CREATE TABLE DONDATHANG (
    MaDon NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NgayLap DATE DEFAULT SYSDATE,
    NgayGioNhanBanh DATE,
    MaKH NUMBER NOT NULL,
    MaNV_Lap NUMBER NOT NULL,
    MaTrangThai NUMBER NOT NULL,
    TongTienHDBan NUMBER(18,2) DEFAULT 0,
    TienDaCoc NUMBER(18,2) DEFAULT 0,
    CONSTRAINT FK_DON_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    CONSTRAINT FK_DON_NV FOREIGN KEY (MaNV_Lap) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_DON_TT FOREIGN KEY (MaTrangThai) REFERENCES TRANGTHAIDON(MaTrangThai)
);

CREATE TABLE CTDONHANG (
    MaCTDH NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaDon NUMBER NOT NULL,
    MaSP NUMBER NOT NULL,
    SoLuong NUMBER NOT NULL,
    DonGia NUMBER(18,2) NOT NULL,
    PhanTramGiam NUMBER(5,2) DEFAULT 0,
    DonGiaVon NUMBER(18,2) NOT NULL,
    CONSTRAINT FK_CTDH_DON FOREIGN KEY (MaDon) REFERENCES DONDATHANG(MaDon),
    CONSTRAINT FK_CTDH_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE CTDONCUSTOM (
    MaCTCustom NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaDon NUMBER NOT NULL,
    MaSP NUMBER NOT NULL,
    SoLuong NUMBER NOT NULL,
    MaSize NUMBER,
    MaCot NUMBER,
    GiaVonDong NUMBER(18,2) NOT NULL,
    MaNhan NUMBER,
    MaTrangTri NUMBER,
    LoiChucTrenBanh NVARCHAR2(255),
    GhiChuThoBanh NVARCHAR2(255),
    DonGia NUMBER(18,2) NOT NULL,
    DonGiaVon NUMBER(18,2) NOT NULL,
    CONSTRAINT FK_CTDC_DON FOREIGN KEY (MaDon) REFERENCES DONDATHANG(MaDon),
    CONSTRAINT FK_CTDC_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP),
    CONSTRAINT FK_CTDC_SIZE FOREIGN KEY (MaSize) REFERENCES KICHCOBANH(MaSize),
    CONSTRAINT FK_CTDC_COT FOREIGN KEY (MaCot) REFERENCES COTBANH(MaCot),
    CONSTRAINT FK_CTDC_NHAN FOREIGN KEY (MaNhan) REFERENCES NHANBANH(MaNhan),
    CONSTRAINT FK_CTDC_TT FOREIGN KEY (MaTrangTri) REFERENCES KIEUTRANGTRI(MaTrangTri)
);

CREATE TABLE LICHSUDONHANG (
    MaLog NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaDon NUMBER NOT NULL,
    MaTrangThai_Cu NUMBER,
    MaTrangThai_Moi NUMBER,
    ThoiGianThayDoi DATE DEFAULT SYSDATE,
    MaNV_CapNhat NUMBER,
    CONSTRAINT FK_LS_DON FOREIGN KEY (MaDon) REFERENCES DONDATHANG(MaDon),
    CONSTRAINT FK_LS_TT_CU FOREIGN KEY (MaTrangThai_Cu) REFERENCES TRANGTHAIDON(MaTrangThai),
    CONSTRAINT FK_LS_TT_MOI FOREIGN KEY (MaTrangThai_Moi) REFERENCES TRANGTHAIDON(MaTrangThai),
    CONSTRAINT FK_LS_NV FOREIGN KEY (MaNV_CapNhat) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE NANGLUCSANXUAT (
    NgaySanXuat DATE PRIMARY KEY,
    GioiHanSoBanh NUMBER NOT NULL,
    SoBanhDaNhan NUMBER DEFAULT 0
);