CREATE TABLE PHUONGTHUCTT (
    MaPTTT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenPTTT NVARCHAR2(100) NOT NULL,
    DaXoa NUMBER(1) DEFAULT 0
);

CREATE TABLE HOADON (
    MaHD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaDon NUMBER NOT NULL,
    NgayXuatHD DATE DEFAULT SYSDATE,
    ThueVAT NUMBER(5,2) DEFAULT 0,
    TongTienThanhToan NUMBER(18,2) NOT NULL,
    MaPTTT NUMBER NOT NULL,
    LoaiHD NVARCHAR2(50),
    CONSTRAINT FK_HD_DON FOREIGN KEY (MaDon) REFERENCES DONDATHANG(MaDon),
    CONSTRAINT FK_HD_PTTT FOREIGN KEY (MaPTTT) REFERENCES PHUONGTHUCTT(MaPTTT)
);

CREATE TABLE LOAITHUCHI (
    MaLoaiThuChi NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenLoaiThuChi NVARCHAR2(150) NOT NULL,
    PhanLoai VARCHAR2(10) CHECK (PhanLoai IN ('IN','OUT')),
    DaXoa NUMBER(1) DEFAULT 0
);

CREATE TABLE PHIEUTHUCHI (
    MaPhieuTC NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NgayTao DATE DEFAULT SYSDATE,
    MaLoaiThuChi NUMBER NOT NULL,
    SoTien NUMBER(18,2) NOT NULL,
    MaNV NUMBER NOT NULL,
    MaHD NUMBER,
    MaPN NUMBER,
    GhiChu NVARCHAR2(255),
    CONSTRAINT FK_TC_LOAI FOREIGN KEY (MaLoaiThuChi) REFERENCES LOAITHUCHI(MaLoaiThuChi),
    CONSTRAINT FK_TC_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_TC_HD FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
    CONSTRAINT FK_TC_PN FOREIGN KEY (MaPN) REFERENCES PHIEUNHAPKHO(MaPN)
);