-- ==========================================
-- V. NHÓM QUẢN LÝ TÀI CHÍNH & SỔ QUỸ
-- ==========================================

CREATE TABLE PHUONGTHUCTT (
    MAPTTT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TENPTTT NVARCHAR2(100) NOT NULL,
    THOIDIEMXOA TIMESTAMP,
    MANX NUMBER,
    CONSTRAINT FK_PTTT_NX FOREIGN KEY (MANX) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE DOISOAT (
    MACA NUMBER PRIMARY KEY,
    TIENKHAIBAODAUCA NUMBER(15,2) DEFAULT 0,
    TONGTIENHETHONG NUMBER(15,2) DEFAULT 0,
    TIENTHUCTEDEM NUMBER(15,2) DEFAULT 0,
    CHENHLECH NUMBER(15,2) DEFAULT 0,
    LYDOCHENHLECH NVARCHAR2(500),
    CONSTRAINT FK_DS_CA FOREIGN KEY (MACA) REFERENCES CALAMVIEC(MACA)
);

CREATE TABLE HOADON (
    MAHD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MADON NUMBER,
    MACA NUMBER NOT NULL,
    NGAYXUATHD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    THUEVAT NUMBER(5,2) DEFAULT 0,
    TONGTIENTHANHTOAN NUMBER(15,2) NOT NULL,
    TIENHANGGOC NUMBER(15,2) DEFAULT 0,
    MAPTTT NUMBER NOT NULL,
    LOAIHD NVARCHAR2(50),
    TRANGTHAI NVARCHAR2(50) DEFAULT 'active',
    CONSTRAINT FK_HD_DON FOREIGN KEY (MADON) REFERENCES DONDATHANG(MADON),
    CONSTRAINT FK_HD_CA FOREIGN KEY (MACA) REFERENCES CALAMVIEC(MACA),
    CONSTRAINT FK_HD_PTTT FOREIGN KEY (MAPTTT) REFERENCES PHUONGTHUCTT(MAPTTT)
);

CREATE TABLE LOAITHUCHI (
    MALOAITHUCHI NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TENLOAITHUCHI NVARCHAR2(200) NOT NULL,
    PHANLOAI NVARCHAR2(50) NOT NULL,
    THOIDIEMXOA TIMESTAMP,
    MANX NUMBER,
    CONSTRAINT FK_LTC_NX FOREIGN KEY (MANX) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE PHIEUTHUCHI (
    MAPHIEUTC NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MALOAITHUCHI NUMBER NOT NULL,
    SOTIEN NUMBER(15,2) NOT NULL,
    MANV NUMBER NOT NULL,
    MAHD NUMBER,
    MAPN NUMBER,
    MACA NUMBER,
    GHICHU NVARCHAR2(500),
    TRANGTHAI NVARCHAR2(50) DEFAULT 'active',
    CONSTRAINT FK_PTC_LTC FOREIGN KEY (MALOAITHUCHI) REFERENCES LOAITHUCHI(MALOAITHUCHI),
    CONSTRAINT FK_PTC_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_PTC_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
    CONSTRAINT FK_PTC_PN FOREIGN KEY (MAPN) REFERENCES PHIEUNHAPKHO(MAPN),
    CONSTRAINT FK_PTC_CA FOREIGN KEY (MACA) REFERENCES CALAMVIEC(MACA)
);

CREATE TABLE HOATDONGNHANVIEN (
    MAHOATDONG  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MANV        NUMBER NOT NULL,
    NHOM        VARCHAR2(50) NOT NULL,
    HANHDONG    NVARCHAR2(200) NOT NULL,
    ENTITY_ID   NUMBER,
    THOIGIAN    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_HDV_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
