-- ==========================================
-- V. NHÓM QUẢN LÝ TÀI CHÍNH & SỔ QUỸ
-- ==========================================

CREATE TABLE PHUONGTHUCTT (
    MaPTTT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenPTTT NVARCHAR2(100) NOT NULL,
    ThoiDiemXoa TIMESTAMP,
    MaNX NUMBER,
    CONSTRAINT FK_PTTT_NX FOREIGN KEY (MaNX) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE CALAMVIEC (
    MaCa NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaNV NUMBER NOT NULL,
    MaMayPOS NUMBER ,
    ThoiGianMoCa TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ThoiGianDongCa TIMESTAMP,
    TrangThai NVARCHAR2(50) DEFAULT 'Đang mở',
    CONSTRAINT FK_Ca_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE DOISOAT (
    MaCa NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TienKhaiBaoDauCa NUMBER(15,2) DEFAULT 0,
    TongTienHeThong NUMBER(15,2) DEFAULT 0,
    TienThucTeDem NUMBER(15,2) DEFAULT 0,
    ChenhLech NUMBER(15,2) DEFAULT 0,
    LyDoChenhLech NVARCHAR2(500),
    CONSTRAINT FK_DS_Ca FOREIGN KEY (MaCa) REFERENCES CALAMVIEC(MaCa)
);

CREATE TABLE HOADON (
    MaHD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaDon NUMBER,
    MaCa NUMBER NOT NULL,
    NgayXuatHD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ThueVAT NUMBER(5,2) DEFAULT 0,
    TongTienThanhToan NUMBER(15,2) NOT NULL,
    MaPTTT NUMBER NOT NULL,
    LoaiHD NVARCHAR2(50),
    CONSTRAINT FK_HD_Don FOREIGN KEY (MaDon) REFERENCES DONDATHANG(MaDon),
    CONSTRAINT FK_HD_Ca FOREIGN KEY (MaCa) REFERENCES CALAMVIEC(MaCa),
    CONSTRAINT FK_HD_PTTT FOREIGN KEY (MaPTTT) REFERENCES PHUONGTHUCTT(MaPTTT)
);

CREATE TABLE LOAITHUCHI (
    MaLoaiThuChi NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenLoaiThuChi NVARCHAR2(200) NOT NULL,
    PhanLoai NVARCHAR2(50) NOT NULL,
    ThoiDiemXoa TIMESTAMP,
    MaNX NUMBER,
    CONSTRAINT FK_LTC_NX FOREIGN KEY (MaNX) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE PHIEUTHUCHI (
    MaPhieuTC NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MaLoaiThuChi NUMBER NOT NULL,
    SoTien NUMBER(15,2) NOT NULL,
    MaNV NUMBER NOT NULL,
    MaHD NUMBER,
    MaPN NUMBER,
    MaCa NUMBER NOT NULL,
    GhiChu NVARCHAR2(500),
    CONSTRAINT FK_PTC_LTC FOREIGN KEY (MaLoaiThuChi) REFERENCES LOAITHUCHI(MaLoaiThuChi),
    CONSTRAINT FK_PTC_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_PTC_HD FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
    CONSTRAINT FK_PTC_PN FOREIGN KEY (MaPN) REFERENCES PHIEUNHAPKHO(MaPN),
    CONSTRAINT FK_PTC_Ca FOREIGN KEY (MaCa) REFERENCES CALAMVIEC(MaCa)
);