@startuml GeneralClassDiagram_ThuNgan
top to bottom direction
skinparam actorBackgroundColor White
skinparam boundaryBackgroundColor White
skinparam controlBackgroundColor White
skinparam entityBackgroundColor White

' Điều chỉnh để thu hẹp chiều ngang và kéo giãn chiều dọc
skinparam nodesep 60
skinparam ranksep 150
skinparam arrowThickness 1.5

' actor "Thu ngân" as TN

boundary "Form_DatBanh"
boundary "Form_DoiSoat"
boundary "Form_HuyDon"
boundary "Form_HuyHoaDon"
boundary "Form_LapPhieuThuChi"
boundary "Form_SuaKhachHang"
boundary "Form_SuaLoaiThuChi"
boundary "Form_SuaSanPham"
boundary "Form_ThanhToan"
boundary "Form_ThemKhachHang"
boundary "Form_ThemLoaiThuChi"
boundary "Form_ThemSanPham"
boundary "GUI_BanHang"
boundary "GUI_BaoCaoDoanhThu"
boundary "GUI_BaoCaoLoiNhuan"
boundary "GUI_CaLamViec"
boundary "GUI_HangThanhVien"
boundary "GUI_KhachHang"
boundary "GUI_QuanLyThuChi"
boundary "GUI_SanPham"

control "Controller_BanHang"
control "Controller_BaoCaoThongKe"
control "Controller_CaLamViec"
control "Controller_HangThanhVien"
control "Controller_KhachHang"
control "Controller_QuanLyThuChi"
control "Controller_SanPham"

entity "CALAMVIEC"
entity "CTDONHANG"
entity "CTDONTUYCHINH"
entity "DANHMUCSANPHAM"
entity "DONDATHANG"
entity "HANGTHANHVIEN"
entity "HOADON"
entity "KHACHHANG"
entity "LOAITHUCHI"
entity "PHIEUNHAPKHO"
entity "PHIEUTHUCHI"
entity "SANPHAM"
entity "THANHVIEN"

' TN -- Form_DatBanh
' TN -- Form_DoiSoat
' TN -- Form_HuyDon
' TN -- Form_HuyHoaDon
' TN -- Form_LapPhieuThuChi
' TN -- Form_SuaKhachHang
' TN -- Form_SuaLoaiThuChi
' TN -- Form_SuaSanPham
' TN -- Form_ThanhToan
' TN -- Form_ThemKhachHang
' TN -- Form_ThemLoaiThuChi
' TN -- Form_ThemSanPham
' TN -- GUI_BanHang
' TN -- GUI_BaoCaoDoanhThu
' TN -- GUI_BaoCaoLoiNhuan
' TN -- GUI_CaLamViec
' TN -- GUI_HangThanhVien
' TN -- GUI_KhachHang
' TN -- GUI_QuanLyThuChi
' TN -- GUI_SanPham

CALAMVIEC "1" -right- "*" PHIEUTHUCHI

Controller_BanHang "1" -up- "1" Form_DatBanh
Controller_BanHang "1" -up- "1" Form_HuyDon
Controller_BanHang "1" -up- "1" Form_HuyHoaDon
Controller_BanHang "1" -up- "1" Form_ThanhToan
Controller_BanHang "1" -up- "1" GUI_BanHang
Controller_BanHang .down.> DONDATHANG
Controller_BanHang .down.> HOADON
Controller_BanHang .down.> KHACHHANG
Controller_BanHang .down.> SANPHAM
Controller_BanHang .down.> THANHVIEN

Controller_BaoCaoThongKe "1" -up- "1" GUI_BaoCaoDoanhThu
Controller_BaoCaoThongKe "1" -up- "1" GUI_BaoCaoLoiNhuan
Controller_BaoCaoThongKe .down.> HOADON
Controller_BaoCaoThongKe .down.> PHIEUNHAPKHO

Controller_CaLamViec "1" -up- "1" Form_DoiSoat
Controller_CaLamViec "1" -up- "1" GUI_CaLamViec
Controller_CaLamViec .down.> CALAMVIEC

Controller_HangThanhVien "1" -up- "1" GUI_HangThanhVien
Controller_HangThanhVien .down.> HANGTHANHVIEN

Controller_KhachHang "1" -up- "1" Form_SuaKhachHang
Controller_KhachHang "1" -up- "1" Form_ThemKhachHang
Controller_KhachHang "1" -up- "1" GUI_KhachHang
Controller_KhachHang .down.> CTDONHANG
Controller_KhachHang .down.> CTDONTUYCHINH
Controller_KhachHang .down.> DONDATHANG
Controller_KhachHang .down.> HANGTHANHVIEN
Controller_KhachHang .down.> KHACHHANG
Controller_KhachHang .down.> SANPHAM

Controller_QuanLyThuChi "1" -up- "1" Form_LapPhieuThuChi
Controller_QuanLyThuChi "1" -up- "1" Form_SuaLoaiThuChi
Controller_QuanLyThuChi "1" -up- "1" Form_ThemLoaiThuChi
Controller_QuanLyThuChi "1" -up- "1" GUI_QuanLyThuChi
Controller_QuanLyThuChi .down.> CALAMVIEC
Controller_QuanLyThuChi .down.> LOAITHUCHI
Controller_QuanLyThuChi .down.> PHIEUTHUCHI

Controller_SanPham "1" -up- "1" Form_SuaSanPham
Controller_SanPham "1" -up- "1" Form_ThemSanPham
Controller_SanPham "1" -up- "1" GUI_SanPham
Controller_SanPham .down.> DANHMUCSANPHAM
Controller_SanPham .down.> DONDATHANG
Controller_SanPham .down.> SANPHAM

DANHMUCSANPHAM "1" -right- "*" SANPHAM
HOADON "1" -left- "1" DONDATHANG
KHACHHANG "1" -left- "*" HOADON
KHACHHANG "1" -right- "1" THANHVIEN
LOAITHUCHI "1" -left- "*" PHIEUTHUCHI

@enduml