@startuml

hide empty description

' Giữ khoảng cách rộng để text không bị đè
skinparam nodesep 120
skinparam ranksep 120

skinparam state {
  BackgroundColor White
  BorderColor Black
}

' Căn chỉnh khung state cho bằng nhau
state "   Đang áp dụng   " as Dang_ap_dung
state "  Ngừng áp dụng  " as Ngung_ap_dung

[*] -> Dang_ap_dung : [Thêm phương thức\nthanh toán\nthành công]
Dang_ap_dung -> Ngung_ap_dung : [Quản lý yêu cầu\nngừng áp dụng]/Xóa mềm
Ngung_ap_dung -> Dang_ap_dung : [Quản lý yêu cầu\nkhôi phục]/Khôi phục
Ngung_ap_dung -> [*]

@enduml
