@startuml MoCaLamViec
mainframe sd Seq_MoCaLamViec
autonumber "<b>##."
skinparam sequenceMessageAlign center
skinparam style strictuml

skinparam noteBackgroundColor transparent
skinparam noteBorderColor transparent

actor "Thu ngân" as TN #White
boundary "GUI_CaLamViec" as UI #White
control "Controller_CaLamViec" as SYS #White
entity ": CALAMVIEC" as DB_CLV #White

TN -> UI: Mở màn hình mở ca
activate UI
deactivate UI

UI -> SYS: Tải danh sách máy thanh toán
activate SYS
deactivate SYS

SYS -->> UI: Hiển thị màn hình với máy thanh toán mặc định

TN -> UI: Chọn máy thanh toán và nhập số tiền đầu ca
activate UI
deactivate UI

TN -> UI: Nhấn nút "Bắt Đầu Làm Việc"
activate UI
deactivate UI

UI -> SYS: Gửi yêu cầu mở ca
activate SYS
deactivate SYS

SYS -> SYS: Kiểm tra dữ liệu (máy đã chọn, số tiền)
activate SYS
deactivate SYS

group alt Kiểm tra dữ liệu
    note over of TN: [Dữ liệu lỗi/Trùng lặp]
    autonumber stop
    TN -[hidden]-> DB_CLV
    autonumber resume "<b>##."
    SYS -->> UI: Thông báo lỗi
else
    note over of TN: [Hợp lệ]
    autonumber stop
    TN -[hidden]-> DB_CLV
    autonumber resume "<b>##."
    SYS -> DB_CLV: Tạo ca làm việc mới
    activate DB_CLV
    deactivate DB_CLV
    
    SYS -> DB_CLV: Ghi nhận đối soát đầu ca
    activate DB_CLV
    deactivate DB_CLV
    
    SYS -->> UI: Chuyển sang màn hình làm việc chính
end
@enduml
