@startuml QuanLyCaLamViec
mainframe sd Seq_QuanLyCaLamViec
autonumber "<b>##."
skinparam sequenceMessageAlign center
skinparam style strictuml

skinparam noteBackgroundColor transparent
skinparam noteBorderColor transparent

actor "Thu ngân" as TN #White
boundary "GUI_CaLamViec" as UI #White
control "Controller_CaLamViec" as SYS #White
entity ": CALAMVIEC" as DB_CLV #White

UI -> UI: Mở màn hình quản lý ca làm việc
activate UI
deactivate UI

TN -> UI: Chọn chức năng
activate UI
deactivate UI

group opt Mở ca làm việc
    autonumber stop
    TN -[hidden]-> DB_CLV
    autonumber resume "<b>##."
    ref over TN, DB_CLV: Mở ca làm việc (Seq_MoCaLamViec)
end

group opt Đóng ca làm việc
    autonumber stop
    TN -[hidden]-> DB_CLV
    autonumber resume "<b>##."
    ref over TN, DB_CLV: Đóng ca làm việc (Seq_DongCaVaDoiSoat)
end
@enduml
