@startuml ThucThe
hide circle
skinparam classAttributeIconSize 0

skinparam nodesep 80
skinparam ranksep 80
skinparam arrowThickness 1.5

class CALAMVIEC <<entity>> {
  +GhiNhanDoiSoatDauCa()
  +KiemTraCaLamViecHienTaiDangMo()
  +LuuKetQuaDoiSoatVaDongCa()
  +TaoCaLamViecMoi()
  +TinhTongDoanhThuCa()
  -maCa: int
  -maMayPOS: String
  -maNV: int
  -thoiGianDongCa: LocalDateTime
  -thoiGianMoCa: LocalDateTime
  -trangThai: String
}

class CAUHINH <<entity>> {
  +LayDuLieu()
  +LuuGioiHanMoi()
  -gioiHanSoBanh: int
  -ngaySanXuat: LocalDate
  -soBanhDaNhan: int
}

class CHITIETPHIEUNHAPKHO <<entity>> {
  +LuuChiTietCacNguyenLieuNhap()
  -maNCC: int
  -maNV: int
  -maPN: int
  -ngayNhap: LocalDateTime
  -tenNhaCungCap: String
  -tenNhanVien: String
  -tongTienNhap: BigDecimal
}

class CHITIETPHIEUXUATHUY <<entity>> {
  +LuuChiTietCacNguyenLieuHuy()
}

class CHITIETPHIEUXUATKHO <<entity>> {
  +LuuChiTietCacNguyenLieuXuat()
  -lyDoXuat: String
  -maNV: int
  -maPX: int
  -ngayXuat: LocalDateTime
  -tenNhanVien: String
}

class CHUCNANG <<entity>> {
  +LayDanhSachChucNang()
  -canAdd: boolean
  -canDelete: boolean
  -canDownload: boolean
  -canEdit: boolean
  -canView: boolean
  -maChucNang: int
  -moTa: String
  -module: SystemModule
  -tenChucNang: String
}

class CONGTHUC <<entity>> {
  +CapNhatCongThuc()
  +LayBangChiTietCongThuc()
  +LayCongThucSanPham()
  +LayDuLieuCongThuc()
  +LuuCongThucMoi()
  +LuuTrangThaiMoi()
  +TruyVanDanhSach()
  -donGia: double
  -maNL: int
  -maSP: int
  -soLuongTieuHao: double
  -tenDVT: String
  -tenNguyenLieu: String
}

class CTDONHANG <<entity>> {
  +LayChiTietDonBanLe()
  -donGia: BigDecimal
  -donGiaVon: BigDecimal
  -maCTHD: int
  -maDon: int
  -maSP: int
  -phanTramGiam: double
  -soLuong: int
}

class CTDONTUYCHINH <<entity>> {
  +LayChiTietDonTuyChinh()
  -donGia: BigDecimal
  -donGiaVon: BigDecimal
  -ghiChuThoBanh: String
  -hinhAnhThamKhao: String
  -loiChucTrenBanh: String
  -maCTTC: int
  -maCot: Integer
  -maDon: int
  -maKC: Integer
  -maNhan: Integer
  -maSP: int
  -maTrangTri: Integer
  -soLuong: int
  -thoiGianChuanBi: Integer
}

class DANHMUCSANPHAM <<entity>> {
  +CapNhatTenDanhMuc()
  +KiemTraTrungLapTen()
  +LuuDanhMucMoi()
  +LuuTrangThaiMoi()
  +TruyVanDanhMuc()
  +TruyVanKiemTraTen()
  -choPhepTuyChinh: int
  -giaBan: double
  -giaVon: double
  -hinhAnh: String
  -maDM: int
  -maNX: Integer
  -maSP: int
  -phienBan: int
  -soLuongTon: double
  -tenSP: String
  -thanhPhan: String
  -thoiDiemXoa: LocalDateTime
  -thoiGianBaoQuan: int
  -thoiGianChuanBi: int
}

class DONDATHANG <<entity>> {
  +CapNhatTrangThai()
  +CapNhatTrangThaiDaHuy()
  +CapNhatTrangThaiHoanThanh()
  +GhiNhanHoanCoc()
  +KiemTraDonHangChuaHoanTat()
  +LocDonHangTheoDieuKien()
  +LuuDonHangDaCoc()
  +LuuPhieuThuCoc()
  +TimKiemLichSuDonHangHoaDonLeDatBanh()
  +TruyVanDanhSachTrongNgay()
  +TruyVanThongTinCoc()
  -diaChiGiao: String
  -hinhThucNhan: Integer
  -maDon: int
  -maKH: Integer
  -maNVLap: int
  -maTrangThai: int
  -ngayGioNhanBanh: LocalDateTime
  -ngayLap: LocalDateTime
  -phienBan: Integer
  -tenTrangThai: String
  -tienDaCoc: BigDecimal
  -tongTienHDBan: BigDecimal
}

class HANGTHANHVIEN <<entity>> {
  +CapNhatThongTinHangLuongNen()
  +LayDanhSachHangSapXepTheoDiemTangDan()
  +LayThongTinHangThanhVien()
  +TaiLaiDanhSach()
  -diemToiThieu: Integer
  -maHang: int
  -maNX: Integer
  -phanTramGiamGia: BigDecimal
  -tenHang: String
  -thoiDiemXoa: LocalDateTime
}

class HOADON <<entity>> {
  +CapNhatTrangThaiDaHuy()
  +LayChiTietHoaDon()
  +LayMaCa()
  +LuuGiaoDichHoanTien()
  +LuuHoaDonMoiHoanThanh()
  +LuuPhieuThuVaoSoQuy()
  +TaoHoaDonVaLuuPhieuThu()
  +TongHopDuLieuHoaDonTrongKhoangThoiGianYeuCau()
  +TruyVanTongDoanhThuTuHoaDonBanHangHoanTat()
  -loaiHD: String
  -maCa: int
  -maDon: Integer
  -maHD: int
  -maPTTT: int
  -ngayXuatHd: LocalDateTime
  -thueVAT: Double
  -tienHangGoc: BigDecimal
  -tongTienThanhToan: BigDecimal
  -trangThai: String
}

class HOATDONGNHANVIEN <<entity>> {
  +GhiNhanLichSuHoatDong()
  -entityId: Integer
  -hanhDong: String
  -maHoatDong: int
  -maNV: int
  -nhom: String
  -tenNhanVien: String
  -thoiGian: LocalDateTime
  -vaitro: String
}

class KHACHHANG <<entity>> {
  +CapNhatThoiDiemXoaNVaMaNguoiXoa()
  +CapNhatThongTinKhachHang()
  +LayThongTinKhachHang()
  +LuuHoSoKhachHangMoi()
  +TaiLaiDanhSach()
  +TruyVanDanhSachKhachHangDaXoa()
  +TruyVanDanhSachKhachHangHoatDong()
  +TruyVanKetHopTuKhoaVaBoLoc()
  +TruyVanKhachHang()
  +TruyVanThongTinKhachHang()
  +TruyVanTrangDuLieuMoi()
  +XoaThoiDiemXoaVaMaNguoiXoa()
  -diaChi: String
  -diemTichLuy: Integer
  -hoTen: String
  -maHang: Integer
  -maKH: int
  -maNX: Integer
  -ngayDangKy: LocalDate
  -phanTramGiamGia: BigDecimal
  -sdt: String
  -tenHang: String
  -tenNguoiXoa: String
  -thoiDiemXoa: LocalDateTime
}

class LOAITHUCHI <<entity>> {
  +CapNhatThongTinLoaiThuChi()
  +GhiNhanTrangThaiMoi()
  +LayDanhSachLoaiThuChi()
  +LayDuLieuLoaiThuChiTheoId()
  +LuuLoaiThuChiMoi()
  -maLoaiThuChi: int
  -maNguoiXoa: Integer
  -phanLoai: String
  -tenLoaiThuChi: String
}

class NGUYENLIEU <<entity>> {
  +CapNhatSoLuongTonKho()
  +CapNhatThongTinNguyenLieu()
  +LayDanhSachNguyenLieu()
  +LayDanhSachNguyenLieuTonKho0()
  +LayDanhSachNguyenLieuVaMucAnToan()
  +LayDuLieuNguyenLieuTheoId()
  +LuuThongTinNguyenLieuMoi()
  +TruSoLuongTonKho()
  +TruyVanDanhSachNguyenLieu()
  +TruyVanTonKhoNguyenLieuTuongUng()
  -datChuanVSATTP: Integer
  -giaVonTrungBinh: BigDecimal
  -maDVT: int
  -maNL: int
  -maNX: Integer
  -mucTonAnToan: Double
  -phienBan: Integer
  -soLuongTonTong: Double
  -tenDVT: String
  -tenNL: String
  -thoiDiemXoa: LocalDateTime
  -xuatXu: String
}

class NHACUNGCAP <<entity>> {
  +CapNhatThongTinNhaCungCap()
  +GhiNhanTrangThaiMoi()
  +Khoa()
  +LayDanhSachNhaCungCap()
  +LayDuLieuChiTiet()
  +LayDuLieuNhaCungCapTheoId()
  +LayThongTinNhaCungCap()
  +LuuThongTinNhaCungCapMoi()
  +TruyVanDanhSachNhaCungCapDangHoatDong()
  -diaChi: String
  -maNCC: int
  -maNX: Integer
  -sdt: String
  -tenNCC: String
  -thoiDiemXoa: LocalDateTime
}

class NHANVIEN <<entity>> {
  +CapNhatThongTinCaNhan()
  +CapNhatTrangThaiLamViec()
  +LayDanhSachCapNhat()
  +LayDanhSachNhanVien()
  +LuuHoSoNhanVienMoi()
  +ThucHienTruyVanThongTinNNhanVienTheoDieuKien()
  +TimKiemNhanVienTheoDieuKien()
  -diaChi: String
  -email: String
  -hoTen: String
  -maNV: int
  -maTaiKhoan: int
  -matKhau: String
  -ngaySinh: LocalDate
  -sdt: String
  -tenDangNhap: String
  -trangThaiLamViec: int
  -trangThaiTK: int
}

class NHANVIEN_VAITRO <<entity>> {
  +LuuVaiTroNhanVien()
  +XoaVaCapNhatVaiTroNhanVien()
  -diaChi: String
  -email: String
  -hoTen: String
  -maNV: int
  -maTaiKhoan: int
  -matKhau: String
  -ngaySinh: LocalDate
  -sdt: String
  -tenDangNhap: String
  -trangThaiLamViec: int
  -trangThaiTK: int
}

class PHIEUNHAPKHO <<entity>> {
  +LayChiTietPhieuNhapSoLoThoiHan()
  +LuuThongTinPhieuNhapKho()
  +TruyVanCacPhieuNhapKho()
  +TruyVanCacPhieuNhapKhoCuaNhaCungCapNay()
  +TruyVanTongChiPhiTuPhieuNhapKho()
  -maNCC: int
  -maNV: int
  -maPN: int
  -ngayNhap: LocalDateTime
  -tenNhaCungCap: String
  -tenNhanVien: String
  -tongTienNhap: BigDecimal
}

class PHIEUTHUCHI <<entity>> {
  +CapNhatTrangThaiPhieuThanhDaHuyVaGhiNhanLyDo()
  +LuuThongTinPhieuThuChiMoi()
  -ghiChu: String
  -maCa: int
  -maHD: Integer
  -maLoaiThuChi: int
  -maNV: int
  -maPhieuTC: int
  -maPieuNhap: Integer
  -ngayTao: LocalDateTime
  -phanLoai: String
  -soTien: double
  -tenLoaiThuChi: String
  -tenNhanVien: String
  -trangThai: String
}

class PHIEUXUATHUY <<entity>> {
  +LuuThongTinPhieuXuatHuy()
}

class PHIEUXUATKHO <<entity>> {
  +LuuThongTinPhieuXuatKho()
  -lyDoXuat: String
  -maNV: int
  -maPX: int
  -ngayXuat: LocalDateTime
  -tenNhanVien: String
}

class SANPHAM <<entity>> {
  +CapNhatTrangThai()
  +HoanTraSoLuongTonKho()
  +KiemTraSanPhamTrongDanhMuc()
  +LayThongTinSanPham()
  +LayThongTinSanPhamBanhGoc()
  +LuuDuLieuCapNhat()
  +LuuSanPhamMoiVaHinhAnh()
  +TruyVanTheoDieuKien()
  -choPhepTuyChinh: int
  -giaBan: double
  -giaVon: double
  -hinhAnh: String
  -maDM: int
  -maNX: Integer
  -maSP: int
  -phienBan: int
  -soLuongTon: double
  -tenSP: String
  -thanhPhan: String
  -thoiDiemXoa: LocalDateTime
  -thoiGianBaoQuan: int
  -thoiGianChuanBi: int
}

class TAIKHOAN <<entity>> {
  +CapNhatTaiKhoanDangNhap()
  +CapNhatTrangThaiTaiKhoan()
  +KiemTraTaiKhoanCoBiVoHieuHoaKhong()
  +KiemTraTrungTenDangNhap()
  +KiemTraTrungTenDangNhapTruNhanVienHienTai()
  +TaoTaiKhoanDangNhap()
}

class THANHVIEN <<entity>> {
  +CongDiemThanhVienNeuCo()
  +TruyVanHangThanhVien()
  -diemToiThieu: Integer
  -maHang: int
  -maNX: Integer
  -phanTramGiamGia: BigDecimal
  -tenHang: String
  -thoiDiemXoa: LocalDateTime
}

class THEKHO <<entity>> {
  +GhiNhanBienDongTheKho()
  +LayDuLieuTheKho()
  +LayLichSuBienDongNhapXuatTon()
  -loaiGiaoDich: String
  -maLo: int
  -ngayGiaoDich: LocalDateTime
  -soLuong: double
  -soLuongConLai: double
}

class VAITRO <<entity>> {
  -maNX: Integer
  -maVaiTro: int
  -moTa: String
  -tenVaiTro: String
  -thoiDiemXoa: LocalDateTime
}

class VAITRO_CHUCNANG <<entity>> {
  +CapNhatQuyenHanChiTiet()
  +LayDanhSachQuyenHanTheoVaiTroCuaTaiKhoan()
  -canAdd: boolean
  -canDelete: boolean
  -canDownload: boolean
  -canEdit: boolean
  -canView: boolean
  -maChucNang: int
  -moTa: String
  -module: SystemModule
  -tenChucNang: String
}

' ==========================================
' QUAN HỆ GIỮA CÁC ENTITY
' ==========================================
CALAMVIEC "1" -right- "*" PHIEUTHUCHI
DANHMUCSANPHAM "1" -right- "*" SANPHAM
DONDATHANG "1" *-left- "*" CTDONHANG
DONDATHANG "1" *-right- "*" CTDONTUYCHINH
HOADON "1" -left- "1" DONDATHANG
KHACHHANG "1" -left- "*" HOADON
KHACHHANG "1" -right- "1" THANHVIEN
LOAITHUCHI "1" -left- "*" PHIEUTHUCHI
NGUYENLIEU "1" -- "*" CHITIETPHIEUNHAPKHO
NGUYENLIEU "1" -- "*" CHITIETPHIEUXUATHUY
NGUYENLIEU "1" -- "*" CHITIETPHIEUXUATKHO
NGUYENLIEU "1" -left- "*" THEKHO
NGUYENLIEU "1" -right- "*" CONGTHUC
NHACUNGCAP "1" -- "*" PHIEUNHAPKHO
NHANVIEN "1" *-down- "*" TAIKHOAN
NHANVIEN "1" -left- "*" HOATDONGNHANVIEN
NHANVIEN "1" -right- "*" NHANVIEN_VAITRO
NHANVIEN_VAITRO "*" -down- "1" VAITRO
PHIEUNHAPKHO "1" -- "*" CHITIETPHIEUNHAPKHO
PHIEUXUATHUY "1" -- "*" CHITIETPHIEUXUATHUY
PHIEUXUATKHO "1" -- "*" CHITIETPHIEUXUATKHO
VAITRO "1" *-right- "*" VAITRO_CHUCNANG
VAITRO_CHUCNANG "*" -down- "1" CHUCNANG
KHACHHANG -[hidden]down- PHIEUTHUCHI

TAIKHOAN -[hidden]down- DANHMUCSANPHAM
CALAMVIEC -[hidden]down- CAUHINH
PHIEUTHUCHI -[hidden]down- HANGTHANHVIEN

@enduml
